Added how to fix locking yourself out
MicrosoftDocs/office-docs-powershell pull request #10021
Opened 2022-10-07 11:58 UTC by IrgendwasMitSchnittlauch

I just locked myself out of the EMS. That's the fix how to solve it. Didn't read the correct way to do it.

2022-10-07 12:02 UTC, opbld31 commented
Learn Build status updates of commit _[2794bc2](https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell/commits/2794bc233eff6ac6b1faa7a606caeacdfacd3c72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md](https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell/blob/patch-2/exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/exchange/control-remote-powershell-access-to-exchange-servers?view=exchange-ps&branch=pr-en-us-10021) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210071158285349-10021/BuildReport?accessString=ae8c52882d49e29adcc2b798eb1d0cab20372fd70bf471abe7a4be26e7db4fbd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-08 07:26 UTC, JohanFreelancer9 commented on exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md
> +  > In case you did that, load the Exchange module in an normal PowerShell to undo your work `add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn`
```suggestion
    >
    > Should you have done that, load the Exchange module in normal PowerShell to undo your work by using the following syntax: `add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn`.
```

2022-10-08 07:27 UTC, JohanFreelancer9 requested changes
Copy review - @IrgendwasMitSchnittlauch, kindly commit the suggested change if you agree with it. Many thanks.

2022-10-09 15:49 UTC, IrgendwasMitSchnittlauch commented
Totaly agree with it :)

2022-10-09 15:53 UTC, opbld32 commented
Learn Build status updates of commit _[ce87060](https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell/commits/ce87060e692a15515907e700587d3a15f8b5a7ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md](https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell/blob/patch-2/exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/exchange/control-remote-powershell-access-to-exchange-servers?view=exchange-ps&branch=pr-en-us-10021) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210091550099993-10021/BuildReport?accessString=a972eab830d2a50c86ee1b8a5f1e97e66587a79f8d00a9ef638e371f3fef4579).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 05:51 UTC, JohanFreelancer9 approved these changes

2022-10-10 17:12 UTC, opbld32 commented
Learn Build status updates of commit _[a563206](https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell/commits/a5632068c4d9a9922bd5ed3fd1491da7c8f92f10)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-79f197cf)

<a id="79f197cf"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit a5632068c4d9a9922bd5ed3fd1491da7c8f92f10 in branch patch-2 of repository https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell into branch main (commit 8544da5e7269efdadc2918f65f3fe5b1e7de500b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210101711278175-10021/BuildReport?accessString=d7642a4f6bd1fee142b6b9ac8f164b034486c745dd157d8c19c85334bae933a6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 17:16 UTC, opbld31 commented
Learn Build status updates of commit _[ccae9ff](https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell/commits/ccae9ff1afa250b0c845343df78f599ecc144593)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a7c8c327)

<a id="a7c8c327"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit ccae9ff1afa250b0c845343df78f599ecc144593 in branch patch-2 of repository https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell into branch main (commit 8544da5e7269efdadc2918f65f3fe5b1e7de500b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210101715587849-10021/BuildReport?accessString=a92327b13d7d5e79431ecbb1d653ef930638a75c0f9caf5c5d53ce3fc654470b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 17:21 UTC, opbld33 commented
Learn Build status updates of commit _[47518ff](https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell/commits/47518ff3080d70f8e9d509f2701fa686a008f8e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md](https://github.com/IrgendwasMitSchnittlauch/office-docs-powershell/blob/patch-2/exchange/docs-conceptual/control-remote-powershell-access-to-exchange-servers.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/exchange/control-remote-powershell-access-to-exchange-servers?view=exchange-ps&branch=pr-en-us-10021) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210101717508148-10021/BuildReport?accessString=2291527d3d8595e41b96fdb9ebe6c1e420f6262e6f702e265b80b1af8a6e1225).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-10 17:26 UTC, merged