Update Set-AtpPolicyForO365.md
MicrosoftDocs/office-docs-powershell pull request #10052
Opened 2022-10-14 06:11 UTC by malauter

Updated based on deprecated message displayed in PowerShell when using this cmdlet with BlockUrls parameter.

2022-10-14 06:16 UTC, opbld32 commented
Learn Build status updates of commit _[c7b50c5](https://github.com/malauter/office-docs-powershell/commits/c7b50c509b622db501842719ecabaa75a77eb532)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md](https://github.com/malauter/office-docs-powershell/blob/patch-4/exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-atppolicyforo365?view=exchange-ps&branch=pr-en-us-10052) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210140611544367-10052/BuildReport?accessString=18e6dd1ff99a161b3d5f4d192f04e0019663f66063f033d21217a5c794b268ef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-14 13:13 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-15 06:22 UTC, JohanFreelancer9 requested changes
Copy review - @malauter, kindly commit the suggested changes. Many thanks.

2022-10-15 06:22 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md
> +BlockURLs is being replaced by the Tenant Allow/Block List. Going forward all tenant blocks must be managed there. Only deletes to BlockURLs are supported.
```suggestion
The BlockUrls parameter is being replaced by the Tenant Allow/Block List. Going forward, all tenant blocks must be managed from there. Only deletes to BlockUrls are supported.
```

2022-10-17 09:36 UTC, opbld33 commented
Learn Build status updates of commit _[bcd9561](https://github.com/malauter/office-docs-powershell/commits/bcd956100d9e426856f799d03528f3b065bba6cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md](https://github.com/malauter/office-docs-powershell/blob/patch-4/exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-atppolicyforo365?view=exchange-ps&branch=pr-en-us-10052) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210170933160775-10052/BuildReport?accessString=73e895f7f7cb7a6cac75def5b2c97b9f2a47e44305c2004e1b3f3a0b2096c0fa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 10:07 UTC, JohanFreelancer9 approved these changes

2022-10-17 17:10 UTC, opbld30 commented
Learn Build status updates of commit _[67c1c47](https://github.com/malauter/office-docs-powershell/commits/67c1c47f5cf17f786b28c23c40e040250d7b55c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md](https://github.com/malauter/office-docs-powershell/blob/patch-4/exchange/exchange-ps/exchange/Set-AtpPolicyForO365.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-atppolicyforo365?view=exchange-ps&branch=pr-en-us-10052) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210171707317281-10052/BuildReport?accessString=31250f3f42c3d08379f6efb0e60a85f1562f7c21629d27d05d4f988275bed765).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-17 17:21 UTC, merged