Update Set-Label.md
MicrosoftDocs/office-docs-powershell pull request #10069
Opened 2022-10-20 23:17 UTC by SethF-MSFT

2022-10-20 23:22 UTC, opbld33 commented
Learn Build status updates of commit _[8bbb867](https://github.com/SethF-MSFT/office-docs-powershell/commits/8bbb867855c8e404189582607dea6fbc4e6b2822)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-Label.md](https://github.com/SethF-MSFT/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-Label.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps&branch=pr-en-us-10069) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210202317511214-10069/BuildReport?accessString=0be5aa4fff0c77ee7e67def868a3b2a0aa9fcd772297c08f617fdd8ad3af5059).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 05:30 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-Label.md
> +Note: In Word, the specified value is used as a bottom margin and left/right margin for left/right aligned content marks. A minimum value of 15 points is required and Word will also add a constant of
```suggestion
**Note**: In Word, the specified value is used as a bottom margin and left or right margin for left-aligned or right-aligned content marks. A minimum value of 15 points is required and Word will also add a constant offset of 5 points to the left margin (for left-aligned content marks) or right margin (for right-aligned content marks).
```

2022-10-21 05:32 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-Label.md
> +Note: In Word, the specified value is used as a top margin and left/right margin for left/right aligned content marks. A minimum value of 15 points is required and Word will also add a constant offse
```suggestion
**Note**: In Word, the specified value is used as a top margin and left or right margin for left-aligned or right-aligned content marks. A minimum value of 15 points is required and Word will also add a constant offset of 5 points to the left margin (for left-aligned content marks) or right margin (for right-aligned content marks).
```

2022-10-21 05:33 UTC, JohanFreelancer9 requested changes
Copy review - @SethF-MSFT, kindly commit the suggested changes. Many thanks.

2022-10-24 05:49 UTC, yogkumgit commented
@SethF-MSFT Gentle reminder

2022-10-24 16:22 UTC, cabailey commented
Don't forget to also update New-Label to keep the information in sync!

2022-10-24 16:59 UTC, opbld33 commented
Learn Build status updates of commit _[571147a](https://github.com/SethF-MSFT/office-docs-powershell/commits/571147a1275a0ff0e7be051315c1aa8837c57140)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-Label.md](https://github.com/SethF-MSFT/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-Label.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps&branch=pr-en-us-10069) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210241656192405-10069/BuildReport?accessString=cbb6a5136faa04ef893bf42c2c2ae9ade5b62d2d9ce47dda5e655fc986d17e95).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 17:03 UTC, opbld30 commented
Learn Build status updates of commit _[749855d](https://github.com/SethF-MSFT/office-docs-powershell/commits/749855d32197aa3e5c3ee307780c58e7be47bf29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-Label.md](https://github.com/SethF-MSFT/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-Label.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps&branch=pr-en-us-10069) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210241656247797-10069/BuildReport?accessString=b36b767f40887ad7c15ec3ddf32a169b10aedeb40f15e1a76763395497c0671f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 17:40 UTC, opbld33 commented
Learn Build status updates of commit _[9a13379](https://github.com/SethF-MSFT/office-docs-powershell/commits/9a13379844e523b895047fe1161f1a00490fe15b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-Label.md](https://github.com/SethF-MSFT/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-Label.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps&branch=pr-en-us-10069) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210241736272646-10069/BuildReport?accessString=71d21ec2905487b5471a6216cd0bacda86da6e6071b5fcddda428fe0cb1961f4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 17:41 UTC, merged