New Teams Shift cmdlet: Update-CsTeamsShiftsConnectionInstance
MicrosoftDocs/office-docs-powershell pull request #10073
Opened 2022-10-21 11:14 UTC by nunocorreia-ms

New cmdlet created in order to patch update a connector instance. Part of 4.8.1-preview release.

2022-10-21 11:18 UTC, nunocorreia-ms commented
@microsoft-github-policy-service agree [company="{microsoft}"]

2022-10-21 11:18 UTC, opbld30 commented
Learn Build status updates of commit _[47bc8a5](https://github.com/nunocorreia-ms/office-docs-powershell/commits/47bc8a5907790bfe6e8f6a873d3d4c69469c2a90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |
[teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/update-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210211114284113-10073/BuildReport?accessString=d8433700dddd0feafefd8189c8dbdd772f6beca2f994d299f9a1a6d77672eac1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-21 11:19 UTC, nunocorreia-ms commented
@microsoft-github-policy-service agree company="microsoft"

2022-10-21 11:19 UTC, nunocorreia-ms commented
@microsoft-github-policy-service agree

2022-10-24 05:50 UTC, yogkumgit commented
@JohanFreelancer9

2022-10-24 05:51 UTC, yogkumgit commented
@get-itips @dariomws @tseward

2022-10-24 11:51 UTC, opbld32 commented
Learn Build status updates of commit _[13e6ddb](https://github.com/nunocorreia-ms/office-docs-powershell/commits/13e6ddbeaa5e4cebffc4ea3dd477695b66c41da6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |
[teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/update-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210241148228800-10073/BuildReport?accessString=acd1eada6e53e7b3dbeab3eaa9f89304948a007e9216e6a71f302108353a118d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 11:55 UTC, opbld31 commented
Learn Build status updates of commit _[7cc5829](https://github.com/nunocorreia-ms/office-docs-powershell/commits/7cc58296b77f5291f0bdc20f5e6a626a8f674a1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |
[teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/update-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210241148480631-10073/BuildReport?accessString=ca3808c10787ddbb623c0ca7937a3af17ddfb9ad8f075b390555f4435a4263e2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-24 13:06 UTC, dariomws approved these changes

2022-10-24 16:15 UTC, tseward approved these changes

2022-10-24 16:15 UTC, tseward commented
@nunocorreia-ms is the `-Break` parameter shipping with the release version of the cmdlet? Sounds like something only useful for MSFT internally.

2022-10-24 16:37 UTC, nunocorreia-ms commented
@tseward thanks for the review and the feedback! Yes the cmdlet will ship with the break parameter. Screenshot from the 4.8.1-preview release:

![image](https://user-images.githubusercontent.com/112094975/197578383-a7a5acf4-b101-442f-bbd6-dbe48d9f7f72.png)

The related cmdlets also have this parameter, but I'll check internally if it makes sense to remove it and I'll update the doc ;)

2022-10-25 04:05 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +This cmdlet updates a Shifts connection instance. Simillarly to the Update-CsTeamsShiftsConnectionInstance cmdlet, it allows the admin to make changes to the settings in the instance such as name, en
```suggestion
This cmdlet updates a Shifts connection instance. Similar to the Update-CsTeamsShiftsConnectionInstance cmdlet, it allows the admin to make changes to the settings in the instance such as name, enabled scenarios, and sync frequency. The complete list of fields is not required allowing the user to update single fields of the instance.
```

2022-10-25 04:06 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +Updates the instance with the specified -ConnectorInstanceId with the given name and sync frequency. Returns the object of updated connector instance.
```suggestion
Updates the instance with the specified -ConnectorInstanceId with the given name and sync frequency. Returns the object of the updated connector instance.
```

2022-10-25 04:06 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +Updates the instance with the specified -ConnectorInstanceId with the new api url. Returns the object of updated connector instance.
```suggestion
Updates the instance with the specified -ConnectorInstanceId with the new API URL. Returns the object of the updated connector instance.
```

2022-10-25 04:06 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +In case of error, we can capture the error response as following:
```suggestion
In case of an error, we can capture the error response as follows:
```

2022-10-25 04:06 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +* To get the entire error message in Json: `$result.ToJsonString()`
```suggestion
* To get the entire error message in JSON: `$result.ToJsonString()`
```

2022-10-25 04:06 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +The request body
```suggestion
The request body.
```

2022-10-25 04:07 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +Wait for .NET debugger to attach
```suggestion
Wait for the .NET debugger to attach.
```

2022-10-25 04:07 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +The connector instance id
```suggestion
The connector instance ID.
```

2022-10-25 04:07 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +The connector specific settings
```suggestion
The connector-specific settings.
```

2022-10-25 04:07 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +The designated actor id that App acts as for Shifts Graph Api calls.
```suggestion
The designated actor ID that App acts as for Shifts Graph API calls.
```

2022-10-25 04:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +The connector enabled scenarios that are synced from WFM system to Shifts in MS Teams.
```suggestion
The connector-enabled scenarios that are synced from the WFM system to Shifts in Microsoft Teams.
```

2022-10-25 04:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +The WFI enabled scenarios that are synced from Shifts in MS Teams to WFM system.
```suggestion
The WFI-enabled scenarios that are synced from Shifts in Microsoft Teams to the WFM system.
```

2022-10-25 04:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +SendAsync Pipeline Steps to be appended to the front of the pipeline
```suggestion
SendAsync Pipeline Steps to be appended to the front of the pipeline.
```

2022-10-25 04:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +SendAsync Pipeline Steps to be prepended to the front of the pipeline
```suggestion
SendAsync Pipeline Steps to be prepended to the front of the pipeline.
```

2022-10-25 04:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +The value of the etag field as returned by the cmdlets
```suggestion
The value of the ETag field as returned by the cmdlets.
```

2022-10-25 04:09 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +The URI for the proxy server to use
```suggestion
The URI for the proxy server to use.
```

2022-10-25 04:09 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +Credentials for a proxy server to use for the remote call
```suggestion
Credentials for a proxy server to use for the remote call.
```

2022-10-25 04:09 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md
> +Use the default credentials for the proxy
```suggestion
Use the default credentials for the proxy.
```

2022-10-25 04:15 UTC, JohanFreelancer9 requested changes
Copy review - @nunocorreia-ms, kindly commit the minor suggested changes. Many thanks.

2022-10-25 08:43 UTC, opbld31 commented
Learn Build status updates of commit _[64d56af](https://github.com/nunocorreia-ms/office-docs-powershell/commits/64d56af43eb0e51658fbf2641b87708794e86f65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |
[teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md](https://github.com/nunocorreia-ms/office-docs-powershell/blob/main/teams/teams-ps/teams/Update-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/update-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-10073) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202210250839239457-10073/BuildReport?accessString=af5c77477c1b222c33f93d16280e0f1eaadb2e8ca5ab5b56683bae260f20ead9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-25 08:52 UTC, nunocorreia-ms commented
@JohanFreelancer9 really appreciate the review! I have committed all the suggested changes. Thank you for the help :)

2022-10-25 10:33 UTC, JohanFreelancer9 approved these changes

2022-10-26 12:21 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-10-26 17:10 UTC, merged