adding missing params
MicrosoftDocs/office-docs-powershell pull request #10128
Opened 2022-11-08 15:42 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/10024

2022-11-08 15:47 UTC, opbld32 commented
Learn Build status updates of commit _[8cecb30](https://github.com/get-itips/office-docs-powershell/commits/8cecb3007ac1921e076a02df75f1744f6823fcf9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantNetworkSite.md](https://github.com/get-itips/office-docs-powershell/blob/patch-395/skype/skype-ps/skype/Set-CsTenantNetworkSite.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-cstenantnetworksite?view=skype-ps&branch=pr-en-us-10128) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202211081542384662-10128/BuildReport?accessString=fa647525a92c768d6a773c345ef96786bae683ca1ee9c4bd09b4a1c705ded016).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-08 15:50 UTC, opbld31 commented
Learn Build status updates of commit _[1128289](https://github.com/get-itips/office-docs-powershell/commits/1128289674446b23e03d8597489da7a0c18bea99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantNetworkSite.md](https://github.com/get-itips/office-docs-powershell/blob/patch-395/skype/skype-ps/skype/Set-CsTenantNetworkSite.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-cstenantnetworksite?view=skype-ps&branch=pr-en-us-10128) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202211081544431805-10128/BuildReport?accessString=ed71161bf3bdd709679ddadac239610975cb75cb3de833b6666a2fabad4cb26a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 08:55 UTC, yogkumgit commented
@JohanFreelancer9

2022-11-09 09:33 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTenantNetworkSite.md
> +This parameter is used to assign a custom emergency calling policy to a network site. For more information see [Assign a custom emergency calling policy to a network site](/microsoftteams/manage-emer
```suggestion
This parameter is used to assign a custom emergency calling policy to a network site. For more information, see [Assign a custom emergency calling policy to a network site](/microsoftteams/manage-emergency-calling-policies#assign-a-custom-emergency-calling-policy-to-a-network-site).
```

2022-11-09 09:34 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-09 14:50 UTC, opbld31 commented
Learn Build status updates of commit _[57ce2a2](https://github.com/get-itips/office-docs-powershell/commits/57ce2a2e40e361def6d755bce6186ba581998760)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantNetworkSite.md](https://github.com/get-itips/office-docs-powershell/blob/patch-395/skype/skype-ps/skype/Set-CsTenantNetworkSite.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-cstenantnetworksite?view=skype-ps&branch=pr-en-us-10128) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202211091447106517-10128/BuildReport?accessString=87a45a26482e34412f6b10a127308175af3967d5dba23a93b0c0a26696dc019d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 14:54 UTC, opbld31 commented
Learn Build status updates of commit _[a41faf9](https://github.com/get-itips/office-docs-powershell/commits/a41faf97ad80124f36955832132da8eaf49c1e2d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantNetworkSite.md](https://github.com/get-itips/office-docs-powershell/blob/patch-395/skype/skype-ps/skype/Set-CsTenantNetworkSite.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-cstenantnetworksite?view=skype-ps&branch=pr-en-us-10128) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202211091447173995-10128/BuildReport?accessString=d3daa66fed6402daa9f072fc315802ab7ce0e72609c3bd49aa2d4488c62e0b6a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-11-09 17:10 UTC, tseward approved these changes

2022-11-09 17:40 UTC, dariomws approved these changes

2022-11-10 05:37 UTC, yogkumgit commented
@JohanFreelancer9

2022-11-10 06:27 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-11-10 16:50 UTC, merged