Update New-CsTeamsVoiceApplicationsPolicy.md
MicrosoftDocs/office-docs-powershell pull request #10196
Opened 2022-12-01 22:52 UTC by JianpingChen

Update New-CsTeamsVoiceApplicationsPolicy.md with documentation for new settings

2022-12-01 22:55 UTC, opbld30 commented
Learn Build status updates of commit _[f394eda](https://github.com/JianpingChen/office-docs-powershell/commits/f394edac075157a23de1fbdea1dbebfce019589c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md](https://github.com/JianpingChen/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/new-csteamsvoiceapplicationspolicy?view=teams-ps&branch=pr-en-us-10196) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212012252025121-10196/BuildReport?accessString=878353334029e264f539bc5a7322b14e3a43cbe4f48c8db583dc9565889168d0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 00:37 UTC, opbld30 commented
Learn Build status updates of commit _[a538080](https://github.com/JianpingChen/office-docs-powershell/commits/a53808077f04095bdd99eb5f1b2e54cadba7cb3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md](https://github.com/JianpingChen/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/new-csteamsvoiceapplicationspolicy?view=teams-ps&branch=pr-en-us-10196) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212020034068450-10196/BuildReport?accessString=aeb96f54d0f1a63b6ad6e4e76a1057e65016708a98f4f069e2b775c13eea297e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-02 15:31 UTC, yogkumgit commented
@JohanFreelancer9

2022-12-02 15:32 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-12-02 16:45 UTC, tseward requested changes

2022-12-02 16:45 UTC, tseward commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +```ps
For the Syntax section, I believe it should not have a language specifier (`ps`, in this case).

2022-12-02 18:09 UTC, get-itips commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +```ps
please whenever  you intend to use powershell code block use powershell instead of ps

2022-12-02 22:31 UTC, dariomws reviewed
Agree with suggested updates.

2022-12-05 04:48 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +This parameter allows supervisors and users to change auto attendants' business hour schedule.
```suggestion
This parameter allows supervisors and users to change auto attendants' business hours schedule.
```

2022-12-05 04:49 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +This parameter allows supervisors and users to change auto attendants' business hour call flow.
```suggestion
This parameter allows supervisors and users to change auto attendants' business hours call flow.
```

2022-12-05 04:50 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +This parameter allows supervisors and users to change auto attendants' after-hour call flow.
```suggestion
This parameter allows supervisors and users to change auto attendants' after-hours call flow.
```

2022-12-05 04:51 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +This parameter allows supervisors and users to change the call queue opt-out setting that allows agents to opt-out of receiving calls.
```suggestion
This parameter allows supervisors and users to change the call queue opt-out setting that allows agents to opt out of receiving calls.
```

2022-12-05 04:55 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +When set to Whisper, users affected by the policy will be allowed to monitor call sessions and whisper to agent in the call.
```suggestion
When set to Whisper, users affected by the policy will be allowed to monitor call sessions and whisper to an agent in the call.
```

2022-12-05 04:55 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +When set to Barge, users affected by the policy will be allowed to monitor call sessions, whisper to agent in the call, or join the call session.
```suggestion
When set to Barge, users affected by the policy will be allowed to monitor call sessions, whisper to an agent in the call, or join the call session.
```

2022-12-05 04:56 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +When set to Barge, users affected by the policy will be allowed to monitor call sessions, whisper to agent in the call, or join the call session.
```suggestion
When set to Barge, users affected by the policy will be allowed to monitor call sessions, whisper to an agent in the call, or join the call session.
```

2022-12-05 04:56 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +When set to Takeover, users affected by the policy will be allowed to monitor call sessions, whisper to agent in the call, join the call session, or take over the call from agent.
```suggestion
When set to Takeover, users affected by the policy will be allowed to monitor call sessions, whisper to an agent in the call, join the call session, or take over the call from an agent.
```

2022-12-05 04:59 UTC, JohanFreelancer9 requested changes
Copy review - @JianpingChen, kindly commit the suggested changes. Many thanks.

2022-12-08 14:00 UTC, yogkumgit commented
@JianpingChen Gentle reminder

2022-12-12 06:09 UTC, yogkumgit commented
@JianpingChen Please implement the suggested changes, so that we can proceed to merge this PR. Thanks

2022-12-16 11:53 UTC, yogkumgit commented
@JianpingChen Please respond and implement the suggested changes, in the even of no reply we may close this PR. Thanks

2022-12-19 11:29 UTC, yogkumgit commented
@tiburd kindly help. Thanks

2022-12-19 17:21 UTC, opbld32 commented
Learn Build status updates of commit _[4e9f640](https://github.com/JianpingChen/office-docs-powershell/commits/4e9f6402f609f95a3eeb00b600a38ae17796a773)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md](https://github.com/JianpingChen/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/new-csteamsvoiceapplicationspolicy?view=teams-ps&branch=pr-en-us-10196) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212191717528537-10196/BuildReport?accessString=da9915479ba271afee1e413b136237458ddb4093372bd0e4c4d44b5f41cde585).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-19 17:25 UTC, opbld33 commented
Learn Build status updates of commit _[e6b1b03](https://github.com/JianpingChen/office-docs-powershell/commits/e6b1b030a79d2388ee89cdcef147f6d9f0a8fb8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md](https://github.com/JianpingChen/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/new-csteamsvoiceapplicationspolicy?view=teams-ps&branch=pr-en-us-10196) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212191720050262-10196/BuildReport?accessString=35448d9f2096159d7ebb72f58760fa2b30581cbb373d6a92739316134304dac1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-19 20:51 UTC, opbld30 commented
Learn Build status updates of commit _[57978fd](https://github.com/JianpingChen/office-docs-powershell/commits/57978fdab998c107a06f0e3740fdc9238faea09d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md](https://github.com/JianpingChen/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/new-csteamsvoiceapplicationspolicy?view=teams-ps&branch=pr-en-us-10196) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212192048232372-10196/BuildReport?accessString=78674b87523d63b27605d31b27f9178226685e59118d23288e7a636ec6cceb94).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-20 06:22 UTC, JohanFreelancer9 approved these changes

2022-12-20 10:42 UTC, yogkumgit commented
@dariomws @get-itips @tseward

2022-12-20 11:04 UTC, dariomws approved these changes

2022-12-20 11:21 UTC, get-itips approved these changes

2022-12-20 14:00 UTC, merged