Adding teams info
MicrosoftDocs/office-docs-powershell pull request #10224
Opened 2022-12-08 11:39 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/10169

2022-12-08 11:43 UTC, opbld31 commented
Learn Build status updates of commit _[2766a7a](https://github.com/get-itips/office-docs-powershell/commits/2766a7a0aed78ca735de1b022bb06ed6fd83b7a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsPrivacyConfiguration.md](https://github.com/get-itips/office-docs-powershell/blob/patch-400/skype/skype-ps/skype/Set-CsPrivacyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-csprivacyconfiguration?view=skype-ps&branch=pr-en-us-10224) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212081139542187-10224/BuildReport?accessString=eee6832817d20f2e074f7ed420e2846a503e67a34b6490b719ce9cd89e034ead).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-08 14:57 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsPrivacyConfiguration.md
> +For information regarding privacy mode in Microsoft Teams, see [User presence in Teams](/microsoftteams/presence-admins)
```suggestion
For information regarding privacy mode in Microsoft Teams, see [User presence in Teams](/microsoftteams/presence-admins).
```

2022-12-08 14:58 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-08 15:42 UTC, dariomws approved these changes

2022-12-12 06:12 UTC, yogkumgit commented
@get-itips

2022-12-12 11:58 UTC, opbld33 commented
Learn Build status updates of commit _[2e88c44](https://github.com/get-itips/office-docs-powershell/commits/2e88c44a662121f2649f014270eccee491867d31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsPrivacyConfiguration.md](https://github.com/get-itips/office-docs-powershell/blob/patch-400/skype/skype-ps/skype/Set-CsPrivacyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-csprivacyconfiguration?view=skype-ps&branch=pr-en-us-10224) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212121155430126-10224/BuildReport?accessString=04346e5bf699edb01c3401cfe8678a5e8413cd634d5c3c40c81573ad85cf8b81).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-12 17:52 UTC, tseward approved these changes

2022-12-13 10:05 UTC, yogkumgit commented
@tiburd Please merge this Pr. Thanks

2022-12-13 15:37 UTC, tiburd commented on skype/skype-ps/skype/Set-CsPrivacyConfiguration.md
> +For information regarding privacy mode in Microsoft Teams, see [User presence in Teams](/microsoftteams/presence-admins).
```suggestion
For information about privacy mode in Microsoft Teams, see [User presence in Teams](/microsoftteams/presence-admins).
```

2022-12-13 15:41 UTC, opbld30 commented
Learn Build status updates of commit _[4191d66](https://github.com/get-itips/office-docs-powershell/commits/4191d660d5aa3a5a784491d006c0d5c0da2ac1fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsPrivacyConfiguration.md](https://github.com/get-itips/office-docs-powershell/blob/patch-400/skype/skype-ps/skype/Set-CsPrivacyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-csprivacyconfiguration?view=skype-ps&branch=pr-en-us-10224) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212131537404700-10224/BuildReport?accessString=88fe075fc78e9b84b70100e4c19965cdd1863226dbdb02dc596e470d8a932262).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-13 15:41 UTC, merged