Added more examples and explanations
MicrosoftDocs/office-docs-powershell pull request #10272
Opened 2022-12-21 13:18 UTC by JensTrier

Updated Set-CsTeamsEmergencyCallRoutingPolicy with more examples and add link to Get. Ensured other pages for '-CsTeamsEmergencyCallRoutingPolicy also referenced the Get cmdlet.

Added more explanation to Get-CsOnlineDialOutPolicy and updated syntax

2022-12-21 13:22 UTC, opbld30 commented
Learn Build status updates of commit _[8c055a3](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/8c055a3063ad7cf1f3d516492601abbcacf9cf20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/get-csonlinedialoutpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Grant-CsDialoutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Grant-CsDialoutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/grant-csdialoutpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/grant-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/New-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Remove-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Remove-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/remove-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Set-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212211318048684-10272/BuildReport?accessString=081a04d71ece27f85e61aa2b8567c1ada3dd43e707cabe000835c0f807e4c11a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 04:48 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md
> +In Microsoft Teams, outbound calling restriction policies are used to restrict the type of audio conferencing and end user PSTN calls that can be made by users in your organization. The policies appl
```suggestion
In Microsoft Teams, outbound calling restriction policies are used to restrict the type of audio conferencing and end user PSTN calls that can be made by users in your organization. The policies apply to all the different PSTN connectivity options for Microsoft Teams; Calling Plan, Direct Routing, and Operator Connect.
```

2022-12-22 04:48 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsDialoutPolicy.md
> +In Microsoft Teams, outbound calling restriction policies are used to restrict the type of audio conferencing and end user PSTN calls that can be made by users in your organization. The policies appl
```suggestion
In Microsoft Teams, outbound calling restriction policies are used to restrict the type of audio conferencing and end user PSTN calls that can be made by users in your organization. The policies apply to all the different PSTN connectivity options for Microsoft Teams; Calling Plan, Direct Routing, and Operator Connect.
```

2022-12-22 04:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md
> +This example assigns a Teams Emergency Call Routing policy(Test) to a user(user1).
```suggestion
This example assigns a Teams Emergency Call Routing policy (Test) to a user (user1).

```

2022-12-22 04:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md
> +This example assigns the Teams Emergency Call Routing policy(Test) to the members of the group sales@contoso.com.
```suggestion
This example assigns the Teams Emergency Call Routing policy (Test) to the members of the group sales@contoso.com.

```

2022-12-22 04:50 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

2022-12-22 07:39 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

Thanks @JohanFreelancer9 & done! Happy holidays and thanks for your awesome help during 2022.

2022-12-22 07:42 UTC, opbld32 commented
Learn Build status updates of commit _[3825d97](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/3825d972c2b1d691a70c495dfb9b3d8c42e23ce3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/get-csonlinedialoutpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Grant-CsDialoutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Grant-CsDialoutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/grant-csdialoutpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/grant-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/New-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Remove-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Remove-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/remove-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Set-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212220738121448-10272/BuildReport?accessString=2335572a9931b823294ccb9ffcb87a25a2ce169aca7feb38a8193d722e7d4d89).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 07:46 UTC, opbld32 commented
Learn Build status updates of commit _[9cc5b73](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/9cc5b73a92c238fa24715e5afb2afa60eb14e03c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Get-CsOnlineDialOutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/get-csonlinedialoutpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Grant-CsDialoutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Grant-CsDialoutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/grant-csdialoutpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Grant-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/grant-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/New-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Remove-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Remove-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/remove-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsEmergencyCallRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensUpdate1/skype/skype-ps/skype/Set-CsTeamsEmergencyCallRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallroutingpolicy?view=skype-ps&branch=pr-en-us-10272) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212220738434385-10272/BuildReport?accessString=d6c05b06eb8fcf0f96266e0673f23e7bb9f2cd2444fcdc7b84a9eb621f3e1322).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-22 11:11 UTC, yogkumgit commented
@JohanFreelancer9

2022-12-22 14:54 UTC, get-itips approved these changes

2022-12-22 15:04 UTC, JohanFreelancer9 commented
> > Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.
> 
> Thanks @JohanFreelancer9 & done! Happy holidays and thanks for your awesome help during 2022.

Thank you @JensTrier. Always a pleasure. Happy holidays to you too!

2022-12-22 15:05 UTC, JohanFreelancer9 approved these changes

2022-12-22 17:19 UTC, tseward approved these changes

2022-12-23 11:58 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-12-27 17:34 UTC, merged