add option to MembershipType
MicrosoftDocs/office-docs-powershell pull request #10274
Opened 2022-12-22 15:07 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/10250

2022-12-22 15:11 UTC, opbld31 commented
Learn Build status updates of commit _[01a0e46](https://github.com/get-itips/office-docs-powershell/commits/01a0e46b1f4bd93497a1189419a8130f72161a3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-TeamChannel.md](https://github.com/get-itips/office-docs-powershell/blob/patch-402/teams/teams-ps/teams/New-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps&branch=pr-en-us-10274) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212221507154355-10274/BuildReport?accessString=715d33fa6ffab092668faf2622cb63edac0f46ff0f0539e85da8f34b4a286c79).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-23 06:27 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-TeamChannel.md
> +Channel membership type, Standard, Shared or Private.
```suggestion
Channel membership type, Standard, Shared, or Private.
```

2022-12-23 06:27 UTC, JohanFreelancer9 requested changes
Copy review.

2022-12-23 11:59 UTC, yogkumgit commented
@get-itips

2022-12-23 12:28 UTC, opbld31 commented
Learn Build status updates of commit _[f2a0549](https://github.com/get-itips/office-docs-powershell/commits/f2a05494bdbce2af05901eda8e783a2187258581)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-TeamChannel.md](https://github.com/get-itips/office-docs-powershell/blob/patch-402/teams/teams-ps/teams/New-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/new-teamchannel?view=teams-ps&branch=pr-en-us-10274) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202212231225141840-10274/BuildReport?accessString=8145c97d531aca79a64c0e5caa58d6ef77f902fbabfe5fdf702b31d8faf97108).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-23 12:53 UTC, yogkumgit commented
@JohanFreelancer9

2022-12-23 15:18 UTC, JohanFreelancer9 approved these changes

2022-12-23 16:11 UTC, tseward approved these changes

2023-01-02 14:24 UTC, yogkumgit commented
@dariomws

2023-01-04 13:37 UTC, yogkumgit commented
@dariomws Please review. Thanks

2023-01-04 13:50 UTC, dariomws approved these changes

2023-01-05 11:20 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-01-05 17:27 UTC, merged