Update Get-CsOnlineVoiceUser.md
MicrosoftDocs/office-docs-powershell pull request #10443
Opened 2023-02-08 14:25 UTC by ckarawani

This command is no longer supported. Deprecated implies it would still be supported and would serve as a warning to move to new cmdlet.

2023-02-09 06:23 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineVoiceUser.md
> +**Note**: This cmdlet **is not longer supported** on the public and GCC cloud instances. You should use the replacement cmdlets described here.
```suggestion
**Note**: This cmdlet **is no longer supported** on the public and GCC cloud instances. You should use the replacement cmdlets described here.
```

2023-02-09 06:24 UTC, JohanFreelancer9 requested changes
Copy review - @ckarawani, kindly commit the suggested change. Many thanks.

2023-02-09 20:41 UTC, dariomws approved these changes
I'm fine after @JohanFreelancer9 suggestion.

2023-02-09 20:42 UTC, dariomws commented
@ckarawani, if you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html 

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=ckarawani

2023-02-10 14:13 UTC, get-itips approved these changes

2023-02-10 14:49 UTC, JohanFreelancer9 approved these changes

2023-02-12 06:16 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-02-13 17:10 UTC, merged