Update Set-CsTeamsCallingPolicy.md
MicrosoftDocs/office-docs-powershell pull request #10460
Opened 2023-02-14 21:06 UTC by nitinjaitely

Making the changes to the note for clarity.

2023-02-15 07:28 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
> +Setting this parameter lets you configure how incoming calls are handled when a user is already in a call or conference or has a call placed on hold. Valid options are: Enabled, Unanswered, and Disab
```suggestion
Setting this parameter lets you configure how incoming calls are handled when a user is already in a call or conference or has a call placed on hold. Valid options are: Enabled, Unanswered, and Disabled. When set to Enabled, new or incoming calls will be rejected with a busy signal. When set to Unanswered, the user's unanswered settings will take effect, such as routing to voicemail or forwarding to another user. Note: The userOverride setting is not currently available for use. The setting will be treated as disabled even if it is configured.
```

2023-02-15 07:29 UTC, JohanFreelancer9 requested changes
Copy review - @nitinjaitely, kindly commit the suggested change. Many thanks.

2023-02-20 12:01 UTC, yogkumgit commented
@nitinjaitely Gentle reminder.

2023-02-27 13:29 UTC, yogkumgit commented
@nitinjaitely kindly implement the suggested changes, else we may proceed to close this PR. Thanks

2023-02-28 16:18 UTC, get-itips approved these changes

2023-03-01 11:24 UTC, yogkumgit commented
@dariomws

2023-03-01 11:26 UTC, yogkumgit commented
@nitinjaitely Closing as it is same as #10460

2023-03-01 11:26 UTC, closed without merging