Various updates
MicrosoftDocs/office-docs-powershell pull request #10511
Opened 2023-02-24 13:47 UTC by JensTrier

Updating *-CsOnlineApplicationInstance with new syntax, references and mention 3rd party application id's.

Adding documentation for Extended Notifications for Teams emergency calling policy.

Adding more information about GroupNotificationOverride to Set-CsUserCallingSettings

2023-02-24 14:15 UTC, yogkumgit commented
@JohanFreelancer9

2023-02-25 10:13 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineApplicationInstance.md
> +Skips the first X returned results and the default value is 0.
```suggestion
Skips the first specified number of returned results. The default value is 0.
```

2023-02-25 10:13 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsOnlineApplicationInstance.md
> +The application ID. The Microsoft application Auto Attendant has the ApplicationId ce933385-9390-45d1-9512-c8d228074e07 and the Microsoft application Call Queue has the ApplicationId 11cd3e2e-fccb-42
```suggestion
The application ID. The Microsoft application Auto Attendant has the ApplicationId ce933385-9390-45d1-9512-c8d228074e07 and the Microsoft application Call Queue has the ApplicationId 11cd3e2e-fccb-42ad-ad00-878b93575e07. Third-party applications available in a tenant will use other ApplicationId's.
```

2023-02-25 10:14 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingExtendedNotification.md
> +This cmdlet supports creating specific emergency calling notification settings per emergency phone number. Used with TeamsEmergencyCallingPolicy.
```suggestion
This cmdlet supports creating specific emergency calling notification settings per emergency phone number. It is used with TeamsEmergencyCallingPolicy.

```

2023-02-25 10:16 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingExtendedNotification.md
> +Creates an extended emergency calling notfication for emergency phone number 911 and stores it in the variable $en1. The variable should afterwards be added to a TeamsEmergencyCallingPolicy instance.
```suggestion
Creates an extended emergency calling notification for the emergency phone number 911 and stores it in the variable $en1. The variable should be added afterward to a TeamsEmergencyCallingPolicy instance.

```

2023-02-25 10:17 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingExtendedNotification.md
> +NotificationGroup is a email list of users and groups to be notified of an emergency call. Individual users or groups are separated by ";", for instance "group1@contoso.com;group2@contoso.com". A max
```suggestion
NotificationGroup is an email list of users and groups to be notified of an emergency call. Individual users or groups are separated by ";", for instance, "group1@contoso.com;group2@contoso.com". A maximum of 50 users can be notified.

```

2023-02-25 10:18 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
> +This example creates a Teams Emergency Calling policy that has an identity of TestECP2, with default settings except for the Notification Group. This parameter expects a single string with all users
```suggestion
This example creates a Teams Emergency Calling policy that has an identity of TestECP2, with default settings, except for the Notification Group. This parameter expects a single string with all users and groups separated by ";".
```

2023-02-25 10:18 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
> +This example creates specifc emergency calling notification settings for two emergency phone numbers and adds them to the existing TestECP3 policy instance.
```suggestion
This example creates specific emergency calling notification settings for two emergency phone numbers and adds them to the existing TestECP3 policy instance.
```

2023-02-25 10:18 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
> +This example removes a specifc emergency calling notification setting from the existing TestECP3 policy instance.
```suggestion
This example removes a specific emergency calling notification setting from the existing TestECP3 policy instance.
```

2023-02-25 10:19 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
> +This parameter represents the PSTN number which can be dialed out if NotificationMode is set to either of the two Conference values.  The PSTN phone cannot be unmuted even when the NotificationMode i
```suggestion
This parameter represents the PSTN number which can be dialed out if NotificationMode is set to either of the two Conference values. The PSTN phone cannot be unmuted even when the NotificationMode is set to ConferenceUnMuted.
```

2023-02-25 10:19 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
> +This example shows updating ApplicationId and DisplayName information for an existing Auto Attendant application instance with Identity "appinstance01@contoso.com".
```suggestion
This example shows updated ApplicationId and DisplayName information for an existing Auto Attendant application instance with Identity "appinstance01@contoso.com".
```

2023-02-25 10:20 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsOnlineApplicationInstance.md
> +The application ID. The Microsoft application Auto Attendant has the ApplicationId ce933385-9390-45d1-9512-c8d228074e07 and the Microsoft application Call Queue has the ApplicationId 11cd3e2e-fccb-42
```suggestion
The application ID. The Microsoft application Auto Attendant has the ApplicationId ce933385-9390-45d1-9512-c8d228074e07 and the Microsoft application Call Queue has the ApplicationId 11cd3e2e-fccb-42ad-ad00-878b93575e07. Third-party applications available in a tenant will use other ApplicationId's.
```

2023-02-25 10:20 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
> +This example creates specifc emergency calling notification settings for two emergency phone numbers and adds them to the existing TestECP policy instance.
```suggestion
This example creates specific emergency calling notification settings for two emergency phone numbers and adds them to the existing TestECP policy instance.
```

2023-02-25 10:20 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
> +This example removes a specifc emergency calling notification setting from the existing TestECP policy instance.
```suggestion
This example removes a specific emergency calling notification setting from the existing TestECP policy instance.
```

2023-02-25 10:21 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
> +Enable ExternalLocationLookupMode. This mode allow users to set Emergency addresses for remote locations.
```suggestion
Enables ExternalLocationLookupMode. This mode allows users to set Emergency addresses for remote locations.
```

2023-02-25 10:21 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Sync-CsOnlineApplicationInstance.md
> +The application ID. The Microsoft application Auto Attendant has the ApplicationId ce933385-9390-45d1-9512-c8d228074e07 and the Microsoft application Call Queue has the ApplicationId 11cd3e2e-fccb-42
```suggestion
The application ID. The Microsoft application Auto Attendant has the ApplicationId ce933385-9390-45d1-9512-c8d228074e07 and the Microsoft application Call Queue has the ApplicationId 11cd3e2e-fccb-42ad-ad00-878b93575e07. Third-party applications available in a tenant will use other ApplicationId's.
```

2023-02-25 10:22 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsUserCallingSettings.md
> +The initial setting is shown as Null. It means that the group notification set for the user in the call group is used. If you set GroupNotificationOverride to Mute, that setting will override the gro
```suggestion
The initial setting is shown as Null. It means that the group notification set for the user in the call group is used. If you set GroupNotificationOverride to Mute, that setting will override the group notification for the user in the call group. If you set the GroupNotificationOverride to Ring or Banner, the group notification set for the user in the call group will be used.

```

2023-02-25 10:29 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

2023-02-25 14:04 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

Thanks! Done

2023-02-26 06:12 UTC, JohanFreelancer9 approved these changes

2023-02-26 20:42 UTC, dariomws approved these changes

2023-02-27 10:41 UTC, JensTrier commented
@JohanFreelancer9 @tseward @dariomws Sorry for the extra work, but I updated the PR with 2 new examples in Get-CsPhoneNumberAssignment. Please have a look.

2023-02-27 13:31 UTC, yogkumgit commented
@get-itips Please review. Thanks

2023-02-27 17:06 UTC, get-itips approved these changes

2023-02-28 12:58 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-02-28 15:59 UTC, merged