Update description for BusyOnBusyEnabledType
MicrosoftDocs/office-docs-powershell pull request #10526
Opened 2023-02-28 01:31 UTC by xinawang

As userOverride option is going to be rolled out in general, updating the description for the parameter

2023-02-28 06:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md
> +Setting this parameter lets you configure how incoming calls are handled when a user is already in a call or conference or has a call placed on hold. Valid options are: Enabled, Unanswered Disabled,
```suggestion
Setting this parameter lets you configure how incoming calls are handled when a user is already in a call or conference or has a call placed on hold. Valid options are: Enabled, Unanswered, Disabled, and UserOverride. When set to Enabled, new or incoming calls will be rejected with a busy signal. When set to Unanswered, the user's unanswered settings will take effect, such as routing to voicemail or forwarding to another user. When set to UserOverride, users can set their busy options directly from call settings in Teams app. 
```

2023-02-28 06:50 UTC, JohanFreelancer9 requested changes
Copy review - @xinawang, kindly commit the suggested changes. Naby thanks.

2023-03-01 04:45 UTC, JohanFreelancer9 approved these changes

2023-03-02 01:48 UTC, dariomws approved these changes

2023-03-02 12:09 UTC, yogkumgit commented
@tseward

2023-03-02 23:54 UTC, xinawang commented
@tseward can I get a sign off? what else is needed to merge?

2023-03-03 11:31 UTC, yogkumgit commented
@tiburd Please merge this Pr. Thanks

2023-03-03 17:12 UTC, merged