Update Set-CsCallQueue.md
MicrosoftDocs/office-docs-powershell pull request #10548
Opened 2023-03-01 21:42 UTC by CLYVR

Adding new AuthorizedUsers parameter

2023-03-01 21:50 UTC, CLYVR commented
@get-itips @dariomws @tseward @tiburd Please and thanks

2023-03-02 01:50 UTC, dariomws approved these changes

2023-03-02 11:09 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsCallQueue.md
> +This is a list of user GUIDs who are authorized to make changes to this call queue.  The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with 4 dashe
```suggestion
This is a list of GUIDs of users who are authorized to make changes to this call queue.  The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with four dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). 
```

2023-03-02 11:11 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsCallQueue.md
> +This is a list of user GUIDs who are authorized to make changes to this call queue.  The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with 4 dashe
```suggestion
This is a list of GUIDs of users who are authorized to make changes to this call queue.  The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with four dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). 
```

2023-03-02 11:12 UTC, JohanFreelancer9 requested changes
Copy review - @CLYVR, kindly commit the suggested changes. Many thanks.

2023-03-02 13:50 UTC, tiburd commented on skype/skype-ps/skype/New-CsCallQueue.md
> +This is a list of user GUIDs who are authorized to make changes to this call queue.  The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with 4 dashe
```suggestion
This is a list of GUIDs for users who are authorized to make changes to this call queue.  The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). 
```

2023-03-02 13:53 UTC, tiburd commented on skype/skype-ps/skype/Set-CsCallQueue.md
> +This is a list of user GUIDs who are authorized to make changes to this call queue.  The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with 4 dashe
```suggestion
This is a list of GUIDs for users who are authorized to make changes to this call queue.  The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). 
```

2023-03-02 13:55 UTC, tiburd commented on skype/skype-ps/skype/New-CsCallQueue.md
> +This is a list of GUIDs for users who are authorized to make changes to this call queue. The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with 4 d
```suggestion
This is a list of GUIDs for users who are authorized to make changes to this call queue. The users must also have a TeamsVoiceApplications policy assigned. The GUID should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). 
```

2023-03-02 13:56 UTC, tiburd commented on skype/skype-ps/skype/Set-CsCallQueue.md
> +This is a list of GUIDs for users who are authorized to make changes to this call queue. The users must also have a TeamsVoiceApplications policy assigned.  The GUID should contain 32 digits with 4 d
```suggestion
This is a list of GUIDs for users who are authorized to make changes to this call queue. The users must also have a TeamsVoiceApplications policy assigned. The GUID should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx). 
```

2023-03-02 13:58 UTC, tiburd commented
> Copy review - @CLYVR, kindly commit the suggested changes. Many thanks.

@CLYVR @JohanFreelancer9 
Thanks for the edit pass, Johan - I committed slightly adjusted edits based on your suggestions.

2023-03-02 15:38 UTC, JohanFreelancer9 approved these changes

2023-03-03 11:32 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-03-14 19:44 UTC, CLYVR commented
@tiburd Is there anything more needed from me on this or can this be merged?  Thanks!

2023-03-14 20:24 UTC, tiburd commented
@CLYVR 
Merging now. Sorry this fell through the cracks around the time I switched to a new device and Outlook format.....

2023-03-14 20:24 UTC, merged