Update Get-CsTeamsAppPermissionPolicy.md
MicrosoftDocs/office-docs-powershell pull request #10677
Opened 2023-03-30 07:37 UTC by xuanzhou4

Add some usage examples and parameters description for Get-CsTeamsAppPermissionPolicy.

2023-03-30 15:51 UTC, get-itips commented on skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
> +Get the Global Teams App Permission Policy.
Please move the description below the code

2023-03-30 15:55 UTC, dariomws requested changes

2023-03-30 15:55 UTC, dariomws commented on skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
> +Get the Global Teams App Permission Policy.
```suggestion
Get the Global Teams App Permission Policy.

```

2023-03-30 15:55 UTC, dariomws commented on skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
> +PrivateCatalogAppsType : AllowedAppList
Please use the output format:
https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide#executable-examples

Thanks!

2023-03-30 15:55 UTC, dariomws commented on skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
> +PrivateCatalogAppsType : AllowedAppList
Same here.

2023-03-30 15:55 UTC, dariomws commented on skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
> +Name of App setup permission policy.If empty, all Identities will be used by default.
```suggestion
Name of App setup permission policy. If empty, all Identities will be used by default.
```

2023-03-31 15:09 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
> +Get the Global Teams App Permission Policy.
```suggestion
Get the global Teams app permission policy.

```

2023-03-31 15:09 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsTeamsAppPermissionPolicy.md
> +Get all the Teams App Permission Policies.
```suggestion
Get all the Teams app permission policies.

```

2023-03-31 15:11 UTC, JohanFreelancer9 requested changes
Copy review - @xuanzhou4, kindy commit the suggested changes. Many thanks.

2023-04-04 10:33 UTC, yogkumgit commented
@JohanFreelancer9 @dariomws

2023-04-04 22:14 UTC, JohanFreelancer9 approved these changes

2023-04-05 12:13 UTC, yogkumgit commented
@dariomws

2023-04-05 17:28 UTC, dariomws approved these changes

2023-04-06 16:57 UTC, merged