EnableShiftPresence option no longer needed in -CsTeamsShiftsPolicy commands
MicrosoftDocs/office-docs-powershell pull request #10690
Opened 2023-04-04 14:55 UTC by martinicr

The Shifts Service team is no longer supporting _shifts based presence_ in their PS commands. You can contact the following MSFT alias for futher details:
- wblocker
- martinflores
- erkandurmaz
- andreagannon

2023-04-04 20:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsShiftsPolicy.md
> +This cmdlet allows you to get properties of a TeamsShiftPolicy instance. Use this to get the policy name, and Teams off shift warning message-specific settings (ShiftNoticeMessageType, ShiftNoticeMes
```suggestion
This cmdlet allows you to get properties of a TeamsShiftPolicy instance. Use this to get the policy name and Teams off shift warning message-specific settings (ShiftNoticeMessageType, ShiftNoticeMessageCustom, ShiftNoticeFrequency, AccessGracePeriodMinutes).

```

2023-04-04 20:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsShiftsPolicy.md
> +This cmdlet allows you to set or update properties of a TeamsShiftPolicy instance. Use this to set the policy name, and Teams off shift warning message-specific settings (ShiftNoticeMessageType, Shif
```suggestion
This cmdlet allows you to set or update properties of a TeamsShiftPolicy instance. Use this to set the policy name and Teams off shift warning message-specific settings (ShiftNoticeMessageType, ShiftNoticeMessageCustom, ShiftNoticeFrequency, AccessGracePeriodMinutes).

```

2023-04-04 20:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsShiftsPolicy.md
> +In this example, the policy instance is called "OffShiftAccess_WarningMessage1_AlwaysShowMessage", a warning message (Message 1) will be always be displayed to the user on opening Teams during off sh
```suggestion
In this example, the policy instance is called "OffShiftAccess_WarningMessage1_AlwaysShowMessage", a warning message (Message 1) will always be displayed to the user on opening Teams during off shift hours.

```

2023-04-04 20:15 UTC, JohanFreelancer9 requested changes
Copy review - @martinicr, kindly commit the minor suggested changes. Many thanks.

2023-04-06 07:21 UTC, yogkumgit commented
@JohanFreelancer9

2023-04-06 07:22 UTC, yogkumgit commented
@dariomws @get-itips @tseward

2023-04-06 10:29 UTC, dariomws commented
@yogkumgit,

@get-itips and @tiburd are trying to contact the list of aliases for further details.

2023-04-07 18:21 UTC, JohanFreelancer9 approved these changes

2023-04-17 08:21 UTC, yogkumgit commented
@get-itips Please update.

2023-04-17 15:51 UTC, get-itips commented
@yogkumgit Still no feedback

2023-04-17 17:10 UTC, tiburd commented
@get-itips @dariomws @tseward 
This PR is created by Martin Flores, @martinicr - if you need more information, please contact him.

Thanks!

2023-04-18 04:46 UTC, dariomws approved these changes

2023-04-18 11:11 UTC, yogkumgit commented
@tseward

2023-04-18 21:58 UTC, merged