Update CsTeamsComplianceRecordingPolicy
MicrosoftDocs/office-docs-powershell pull request #10734
Opened 2023-04-14 16:44 UTC by abnan

Updating documentation for CsTeamsComplianceRecordingPolicy to add new policy bit

2023-04-16 15:26 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsComplianceRecordingPolicy.md
> +Setting this attribute to true enables compliance recording for calls which have been re-routed from a compliance recording enabled user. Supported call scenarios include forward, transfer, delegatio
```suggestion
Setting this attribute to true enables compliance recording for calls that have been re-routed from a compliance recording-enabled user. Supported call scenarios include forward, transfer, delegation, call groups, and simultaneous ring.

```

2023-04-16 15:26 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md
> +Setting this attribute to true enables compliance recording for calls which have been re-routed from a compliance recording enabled user. Supported call scenarios include forward, transfer, delegatio
```suggestion
Setting this attribute to true enables compliance recording for calls that have been re-routed from a compliance recording-enabled user. Supported call scenarios include forward, transfer, delegation, call groups, and simultaneous ring.

```

2023-04-16 15:27 UTC, JohanFreelancer9 requested changes
Copy review - @abnan, kindly commit the suggested changes. Many thanks.

2023-04-17 05:51 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsComplianceRecordingPolicy.md
> +
```suggestion
```

2023-04-17 05:51 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md
> +
```suggestion
```

2023-04-17 05:52 UTC, JohanFreelancer9 requested changes
Apologies @abnan, please also commit these suggestions to remove the extra blank lines. Many thanks.

2023-04-17 06:49 UTC, JohanFreelancer9 approved these changes

2023-04-17 09:10 UTC, dariomws approved these changes

2023-04-18 11:05 UTC, yogkumgit commented
@get-itips @tseward

2023-04-18 13:21 UTC, get-itips approved these changes

2023-04-19 11:08 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-04-19 14:24 UTC, merged