Update Set-ThrottlingPolicyAssociation.md
MicrosoftDocs/office-docs-powershell pull request #10822
Opened 2023-05-09 06:05 UTC by v-smandalika

2023-05-10 08:09 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-ThrottlingPolicyAssociation.md
> +For remote mailbox, use the Set-RemoteMailbox -ExchangeGUID cmdlet, if ExchangeGUID isn't populated.
```suggestion
For remote mailboxes, use the Set-RemoteMailbox -ExchangeGUID cmdlet if ExchangeGUID isn't populated.
```

2023-05-10 08:11 UTC, JohanFreelancer9 requested changes
Copy review - @v-smandalika, kindly commit the suggested changes. Many thanks.

2023-05-10 11:02 UTC, JohanFreelancer9 approved these changes

2023-05-19 04:50 UTC, v-smandalika commented
Hi @AshaIyengar21 ,

Apologies I missed assigning this PR to you earlier, when I had emailed you this PR for a validation of my self-review changes.

Thanks,
@v-smandalika

2023-05-23 07:31 UTC, AshaIyengar21 commented on exchange/exchange-ps/exchange/Set-ThrottlingPolicyAssociation.md
> +In data center deployments, the Identity parameter-referred object and the ThrottlingPolicy parameter-referred object must be in the same tenant.
Please retain the previous sentence as is..your proposed change, changes the meaning of the sentence itself and hence seem to be inaccurate

2023-05-23 07:51 UTC, v-smandalika commented
Hi @claydetels19 ,

SME Bhalchandra Atre has approved the updates we have made in this PR; and, the internal-review comments have also been incorporated.

We are hereby assigning the PR to you for help in reviewing it and in assigning the Sign off label.


Thanks,
@v-smandalika

2023-05-23 15:29 UTC, merged