Update Set-CsTeamsVoiceApplicationsPolicy.md
MicrosoftDocs/office-docs-powershell pull request #10866
Opened 2023-05-19 00:38 UTC by CLYVR

Updates for new policy keys - also re-org'd to group into AA/CQ/Metrics

2023-05-19 01:24 UTC, CLYVR commented
@DaniEASmith Please and thank you!

2023-05-19 15:29 UTC, Stacyrch140 commented
Hi @CLYVR  - 

**Following is a blocking issue that needs to be resolved before we can merge:**

teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
- These articles don't have Acrolinx scorecards. 

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=main)

**Blocking**
- All articles in the PR have an Acrolinx score of 80 or higher. Limited exceptions are available. For more information, see [Minimum Acrolinx topic scores for publishing](https://review.learn.microsoft.com/en-us/office-authoring-guide/acrolinx-min-score).

***

After you resolve the blocking issues, remove the **Back to submitter** label and add the **Sign off** label again. 

If you need help resolving issues in this PR, post your question in the [Ask an Admin Teams Channel](https://teams.microsoft.com/l/channel/19%3aea9a561f603c4fbb9cf3931a6849eae4%40thread.skype/Ask%2520an%2520Admin?groupId=7079ffbf-1420-4ee2-9ddc-a2c351337320&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).


Thanks, 
Stacy

2023-05-19 15:32 UTC, DaniEASmith commented
> Hi @CLYVR -
> 
> **Following is a blocking issue that needs to be resolved before we can merge:**
> 
> teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
> 
> * These articles don't have Acrolinx scorecards.
> 
> **Reference**
> 
> [Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=main)
> 
> **Blocking**
> 
> * All articles in the PR have an Acrolinx score of 80 or higher. Limited exceptions are available. For more information, see [Minimum Acrolinx topic scores for publishing](https://review.learn.microsoft.com/en-us/office-authoring-guide/acrolinx-min-score).
> 
> After you resolve the blocking issues, remove the **Back to submitter** label and add the **Sign off** label again.
> 
> If you need help resolving issues in this PR, post your question in the [Ask an Admin Teams Channel](https://teams.microsoft.com/l/channel/19%3aea9a561f603c4fbb9cf3931a6849eae4%40thread.skype/Ask%2520an%2520Admin?groupId=7079ffbf-1420-4ee2-9ddc-a2c351337320&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).
> 
> Thanks, Stacy

How do we get Acrolinx scorecard to show up? This wasn't something that either of us removed. I don't know how that would occur.

2023-05-19 15:53 UTC, tiburd commented
This is a public repo PR; as of now, it's not expected to have an Acrolinx scorecard.

I manage a team of Upwork freelance partners who will review this PR; after it's approved, I'll merge it.

2023-05-19 17:32 UTC, CLYVR commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
>  New-CsTeamsVoiceApplicationsPolicy -Identity SDA-Allow-CQ-Moh -AllowCallQueueMusicOnHoldChange $true
@tseward The examples are meant to be directly executed.  Yes the identity would be unique to the cx's environment however identity is shown in other policies.  Happy to change if needed but just following what was already there / what is done elsewhere.

### -------------------------- Example 1 --------------------------
```
Set-CsOnlineVoicemailPolicy -Identity "CustomOnlineVoicemailPolicy" -MaximumRecordingLength ([TimeSpan]::FromSeconds(60))
```

### Example 1
```powershell
PS C:\> Set-CsTeamsShiftsPolicy -Identity OffShiftAccess_WarningMessage1_AlwaysShowMessage -ShiftNoticeMessageType Message1 -ShiftNoticeFrequency always -AccessGracePeriodMinutes 5
```

And in cmdlets:

### -------------------------- Example 1 -------------------------- 
```
Set-CsCallQueue -Identity e7e00636-47da-449c-a36b-1b3d6ee04440 -UseDefaultMusicOnHold $true
```

2023-05-21 10:12 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
```suggestion
```

2023-05-21 10:13 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +
```suggestion
```

2023-05-21 10:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +When set to `All`, users affected by the policy will receive real-time metrics for all auto attendants in the tenant.
```suggestion
When set to `All`, users affected by the policy will receive real-time metrics for all auto attendants in the organization.
```

2023-05-21 10:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +When set to `All`, users affected by the policy will receive real-time metrics for all call queues in the tenant.
```suggestion
When set to `All`, users affected by the policy will receive real-time metrics for all call queues in the organization.
```

2023-05-21 10:16 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +When set to `All`, users affected by the policy will receive real-time metrics for all agents in all queues call queues in the tenant.
```suggestion
When set to `All`, users affected by the policy will receive real-time metrics for all agents in all call queues in the organization.
```

2023-05-21 10:17 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
> +`TeamsVoiceApplicationsPolicy` is used for **Supervisor Delegated Administration** which allows tenant admins to permit certain users to make changes to auto attendant and call queue configurations.
```suggestion
`TeamsVoiceApplicationsPolicy` is used for **Supervisor Delegated Administration** which allows admins in the organization to permit certain users to make changes to auto attendant and call queue configurations.
```

2023-05-21 10:34 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
> +When set to `All`, users affected by the policy will receive real-time metrics for all auto attendants in the tenant.
```suggestion
When set to `All`, users affected by the policy will receive real-time metrics for all auto attendants in the organization.
```

2023-05-21 10:35 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
> +When set to `All`, users affected by the policy will receive real-time metrics for all call queues in the tenant.
```suggestion
When set to `All`, users affected by the policy will receive real-time metrics for all call queues in the organization.
```

2023-05-21 10:37 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsVoiceApplicationsPolicy.md
> +When set to `All`, users affected by the policy will receive real-time metrics for all agents in all queues call queues in the tenant.
```suggestion
When set to `All`, users affected by the policy will receive real-time metrics for all agents in all call queues in the organization.
```

2023-05-21 10:44 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsVoiceApplicationsPolicy.md
> +`TeamsVoiceApplicationsPolicy` is used for **Supervisor Delegated Administration** which allows tenant admins to permit certain users to make changes to auto attendant and call queue configurations.
```suggestion
`TeamsVoiceApplicationsPolicy` is used for **Supervisor Delegated Administration** which allows admins in the organization to permit certain users to make changes to auto attendant and call queue configurations.
```

2023-05-21 10:46 UTC, JohanFreelancer9 requested changes
Copy review - @CLYVR, kindly commit the suggested minor changes. Many thanks.

2023-05-22 09:02 UTC, dariomws approved these changes

2023-05-22 17:02 UTC, get-itips approved these changes

2023-05-22 22:49 UTC, merged