Update Set-TransportRule.md
MicrosoftDocs/office-docs-powershell pull request #10878
Opened 2023-05-24 13:03 UTC by m-nestorovic

Clarified what is required in order for message to be considered as InOrganization.

Work Item ID in the ADO: 3490530

2023-05-25 18:13 UTC, chrisda commented
Sorry, man. I thought I merged your changes, and I had a correction to make, so I did it in another PR, which is now conflicting with your PR.

So, closing your PR.

2023-06-05 08:28 UTC, m-nestorovic commented
No problem at all. I see that changes are applied so everything is good.

Thanks!

2023-06-05 09:19 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-TransportRule.md
> +- InOrganization: The message was sent or received over an authenticated connection **AND** the sender is a mailbox, mail user, group, or mail-enabled public folder in your organization, **OR** the s
```suggestion
- InOrganization: The message was sent or received over an authenticated connection *and* the sender is a mailbox, mail user, group, or mail-enabled public folder in your organization, *or* the sender's email address is in an accepted domain that's configured as an authoritative domain or an internal relay domain in your organization.
```

2023-06-05 09:19 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-TransportRule.md
> +- InOrganization: The message was sent or received over an authenticated connection **AND** the sender is a mailbox, mail user, group, or mail-enabled public folder in your organization, **OR** the s
```suggestion
- InOrganization: The message was sent or received over an authenticated connection *and* the sender is a mailbox, mail user, group, or mail-enabled public folder in your organization, *or* the sender's email address is in an accepted domain that's configured as an authoritative domain or an internal relay domain in your organization.
```

2023-06-05 09:20 UTC, JohanFreelancer9 requested changes
Copy review - @m-nestorovic, kindly commit the suggested changes. For reference, we do not use capitalization and bold type for emphasis. Many thanks.

2023-06-05 15:26 UTC, closed without merging