Update Get-CsOnlineUser.md
MicrosoftDocs/office-docs-powershell pull request #10889
Opened 2023-05-26 13:50 UTC by pbafna03

2023-05-27 09:29 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineUser.md
> +Sorting is now enabled in Teams PowerShell Module 5.1.0 and later by using the "-Sort" or "-OrderBy" parameters. This parameter is currently rolled out in commercial environments only. For Example:
```suggestion
Sorting is now enabled in Teams PowerShell Module 5.1.0 and later by using the "-Sort" or "-OrderBy" parameters. This parameter is currently rolled out in commercial environments only. For example:
```

2023-05-27 09:30 UTC, JohanFreelancer9 requested changes
Copy review - @pbafna03, kindly commit the minor suggested change. Many thanks.

2023-05-28 08:32 UTC, JohanFreelancer9 approved these changes

2023-05-29 08:41 UTC, dariomws approved these changes

2023-05-29 17:55 UTC, get-itips approved these changes

2023-05-30 10:47 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-05-30 18:49 UTC, merged