Update CsTeamsComplianceRecordingPolicy documentation due to rollback
MicrosoftDocs/office-docs-powershell pull request #10932
Opened 2023-06-09 18:49 UTC by abnan

2023-06-10 07:24 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsComplianceRecordingPolicy.md
> +Setting this attribute to true enables compliance recording for calls that have been re-routed from a compliance recording-enabled user. Supported call scenarios include forward, transfer, delegation
```suggestion
Setting this attribute to true enables compliance recording for calls that have been re-routed from a compliance recording-enabled user. Supported call scenarios include forward, transfer, delegation, call groups, and simultaneous ring. (Only available in Microsoft Teams PowerShell version 5.1.1-preview.)

```

2023-06-10 07:24 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md
> +Setting this attribute to true enables compliance recording for calls that have been re-routed from a compliance recording-enabled user. Supported call scenarios include forward, transfer, delegation
```suggestion
Setting this attribute to true enables compliance recording for calls that have been re-routed from a compliance recording-enabled user. Supported call scenarios include forward, transfer, delegation, call groups, and simultaneous ring. (Only available in Microsoft Teams PowerShell version 5.1.1-preview.)

```

2023-06-10 07:25 UTC, JohanFreelancer9 requested changes
Copy review - @abnan, kindly commit the suggested changes. Many thanks.

2023-06-11 09:34 UTC, JohanFreelancer9 approved these changes

2023-06-12 13:33 UTC, get-itips approved these changes

2023-06-12 13:48 UTC, dariomws reviewed
Hi @abnan, my apologies, but I don't understand the purpose of this PR. Can you explain it?

For example, I cannot see this parameter in the GA or Preview version of the TPM. Maybe it should be removed from the articles.

Thanks!

2023-06-12 13:56 UTC, abnan commented
@dariomws the parameter added should be available in version 5.1.1-preview. Due to a rollback by the Teams powershell team this parameter got removed in versions 5.2.0 and onward. They plan on re-releasing it, but meanwhile I am updating the documentation to capture which version to use for availing this parameter. The workaround (to use version 5.1.1-preview) for the time-being has been suggested by the Teams powershell team.

2023-06-13 04:35 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-06-13 14:43 UTC, merged