Updating guidance for phone number assignment in GCCH & DoD
MicrosoftDocs/office-docs-powershell pull request #10943
Opened 2023-06-14 10:42 UTC by JensTrier

Change the recommended parameter to use.

2023-06-14 16:50 UTC, get-itips approved these changes

2023-06-14 20:35 UTC, dariomws approved these changes

2023-06-15 09:32 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +The line Uniform Resource Identifier (URI) must be specified using the E.164 format and use the "tel:" prefix. For example: tel:+14255551297.
```suggestion
The line Uniform Resource Identifier (URI) must be specified using the E.164 format and the "tel:" prefix, for example, tel:+14255551297.
```

2023-06-15 09:37 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the minor suggested change. Many thanks.

2023-06-15 09:40 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the minor suggested change. Many thanks.

Thanks Johan & done!

2023-06-15 10:36 UTC, JohanFreelancer9 approved these changes

2023-06-15 15:28 UTC, merged