Updates toCsTenantDialPlan and Set-CsUser
MicrosoftDocs/office-docs-powershell pull request #11078
Opened 2023-07-14 09:20 UTC by JensTrier

Updating *-CsTenantDialPlan and adding a deprecation note to Set-CsUser for -HostedVoicemail parameter

2023-07-14 14:53 UTC, yogkumgit commented
@JohanFreelancer9

2023-07-14 20:14 UTC, get-itips approved these changes

2023-07-15 04:33 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTenantDialPlan.md
> +`Set-CsTenantDialPlan` cmdlet to make the change permanent.
```suggestion
This example changes the name of a normalization rule. Keep in mind that changing the name also changes the name portion of the Identity.
The `Set-CsVoiceNormalizationRule` cmdlet doesn't have a Name parameter, so in order to change the name, we first call the `Get-CsTenantDialPlan` cmdlet to retrieve the Dial Plan with
the Identity Global and assign the returned object to the variable $DP. Then we filter the NormalizationRules Object for the rule RedmondFourDigit and assign the returned object to
the variable $NR. We then assign the string RedmondRule to the Name property of the object. Finally, we pass the variable back to the NormalizationRules parameter of the
`Set-CsTenantDialPlan` cmdlet to make the change permanent.
```

2023-07-15 04:34 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTenantDialPlan.md
> +This example changes the name of an normalization rule. Keep in mind that changing the name also changes the name portion of the Identity.
```suggestion
This example changes the name of a normalization rule. Keep in mind that changing the name also changes the name portion of the Identity.
```

2023-07-15 04:36 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTenantDialPlan.md
> +This string can be up to 49 characters long. Valid characters are alphabetic or numeric characters, hyphen (-), dot (.) and parentheses (()).
```suggestion
This string can be up to 49 characters long. Valid characters are alphabetic or numeric characters, hyphen (-), dot (.), and parentheses (()).
```

2023-07-15 04:39 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the two additional changes. Many thanks.

2023-07-16 08:38 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the two additional changes. Many thanks.

Thanks & Done!

2023-07-17 04:44 UTC, JohanFreelancer9 approved these changes

2023-07-17 14:47 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-07-17 18:54 UTC, merged