Add missing params
MicrosoftDocs/office-docs-powershell pull request #11158
Opened 2023-08-14 17:21 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/11135

2023-08-16 06:01 UTC, yogkumgit commented
@tseward

2023-08-17 16:24 UTC, get-itips commented
> @JohanFreelancer9

@yogkumgit The PR is still draft.

2023-08-19 10:09 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsExternalAccessPolicy.md
> +Position: Con nombre
```suggestion
Position: Named
```

2023-08-19 10:10 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsAppPermissionPolicy.md
> +Position: Con nombre
```suggestion
Position: Named

```

2023-08-19 10:11 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsAppSetupPolicy.md
> +Position: Con nombre
```suggestion
Position: Named
```

2023-08-19 10:14 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsUpgradePolicy.md
> +Not supported anymore, see Description section.
```suggestion
Not supported anymore, see the Description section.
```

2023-08-19 10:14 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsVideoInteropServicePolicy.md
>  For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2023-08-19 10:15 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsMeetingTemplatePermissionPolicy.md
> +Position: Con nombre
```suggestion
Position: Named
```

2023-08-19 10:15 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsShiftsPolicy.md
> +Position: Con nombre
```suggestion
Position: Named

```

2023-08-19 10:18 UTC, JohanFreelancer9 requested changes
Copy review.

2023-08-21 11:55 UTC, yogkumgit commented
@get-itips

2023-08-21 13:03 UTC, JohanFreelancer9 approved these changes

2023-09-15 08:41 UTC, msbemba approved these changes

2023-09-15 15:17 UTC, merged