Clarify limit and add example
MicrosoftDocs/office-docs-powershell pull request #11156
Opened 2023-08-14 16:22 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/11116

2023-08-15 08:38 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +By default, a maximum of 500 results are returned.
```suggestion
By default, this cmdlet returns a maximum of 500 results.

```

2023-08-15 08:39 UTC, JohanFreelancer9 requested changes
Copy review.

2023-08-15 14:47 UTC, JohanFreelancer9 approved these changes

2023-08-16 05:59 UTC, yogkumgit commented
@tseward

2023-08-16 07:04 UTC, JensTrier commented
@get-itips thanks for making this improvement

2023-08-17 15:23 UTC, yogkumgit commented
@tseward Gentle reminder

2023-09-15 06:40 UTC, msbemba approved these changes

2023-09-15 12:19 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-09-15 15:15 UTC, merged