Update Meeting Policy setting - AllowUserToJoinExternalMeeting enum
MicrosoftDocs/office-docs-powershell pull request #11226
Opened 2023-08-31 21:09 UTC by kpyapali

Enum values changed as with content team review.
Also updated the Default value of this enum.
Text changed as well.

enum AllowUserToJoinExternalMeeting
Possible values are:
- Anyone 
- PeopleInTrustedOrganizationsOnly
- Blocked

Default value: Anyone

2023-09-01 06:56 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
> +Determines whether the user is allowed to join external meeting.
```suggestion
Determines whether the user is allowed to join external meetings.
```

2023-09-01 06:56 UTC, JohanFreelancer9 requested changes
Copy review - @kpyapali, kindly commit the minor suggested change. Many thanks.

2023-09-02 07:58 UTC, JohanFreelancer9 approved these changes

2023-09-05 20:09 UTC, kpyapali commented
@yogkumgit - Who can help with merging this PR? 
Seems I don't have write permissions.

2023-09-07 21:13 UTC, get-itips approved these changes

2023-09-07 21:14 UTC, get-itips commented
> @yogkumgit - Who can help with merging this PR? Seems I don't have write permissions.

@tiburd

2023-09-07 22:04 UTC, tiburd commented
> > @yogkumgit - Who can help with merging this PR? Seems I don't have write permissions.
> 
> @tiburd

I'm working on it. I'll ping you on Teams.

2023-09-08 11:21 UTC, JohanFreelancer9 approved these changes

2023-09-08 22:52 UTC, merged