Add missing parameters
MicrosoftDocs/office-docs-powershell pull request #11252
Opened 2023-09-07 16:37 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/11197

2023-09-15 12:08 UTC, yogkumgit commented
@JohanFreelancer9

2023-09-18 10:13 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +This setting governs which users in a tenant can add which registration form questions to event registration page for attendees to answer when registering for the event.
```suggestion
This setting governs which users in a tenant can add which registration form questions to an event registration page for attendees to answer when registering for the event.

```

2023-09-18 10:13 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +This setting describes how IT Admins can control which types of townhall can have their recordings published.
```suggestion
This setting describes how IT admins can control which types of Town Hall attendees can have their recordings published.

```

2023-09-18 10:13 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +This setting describes how IT Admins can control which types of webinars can have their recordings published.
```suggestion
This setting describes how IT admins can control which types of webinar attendees can have their recordings published.

```

2023-09-18 10:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +This setting governs the access to the integrations tab in event creation workflow.
```suggestion
This setting governs access to the integrations tab in the event creation workflow.

```

2023-09-18 10:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +This setting governs if the user can enable Comment Stream chat experience for Townhalls.
```suggestion
This setting governs whether the user can enable the Comment Stream chat experience for Town Halls.

```

2023-09-18 10:14 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-18 16:03 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +None,InviteOnly,EveryoneInCompanyIncludingGuests,Everyone.
```suggestion
None, InviteOnly, EveryoneInCompanyIncludingGuests, Everyone.

```

2023-09-18 16:04 UTC, JohanFreelancer9 requested changes
Apologies @get-itips, one more, please.

2023-09-19 01:48 UTC, JohanFreelancer9 approved these changes

2023-09-21 15:50 UTC, merged