add UseDeviceAuthentication
MicrosoftDocs/office-docs-powershell pull request #11253
Opened 2023-09-07 16:49 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/11190

2023-09-08 11:59 UTC, yogkumgit commented
@JohanFreelancer9

2023-09-08 14:02 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Connect-MicrosoftTeams.md
> +Use device code authentication instead of a browser control
```suggestion
Use device code authentication instead of a browser control.
```

2023-09-08 14:02 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-08 14:32 UTC, JohanFreelancer9 approved these changes

2023-09-15 14:22 UTC, msbemba approved these changes

2023-09-18 11:39 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-09-26 13:03 UTC, yogkumgit commented
@tiburd Please merged this PR. Thanks

2023-09-26 17:00 UTC, merged