Update Move-CsUser.md
MicrosoftDocs/office-docs-powershell pull request #11272
Opened 2023-09-13 20:55 UTC by ruchiagrawal9221

Updating public doc for upcoming deprecation for contact migration

2023-09-14 03:25 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Move-CsUser.md
> +> - From November 10, 2023 onwards, moving users from Teams to On-Premises will discontinue migrating their contacts. This is mainly due to Microsoft's continuous efforts to tighten the security and
```suggestion
> As of November 10, 2023, moving users from Teams to an on-premises deployment will no longer migrate their contacts. This is mainly due to our continuous efforts to tighten security and protect customers' data. After carefully analyzing the usage patterns and performing risk assessments with the legacy infrastructure, we decided to deprecate this feature. 
```

2023-09-14 03:28 UTC, JohanFreelancer9 requested changes
Copy review - @ruchiagrawal9221, kindly commit the suggested changes. Many thanks.

2023-09-14 08:38 UTC, JohanFreelancer9 approved these changes

2023-09-15 21:55 UTC, get-itips approved these changes

2023-09-19 17:18 UTC, ruchiagrawal9221 commented
@msbemba  could you pls complete the review on this PR so this can be completed?

2023-09-19 17:26 UTC, msbemba approved these changes
Approved

2023-09-19 20:45 UTC, ruchiagrawal9221 commented
Can someone please merge this PR ?

2023-09-20 16:55 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-09-20 17:13 UTC, merged

2023-09-20 17:36 UTC, ruchiagrawal9221 commented
Thanks @yogkumgit