Update Get-CsPhoneNumberAssignment.md
MicrosoftDocs/office-docs-powershell pull request #11330
Opened 2023-09-29 08:54 UTC by JensTrier

Update to add more information and example for Shared Calling.

2023-09-29 10:34 UTC, yogkumgit commented
@JohanFreelancer9

2023-09-29 12:16 UTC, get-itips approved these changes

2023-09-29 13:39 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +This example returns all phone numbers assigned as emergency numbers in the Teams Shared Calling Routing Policy instance SC1.
```suggestion
This example returns all phone numbers assigned as emergency numbers in the Teams shared calling routing policy instance SC1.

```

2023-09-29 13:39 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +Filters the returned results based on the user or resource account ID the phone number is assigned to. Supported values are UserPrincipalName, SIP address, ObjectId and the Teams Shared Calling Routi
```suggestion
Filters the returned results based on the user or resource account ID the phone number is assigned to. Supported values are UserPrincipalName, SIP address, ObjectId, and the Teams shared calling routing policy instance name.

```

2023-09-29 13:39 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-29 14:29 UTC, JohanFreelancer9 approved these changes

2023-10-02 14:26 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-10-04 15:23 UTC, merged