updated docs to include the new copilot related meeting policy settings.
MicrosoftDocs/office-docs-powershell pull request #11341
Opened 2023-10-02 16:16 UTC by boboPD

2023-10-03 06:52 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +This setting allows the admin to choose if Copilot will be enabled with a persisted transcript or a non-persisted transcript.
```suggestion
This setting allows the admin to choose whether Copilot will be enabled with a persisted transcript or a non-persisted transcript.
```

2023-10-03 06:53 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +This setting gives admins the ability to auto-start copilot.
```suggestion
This setting gives admins the ability to auto-start Copilot.
```

2023-10-03 06:53 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
> +This setting allows the admin to choose if Copilot will be enabled with a persisted transcript or a non-persisted transcript.
```suggestion
This setting allows the admin to choose whether Copilot will be enabled with a persisted transcript or a non-persisted transcript.
```

2023-10-03 06:54 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
> +This setting gives admins the ability to auto-start copilot.
```suggestion
This setting gives admins the ability to auto-start Copilot.
```

2023-10-03 06:58 UTC, JohanFreelancer9 requested changes
Copy review - @boboPD, kindly commit the minor suggested changes. Many thanks.

2023-10-04 05:39 UTC, JohanFreelancer9 approved these changes

2023-10-04 18:40 UTC, get-itips approved these changes

2023-10-05 16:45 UTC, boboPD commented
@yogkumgit these changes are ready to be merged in now. Is there anything else that you need from me?

2023-10-09 11:27 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-10-09 21:43 UTC, merged