Update New-CsTeamsEventsPolicy.md
MicrosoftDocs/office-docs-powershell pull request #11358
Opened 2023-10-09 20:48 UTC by gregorionMS

Updated EventAccessType to correctly reflect admin settings for Webinar and Town hall

2023-10-09 20:53 UTC, gregorionMS commented
Added clarity around EventAccessType to account for impact for Town halls for In Organization and Public 

_This setting governs which users can access the event for Town hall and access the event registration page or the event site to register for Webinar. It also governs which user type is allowed to join the session/s in the event for both event types. Possible values are:_

2023-10-10 11:12 UTC, yogkumgit commented
@JohanFreelancer9

2023-10-10 17:55 UTC, get-itips reviewed
Hello @gregorionMS how are you?
Are you a Microsoft employee? If so, can you please link your GH profile to your Microsoft profile so a blue Microsoft submitter badge is added?
Thanks

2023-10-10 18:04 UTC, gregorionMS commented
I am a Microsoft employee, I will attempt to do that right now thank you

Jigesh Parekh

From: Andres Mariano Gorzelany ***@***.***>
Date: Tuesday, October 10, 2023 at 10:55 AM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Jigesh Parekh ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Update New-CsTeamsEventsPolicy.md (PR #11358)

@get-itips commented on this pull request.

Hello @gregorionMS<https://github.com/gregorionMS> how are you?
Are you a Microsoft employee? If so, can you please link your GH profile to your Microsoft profile so a blue Microsoft submitter badge is added?
Thanks

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/office-docs-powershell/pull/11358#pullrequestreview-1668504368>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDE5AQZDPOUI3WGY3K2RFILX6WD2HAVCNFSM6AAAAAA5ZKPDHOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRYGUYDIMZWHA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-10 18:08 UTC, get-itips commented
@gregorionMS Thanks, and please make the same edit for Set-CsTeamsEventsPolicy

2023-10-10 18:10 UTC, gregorionMS commented
I will, Im trying to find some instructions online on how to link the profiles but cant seem to get any clarity, can you provide some instructions on how to link these profiles?

Thank you for your help on this

Jigesh Parekh

From: Andres Mariano Gorzelany ***@***.***>
Date: Tuesday, October 10, 2023 at 11:09 AM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Jigesh Parekh ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Update New-CsTeamsEventsPolicy.md (PR #11358)

@gregorionMS<https://github.com/gregorionMS> Thanks, and please make the same edit for Set-CsTeamsEventsPolicy

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/office-docs-powershell/pull/11358#issuecomment-1755973426>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDE5AQ6TM7UJCTZ7PESBSLLX6WFL5AVCNFSM6AAAAAA5ZKPDHOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJVHE3TGNBSGY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-10 18:13 UTC, get-itips commented
I think this is the link https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main

2023-10-10 18:36 UTC, gregorionMS commented
Thanks man, I think im good to go.

I submitted another PR

Update New-CsTeamsEventsPolicy.md by gregorionMS · Pull Request #11360 · MicrosoftDocs/office-docs-powershell (github.com)<https://github.com/MicrosoftDocs/office-docs-powershell/pull/11360>


Thank you again

Jigesh

From: Andres Mariano Gorzelany ***@***.***>
Date: Tuesday, October 10, 2023 at 11:13 AM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Jigesh Parekh ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Update New-CsTeamsEventsPolicy.md (PR #11358)

I think this is the link https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/office-docs-powershell/pull/11358#issuecomment-1755979447>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDE5AQ47ITARDJGCUBNNV4TX6WF5PAVCNFSM6AAAAAA5ZKPDHOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJVHE3TSNBUG4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-10 19:15 UTC, get-itips commented
@gregorionMS The new PR also edits the same article; for the New-

2023-10-10 19:35 UTC, gregorionMS commented
Apologies, good catch- just pushed the changes

[A screenshot of a computer  Description automatically generated]
From: Andres Mariano Gorzelany ***@***.***>
Date: Tuesday, October 10, 2023 at 12:15 PM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Jigesh Parekh ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Update New-CsTeamsEventsPolicy.md (PR #11358)

@gregorionMS<https://github.com/gregorionMS> The new PR also edits the same article; for the New-

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/office-docs-powershell/pull/11358#issuecomment-1756078759>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDE5AQ3KWVFF3YZL3SKKLEDX6WNEVAVCNFSM6AAAAAA5ZKPDHOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONJWGA3TQNZVHE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-10 20:05 UTC, get-itips commented
Can you add the changes to this PR that edits those 2 articles? If you do not know how to, no problem.

2023-10-11 05:03 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> +This setting governs which users can access the event for Town hall and access the event registration page or the event site to register for Webinar. It also governs which user type is allowed to joi
```suggestion
This setting governs which users can access the Town hall event and access the event registration page or the event site to register for a Webinar. It also governs which user type is allowed to join the session or sessions in the event for both event types. 

```

2023-10-11 05:04 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> + - **EveryoneInCompanyExcludingGuests**: For Webinar - enables creating events to allow only in-tenant users to register and join the event. For Town hall - enables creating events to allow only in-t
```suggestion
 - **EveryoneInCompanyExcludingGuests**: For Webinar - enables creating events to allow only in-tenant users to register and join the event. For Town hall - enables creating events to allow only in-tenant users to join the event (Note: for Town hall, in-tenant users include guests; this parameter will disable public Town halls). 

```

2023-10-11 05:06 UTC, JohanFreelancer9 requested changes
Copy review - @gregorionMS kindly commit the minor suggested changes. Many thanks.

2023-10-11 15:43 UTC, get-itips approved these changes
I'm ok after suggestions are applied

2023-10-11 17:10 UTC, gregorionMS commented
Thank you all for the help, when can we see the proposed changes pushed live?

All the best

Jigesh Parekh

From: Andres Mariano Gorzelany ***@***.***>
Date: Wednesday, October 11, 2023 at 8:43 AM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Jigesh Parekh ***@***.***>, Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Update New-CsTeamsEventsPolicy.md (PR #11358)

@get-itips approved this pull request.

I'm ok after suggestions are applied

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/office-docs-powershell/pull/11358#pullrequestreview-1671669087>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BDE5AQZ636IYIBOA7TO62SDX625B3ANCNFSM6AAAAAA5ZKPDHM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-12 05:50 UTC, JohanFreelancer9 approved these changes

2023-10-12 10:36 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-10-12 13:10 UTC, merged