Update New-CsTeamsMessagingPolicy.md
MicrosoftDocs/office-docs-powershell pull request #11362
Opened 2023-10-11 08:00 UTC by saleens7

2023-10-12 10:37 UTC, yogkumgit commented
@JohanFreelancer9

2023-10-12 21:42 UTC, get-itips approved these changes

2023-10-13 04:00 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +This policy gives admins the ability to auto-start copilot.
```suggestion
This policy gives admins the ability to auto-start Copilot.
```

2023-10-13 04:00 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +This policy gives admins the ability to choose if copilot will be enabled with a persisted transcript or a non-persisted transcript.
```suggestion
This policy gives admins the ability to choose if Copilot will be enabled with a persisted transcript or a non-persisted transcript.
```

2023-10-13 04:02 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMessagingPolicy.md
> +This setting enables creation of custom emojis/reactions within a tenant for the specified policy users.
```suggestion
This setting enables the creation of custom emojis and reactions within an organization for the specified policy users.
```

2023-10-13 04:04 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMessagingPolicy.md
> +This settings enable/disable the editing/deletion of custom emojis and reactions for the users included in the messaging policy
```suggestion
These settings enable and disable the editing and deletion of custom emojis and reactions for the users included in the messaging policy.
```

2023-10-13 04:05 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
> +This policy gives admins the ability to auto-start copilot.
```suggestion
This policy gives admins the ability to auto-start Copilot.
```

2023-10-13 04:06 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
> +This policy gives admins the ability to choose if copilot will be enabled with a persisted transcript or a non-persisted transcript.
```suggestion
This policy gives admins the ability to choose if Copilot will be enabled with a persisted transcript or a non-persisted transcript.
```

2023-10-13 04:09 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMessagingPolicy.md
> +This setting enables creation of custom emojis/reactions within a tenant for the specified policy users.
```suggestion
This setting enables the creation of custom emojis and reactions within an organization for the specified policy users.
```

2023-10-13 04:11 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMessagingPolicy.md
> +This settings enable/disable the editing/deletion of custom emojis and reactions for the users included in the messaging policy
```suggestion
These settings enable and disable the editing and deletion of custom emojis and reactions for the users included in the messaging policy.
```

2023-10-13 04:13 UTC, JohanFreelancer9 requested changes
Copy review - @saleens7, kindly commit the suggested changes. Many thanks.

2023-10-17 10:27 UTC, yogkumgit commented
@saleens7 Gentle reminder.

2023-10-17 17:49 UTC, msbemba approved these changes

2023-10-23 10:51 UTC, yogkumgit commented
@tiburd Please help. Thanks

2023-11-20 17:51 UTC, merged