Update New-CsTeamTemplate.md
MicrosoftDocs/office-docs-powershell pull request #11378
Opened 2023-10-16 20:26 UTC by JasonLewisMSFT

Adding a note that template changes may take up to 24 hours before users can see changes to the template.

2023-10-17 17:43 UTC, msbemba approved these changes

2023-10-17 20:43 UTC, get-itips approved these changes
Approving but I think we need @JohanFreelancer9 too @yogkumgit

2023-10-18 07:59 UTC, JohanFreelancer9 requested changes
Copy review - @JasonLewisMSFT, kindly commit the suggested change. Many thanks.

2023-10-19 07:27 UTC, yogkumgit commented
@JohanFreelancer9

2023-10-19 08:46 UTC, JohanFreelancer9 approved these changes

2023-10-19 15:16 UTC, JasonLewisMSFT commented
Is there anything else I need to do on my side to complete the PR?

2023-10-19 17:14 UTC, get-itips commented
@tiburd

2023-10-19 19:10 UTC, merged