Updating Get-CsPhoneNumberAssignment
MicrosoftDocs/office-docs-powershell pull request #11392
Opened 2023-10-19 07:33 UTC by JensTrier

Updating Get-CsPhoneNumberAssignment with new output parameter introduced in TPM 5.7.0

2023-10-20 13:10 UTC, yogkumgit commented
@JohanFreelancer9

2023-10-20 13:39 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +The source of the phone number. Online for phone numbers assigned in Microsoft 365 and OnPremises for phone number assigned in AD on-premises and synchronized into Microsoft 365.
```suggestion
The source of the phone number. Online for phone numbers assigned in Microsoft 365 and OnPremises for phone numbers assigned in AD on-premises and synchronized into Microsoft 365.

```

2023-10-20 13:40 UTC, JohanFreelancer9 requested changes
@JensTrier, small edit, please.

2023-10-20 13:46 UTC, JensTrier commented
> @JensTrier, small edit, please.

@JohanFreelancer9 thanks & done!

2023-10-20 19:04 UTC, get-itips approved these changes

2023-10-21 05:42 UTC, JohanFreelancer9 approved these changes

2023-10-23 10:52 UTC, yogkumgit commented
@tiburd

2023-10-23 14:48 UTC, merged