Improve description for NotificationMode
MicrosoftDocs/office-docs-powershell pull request #11409
Opened 2023-10-24 15:49 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/11361

2023-10-25 05:33 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
> +Possible values are NotificationOnly, ConferenceMuted, ConferenceUnMuted.
```suggestion
Possible values are NotificationOnly, ConferenceMuted, and ConferenceUnMuted.
```

2023-10-25 05:33 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
> +Possible values are NotificationOnly, ConferenceMuted, ConferenceUnMuted.
```suggestion
Possible values are NotificationOnly, ConferenceMuted, and ConferenceUnMuted.
```

2023-10-25 05:33 UTC, JohanFreelancer9 requested changes
Copy review.

2023-10-25 06:00 UTC, JensTrier approved these changes

2023-10-25 15:49 UTC, JohanFreelancer9 approved these changes

2023-10-26 16:13 UTC, msbemba approved these changes

2023-10-27 09:33 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-10-31 16:44 UTC, merged