Update Get-CaseHoldRule.md
MicrosoftDocs/office-docs-powershell pull request #11506
Opened 2023-12-04 11:01 UTC by pjsfonseca69

timeout issue when running only the command Get-CaseHoldRule without any parameter

2023-12-04 17:42 UTC, chrisda commented
@pjsfonseca69, where does your command get the $org variable from? We should declare it or remove it.

2023-12-05 03:35 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Get-CaseHoldRule.md
> +In large environments, running this cmdlet without any parametersresults in a timeout. As a workaround, you can run the following command:
```suggestion
In large environments, running this cmdlet without any parameters results in a timeout. As a workaround, you can run the following command:
```

2023-12-05 03:36 UTC, JohanFreelancer9 requested changes
Copy review.

2023-12-05 08:56 UTC, pjsfonseca69 commented
> @pjsfonseca69, where does your command get the $org variable from? We should declare it or remove it.

What do you mean, we don't use any $org variable we just run Get-CaseHoldRule

2023-12-05 18:09 UTC, merged