Add TeamsAIPolicy cmdlets public docs
MicrosoftDocs/office-docs-powershell pull request #12077
Opened 2024-08-16 21:59 UTC by Andy447

Add new TeamsAIPolicy cmdlets public docs for 5 cmdlets

2024-08-16 22:03 UTC, Andy447 commented
@microsoft-github-policy-service agree company="{Microsoft}"

2024-08-17 11:35 UTC, shivtorov commented on teams/teams-ps/teams/Grant-CsTeamsAIPolicy.md
> +This cmdlet applies an instance of the Teams media connectivity policy to users or groups in a tenant.
```suggestion
This cmdlet applies an instance of the Teams AI policy to users or groups in a tenant.
```

2024-08-17 11:36 UTC, shivtorov commented on teams/teams-ps/teams/Grant-CsTeamsAIPolicy.md
> +This cmdlet applies an instance of the Teams media connectivity policy to users or groups in a tenant.
```suggestion
This cmdlet applies an instance of the Teams AI policy to users or groups in a tenant.
```

2024-08-26 17:06 UTC, Andy447 commented
@shivtorov Can you please review this PR? Thank you!

2024-08-26 22:24 UTC, shivtorov commented
> [Andy447](/Andy447)
@Andy447, I'm not a Microsoft employee, just a random contributor.

2024-09-04 15:08 UTC, michbrown-png requested changes

2024-09-04 15:08 UTC, michbrown-png commented on teams/teams-ps/teams/Get-CsTeamsAIPolicy.md
> +retrieves Teams AI policies, shows "EnrollFace" and "EnrollVoice" values.
Please capitalize the first letter of the word "Retrieves". To confirm, this cmdlet retrieves all Teams AI policies created for this tenant and shows what the EnrollFace and EnrollVoice values are for each policy?

2024-09-04 15:08 UTC, michbrown-png commented on teams/teams-ps/teams/Set-CsTeamsAIPolicy.md
> +This cmdlet Set Teams AI policy EnrollFace/EnrollVoice value for current tenant. The value can be "Enabled" or "Disabled"
Please make this description a little more clear. It is a bit ambiguous.

Recommended Edits:
This cmdlet sets the Teams AI policy EnrollFace and EnrollVoice value for the tenant. The values of EnrollFace and EnrollVoice can be set to "Enabled" or "Disabled"

2024-09-04 15:09 UTC, michbrown-png commented
@Andy447 - Please make the suggested changes

2024-09-04 20:39 UTC, merged