Update parameters for legacy Exchange tokens
MicrosoftDocs/office-docs-powershell pull request #12360
Opened 2024-11-12 01:04 UTC by samantharamon

- Adds a description to the `AllowLegacyExchangeTokens` and `BlockLegacyExchangeTokens` parameters of the `Set-AuthenticationPolicy` cmdlet.
- Adds a description to the `AllowLegacyExchangeTokens` parameter of the `Remove-AuthenticationPolicy` cmdlet.
- Adds the `AllowLegacyExchangeTokens` parameter to the `Get-AuthenticationPolicy` cmdlet.

2024-11-22 02:38 UTC, Oleg-O requested changes

2024-12-12 01:11 UTC, chrisda commented
@samantharamon, we shouldn't promise future functionality, so I removed that "Improvements are underway to populate these arrays with Outlook add-ins that were allowed or blocked from getting legacy tokens." sentence.

2024-12-12 18:25 UTC, davidchesnut requested changes

2024-12-12 18:25 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
> +Remove-AuthenticationPolicy -Identity "Legacy Exchange Tokens" -AllowLegacyExchangeTokens
```suggestion
Remove-AuthenticationPolicy -Identity "LegacyExchangeTokens" -AllowLegacyExchangeTokens
```

2024-12-12 18:25 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
> +In Exchange Online, this example returns your organization to its previous state before legacy Exchange token issuance was allowed or blocked for Outlook add-ins. Since this switch applies to the ent
```suggestion
In Exchange Online, this example enables legacy Exchange tokens to be issued to Outlook add-ins. This switch applies to the entire organization. The Identity parameter is required, and its value must be set to "LegacyExchangeTokens". Specific authentication polices can't be applied.
```

2024-12-12 18:25 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
> +The AllowLegacyExchangeTokens switch returns your organization to its previous state before changes were made to allow or block legacy Exchange tokens for Outlook add-ins. You don't need to specify a
```suggestion
The AllowLegacyExchangeTokens switch enables legacy Exchange tokens to be issued to Outlook add-ins for your organization. You don't need to specify a value with this switch.
```

2024-12-12 18:25 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Remove-AuthenticationPolicy.md
> +This switch applies to the entire organization. Although the Identity parameter is required, its value is ignored. You can pass any non-empty value as the Identity parameter.
```suggestion
This switch applies to the entire organization. The Identity parameter is required, and its value must be set to "LegacyExchangeTokens". Specific authentication polices can't be applied.
```

2024-12-12 18:25 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
> +Set-AuthenticationPolicy -Identity "Legacy Exchange Tokens" -BlockLegacyExchangeTokens
```suggestion
Set-AuthenticationPolicy -Identity "LegacyExchangeTokens" -BlockLegacyExchangeTokens
```

2024-12-12 18:25 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
> +In Exchange Online, this example blocks legacy Exchange tokens from being issued to Outlook add-ins. Since this switch applies to the entire organization, the authentication policy specified with the
```suggestion
In Exchange Online, this example blocks legacy Exchange tokens from being issued to Outlook add-ins. The switch applies to the entire organization, and the Identity parameter must be set to the value "LegacyExchangeTokens". Specific authentication polices can't be applied.
```

2024-12-12 18:28 UTC, davidchesnut requested changes

2024-12-12 18:28 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
> +The BlockLegacyExchangeTokens switch specifies whether to block legacy Exchange tokens for Outlook add-ins. You don't need to specify a value with this switch.
```suggestion
The BlockLegacyExchangeTokens switch specifies to block legacy Exchange tokens being issued to Outlook add-ins. You don't need to specify a value with this switch.
```

2024-12-12 18:28 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
> +This switch applies to the entire organization. Although the Identity parameter is required, its value is ignored. You can pass any non-empty value as the Identity parameter.
```suggestion
The switch applies to the entire organization. The Identity parameter is required and must be set to the value "LegacyExchangeTokens". Specific authentication polices can't be applied.
```

2024-12-12 18:28 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
> +The AllowLegacyExchangeTokens switch specifies whether to allow legacy Exchange tokens for Outlook add-ins. You don't need to specify a value with this switch.
```suggestion
The AllowLegacyExchangeTokens switch specifies to allow legacy Exchange tokens to be issued to Outlook add-ins. You don't need to specify a value with this switch.
```

2024-12-12 18:28 UTC, davidchesnut commented on exchange/exchange-ps/exchange/Set-AuthenticationPolicy.md
> +This switch applies to the entire organization. Although the Identity parameter is required, its value is ignored. You can pass any non-empty value as the Identity parameter.
```suggestion
The switch applies to the entire organization. The Identity parameter is required and must be set to the value "LegacyExchangeTokens". Specific authentication polices can't be applied.
```

2024-12-12 18:33 UTC, merged