Update New-CsOnlineSession.md
MicrosoftDocs/office-docs-powershell pull request #6501
Opened 2020-09-11 23:19 UTC by pupara

Removed UserName. Made Credential as default.

2020-09-11 23:22 UTC, opbld31 commented
Docs Build status updates of commit _[f654b1c](https://github.com/pupara/office-docs-powershell/commits/f654b1ce53ccb094f9629a920efba7ff70201a3e)_: 

:clock10: **Full build**: the average full build time is _17 min(s) 31 sec(s)_, this is based on the last _1000_ build(s) for this repository.

2020-09-11 23:35 UTC, opbld30 commented
Docs Build status updates of commit _[f654b1c](https://github.com/pupara/office-docs-powershell/commits/f654b1ce53ccb094f9629a920efba7ff70201a3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/pupara/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsOnlineSession.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202009112319289814-6501%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FV68hngb6ps48EYnR0vbZiLB%2FMv5peqgiZP3Zq7SL%2Fo%3D&st=2020-09-11T23%3A30%3A40Z&se=2020-10-12T23%3A35%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-11 23:38 UTC, opbld30 commented
Docs Build status updates of commit _[3a34cea](https://github.com/pupara/office-docs-powershell/commits/3a34cea3c6735e5dbe9f5f13cf91c7ef2629f9fe)_: 

:clock10: **Full build**: the average full build time is _17 min(s) 31 sec(s)_, this is based on the last _1000_ build(s) for this repository.

2020-09-11 23:53 UTC, opbld30 commented
Docs Build status updates of commit _[3a34cea](https://github.com/pupara/office-docs-powershell/commits/3a34cea3c6735e5dbe9f5f13cf91c7ef2629f9fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/pupara/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsOnlineSession.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202009112330172231-6501%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gHxWk7ys7ZR26xzr7hJ%2BKTF%2BRaKradVYHAFXfqjBkts%3D&st=2020-09-11T23%3A48%3A45Z&se=2020-10-12T23%3A53%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-12 17:22 UTC, opbld30 commented
Docs Build status updates of commit _[d48a3b9](https://github.com/pupara/office-docs-powershell/commits/d48a3b9fbf01be33f86f9957f1b28df3d9004736)_: 

:clock10: **Full build**: the average full build time is _17 min(s) 31 sec(s)_, this is based on the last _1000_ build(s) for this repository.

2020-09-12 17:36 UTC, opbld30 commented
Docs Build status updates of commit _[d48a3b9](https://github.com/pupara/office-docs-powershell/commits/d48a3b9fbf01be33f86f9957f1b28df3d9004736)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsOnlineSession.md](https://github.com/pupara/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsOnlineSession.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202009121719390649-6501%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YzJjFb6YCIa3JeEKiwoAp0B9zt4uLzBSRg0FQvxW2lg%3D&st=2020-09-12T17%3A31%3A38Z&se=2020-10-13T17%3A36%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-15 12:19 UTC, get-itips commented on skype/skype-ps/skype/New-CsOnlineSession.md
> +> UserName has been deprecated and is not avaiable in Teams Powershell module. Please use Credential parameter to provide username and password.
```suggestion
Please Note: UserName has been deprecated and is not avaiable in Teams Powershell module. Please use Credential parameter to provide username and password. 
```

2020-09-15 12:19 UTC, get-itips commented on skype/skype-ps/skype/New-CsOnlineSession.md
> +> [!WARNING]
```suggestion
```

2020-09-15 12:20 UTC, get-itips requested changes
[!WARNING] or [!NOTE] are not to be used on cmdlet's articles as they break online help. Can you kindly review my suggestion?

2020-09-15 12:29 UTC, get-itips commented on skype/skype-ps/skype/New-CsOnlineSession.md
> +Type: String
```suggestion
Type: String
Parameter Sets: (All)
```

2020-09-15 12:53 UTC, dariomws requested changes
Agree with @get-itips suggested changes.

2020-09-15 12:53 UTC, dariomws commented on skype/skype-ps/skype/New-CsOnlineSession.md
> +> UserName has been deprecated and is not avaiable in Teams Powershell module. Please use Credential parameter to provide username and password.
```suggestion
Please Note: UserName has been deprecated and is not available in the Teams Powershell module. Please use the Credential parameter to provide username and password.
```

2020-09-15 15:26 UTC, merged