Clarifying same tenant
MicrosoftDocs/office-docs-powershell pull request #6694
Opened 2020-10-16 17:24 UTC by get-itips

Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/6668

2020-10-16 17:27 UTC, opbld33 commented
Docs Build status updates of commit _[ff4193f](https://github.com/get-itips/office-docs-powershell/commits/ff4193f531bfa71e84e6e09f42c4e31f16aa858f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteCollectionAppCatalog.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteCollectionAppCatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spositecollectionappcatalog?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-1d27ebc0-3dd2b2fe)
[sharepoint/docfx.json](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/docfx.json) | :warning:Warning | | [Details](#user-content-ed5a659a-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInDesignPackageVisibility.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInDesignPackageVisibility.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spobuiltindesignpackagevisibility?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-6a630899-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMoveReport.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMoveReport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spocrossgeomovereport?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-9a2098a8-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spodataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-6c4a9aec-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHomeSite.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHomeSite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spohomesite?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-8cb4bb70-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoCompanyAllowedDataLocation.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoCompanyAllowedDataLocation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomultigeocompanyalloweddatalocation?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-212d8dbb-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomultigeoexperience?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-1bab962c-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteCollectionAppCatalogs.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteCollectionAppCatalogs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositecollectionappcatalogs?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-fa249a03-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositeuserinvitations?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-08498d28-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOStorageEntity.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOStorageEntity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spostorageentity?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-fec6dffb-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteRenameState.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteRenameState.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositerenamestate?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-78c5fa4d-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroup.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spounifiedgroup?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-f4d250b6-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDataEncryptionPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDataEncryptionPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositedataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-67ffaba2-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubToHubAssociation.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubToHubAssociation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spohubtohubassociation?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-bda2e014-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spodataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-fb313399-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromWeb.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteScriptFromWeb.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositescriptfromweb?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-63ad1736-3dd2b2fe)
[sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOHubToHubAssociation.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOHubToHubAssociation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/shar [...]

2020-10-19 12:58 UTC, dariomws approved these changes

2020-10-19 15:13 UTC, tseward requested changes

2020-10-19 15:13 UTC, tseward commented on sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md
> +Swaps the location of a source site with a target site in the same SharePoint online tenant while archiving the original target site.
Capitalize the "O" in Online.

2020-10-19 15:15 UTC, tseward commented
I feel this change is unnecessary. Given a SharePoint admin must use `Connect-SPOService` which only allows you to connect to a single tenant, it should be self-evident that site swap can only occur within the specified tenant.

If we were to make this statement, it would possibly need to be expanded to other cmdlets/docs.

2020-10-19 15:17 UTC, opbld30 commented
Docs Build status updates of commit _[5233fc4](https://github.com/get-itips/office-docs-powershell/commits/5233fc40302171d809f2ca284bc86658d379c034)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteCollectionAppCatalog.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOSiteCollectionAppCatalog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spositecollectionappcatalog?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-1d27ebc0-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubToHubAssociation.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Add-SPOHubToHubAssociation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/add-spohubtohubassociation?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-bda2e014-c026747a)
[sharepoint/docfx.json](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/docfx.json) | :warning:Warning | | [Details](#user-content-ed5a659a-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInDesignPackageVisibility.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInDesignPackageVisibility.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spobuiltindesignpackagevisibility?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-6a630899-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataEncryptionPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spodataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-6c4a9aec-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMoveReport.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMoveReport.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spocrossgeomovereport?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-9a2098a8-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHomeSite.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOHomeSite.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spohomesite?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-8cb4bb70-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteCollectionAppCatalogs.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteCollectionAppCatalogs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositecollectionappcatalogs?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-fa249a03-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoExperience.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomultigeoexperience?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-1bab962c-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoCompanyAllowedDataLocation.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMultiGeoCompanyAllowedDataLocation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spomultigeocompanyalloweddatalocation?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-212d8dbb-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteUserInvitations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositeuserinvitations?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-08498d28-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDataEncryptionPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteDataEncryptionPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositedataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-67ffaba2-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteRenameState.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteRenameState.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spositerenamestate?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-78c5fa4d-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOStorageEntity.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOStorageEntity.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spostorageentity?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-fec6dffb-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Register-SPODataEncryptionPolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/register-spodataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-fb313399-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroupMoveState.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroupMoveState.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spounifiedgroupmovestate?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-10b55058-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteCollectionAppCatalogById.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteCollectionAppCatalogById.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spositecollectionappcatalogbyid?view=sharepoint-ps&branch=pr-en-us-6694) (sharepoint-ps) | [Details](#user-content-83b01673-c026747a)
[sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteCollectionAppCatalog.md](https://github.com/get-itips/office-docs-powershell/blob/patch-270/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteCollectionAppCatalog.md) | :warning: [...]

2020-10-19 15:20 UTC, get-itips commented
Yeah you are right, it is implied. @tseward

2020-10-19 15:20 UTC, closed without merging