Create Get-TeamTargetingHierarchyStatus.md
MicrosoftDocs/office-docs-powershell pull request #7309
Opened 2021-02-17 23:16 UTC by ayrtonsoftware

2021-02-17 23:19 UTC, opbld32 commented
Docs Build status updates of commit _[3563b95](https://github.com/ayrtonsoftware/office-docs-powershell/commits/3563b95fd1c4c0b560451a5ce87eba6c66cde068)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-3/teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamtargetinghierarchystatus?view=teams-ps&branch=pr-en-us-7309) (teams-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202102172316345638-7309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v1PIGHWlOdrP257h7XrrVLXUBa3TOLvl43Sl7A9XdUQ%3D&st=2021-02-17T23%3A14%3A29Z&se=2021-03-20T23%3A19%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-25 13:07 UTC, tseward requested changes

2021-02-25 13:07 UTC, tseward commented on teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
> +Key       Value
Output from a cmdlet should be encased in ```output:

\```powershell
\> Cmdlet
\```

\```output
Result
\```

2021-02-25 13:07 UTC, tseward commented on teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
> +Get the status of a hierarchy upload (see [Set-TeamTargetingHierarchy](https://docs.microsoft.com/powershell/module/teams/get-teamtargetinghierarchy))
Can you move the reference to `Set-TeamTargetingHierarchy` to the Related Links section?

2021-02-25 17:07 UTC, get-itips commented on teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md
> +author: mbergamo
author metadata should be a github username

2021-02-25 17:09 UTC, get-itips requested changes
small suggestions and also see Trevor's

2021-02-25 18:20 UTC, dariomws commented
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=ayrtonsoftware

2021-02-25 18:20 UTC, dariomws approved these changes
I'm ok after suggestions.

2021-03-01 15:04 UTC, yogkumgit commented
@ayrtonsoftware

2021-04-19 16:35 UTC, yogkumgit commented
Gentle reminder @ayrtonsoftware Please implement the suggestions. Thanks

2021-05-14 12:48 UTC, yogkumgit commented
@Kateyanne Please help.

2021-06-04 18:34 UTC, Kateyanne commented
@ayrtonsoftware please review the comments and implement the suggestions. Then we can push this to live.

2021-06-09 18:40 UTC, opbld33 commented
Docs Build status updates of commit _[0527f34](https://github.com/ayrtonsoftware/office-docs-powershell/commits/0527f344f0a88117b95692bcaba84040778e62e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-3/teams/teams-ps/teams/Get-TeamTargetingHierarchyStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamtargetinghierarchystatus?view=teams-ps&branch=pr-en-us-7309) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091837144511-7309%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F9ZSyGvBIXpigWlLVn9qObSXPSedIqe1p2XXbAFh%2Bns%3D&st=2021-06-09T18%3A35%3A52Z&se=2021-07-10T18%3A40%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 18:46 UTC, merged