Create Set-TeamTargetingHierarchy.md
MicrosoftDocs/office-docs-powershell pull request #7310
Opened 2021-02-17 23:42 UTC by ayrtonsoftware

2021-02-17 23:44 UTC, opbld32 commented
Docs Build status updates of commit _[32bf66b](https://github.com/ayrtonsoftware/office-docs-powershell/commits/32bf66b5011ec4ea8cf974dc98739b24cb446e17)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md) | :x:Error | | [Details](#user-content-5317bd59-05db8825)
[teams/teams-ps/teams/index.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/index.yml) | :warning:Warning | | [Details](#user-content-0279dfca-05db8825)
[teams/teams-ps/teams/New-CsCustomPolicyPackage.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/New-CsCustomPolicyPackage.yml) | :warning:Warning | | [Details](#user-content-3f5acb7b-05db8825)
[teams/teams-ps/teams/Remove-CsCustomPolicyPackage.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Remove-CsCustomPolicyPackage.yml) | :warning:Warning | | [Details](#user-content-ef62087b-05db8825)

<a id="5317bd59-05db8825"></a>
### [teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/iajv-s/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md:36:(153) '```
- Apogee
  - New Jersey
    - Basking Ridge...'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="0279dfca-05db8825"></a>
### [teams/teams-ps/teams/index.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/index.yml)
 - **Line 54, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamArchivedState'.`````
 - **Line 62, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamTargetingHierarchy'.`````
 - **Line 63, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Update-CsCustomPolicyPackage'.`````
 - **Line 65, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Update-TeamsAppInstallation'.`````

<a id="3f5acb7b-05db8825"></a>
### [teams/teams-ps/teams/New-CsCustomPolicyPackage.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/New-CsCustomPolicyPackage.yml)
 - **Line 10, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Update-CsCustomPolicyPackage.yml'.`````

<a id="ef62087b-05db8825"></a>
### [teams/teams-ps/teams/Remove-CsCustomPolicyPackage.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Remove-CsCustomPolicyPackage.yml)
 - **Line 15, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Update-CsCustomPolicyPackage.yml'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202102172342100860-7310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8xmnyBT4pzaafy4SyMd6FADHI%2FNegilUW99lMKnOCnU%3D&st=2021-02-17T23%3A39%3A37Z&se=2021-03-20T23%3A44%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 17:04 UTC, opbld32 commented
Docs Build status updates of commit _[0073730](https://github.com/ayrtonsoftware/office-docs-powershell/commits/0073730e93bd12d9a800c42f4dd1d8c1fa856a21)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md) | :x:Error | | [Details](#user-content-5317bd59-bf683465)
[teams/teams-ps/teams/index.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/index.yml) | :warning:Warning | | [Details](#user-content-0279dfca-bf683465)

<a id="5317bd59-bf683465"></a>
### [teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/343i-s/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md:37:(153) '```
- Apogee
  - New Jersey
    - Basking Ridge...'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="0279dfca-bf683465"></a>
### [teams/teams-ps/teams/index.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/index.yml)
 - **Line 62, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamTargetingHierarchy'.`````
 - **Line 65, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Update-TeamsAppInstallation'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202102181702160025-7310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kkdvdGg8dqbBUHNzcHx1AJC9CTFx8TFuYM6b84OX4HM%3D&st=2021-02-18T16%3A59%3A52Z&se=2021-03-21T17%3A04%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-25 13:05 UTC, tseward requested changes

2021-02-25 13:05 UTC, tseward commented on teams/teams-ps/teams/Set-TeamTargetingHierarchy.md
> +A sample CSV file uses the following format:
Keep in mind that markdown and HTML tags will not render properly in PowerShell.

2021-02-25 13:05 UTC, tseward commented on teams/teams-ps/teams/Set-TeamTargetingHierarchy.md
> +Key       Value
Output from a cmdlet should be encased in ```output:

\```powershell
\> Cmdlet
\```

\```output
Result
\```

2021-02-25 17:08 UTC, get-itips commented on teams/teams-ps/teams/Set-TeamTargetingHierarchy.md
> +author: mbergamo
author metadata should be a github username

2021-02-25 17:09 UTC, get-itips requested changes
small suggestions and also see Trevor's

2021-02-25 18:32 UTC, dariomws approved these changes
I'm ok after suggestions.

2021-03-01 15:05 UTC, yogkumgit commented
@ayrtonsoftware

2021-03-09 01:27 UTC, opbld30 commented
Docs Build status updates of commit _[2d04e14](https://github.com/ayrtonsoftware/office-docs-powershell/commits/2d04e146b28141921d694a03d264216085bad743)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-teamtargetinghierarchy?view=teams-ps&branch=pr-en-us-7310) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202103090124578386-7310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XGSqHgSbxX8qdaj%2FLp%2FqUqnTKHs%2Fz3vTe93EWRA6ssE%3D&st=2021-03-09T01%3A22%3A52Z&se=2021-04-09T01%3A27%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 01:30 UTC, opbld32 commented
Docs Build status updates of commit _[246d01d](https://github.com/ayrtonsoftware/office-docs-powershell/commits/246d01dc2a9fd9d969f5d2dfa275084578bbcdb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-teamtargetinghierarchy?view=teams-ps&branch=pr-en-us-7310) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202103090125148034-7310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q%2F8o5UiEifAI6FdYspEAzpVDzNXkq%2BUm%2FPZ4nnkZ%2FQo%3D&st=2021-03-09T01%3A25%3A45Z&se=2021-04-09T01%3A30%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-14 12:50 UTC, yogkumgit commented
@ayrtonsoftware Please update the PR with suggestions.

2021-06-09 18:48 UTC, opbld31 commented
Docs Build status updates of commit _[ba7fabb](https://github.com/ayrtonsoftware/office-docs-powershell/commits/ba7fabba18d2512ec62f78cc598f404daf11a7ce)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md) | :x:Error | | [Details](#user-content-aa88d62394a8f8176ab6d84d892b52a7-68ba0010)
[teams/teams-ps/teams/index.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/index.yml) | :warning:Warning | | [Details](#user-content-b61f50182cfc6b2c2e4f61000005186d-68ba0010)

<a id="aa88d62394a8f8176ab6d84d892b52a7-68ba0010"></a>
### [teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/04qn-s/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md:17:(153) '```text
TargetName,ParentName,TeamId,Location:Clo...'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="b61f50182cfc6b2c2e4f61000005186d-68ba0010"></a>
### [teams/teams-ps/teams/index.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/index.yml)
 - **Line 63, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamTargetingHierarchy'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091845594544-7310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ax2uNfWNAk5iabx8rfBOw4FWR4odsRE%2FBPVh9pIQExg%3D&st=2021-06-09T18%3A43%3A42Z&se=2021-07-10T18%3A48%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 19:08 UTC, opbld33 commented
Docs Build status updates of commit _[ee3bbce](https://github.com/ayrtonsoftware/office-docs-powershell/commits/ee3bbcecfe03f9e13a58f49302a76813a5b700fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-TeamTargetingHierarchy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-teamtargetinghierarchy?view=teams-ps&branch=pr-en-us-7310) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091905005588-7310%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kS91A5wF2arH6hBM4SpE%2FcRU%2FzkbH0W1dtIWt65fj3k%3D&st=2021-06-09T19%3A03%3A04Z&se=2021-07-10T19%3A08%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 19:08 UTC, merged