Create Remove-TeamTargetingHierarchy.md
MicrosoftDocs/office-docs-powershell pull request #7311
Opened 2021-02-17 23:47 UTC by ayrtonsoftware

2021-02-17 23:50 UTC, opbld31 commented
Docs Build status updates of commit _[b87501e](https://github.com/ayrtonsoftware/office-docs-powershell/commits/b87501ee5322b4e84c635b38ce5eab5b37cd501f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-5/teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md) | :x:Error | | [Details](#user-content-aab7f35d-1538806f)
[teams/teams-ps/teams/index.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-5/teams/teams-ps/teams/index.yml) | :warning:Warning | | [Details](#user-content-0279dfca-1538806f)

<a id="aab7f35d-1538806f"></a>
### [teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-5/teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/aiqo-s/teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md:23:(31) 'No parameters.'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="0279dfca-1538806f"></a>
### [teams/teams-ps/teams/index.yml](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-5/teams/teams-ps/teams/index.yml)
 - **Line 50, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Remove-TeamTargetingHierarchy'.`````
 - **Line 65, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Update-TeamsAppInstallation'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202102172347424783-7311%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AAbNlMl3njbKB7Fd7z4P%2Fg4s7LefnmX%2B7DLhb2LxjV4%3D&st=2021-02-17T23%3A45%3A09Z&se=2021-03-20T23%3A50%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 17:01 UTC, opbld30 commented
Docs Build status updates of commit _[24de076](https://github.com/ayrtonsoftware/office-docs-powershell/commits/24de076dce13fbd24d5d0a599d5168122b0a0433)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-5/teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-teamtargetinghierarchy?view=teams-ps&branch=pr-en-us-7311) (teams-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202102181658439106-7311%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MZTZjZCfh77ZlJVhaRcdchlbm7rCAy3G9F5VO3IqZQs%3D&st=2021-02-18T16%3A56%3A52Z&se=2021-03-21T17%3A01%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 17:04 UTC, opbld30 commented
Docs Build status updates of commit _[8f8f4ff](https://github.com/ayrtonsoftware/office-docs-powershell/commits/8f8f4ffdf8b88eeebafb225a11673ae8d002839b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-5/teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-teamtargetinghierarchy?view=teams-ps&branch=pr-en-us-7311) (teams-ps) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202102181659166820-7311%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ke4oJqNfibiLTlwo1R1u8RSbDvN9nQlLrX3qS0GI7Ac%3D&st=2021-02-18T16%3A59%3A44Z&se=2021-03-21T17%3A04%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-26 18:58 UTC, tseward requested changes

2021-02-26 18:58 UTC, tseward commented on teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
> +## DESCRIPTION
Can you add a description, even if it is identical to the Synopsis?

2021-02-26 19:27 UTC, get-itips commented on teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
> +author: mbergamo
this should be a github username

2021-02-26 19:30 UTC, get-itips commented on teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md
> +
Here should be an example's description

2021-02-26 20:38 UTC, dariomws approved these changes
I'm ok after the suggestion. Thanks!

2021-03-01 15:05 UTC, yogkumgit commented
@ayrtonsoftware

2021-04-19 16:37 UTC, yogkumgit commented
Gentle reminder @ayrtonsoftware Please implement the suggestions. Thanks

2021-05-14 12:50 UTC, yogkumgit commented
@Kateyanne Please help

2021-06-04 18:30 UTC, Kateyanne commented
@get-itips are you able to implement the suggestions yourself?

2021-06-04 18:33 UTC, get-itips commented
> @get-itips are you able to implement the suggestions yourself?

I am afraid only someone with push permissions on the repo or the PR author

2021-06-09 18:51 UTC, opbld33 commented
Docs Build status updates of commit _[0443ccf](https://github.com/ayrtonsoftware/office-docs-powershell/commits/0443ccff148c532e5ea4b15db7e572b5788560a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-5/teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-teamtargetinghierarchy?view=teams-ps&branch=pr-en-us-7311) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091849065917-7311%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lWiS%2Fy2X70gI%2Fm%2FCm7h%2FDqJ0PQpKD7mJGuACXcDSNvU%3D&st=2021-06-09T18%3A46%3A53Z&se=2021-07-10T18%3A51%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 19:11 UTC, opbld30 commented
Docs Build status updates of commit _[b407c85](https://github.com/ayrtonsoftware/office-docs-powershell/commits/b407c8565062794fe364d3edd80dcbec7ce4ec96)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md](https://github.com/ayrtonsoftware/office-docs-powershell/blob/patch-5/teams/teams-ps/teams/Remove-TeamTargetingHierarchy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-teamtargetinghierarchy?view=teams-ps&branch=pr-en-us-7311) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091908419772-7311%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j5UtE8h29C5%2F4196LgiO3F2xg7ZhFNHPzgQTMjhaC88%3D&st=2021-06-09T19%3A06%3A35Z&se=2021-07-10T19%3A11%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 20:08 UTC, tseward approved these changes

2021-06-09 20:21 UTC, merged