Update Get-Team.md
MicrosoftDocs/office-docs-powershell pull request #7477
Opened 2021-03-23 09:43 UTC by rajgodwin

Updated the old note which was no longer applicable with a new note.

2021-03-23 09:45 UTC, opbld31 commented
Docs Build status updates of commit _[16376b8](https://github.com/rajgodwin/office-docs-powershell/commits/16376b8d8dec7b15e0e9e2f5a522de6969dd01e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-Team.md](https://github.com/rajgodwin/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/Get-Team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps&branch=pr-en-us-7477) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202103230943089892-7477%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NV7%2BVmFENcDGNcvyxCzhJHuKo052CluYHtAEtfaDaEw%3D&st=2021-03-23T09%3A40%3A55Z&se=2021-04-23T09%3A45%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-23 16:02 UTC, dariomws approved these changes

2021-03-23 16:20 UTC, tseward approved these changes

2021-03-23 16:21 UTC, tseward commented
I would suggest a small verbiage change; instead of using "At times", use "May".

2021-03-24 12:09 UTC, get-itips approved these changes

2021-03-25 09:32 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-Team.md
>  >[!NOTE]
```suggestion
> [!NOTE]
```

2021-03-25 09:34 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-Team.md
> +>At times, Get-Team returns multiple results matching the input and not just the exact match for attributes like DisplayName/MailNickName. This is a known behaviour.
```suggestion
> Get-Team may return multiple results matching the input and not just the exact match for attributes like DisplayName/MailNickName. This is known behavior.
```

2021-03-25 09:38 UTC, JohanFreelancer9 requested changes
Copy review - a few minor changes, including @tseward's suggestion.

2021-03-25 10:18 UTC, opbld32 commented
Docs Build status updates of commit _[cb2aa4c](https://github.com/rajgodwin/office-docs-powershell/commits/cb2aa4c88e146c97cb22b161562644912c956f2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-Team.md](https://github.com/rajgodwin/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/Get-Team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps&branch=pr-en-us-7477) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202103251015548195-7477%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3WPAibFbVFvjTmp7%2B5ayKtFH3SxKPCNSzbNg%2BQ4xht0%3D&st=2021-03-25T10%3A13%3A45Z&se=2021-04-25T10%3A18%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 10:21 UTC, opbld32 commented
Docs Build status updates of commit _[5517fb2](https://github.com/rajgodwin/office-docs-powershell/commits/5517fb2a867253024f7300341169e959bd8193e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-Team.md](https://github.com/rajgodwin/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/Get-Team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps&branch=pr-en-us-7477) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202103251016200135-7477%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vGlUe7rNq2LyESbGO2DG9EUE0RY17bGwTACxEZ%2FyeQY%3D&st=2021-03-25T10%3A16%3A38Z&se=2021-04-25T10%3A21%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 16:34 UTC, opbld33 commented
Docs Build status updates of commit _[ca00900](https://github.com/rajgodwin/office-docs-powershell/commits/ca00900f0b67738ca0cb9dc30a75e583ddc02974)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-Team.md](https://github.com/rajgodwin/office-docs-powershell/blob/patch-1/teams/teams-ps/teams/Get-Team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps&branch=pr-en-us-7477) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202103251631138953-7477%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WhbgpWpXJ%2BO0DWJ4Gln6vR2UjVGIoPVc%2FdFL6O7bZNY%3D&st=2021-03-25T16%3A29%3A10Z&se=2021-04-25T16%3A34%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 18:07 UTC, merged