Adding missing desc
MicrosoftDocs/office-docs-powershell pull request #7627
Opened 2021-04-16 13:05 UTC by get-itips

@tseward Trevor, do you have the correct description for `-UsageDatabaseEnabled` parameter?

Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7548

2021-04-16 13:08 UTC, opbld30 commented
Docs Build status updates of commit _[52cc3aa](https://github.com/get-itips/office-docs-powershell/commits/52cc3aa60c85987bf292607b6fbac90b1581fcbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md](https://github.com/get-itips/office-docs-powershell/blob/patch-343/sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spusagedefinition?view=sharepoint-ps&branch=pr-en-us-7627) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202104161305315034-7627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=78WV5RLaMu1J8fYnHIQrr3lP9Q3NOEJi7xRtFWPE91w%3D&st=2021-04-16T13%3A03%3A15Z&se=2021-05-17T13%3A08%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 19:05 UTC, tseward commented
@get-itips `UsageDatabaseEnabled` sets the particular `SPUsageDefintion` (i.e. `SQL IO Usage`) to export usage data from the local server (where usage data is stored, same basepath as ULS logs) to the Usage database.

2021-04-16 19:05 UTC, tseward approved these changes

2021-04-16 21:02 UTC, opbld33 commented
Docs Build status updates of commit _[f54a87f](https://github.com/get-itips/office-docs-powershell/commits/f54a87f74e732550b4b1239f84dc1143990a864b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md](https://github.com/get-itips/office-docs-powershell/blob/patch-343/sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spusagedefinition?view=sharepoint-ps&branch=pr-en-us-7627) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202104162059090641-7627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qMBRxY0ruNHQvVeWsWQHxhBFsWEClY773P4ZPMo%2BCwo%3D&st=2021-04-16T20%3A56%3A59Z&se=2021-05-17T21%3A01%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 14:46 UTC, tseward requested changes

2021-04-17 14:46 UTC, tseward commented on sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md
> +Set to export usage data from the local server.
I would expand to "local server to the Usage database.".

2021-04-17 14:58 UTC, opbld33 commented
Docs Build status updates of commit _[ced4e92](https://github.com/get-itips/office-docs-powershell/commits/ced4e925cae2fdf2e9a25964f535c68503f28a61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md](https://github.com/get-itips/office-docs-powershell/blob/patch-343/sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spusagedefinition?view=sharepoint-ps&branch=pr-en-us-7627) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202104171456104983-7627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JHqaUirNjxEBbEU39pjZxKpmauptWYRK8ZDCH69nZkM%3D&st=2021-04-17T14%3A53%3A47Z&se=2021-05-18T14%3A58%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-18 18:05 UTC, tseward approved these changes

2021-04-19 16:12 UTC, dariomws approved these changes

2021-04-19 16:15 UTC, yogkumgit commented
@Kateyanne

2021-04-20 15:53 UTC, opbld32 commented
Docs Build status updates of commit _[d7cb37f](https://github.com/get-itips/office-docs-powershell/commits/d7cb37f385ce955c2e57275a0b875bf70812f530)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md](https://github.com/get-itips/office-docs-powershell/blob/patch-343/sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spusagedefinition?view=sharepoint-ps&branch=pr-en-us-7627) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202104201551109348-7627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WkXpVKELAk2%2FiHEnRfwlhhbKIsUa8548xE8ktsys2go%3D&st=2021-04-20T15%3A48%3A55Z&se=2021-05-21T15%3A53%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 16:49 UTC, opbld33 commented
Docs Build status updates of commit _[7b9f28b](https://github.com/get-itips/office-docs-powershell/commits/7b9f28b509875907061feb95b0a9e4d53579fef0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md](https://github.com/get-itips/office-docs-powershell/blob/patch-343/sharepoint/sharepoint-ps/sharepoint-server/Set-SPUsageDefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-server/set-spusagedefinition?view=sharepoint-ps&branch=pr-en-us-7627) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202104201646338238-7627%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C4Tzdj8BJb0XMGDqpiUayh%2Fge2q0JzGqBei47ijzjxI%3D&st=2021-04-20T16%3A44%3A16Z&se=2021-05-21T16%3A49%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 16:49 UTC, merged