Create Get-WhiteboardOwners
MicrosoftDocs/office-docs-powershell pull request #7816
Opened 2021-05-21 21:21 UTC by shlevari

Added documentation for the Get-WhiteboardOwners powershell module.

2021-05-21 21:23 UTC, opbld31 commented
Docs Build status updates of commit _[f02d887](https://github.com/shlevari/office-docs-powershell/commits/f02d8873f2205ace28a30a1e73fcee8afc154393)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/whiteboard/get-whiteboardowners?view=whiteboard-ps&branch=pr-en-us-7816) (whiteboard-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202105212121159880-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r1B4eo6zIgbPUfBSg1VCE7Npa2emgq%2Bf8tP9LqYiNwk%3D&st=2021-05-21T21%3A18%3A52Z&se=2021-06-21T21%3A23%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 12:06 UTC, get-itips commented on whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md
> +Get-WhiteboardOwners -Geography <geography> -ContinuationToken <optionalToken> [<CommonParameters>]
```suggestion
Get-WhiteboardOwners [-Geography] <String> [[-ContinuationToken] <String>] [-ForceAuthPrompt]
 [<CommonParameters>]
```

2021-05-25 12:10 UTC, get-itips commented on whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md
> +```yaml
Please see this, it is the output given by PlatyPS for the Geography parameter

![image](https://user-images.githubusercontent.com/36666927/119495525-b9933400-bd1f-11eb-92ee-cf1034681eaf.png)

2021-05-25 12:11 UTC, get-itips requested changes
Can you run PlatyPS against the cmdlet and correct the parameters yaml? Thank you

2021-05-26 06:07 UTC, yogkumgit commented
@shlevari review and implement the suggested changes. Thanks

2021-05-31 12:02 UTC, yogkumgit commented
@shlevari Gentle reminder

2021-06-09 18:58 UTC, opbld30 commented
Docs Build status updates of commit _[4313a04](https://github.com/shlevari/office-docs-powershell/commits/4313a04247b22a940e5db2e19e9a09bd1de5786d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/whiteboard/get-whiteboardowners?view=whiteboard-ps&branch=pr-en-us-7816) (whiteboard-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091854438121-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kquj5QnJ6d0cMSrP29Vi%2BhjIPygGtRHgeXf4NUgHsm0%3D&st=2021-06-09T18%3A53%3A04Z&se=2021-07-10T18%3A58%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 19:06 UTC, opbld30 commented
Docs Build status updates of commit _[4e7d397](https://github.com/shlevari/office-docs-powershell/commits/4e7d397f67a6b22e846d9dc308f48d2ab9d45e91)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :x:Error | | [Details](#user-content-f8aa471006a2327ad3d47f17144a1ee7-aa4106d4)
[whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml) | :warning:Warning | | [Details](#user-content-74ac5a8d775c0693184d1b955a65205e-aa4106d4)

<a id="f8aa471006a2327ad3d47f17144a1ee7-aa4106d4"></a>
### [whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/e50r-s/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md:43:(517) '```yaml
Type: String
Parameter Sets: (All)
Alia...'
 Invalid yaml: unknown key Acept wildcard charaters, please try to use PlatyPS validate the content
`````

<a id="74ac5a8d775c0693184d1b955a65205e-aa4106d4"></a>
### [whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml)
 - **Line 6, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftWhiteboardAdmin.Get-WhiteboardOwners'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091904038486-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qGMwBf4w3xXzfOJt9LpiAyJAQwMylQIjwjOFIJezm9k%3D&st=2021-06-09T19%3A01%3A53Z&se=2021-07-10T19%3A06%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 19:09 UTC, opbld33 commented
Docs Build status updates of commit _[44f9454](https://github.com/shlevari/office-docs-powershell/commits/44f94541018a7b61f4664baf90a466f8dadbb212)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :x:Error | | [Details](#user-content-f8aa471006a2327ad3d47f17144a1ee7-d63d7b70)
[whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml) | :warning:Warning | | [Details](#user-content-74ac5a8d775c0693184d1b955a65205e-d63d7b70)

<a id="f8aa471006a2327ad3d47f17144a1ee7-d63d7b70"></a>
### [whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/vpov-s/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md:43:(517) '```yaml
Type: String
Parameter Sets: (All)
Alia...'
 Invalid yaml: unknown key Acept wildcard charaters, please try to use PlatyPS validate the content
`````

<a id="74ac5a8d775c0693184d1b955a65205e-d63d7b70"></a>
### [whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml)
 - **Line 6, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftWhiteboardAdmin.Get-WhiteboardOwners'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091904403845-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3tUzgi7D0Ha6fyufAdjlTUElzoKCf0VBjzwUZk3tudk%3D&st=2021-06-09T19%3A04%3A50Z&se=2021-07-10T19%3A09%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 18:42 UTC, opbld32 commented
Docs Build status updates of commit _[cb2c9ad](https://github.com/shlevari/office-docs-powershell/commits/cb2c9ad8ba60427301d6fe34a61f0f004460f640)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :x:Error | | [Details](#user-content-f8aa471006a2327ad3d47f17144a1ee7-35884434)
[whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml) | :warning:Warning | | [Details](#user-content-74ac5a8d775c0693184d1b955a65205e-35884434)

<a id="f8aa471006a2327ad3d47f17144a1ee7-35884434"></a>
### [whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/3twq-s/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md:29:(476) '```output
TenantId:                  tenantId
Ge...'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="74ac5a8d775c0693184d1b955a65205e-35884434"></a>
### [whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml)
 - **Line 6, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftWhiteboardAdmin.Get-WhiteboardOwners'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106101837227784-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LqByMnVQW0el5IAsrxji5ilOy8rfibJr6WYuIMhxAHk%3D&st=2021-06-10T18%3A37%3A50Z&se=2021-07-11T18%3A42%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 18:48 UTC, opbld30 commented
Docs Build status updates of commit _[98d9967](https://github.com/shlevari/office-docs-powershell/commits/98d9967b5be0b22717df508650f205582f387c2a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :x:Error | | [Details](#user-content-f8aa471006a2327ad3d47f17144a1ee7-da457968)
[whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml) | :warning:Warning | | [Details](#user-content-74ac5a8d775c0693184d1b955a65205e-da457968)

<a id="f8aa471006a2327ad3d47f17144a1ee7-da457968"></a>
### [whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/vuk2-s/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md:43:(517) '```yaml
Type: String
Parameter Sets: (All)
Alia...'
 Invalid yaml: unknown key Acept wildcard charaters, please try to use PlatyPS validate the content
`````

<a id="74ac5a8d775c0693184d1b955a65205e-da457968"></a>
### [whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml)
 - **Line 6, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftWhiteboardAdmin.Get-WhiteboardOwners'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106101845486029-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mr84jUkSzSwy6yCjTIDxyaGwmdJoN45gT8SFxpVsYXo%3D&st=2021-06-10T18%3A43%3A37Z&se=2021-07-11T18%3A48%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 00:46 UTC, opbld33 commented
Docs Build status updates of commit _[a7d780b](https://github.com/shlevari/office-docs-powershell/commits/a7d780b25c3583398ddc28f9c2d64f7f648d31ab)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :x:Error | | [Details](#user-content-f8aa471006a2327ad3d47f17144a1ee7-3f1cfca3)
[whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml) | :warning:Warning | | [Details](#user-content-74ac5a8d775c0693184d1b955a65205e-3f1cfca3)

<a id="f8aa471006a2327ad3d47f17144a1ee7-3f1cfca3"></a>
### [whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/3tqs-s/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md:41:(517) '```yaml
Type: String
Parameter Sets: (All)
Alia...'
 Invalid yaml: unknown key Acept wildcard charaters, please try to use PlatyPS validate the content
`````

<a id="74ac5a8d775c0693184d1b955a65205e-3f1cfca3"></a>
### [whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml)
 - **Line 6, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftWhiteboardAdmin.Get-WhiteboardOwners'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106110043203614-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ltwxofUwXqKr2Zu%2FeyVZHD6PB1SDAFin0FopryzDY%2BA%3D&st=2021-06-11T00%3A41%3A13Z&se=2021-07-12T00%3A46%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 00:49 UTC, opbld33 commented
Docs Build status updates of commit _[26943e5](https://github.com/shlevari/office-docs-powershell/commits/26943e595b7e272ade65e505c4923325869a48e3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :x:Error | | [Details](#user-content-f8aa471006a2327ad3d47f17144a1ee7-e890c9dc)
[whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml) | :warning:Warning | | [Details](#user-content-74ac5a8d775c0693184d1b955a65205e-e890c9dc)

<a id="f8aa471006a2327ad3d47f17144a1ee7-e890c9dc"></a>
### [whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/xlcx-s/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md:41:(517) '```yaml
Type: String
Parameter Sets: (All)
Alia...'
 Invalid yaml: unknown key Acept wildcard charaters, please try to use PlatyPS validate the content
`````

<a id="74ac5a8d775c0693184d1b955a65205e-e890c9dc"></a>
### [whiteboard/whiteboard-ps/whiteboard/index.yml](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/index.yml)
 - **Line 6, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'MicrosoftWhiteboardAdmin.Get-WhiteboardOwners'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106110044254137-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rCJOXuxBmHvew7z31bvlf235g5KPzm%2BOYn8Q8S%2FINwQ%3D&st=2021-06-11T00%3A44%3A07Z&se=2021-07-12T00%3A49%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 01:05 UTC, opbld30 commented
Docs Build status updates of commit _[5cb75a7](https://github.com/shlevari/office-docs-powershell/commits/5cb75a7ba22308a27438472e83fbc256ed983193)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md](https://github.com/shlevari/office-docs-powershell/blob/patch-2/whiteboard/whiteboard-ps/whiteboard/Get-WhiteboardOwners.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/whiteboard/get-whiteboardowners?view=whiteboard-ps&branch=pr-en-us-7816) (whiteboard-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106110102458611-7816%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QuppTE%2FtBY7dlGpwlBVTYoY1EcbVzr1ZDo9P0F58W4A%3D&st=2021-06-11T01%3A00%3A40Z&se=2021-07-12T01%3A05%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 01:05 UTC, merged