Update Set-CsWebServiceConfiguration.md
MicrosoftDocs/office-docs-powershell pull request #7862
Opened 2021-06-02 11:22 UTC by priyanshamishra

Adding clarification for the parameter -EnableCORS.

2021-06-02 11:23 UTC, priyanshamishra commented
@MicrosoftDocs/marveldocs-pubops PR is ready for review. Please review and publish.

2021-06-02 11:25 UTC, opbld33 commented
Docs Build status updates of commit _[548c11e](https://github.com/priyanshamishra/office-docs-powershell/commits/548c11e7e3e24e73d8aa751cc5b6da69fbf0643d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md) | :x:Error | | [Details](#user-content-e4d9e5d7b55b86bc11388ef8ae726bd9-10bc8a0e)
[skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-18959862fd44600f52af78e9342c5f1e-10bc8a0e)
[skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml) | :warning:Warning | | [Details](#user-content-503827085a105ecdc7ff5fb82679cc05-10bc8a0e)
[skype/skype-ps/skype/New-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-6f5cd34217a89e014b15fe31a452ef49-10bc8a0e)
[skype/skype-ps/skype/New-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsXmppAllowedPartner.yml) | :warning:Warning | | [Details](#user-content-9e0f9f21d549f203ccb30eeea234f11b-10bc8a0e)
[skype/skype-ps/skype/New-CsWebTrustedCACertificate.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebTrustedCACertificate.yml) | :warning:Warning | | [Details](#user-content-91b7864dbfad03947597983d17b05d10-10bc8a0e)
[skype/skype-ps/skype/New-CsWebOrigin.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebOrigin.yml) | :warning:Warning | | [Details](#user-content-404161c56cafb7c7791e947725538bef-10bc8a0e)
[skype/skype-ps/skype/index.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/index.yml) | :warning:Warning | | [Details](#user-content-26220b46a4f9444dae3347b62a0e9de2-10bc8a0e)
[skype/skype-ps/skype/Remove-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Remove-CsXmppAllowedPartner.yml) | :warning:Warning | | [Details](#user-content-7423d96dc370dbaeb0ffc915761cab8d-10bc8a0e)
[skype/skype-ps/skype/Remove-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Remove-CsWebServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-242c5abfd090bcbb764a00ef64c9362e-10bc8a0e)

<a id="e4d9e5d7b55b86bc11388ef8ae726bd9-10bc8a0e"></a>
### [skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/dabz-s/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md:281:(1178) '```yaml
Type: Boolean
Position: Named
Default v...'
 Invalid yaml: unknown key Applies to, please try to use PlatyPS validate the content
`````

<a id="18959862fd44600f52af78e9342c5f1e-10bc8a0e"></a>
### [skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="503827085a105ecdc7ff5fb82679cc05-10bc8a0e"></a>
### [skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml)
 - **Line 24, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsXmppAllowedPartner.yml'.`````

<a id="6f5cd34217a89e014b15fe31a452ef49-10bc8a0e"></a>
### [skype/skype-ps/skype/New-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebServiceConfiguration.yml)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="9e0f9f21d549f203ccb30eeea234f11b-10bc8a0e"></a>
### [skype/skype-ps/skype/New-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsXmppAllowedPartner.yml)
 - **Line 24, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsXmppAllowedPartner.yml'.`````

<a id="91b7864dbfad03947597983d17b05d10-10bc8a0e"></a>
### [skype/skype-ps/skype/New-CsWebTrustedCACertificate.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebTrustedCACertificate.yml)
 - **Line 20, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="404161c56cafb7c7791e947725538bef-10bc8a0e"></a>
### [skype/skype-ps/skype/New-CsWebOrigin.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebOrigin.yml)
 - **Line 19, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="26220b46a4f9444dae3347b62a0e9de2-10bc8a0e"></a>
### [skype/skype-ps/skype/index.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/index.yml)
 - **Line 1163, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'SkypeForBusiness.Set-CsWebServiceConfiguration'.`````
 - **Line 1164, Column 5**: **[Warning-xref-not-found]** `````Cross reference not found: 'SkypeForBusiness.Set-CsXmppAllowedPartner'.`````

<a id="7423d96dc370dbaeb0ffc915761cab8d-10bc8a0e"></a>
### [skype/skype-ps/skype/Remove-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Remove-CsXmppAllowedPartner.yml)
 - **Line 24, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsXmppAllowedPartner.yml'.`````

<a id="242c5abfd090bcbb764a00ef64c9362e-10bc8a0e"></a>
### [skype/skype-ps/skype/Remove-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Remove-CsWebServiceConfiguration.yml)
 - **Line 23, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106021122414111-7862%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2Ut4UxG8Samc6eB1hnpH%2BQZ1MFogHyul [...]

2021-06-02 14:14 UTC, Kateyanne commented
@get-itips please review @JohanFreelancer9 please edit. Thank you. @e0i fyi

2021-06-02 14:22 UTC, get-itips requested changes
The parameter needs to be also added to the SYNTAX section of the markdown file.

2021-06-02 16:46 UTC, dariomws approved these changes
I'm ok once @get-itips's suggestion is applied.

2021-06-02 16:48 UTC, dariomws reviewed
Sorry, I found a small detail

2021-06-02 16:48 UTC, dariomws commented on skype/skype-ps/skype/Set-CsWebServiceConfiguration.md
> +Applies to: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
```suggestion
Type: Boolean
Parameter Sets: (All)
Aliases: 
Applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019

Required: False
Position: Named
Default value: False
Accept pipeline input: False
Accept wildcard characters: False
```

2021-06-03 04:09 UTC, opbld30 commented
Docs Build status updates of commit _[20ddc5f](https://github.com/priyanshamishra/office-docs-powershell/commits/20ddc5fe259e48f5397f82ee8dbbacce787d9d37)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md) | :x:Error | | [Details](#user-content-e4d9e5d7b55b86bc11388ef8ae726bd9-fa51c57c)
[skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml) | :warning:Warning | | [Details](#user-content-2989c7e3e2b6daff14a4e756123a25ca-fa51c57c)
[skype/skype-ps/skype/Get-CsClientVersionConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsClientVersionConfiguration.yml) | :warning:Warning | | [Details](#user-content-b8ed8b7504f95c99537b5e0bc96007c6-fa51c57c)
[skype/skype-ps/skype/Get-CsNetworkSite.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsNetworkSite.yml) | :warning:Warning | | [Details](#user-content-756320d9c05299d993e02ac82c2e6344-fa51c57c)
[skype/skype-ps/skype/Get-CsNetworkRegionLink.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsNetworkRegionLink.yml) | :warning:Warning | | [Details](#user-content-2c93a3d6ee2cfab63adafd32d724f5ae-fa51c57c)
[skype/skype-ps/skype/Get-CsDialPlan.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsDialPlan.yml) | :warning:Warning | | [Details](#user-content-ba1e87ae357584a4f3e64cd7b55e3e80-fa51c57c)
[skype/skype-ps/skype/Get-CsRgsHolidaySet.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsRgsHolidaySet.yml) | :warning:Warning | | [Details](#user-content-d49e11172f15015597197c45d70fddb1-fa51c57c)
[skype/skype-ps/skype/Get-CsTrunkConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsTrunkConfiguration.yml) | :warning:Warning | | [Details](#user-content-7aafa6f06595097a3e10116a88de4e05-fa51c57c)
[skype/skype-ps/skype/Get-CsVideoInteropServerSyntheticTransactionConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsVideoInteropServerSyntheticTransactionConfiguration.yml) | :warning:Warning | | [Details](#user-content-1abeb71f709d34696aad3baf14c7d3b1-fa51c57c)
[skype/skype-ps/skype/Get-CsDatabaseMirrorState.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsDatabaseMirrorState.yml) | :warning:Warning | | [Details](#user-content-a2e5a6f40f997b4a23312437c281573a-fa51c57c)
[skype/skype-ps/skype/Get-CsUCPhoneConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsUCPhoneConfiguration.yml) | :warning:Warning | | [Details](#user-content-292ae9169c86eb3cbd171efc9e094f7c-fa51c57c)
[skype/skype-ps/skype/Get-CsUnassignedNumber.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsUnassignedNumber.yml) | :warning:Warning | | [Details](#user-content-87c0c1f0fcbf8fabd13a57efff5334c0-fa51c57c)
[skype/skype-ps/skype/Get-CsUserDatabaseState.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsUserDatabaseState.yml) | :warning:Warning | | [Details](#user-content-5f116b99967bbcf7975871d787a97da2-fa51c57c)
[skype/skype-ps/skype/Get-CsTrustedApplicationPool.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsTrustedApplicationPool.yml) | :warning:Warning | | [Details](#user-content-12ae9d3c7f159fcf93dd75bdee451fb8-fa51c57c)
[skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-18959862fd44600f52af78e9342c5f1e-fa51c57c)
[skype/skype-ps/skype/Get-CsUICulture.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsUICulture.yml) | :warning:Warning | | [Details](#user-content-91d60ab9dd30fc1c706786ec4aafacc9-fa51c57c)
[skype/skype-ps/skype/Install-CsMirrorDatabase.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Install-CsMirrorDatabase.yml) | :warning:Warning | | [Details](#user-content-1d41a893a4ef27828716b209e6566fdb-fa51c57c)
[skype/skype-ps/skype/Invoke-CsUcsRollback.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Invoke-CsUcsRollback.yml) | :warning:Warning | | [Details](#user-content-be1ec263653cb232abd47ffe97fd3ceb-fa51c57c)
[skype/skype-ps/skype/Install-CsDatabase.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Install-CsDatabase.yml) | :warning:Warning | | [Details](#user-content-dfb76878be0045255c9d172b96ab5ef3-fa51c57c)
[skype/skype-ps/skype/New-CsAnnouncement.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsAnnouncement.yml) | :warning:Warning | | [Details](#user-content-70be0e5d96ea090773f67a40d6163df3-fa51c57c)
[skype/skype-ps/skype/New-CsClientVersionConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsClientVersionConfiguration.yml) | :warning:Warning | | [Details](#user-content-f6403687083aea6d6c50f7cc211feb01-fa51c57c)
[skype/skype-ps/skype/Grant-CsDialPlan.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Grant-CsDialPlan.yml) | :warning:Warning | | [Details](#user-content-ad249f4462a525a3290d5e03893f1196-fa51c57c)
[skype/skype-ps/skype/New-CsNetworkSite.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsNetworkSite.yml) | :warning:Warning | | [Details](#user-content-5302fd62d329e2572aadc09aa360744e-fa51c57c)
[skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml) | :warning:Warning | | [Details](#user-content-503827085a105ecdc7ff5fb82679cc05-fa51c57c)
[skype/skype-ps/skype/New-CsNetworkRegionLink.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsNetworkRegionLink.yml) | :warning:Warning | | [Details](#user-content-7a9af0afb8cdf12040088595b590ef22-fa51c57c)
[skype/skype-ps/skype/New-CsDialPlan.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsDialPlan.yml) | :warning:Warning | | [Details](#user-content-0095326a287d5dfab838b9eb89058812-fa51c57c)
[skype/skype-ps/skype/New-CsTrunkConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsTrunkConfiguration.yml) | :warning:Warning | | [Details](#user-content-a3c8a7b8fceab3b820ae196607eb3524-fa51c57c)
[skype/skype-ps/skype/New-CsRgsHolidaySet.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsRgsHolidaySet.yml) | :warning:Warning | | [Details](#user-content-206024397e28ddb156accf36f4112c7c-fa51c57c)
[skype/skype-ps/skype/New-CsRgsHoliday.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsRgsHoliday.yml) | :warning:Warning | | [Details](#user-content-ecfc413c902c8 [...]

2021-06-03 07:15 UTC, JohanFreelancer9 approved these changes

2021-06-03 12:21 UTC, yogkumgit commented
@priyanshamishra please review and update

2021-06-04 04:03 UTC, opbld31 commented
Docs Build status updates of commit _[8b9d897](https://github.com/priyanshamishra/office-docs-powershell/commits/8b9d8977a069d5b9175a2327935a05e82bb193af)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md) | :x:Error | | [Details](#user-content-e4d9e5d7b55b86bc11388ef8ae726bd9-b5360a41)
[skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-18959862fd44600f52af78e9342c5f1e-b5360a41)
[skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml) | :warning:Warning | | [Details](#user-content-503827085a105ecdc7ff5fb82679cc05-b5360a41)
[skype/skype-ps/skype/Get-CsXmppGatewayConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsXmppGatewayConfiguration.yml) | :warning:Warning | | [Details](#user-content-6b18f525dbf0c3e928fe40bb7e875e22-b5360a41)
[skype/skype-ps/skype/New-CsWebOrigin.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebOrigin.yml) | :warning:Warning | | [Details](#user-content-404161c56cafb7c7791e947725538bef-b5360a41)
[skype/skype-ps/skype/New-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsXmppAllowedPartner.yml) | :warning:Warning | | [Details](#user-content-9e0f9f21d549f203ccb30eeea234f11b-b5360a41)
[skype/skype-ps/skype/New-CsWebTrustedCACertificate.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebTrustedCACertificate.yml) | :warning:Warning | | [Details](#user-content-91b7864dbfad03947597983d17b05d10-b5360a41)
[skype/skype-ps/skype/Remove-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Remove-CsWebServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-242c5abfd090bcbb764a00ef64c9362e-b5360a41)
[skype/skype-ps/skype/New-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-6f5cd34217a89e014b15fe31a452ef49-b5360a41)
[skype/skype-ps/skype/index.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/index.yml) | :warning:Warning | | [Details](#user-content-26220b46a4f9444dae3347b62a0e9de2-b5360a41)
[skype/skype-ps/skype/Remove-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Remove-CsXmppAllowedPartner.yml) | :warning:Warning | | [Details](#user-content-7423d96dc370dbaeb0ffc915761cab8d-b5360a41)
[skype/skype-ps/skype/Test-CsXmppIM.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Test-CsXmppIM.yml) | :warning:Warning | | [Details](#user-content-0a99e452e91ec4dc21d7a11e0576bd17-b5360a41)

<a id="e4d9e5d7b55b86bc11388ef8ae726bd9-b5360a41"></a>
### [skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md)
 - **Line 0, Column 0**: **[Error-MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: W:/f00j-s/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md:281:(1178) '```yaml
Type: Boolean
Position: Named
Default v...'
 Invalid yaml: unknown key Applies to, please try to use PlatyPS validate the content
`````

<a id="18959862fd44600f52af78e9342c5f1e-b5360a41"></a>
### [skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsWebServiceConfiguration.yml)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="503827085a105ecdc7ff5fb82679cc05-b5360a41"></a>
### [skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsXmppAllowedPartner.yml)
 - **Line 24, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsXmppAllowedPartner.yml'.`````

<a id="6b18f525dbf0c3e928fe40bb7e875e22-b5360a41"></a>
### [skype/skype-ps/skype/Get-CsXmppGatewayConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Get-CsXmppGatewayConfiguration.yml)
 - **Line 20, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsXmppGatewayConfiguration.yml'.`````

<a id="404161c56cafb7c7791e947725538bef-b5360a41"></a>
### [skype/skype-ps/skype/New-CsWebOrigin.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebOrigin.yml)
 - **Line 19, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="9e0f9f21d549f203ccb30eeea234f11b-b5360a41"></a>
### [skype/skype-ps/skype/New-CsXmppAllowedPartner.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsXmppAllowedPartner.yml)
 - **Line 24, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsXmppAllowedPartner.yml'.`````

<a id="91b7864dbfad03947597983d17b05d10-b5360a41"></a>
### [skype/skype-ps/skype/New-CsWebTrustedCACertificate.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebTrustedCACertificate.yml)
 - **Line 20, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="242c5abfd090bcbb764a00ef64c9362e-b5360a41"></a>
### [skype/skype-ps/skype/Remove-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Remove-CsWebServiceConfiguration.yml)
 - **Line 23, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="6f5cd34217a89e014b15fe31a452ef49-b5360a41"></a>
### [skype/skype-ps/skype/New-CsWebServiceConfiguration.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsWebServiceConfiguration.yml)
 - **Line 22, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsWebServiceConfiguration.yml'.`````

<a id="26220b46a4f9444dae3347b62a0e9de2-b5360a41"></a>
### [skype/skype-ps/skype/index.yml](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/index.yml)
 - **Line 1163, Column 5**: **[Warning-xr [...]

2021-06-04 21:14 UTC, opbld32 commented
Docs Build status updates of commit _[bb64792](https://github.com/priyanshamishra/office-docs-powershell/commits/bb64792ce12a790e6b616f164003d1c8da1bb346)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cswebserviceconfiguration?view=skype-ps&branch=pr-en-us-7862) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106042111375321-7862%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=USahsC68BIzKajaR%2Bt0P8fSjgyqCKIFpqVGP%2B6DZxpE%3D&st=2021-06-04T21%3A09%3A40Z&se=2021-07-05T21%3A14%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 22:09 UTC, dstrome commented
@priyanshamishra @Kateyanne - I fixed the syntax issue that was causing the error, however, there are some parameter properties missing from the new parameter that was added:

- Parameter Sets
- Aliases
- Required

Also, the new parameter doesn't appear in any of the parameter sets at the top of the topic. 

All of these issues must be fixed before you publish the topic, so I've placed the *Do not merge* label on the PR. When these issues are fixed, you can remove the label and merge the PR.

2021-06-05 06:10 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsWebServiceConfiguration.md
> +Applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
```suggestion
Position: Named
Parameter Sets: (All)
Aliases:
Applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019

Required: False
Position: Named
Default value: False
Accept pipeline input: False
Accept wildcard characters: False
```

2021-06-05 06:22 UTC, JohanFreelancer9 requested changes
@priyanshamishra - I have added the missing parameter properties as suggested changes - please commit the suggestions if you agree with them. Also, please add the new parameter in the parameter sets at the top of the topic as per @dstrome's request.

2021-06-08 06:25 UTC, opbld33 commented
Docs Build status updates of commit _[e01dd38](https://github.com/priyanshamishra/office-docs-powershell/commits/e01dd38ea5eb328877ee1b8bfd608ab3f0435558)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cswebserviceconfiguration?view=skype-ps&branch=pr-en-us-7862) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106080622302614-7862%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mjGhztE7jkjlHL5ovIa0i9rY8IBsDdu%2F9gJQw8HvGOM%3D&st=2021-06-08T06%3A20%3A17Z&se=2021-07-09T06%3A25%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-08 13:53 UTC, yogkumgit commented
@JohanFreelancer9  and @get-itips

2021-06-08 14:26 UTC, get-itips commented
> @JohanFreelancer9 and @get-itips

The PR author still needs to apply suggestions, for example, include the parameter in the syntax section.

2021-06-09 08:49 UTC, opbld32 commented
Docs Build status updates of commit _[92a845f](https://github.com/priyanshamishra/office-docs-powershell/commits/92a845f31f6cf0613be3d761f2589c397ec5e363)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cswebserviceconfiguration?view=skype-ps&branch=pr-en-us-7862) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106090845528726-7862%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mWcwCXiwIkjyC6t00FKxIRngx3djMAVFUiaqpgmNV6I%3D&st=2021-06-09T08%3A44%3A04Z&se=2021-07-10T08%3A49%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 16:21 UTC, yogkumgit commented
@JohanFreelancer9 and @get-itips

2021-06-09 19:00 UTC, get-itips commented
@priyanshamishra The parameter -EnableCORS is still missing from the syntax section, can you add it please? Thanks

2021-06-10 03:51 UTC, priyanshamishra commented
> @priyanshamishra The parameter -EnableCORS is still missing from the syntax section, can you add it please? Thanks

I have added the parameter to the syntax section.

2021-06-10 03:52 UTC, opbld33 commented
Docs Build status updates of commit _[ebd7858](https://github.com/priyanshamishra/office-docs-powershell/commits/ebd7858d6bca84ebabfe7b990c83277cf8a406e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cswebserviceconfiguration?view=skype-ps&branch=pr-en-us-7862) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106100349102056-7862%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mR85nRYy3jMHtL8VBJnKgmnB9RVaXiZm8mNS2IepKB4%3D&st=2021-06-10T03%3A47%3A11Z&se=2021-07-11T03%3A52%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-10 04:16 UTC, JohanFreelancer9 approved these changes

2021-06-10 10:02 UTC, yogkumgit commented
@get-itips

2021-06-10 14:19 UTC, get-itips approved these changes

2021-06-10 18:56 UTC, Kateyanne commented
@dstrome do you concur this can now be merged?

2021-06-11 16:27 UTC, opbld30 commented
Docs Build status updates of commit _[8c792cb](https://github.com/priyanshamishra/office-docs-powershell/commits/8c792cb75b63f1094dc98a7f434f44d647c8674b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsWebServiceConfiguration.md](https://github.com/priyanshamishra/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsWebServiceConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cswebserviceconfiguration?view=skype-ps&branch=pr-en-us-7862) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106111624089070-7862%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5zeDeFd7EEFvRA5myhNzSsv948rmyou2bbWXZf%2Be3sI%3D&st=2021-06-11T16%3A22%3A12Z&se=2021-07-12T16%3A27%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-11 16:48 UTC, merged