Update Move-CsUser.md
MicrosoftDocs/office-docs-powershell pull request #7904
Opened 2021-06-08 23:48 UTC by bjwhalen

updated since MoveToTeams switch no longer required.

2021-06-08 23:51 UTC, opbld30 commented
Docs Build status updates of commit _[53d8184](https://github.com/bjwhalen/office-docs-powershell/commits/53d8184cbd10e5954143d3328a6976d518c6ded8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Move-CsUser.md) | :x:Error | | [Details](#user-content-bff1880f870ca1d8805755e6199adade-60728edc)
[skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml) | :warning:Warning | | [Details](#user-content-2989c7e3e2b6daff14a4e756123a25ca-60728edc)
[skype/skype-ps/skype/Debug-CsAddressBookReplication.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsAddressBookReplication.yml) | :warning:Warning | | [Details](#user-content-560eda5289c99a741f7ecaee66e88f56-60728edc)
[skype/skype-ps/skype/Export-CsLisConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Export-CsLisConfiguration.yml) | :warning:Warning | | [Details](#user-content-4311dab54afa2cdd0fdecedd521a418d-60728edc)
[skype/skype-ps/skype/Approve-CsDeviceUpdateRule.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Approve-CsDeviceUpdateRule.yml) | :warning:Warning | | [Details](#user-content-76225584b96cc482114eb0d6ad8d35b8-60728edc)
[skype/skype-ps/skype/Convert-CsUserData.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Convert-CsUserData.yml) | :warning:Warning | | [Details](#user-content-de6b735a56330198b4471e3d61072a96-60728edc)
[skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml) | :warning:Warning | | [Details](#user-content-5b0c7aa08a8a09fb612a7fcea49272cb-60728edc)
[skype/skype-ps/skype/Debug-CsDataConference.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsDataConference.yml) | :warning:Warning | | [Details](#user-content-76cd46aa5f2ebd3ca25c81246b53b822-60728edc)
[skype/skype-ps/skype/Enable-CsMeetingRoom.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-7f79575f4c926fb4cf859f8b0cd336b3-60728edc)
[skype/skype-ps/skype/Disable-CsMeetingRoom.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Disable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-fbf528d33ca281a47815a84b1ca6d38a-60728edc)
[skype/skype-ps/skype/Enable-CsPublicProvider.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsPublicProvider.yml) | :warning:Warning | | [Details](#user-content-e0d0020b651061faa1ea3eb20cfd90d7-60728edc)
[skype/skype-ps/skype/Debug-CsLisConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsLisConfiguration.yml) | :warning:Warning | | [Details](#user-content-eede4467c4735fc0e75a4544463eba1c-60728edc)
[skype/skype-ps/skype/Disable-CsHostingProvider.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Disable-CsHostingProvider.yml) | :warning:Warning | | [Details](#user-content-7890cdb6d206f8a21782c1b175110b58-60728edc)
[skype/skype-ps/skype/Enable-CsHostingProvider.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsHostingProvider.yml) | :warning:Warning | | [Details](#user-content-6bec6124fff513cb5f513d6f9379e38d-60728edc)
[skype/skype-ps/skype/Disable-CsComputer.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Disable-CsComputer.yml) | :warning:Warning | | [Details](#user-content-60e53150ca6e0f3c60c65a82ec650bce-60728edc)
[skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml) | :warning:Warning | | [Details](#user-content-b3adbc432a8402141afc7bac7adf9d9f-60728edc)
[skype/skype-ps/skype/Enable-CsTopology.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsTopology.yml) | :warning:Warning | | [Details](#user-content-6fb5056995de31b3f33a28a921be1cc2-60728edc)
[skype/skype-ps/skype/Get-CsAccessEdgeConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAccessEdgeConfiguration.yml) | :warning:Warning | | [Details](#user-content-65c7d62e008e510b1a6d900757d3fa20-60728edc)
[skype/skype-ps/skype/Disable-CsPublicProvider.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Disable-CsPublicProvider.yml) | :warning:Warning | | [Details](#user-content-00090a0918f34d3ccf1a431d5a522e87-60728edc)
[skype/skype-ps/skype/Get-CsApplicationMeetingConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsApplicationMeetingConfiguration.yml) | :warning:Warning | | [Details](#user-content-53ed777e79b80f599b1e01e1022a4448-60728edc)
[skype/skype-ps/skype/Get-CsArchivingConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsArchivingConfiguration.yml) | :warning:Warning | | [Details](#user-content-3721516abf0ed5136c8bcd165179b3ec-60728edc)
[skype/skype-ps/skype/Get-CsBlockedDomain.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsBlockedDomain.yml) | :warning:Warning | | [Details](#user-content-31ceb23fdd2380bd68e71ce7e980c9c2-60728edc)
[skype/skype-ps/skype/Get-CsAnalogDevice.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAnalogDevice.yml) | :warning:Warning | | [Details](#user-content-8a9f2aafc5739d219b9e96381a40e500-60728edc)
[skype/skype-ps/skype/Get-CsAdPrincipal.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAdPrincipal.yml) | :warning:Warning | | [Details](#user-content-152da6886e7500b9481d28f58dbfedb5-60728edc)
[skype/skype-ps/skype/Get-CsApplicationAccessPolicy.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsApplicationAccessPolicy.yml) | :warning:Warning | | [Details](#user-content-86df3068453e06ff0e0b92ed0c518108-60728edc)
[skype/skype-ps/skype/Get-CsAddressBookConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAddressBookConfiguration.yml) | :warning:Warning | | [Details](#user-content-0d436e28b52e7ffd9a7ac36365c517e1-60728edc)
[skype/skype-ps/skype/Enable-CsComputer.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsComputer.yml) | :warning:Warning | | [Details](#user-content-1f99a67827c75608f3b97149ef5a2466-60728edc)
[skype/skype-ps/skype/Get-CsAllowedDomain.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAllowedDomain.yml) | :warning:Warning | | [Details](#user-content-23d2227dece722369b94dd720a9f2bf3-60728edc)
[skype/skype-ps/skype/Get-CsBandwidthPolicyServiceConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsBandwidthPolicyServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-5fa7dd8d3de627b7c76d90e386bf9071-60728edc)
[skype/skype-ps/skype/Get-CsAudioTestServiceApplication.yml](https://github.com/b [...]

2021-06-09 02:21 UTC, opbld30 commented
Docs Build status updates of commit _[4edb17e](https://github.com/bjwhalen/office-docs-powershell/commits/4edb17e20808836ddba6657474241f9964ceb9a7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Move-CsUser.md) | :x:Error | | [Details](#user-content-bff1880f870ca1d8805755e6199adade-40803a4c)
[skype/skype-ps/skype/Enable-CsComputer.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsComputer.yml) | :warning:Warning | | [Details](#user-content-1f99a67827c75608f3b97149ef5a2466-40803a4c)
[skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml) | :warning:Warning | | [Details](#user-content-5b0c7aa08a8a09fb612a7fcea49272cb-40803a4c)
[skype/skype-ps/skype/Disable-CsComputer.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Disable-CsComputer.yml) | :warning:Warning | | [Details](#user-content-60e53150ca6e0f3c60c65a82ec650bce-40803a4c)
[skype/skype-ps/skype/Debug-CsDataConference.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsDataConference.yml) | :warning:Warning | | [Details](#user-content-76cd46aa5f2ebd3ca25c81246b53b822-40803a4c)
[skype/skype-ps/skype/Clear-CsPersistentChatRoom.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Clear-CsPersistentChatRoom.yml) | :warning:Warning | | [Details](#user-content-95b7fabb24606df45c639b89148a2a1e-40803a4c)
[skype/skype-ps/skype/Debug-CsLisConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsLisConfiguration.yml) | :warning:Warning | | [Details](#user-content-eede4467c4735fc0e75a4544463eba1c-40803a4c)
[skype/skype-ps/skype/Disable-CsMeetingRoom.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Disable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-fbf528d33ca281a47815a84b1ca6d38a-40803a4c)
[skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml) | :warning:Warning | | [Details](#user-content-2989c7e3e2b6daff14a4e756123a25ca-40803a4c)
[skype/skype-ps/skype/Approve-CsDeviceUpdateRule.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Approve-CsDeviceUpdateRule.yml) | :warning:Warning | | [Details](#user-content-76225584b96cc482114eb0d6ad8d35b8-40803a4c)
[skype/skype-ps/skype/Enable-CsPublicProvider.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsPublicProvider.yml) | :warning:Warning | | [Details](#user-content-e0d0020b651061faa1ea3eb20cfd90d7-40803a4c)
[skype/skype-ps/skype/Get-CsAddressBookConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAddressBookConfiguration.yml) | :warning:Warning | | [Details](#user-content-0d436e28b52e7ffd9a7ac36365c517e1-40803a4c)
[skype/skype-ps/skype/Get-CsAccessEdgeConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAccessEdgeConfiguration.yml) | :warning:Warning | | [Details](#user-content-65c7d62e008e510b1a6d900757d3fa20-40803a4c)
[skype/skype-ps/skype/Disable-CsPublicProvider.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Disable-CsPublicProvider.yml) | :warning:Warning | | [Details](#user-content-00090a0918f34d3ccf1a431d5a522e87-40803a4c)
[skype/skype-ps/skype/Enable-CsHostingProvider.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsHostingProvider.yml) | :warning:Warning | | [Details](#user-content-6bec6124fff513cb5f513d6f9379e38d-40803a4c)
[skype/skype-ps/skype/Get-CsAdPrincipal.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAdPrincipal.yml) | :warning:Warning | | [Details](#user-content-152da6886e7500b9481d28f58dbfedb5-40803a4c)
[skype/skype-ps/skype/Debug-CsAddressBookReplication.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Debug-CsAddressBookReplication.yml) | :warning:Warning | | [Details](#user-content-560eda5289c99a741f7ecaee66e88f56-40803a4c)
[skype/skype-ps/skype/Get-CsAudioTestServiceApplication.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAudioTestServiceApplication.yml) | :warning:Warning | | [Details](#user-content-c6c7f2ff4670df18625fe3cb6b1875d3-40803a4c)
[skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml) | :warning:Warning | | [Details](#user-content-b3adbc432a8402141afc7bac7adf9d9f-40803a4c)
[skype/skype-ps/skype/Enable-CsMeetingRoom.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Enable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-7f79575f4c926fb4cf859f8b0cd336b3-40803a4c)
[skype/skype-ps/skype/Get-CsApplicationMeetingConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsApplicationMeetingConfiguration.yml) | :warning:Warning | | [Details](#user-content-53ed777e79b80f599b1e01e1022a4448-40803a4c)
[skype/skype-ps/skype/Get-CsAVEdgeConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsAVEdgeConfiguration.yml) | :warning:Warning | | [Details](#user-content-b27bc37ed225ebb73e6c5975893f917f-40803a4c)
[skype/skype-ps/skype/Convert-CsUserData.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Convert-CsUserData.yml) | :warning:Warning | | [Details](#user-content-de6b735a56330198b4471e3d61072a96-40803a4c)
[skype/skype-ps/skype/Export-CsLisConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Export-CsLisConfiguration.yml) | :warning:Warning | | [Details](#user-content-4311dab54afa2cdd0fdecedd521a418d-40803a4c)
[skype/skype-ps/skype/Get-CsCallViaWorkPolicy.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsCallViaWorkPolicy.yml) | :warning:Warning | | [Details](#user-content-4c05f9c12d4095d27a54bb56e0cb4455-40803a4c)
[skype/skype-ps/skype/Get-CsClientVersionPolicy.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsClientVersionPolicy.yml) | :warning:Warning | | [Details](#user-content-1f3eb17ce6fa2f3d4a17821783fb09dd-40803a4c)
[skype/skype-ps/skype/Get-CsArchivingConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsArchivingConfiguration.yml) | :warning:Warning | | [Details](#user-content-3721516abf0ed5136c8bcd165179b3ec-40803a4c)
[skype/skype-ps/skype/Get-CsCallParkOrbit.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsCallParkOrbit.yml) | :warning:Warning | | [Details](#user-content-6204ccb882b9c5e9a8673446c864fa07-40803a4c)
[skype/skype-ps/skype/Get-CsBackupServiceConfiguration.yml](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Get-CsBackupServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-a97a046abee6a172ae79429b82afcf03-40803a4c)
[skype/skype-ps/skype/Disable-CsHostingProvider.yml [...]

2021-06-09 17:03 UTC, opbld33 commented
Docs Build status updates of commit _[3a05429](https://github.com/bjwhalen/office-docs-powershell/commits/3a0542916ab34826fe1b4ce7b307b3d7f91765c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Move-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps&branch=pr-en-us-7904) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091700199415-7904%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HXArdvVEr7qbDe69BSz2rOdTNiGAAUxhkVpnDVcZUhQ%3D&st=2021-06-09T16%3A58%3A16Z&se=2021-07-10T17%3A03%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 17:05 UTC, dariomws requested changes

2021-06-09 17:05 UTC, dariomws commented on skype/skype-ps/skype/Move-CsUser.md
> +In Example 2, the Move-CsUser cmdlet is first used to move the user account with sip address PilarA@contoso.com to TeamsOnly in Microsoft 365. Then, using Teams PowerShell  the mode is updated to rem
```suggestion
In Example 2, the Move-CsUser cmdlet is first used to move the user account with the sip address PilarA@contoso.com to TeamsOnly in Microsoft 365. Then, using Teams PowerShell, the mode is updated to remove TeamsOnly mode so the user can use Skype for Business Online. 
```

2021-06-09 17:05 UTC, dariomws commented on skype/skype-ps/skype/Move-CsUser.md
> +This parameter is no longer needed. This parameter is only  available with Skype for Business Server 2019 and CU8 for Skype for Business Server 2015 and previously was required to move a user *direct
```suggestion
This parameter is no longer needed. This parameter is only available with Skype for Business Server 2019 and CU8 for Skype for Business Server 2015 and previously was required to move a user *directly* to TeamsOnly in Microsoft 365. However, when using Move-CsUser, users are now always moved to TeamsOnly, whether this switch is specified or not.
```

2021-06-09 17:09 UTC, dariomws requested changes

2021-06-09 17:09 UTC, dariomws commented on skype/skype-ps/skype/Move-CsUser.md
> +The hosted migration service is the service in Office 365 that performs user moves. By default, there is no need to specify a value for this parameter, as long as the hosting provider has its AutoDis
```suggestion
The hosted migration service is the service in Office 365 that performs user moves. By default, there is no need to specify a value for this parameter, as long as the hosting provider has its AutoDiscover URL properly configured and you are using an admin account the ends in .onmicrosoft.com. If you are using a user account from on-premises that synchronized to the cloud, you must specify this parameter. See [Required administrative credentials](/skypeforbusiness/hybrid/move-users-between-on-premises-and-cloud#required-administrative-credentials).
```

2021-06-09 17:10 UTC, opbld30 commented
Docs Build status updates of commit _[4aa6260](https://github.com/bjwhalen/office-docs-powershell/commits/4aa6260c9b1a1ca2c95144a0c4b2c2fe6eaede98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Move-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps&branch=pr-en-us-7904) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091707118687-7904%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7Fcss6EvarYla5YDNoYwwnth%2BBtSq91z4SqCzdGkKn8%3D&st=2021-06-09T17%3A04%3A59Z&se=2021-07-10T17%3A09%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 17:13 UTC, opbld30 commented
Docs Build status updates of commit _[4aa6260](https://github.com/bjwhalen/office-docs-powershell/commits/4aa6260c9b1a1ca2c95144a0c4b2c2fe6eaede98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Move-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps&branch=pr-en-us-7904) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091707224800-7904%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JxCnKomTVABelxY43QxvM4ci8idD84kysbGA9eKoNpQ%3D&st=2021-06-09T17%3A08%3A01Z&se=2021-07-10T17%3A13%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 17:16 UTC, opbld30 commented
Docs Build status updates of commit _[dbbb58e](https://github.com/bjwhalen/office-docs-powershell/commits/dbbb58ef00b27a0c800fbc937d9d53251b3d8fef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Move-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps&branch=pr-en-us-7904) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091711299006-7904%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Yc5wFGYfEYG%2B9G5DEFDFrfLPfEmsfRBOZXdSARZznAs%3D&st=2021-06-09T17%3A11%3A04Z&se=2021-07-10T17%3A16%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 17:19 UTC, opbld30 commented
Docs Build status updates of commit _[e6cacc7](https://github.com/bjwhalen/office-docs-powershell/commits/e6cacc7dc62015230c949f37799d988c4c896a58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/bjwhalen/office-docs-powershell/blob/patch-74/skype/skype-ps/skype/Move-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps&branch=pr-en-us-7904) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106091707264914-7904%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mVvv3KNHq6ODJrs7TLszSBMdr0rKbxurUBrtByNfjTA%3D&st=2021-06-09T17%3A14%3A00Z&se=2021-07-10T17%3A19%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 17:28 UTC, dariomws approved these changes
Thank you @bjwhalen and @chrisda!

2021-06-09 18:02 UTC, merged

2021-06-09 19:06 UTC, get-itips reviewed
Reviewed