Update Set-SPOSite.md
MicrosoftDocs/office-docs-powershell pull request #7958
Opened 2021-06-18 18:01 UTC by SanjoyanM

new cmdlet option added

Set-SPOSite -Identity <site url> -ConditionalAccessPolicy AuthenticationContext -AuthenticationContextName "Name of Authentication Context"

2021-06-18 18:15 UTC, opbld32 commented
Docs Build status updates of commit _[6e167fb](https://github.com/SanjoyanM/office-docs-powershell/commits/6e167fbcff135ff9aab69962be8c6634483d973a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/SanjoyanM/office-docs-powershell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-7958) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106181801094894-7958%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=56YJ1bVpwHjGxuJGL6BX9RpI1ssWcWBb5pZUj1uj7io%3D&st=2021-06-18T18%3A10%3A03Z&se=2021-07-19T18%3A15%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 12:22 UTC, dariomws requested changes

2021-06-21 12:22 UTC, dariomws commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
> +- AuthenticationContext: Assign a Azure AD authentication context. Must add the AuthenticationContextName  Please read https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/conce
```suggestion
- AuthenticationContext: Assign an Azure AD authentication context. Must add the AuthenticationContextName. Please read /azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#configure-authentication-contexts.
```

2021-06-21 12:25 UTC, dariomws requested changes
AuthenticationContextName parameter doesn't appear in the Syntax section.

2021-06-21 12:26 UTC, get-itips requested changes
I am ok once @dariomws suggestions are applied.

2021-06-22 07:36 UTC, opbld33 commented
Docs Build status updates of commit _[9bc25f5](https://github.com/SanjoyanM/office-docs-powershell/commits/9bc25f57a5dd7f98400c7712c2b7fb724d5e52d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/SanjoyanM/office-docs-powershell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-7958) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106220733000681-7958%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i6zdHAkAvJSPcFEZdiHuKukFPkiB9cDxtwaA760bJGQ%3D&st=2021-06-22T07%3A31%3A37Z&se=2021-07-23T07%3A36%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 07:39 UTC, opbld30 commented
Docs Build status updates of commit _[bf3a005](https://github.com/SanjoyanM/office-docs-powershell/commits/bf3a005f1651bfc78d69243aed598c7734641a8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/SanjoyanM/office-docs-powershell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-7958) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106220734143642-7958%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Jf85VEh6i0dDajTErNIVWWquG2q5hXJKQhBsX41%2FJjQ%3D&st=2021-06-22T07%3A34%3A57Z&se=2021-07-23T07%3A39%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 08:04 UTC, dariomws approved these changes

2021-06-22 13:26 UTC, yogkumgit commented
@tseward

2021-06-22 13:33 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
> +- AuthenticationContext: Assign an Azure AD authentication context. Must add the AuthenticationContextName. Please read /azure/active-directory/conditional-access/concept-conditional-access-cloud-app
```suggestion
- AuthenticationContext: Assign an Azure AD authentication context. Must add the AuthenticationContextName. Please read [Configure authentication contexts](/azure/active-directory/conditional-access/concept-conditional-access-cloud-apps#configure-authentication-contexts).
```

2021-06-22 13:45 UTC, get-itips approved these changes

2021-06-22 13:48 UTC, opbld31 commented
Docs Build status updates of commit _[77c96fc](https://github.com/SanjoyanM/office-docs-powershell/commits/77c96fce0aea76c069473614530aae69939275e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/SanjoyanM/office-docs-powershell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-7958) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106221345163554-7958%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i4GDyAovpfxGUQtiPz9pKH1GY0jnWlRp90JtRFidfDU%3D&st=2021-06-22T13%3A43%3A28Z&se=2021-07-23T13%3A48%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 18:31 UTC, tseward approved these changes

2021-06-23 14:06 UTC, yogkumgit commented
@Kateyanne Please merge this PR. Thanks

2021-06-23 15:24 UTC, opbld32 commented
Docs Build status updates of commit _[c2b6414](https://github.com/SanjoyanM/office-docs-powershell/commits/c2b6414124424ec5e9ca46b5149cdee87617d5cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/SanjoyanM/office-docs-powershell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-7958) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C23%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202106231521108893-7958%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AaLRb0wV0zlnqe6xmXrtpOBJlQSzA6trTECyPKYODG8%3D&st=2021-06-23T15%3A19%3A11Z&se=2021-07-24T15%3A24%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-23 15:44 UTC, merged