Isrumnon patch 2
MicrosoftDocs/office-docs-powershell pull request #8590
Opened 2021-11-12 16:26 UTC by isrumnon

2021-11-12 16:29 UTC, opbld30 commented
Docs Build status updates of commit _[1c5bee5](https://github.com/isrumnon/office-docs-powershell-new/commits/1c5bee5b3f1d7b18a0507e28eacd6c9707d11494)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/isrumnon-patch-2/skype/skype-ps/skype/Get-CsTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps&branch=pr-en-us-8590) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202111121626520846-8590%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T16%3A29%3A10Z&sr=b&sp=r&sig=YjnUb3av28IFDZuQRCuYg0O19Pc%2FpBWnz4eYV3VGpyY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 06:37 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2021-11-15 07:58 UTC, dariomws requested changes
Please move this note from "Examples" section to "Description". Thanks.

2021-11-15 07:58 UTC, dariomws commented on skype/skype-ps/skype/Get-CsTenant.md
> +**NOTE**
```suggestion
**NOTE:**
```

2021-11-15 07:58 UTC, dariomws commented on skype/skype-ps/skype/Get-CsTenant.md
> +Beginning TPM 2.6.2 onwards, the below updates are applicable for TeamsOnly customers
```suggestion
Beginning TPM 2.6.2 onwards, the below updates are applicable for TeamsOnly customers.
```

2021-11-15 08:04 UTC, opbld31 commented
Docs Build status updates of commit _[a8e4a20](https://github.com/isrumnon/office-docs-powershell-new/commits/a8e4a207fd6800880cb0d49054d3f5dabca0db67)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/isrumnon-patch-2/skype/skype-ps/skype/Get-CsTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps&branch=pr-en-us-8590) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202111150801551677-8590%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T08%3A04%3A37Z&sr=b&sp=r&sig=cI37SJFsxCDhA5u5h5%2B1WzSyjEBcoV2IwHstM1kC5kM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 08:06 UTC, opbld33 commented
Docs Build status updates of commit _[4f0de31](https://github.com/isrumnon/office-docs-powershell-new/commits/4f0de31a545020540c3e4d188aae23847145e42c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/isrumnon-patch-2/skype/skype-ps/skype/Get-CsTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps&branch=pr-en-us-8590) (skype-ps) |

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 14:55 UTC, opbld31 commented
Docs Build status updates of commit _[cf179e9](https://github.com/isrumnon/office-docs-powershell-new/commits/cf179e90b6522829a8eac0b331d24a6f1083ba21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/isrumnon-patch-2/skype/skype-ps/skype/Get-CsTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps&branch=pr-en-us-8590) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202111151451110611-8590%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T14%3A55%3A12Z&sr=b&sp=r&sig=LO9tyUpFchL28%2FkI0WshFks94R1dL%2BVCqQwXnmQf6dk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 15:01 UTC, dariomws approved these changes
Thank you @isrumnon.

I think it's a good idea to replace TPM with "Microsoft Teams PowerShell version" or "Microsoft Teams PowerShell Module version" as @get-itips suggested.
With just TPM we can expect that someone opens an issue to ask about what the acronym means.

2021-11-15 15:10 UTC, isrumnon commented
Done

From: Dario Woitasen ***@***.***>
Sent: Monday, November 15, 2021 8:31 PM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Isaiah Rumnong ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Isrumnon patch 2 (PR #8590)


@dariomws approved this pull request.

Thank you @isrumnon<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fisrumnon&data=04%7C01%7CIsaiah.Rumnong%40microsoft.com%7C0be231f2585b40f76efe08d9a848c819%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637725852852530622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BIvH8WJskgQoJZmLfnFya7Wt6twIPx40CmfEqMwFVzw%3D&reserved=0>.

I think it's a good idea to replace TPM with "Microsoft Teams PowerShell version" or "Microsoft Teams PowerShell Module version" as @get-itips<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fget-itips&data=04%7C01%7CIsaiah.Rumnong%40microsoft.com%7C0be231f2585b40f76efe08d9a848c819%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637725852852530622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jmN7W0C4JMOxBCfDJe8n%2FkHThn030tulCmLtubjHtqs%3D&reserved=0> suggested.
With just TPM we can expect that someone opens an issue to ask about what the acronym means.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-docs-powershell%2Fpull%2F8590%23pullrequestreview-806177519&data=04%7C01%7CIsaiah.Rumnong%40microsoft.com%7C0be231f2585b40f76efe08d9a848c819%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637725852852540615%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mttFCpg0MSRqVxlY7RiUi8lQcynOdzYLm8FfwgbCRM0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVKV6V5IMP5JKZNCDKUA7CLUMEOD7ANCNFSM5H5GWLCA&data=04%7C01%7CIsaiah.Rumnong%40microsoft.com%7C0be231f2585b40f76efe08d9a848c819%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637725852852540615%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MaOHo%2FeuOO3cO%2F57vX1Are3Xln9y8ugM4HIf87bOKLo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CIsaiah.Rumnong%40microsoft.com%7C0be231f2585b40f76efe08d9a848c819%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637725852852550609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UluvADe3sZi7r0hbO9vDNuRzKoYIP9TsF5lrNxAYrI0%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CIsaiah.Rumnong%40microsoft.com%7C0be231f2585b40f76efe08d9a848c819%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637725852852550609%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XnCADUXv%2B8oyCdKiWAWrjfvhraEW%2F%2Bf%2BY7Ix%2BqyaseQ%3D&reserved=0>.

2021-11-15 15:11 UTC, opbld30 commented
Docs Build status updates of commit _[77db169](https://github.com/isrumnon/office-docs-powershell-new/commits/77db1698ff69eef706bc8ca331d9ce0b4172018a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/isrumnon-patch-2/skype/skype-ps/skype/Get-CsTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps&branch=pr-en-us-8590) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202111151509132514-8590%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T15%3A11%3A50Z&sr=b&sp=r&sig=dSaABvMA3KeW%2FDkauhXOHPOvYuxEoKSos8qZUTAcFss%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 15:21 UTC, tseward approved these changes

2021-11-16 12:06 UTC, yogkumgit commented
@get-itips

2021-11-16 12:29 UTC, get-itips approved these changes

2021-11-16 12:33 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2021-11-16 16:55 UTC, opbld30 commented
Docs Build status updates of commit _[d13d5e7](https://github.com/isrumnon/office-docs-powershell-new/commits/d13d5e7f8d869722168ec9c7627faebe51ca4970)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/isrumnon-patch-2/skype/skype-ps/skype/Get-CsTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps&branch=pr-en-us-8590) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202111161652472976-8590%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T16%3A55%3A09Z&sr=b&sp=r&sig=kRDNUJ4gOg0JkPi%2BOB3%2FoHYUAVRNbEzMimWfrSV4lrw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 16:57 UTC, merged