Update Enable-CsOnlineDialInConferencingUser.md
MicrosoftDocs/office-docs-powershell pull request #8621
Opened 2021-11-19 02:20 UTC by ruizoscar

Adding a note to announce the deprecation of the cmdlet and the target date for the deprecation.

2021-11-19 02:22 UTC, opbld32 commented
Docs Build status updates of commit _[5029186](https://github.com/ruizoscar/office-docs-powershell/commits/5029186213c167cf01b70398387cb362bda4692e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md](https://github.com/ruizoscar/office-docs-powershell/blob/patch-8/skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8621) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202111190220207161-8621%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T02%3A22%3A42Z&sr=b&sp=r&sig=nQAqhmNov84q6iKw94voETQ3J%2BfI2HcuB5LMFGy%2Br6Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 16:55 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2021-11-22 16:57 UTC, dariomws requested changes
Minor fix.

2021-11-22 16:57 UTC, dariomws commented on skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md
> +> This cmdlet will be deprecated on December 31, 2021. To enable Audio Conferencing for a user, please assign an Audio Conferencing license to the user and the user will be automatically enabled. For
```suggestion
> This cmdlet will be deprecated on December 31, 2021. To enable Audio Conferencing for a user, please assign an Audio Conferencing license to the user and the user will be automatically enabled. For additional information, see [Assign licenses to users](https://docs.microsoft.com/microsoft-365/admin/manage/assign-licenses-to-users).
```

2021-11-22 16:58 UTC, get-itips requested changes
please remove the en-us path from the url, thank you!

2021-11-22 23:48 UTC, tseward approved these changes
Approved pending removal of 'en-us' from the path.

2021-11-23 06:57 UTC, yogkumgit commented
@ruizoscar Please implement the suggestions. Thanks

2022-01-10 03:53 UTC, yogkumgit commented
@ruizoscar Please update the PR. Thanks

2022-01-17 06:37 UTC, yogkumgit commented
@tiburd Kindly take the appropriate next step. Thanks

2022-01-18 04:42 UTC, JohanFreelancer9 approved these changes
Copy review - Approved pending 'en-us' removal from the path.

2022-01-18 20:47 UTC, opbld31 commented
Docs Build status updates of commit _[33d7be1](https://github.com/ruizoscar/office-docs-powershell/commits/33d7be10767ea27ef45bfe167925ba1c13c77c32)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6eed2834)

<a id="6eed2834"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201182046440259-8621%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T20%3A47%3A18Z&sr=b&sp=r&sig=46hja0ftgI3BYt4R%2FJ8i%2FRRkyVj2agyOhx6McyCN%2F7c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 20:52 UTC, tiburd commented on skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md
> +> This cmdlet will be deprecated on December 31, 2021. To enable Audio Conferencing for a user, please assign an Audio Conferencing license to the user and the user will be automatically enabled. For
```suggestion
> This cmdlet will be deprecated on December 31, 2021. To enable Audio Conferencing for a user, please assign an Audio Conferencing license to the user and the user will be automatically enabled. For additional information, see [Assign licenses to users](/microsoft-365/admin/manage/assign-licenses-to-users).
```

2022-01-18 20:53 UTC, opbld31 commented
Docs Build status updates of commit _[a2ec929](https://github.com/ruizoscar/office-docs-powershell/commits/a2ec9294cd08427396c8778e5f3dbee8011a6258)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6fd54f2e)

<a id="6fd54f2e"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201182052429972-8621%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T20%3A53%3A07Z&sr=b&sp=r&sig=d40B0wnpLQsd7RzKLVVnGYALRCIikbPkLo8LQ1TWPGE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 20:56 UTC, opbld30 commented
Docs Build status updates of commit _[2e761e2](https://github.com/ruizoscar/office-docs-powershell/commits/2e761e246f063afe5e1647cfe5542f7f84999143)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md](https://github.com/ruizoscar/office-docs-powershell/blob/patch-8/skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8621) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201182053347278-8621%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T20%3A56%3A12Z&sr=b&sp=r&sig=lqNINzqW4NYyTNq3FyZTgS9o8mXZBFNwPonxo3G7phc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 20:56 UTC, merged