Update Enable-CsOnlineDialInConferencingUser.md
MicrosoftDocs/office-docs-powershell pull request #8652
Opened 2021-11-30 20:13 UTC by ruizoscar

Adding a note to outline the deprecation of this cmdlet.

2021-11-30 20:16 UTC, opbld33 commented
Docs Build status updates of commit _[09114ea](https://github.com/ruizoscar/office-docs-powershell/commits/09114ea4bf932adc1b8245d40997f67208238c23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md](https://github.com/ruizoscar/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8652) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C30%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202111302013543118-8652%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-31T20%3A16%3A10Z&sr=b&sp=r&sig=%2FoZ5iAa3CJ1JFrM7TgQ2ygWx54eI7zpZtyKfCgQupKU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-01 05:36 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2021-12-01 06:52 UTC, dariomws approved these changes
Maybe the article could be replaced by:
https://docs.microsoft.com/microsoftteams/manage-the-audio-conferencing-settings-for-my-organization-in-teams#assign-an-audio-conferencing-license

2021-12-01 06:52 UTC, dariomws commented on skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md
> +> This cmdlet will be deprecated on December 31, 2021. To enable Audio Conferencing for a given user, assign an Audio Conferencing license to the user or enable the Audio Conferencing component in th
```suggestion
> This cmdlet will be deprecated on December 31, 2021. To enable Audio Conferencing for a given user, assign an Audio Conferencing license to the user or enable the Audio Conferencing component in the user's license. For additional information, see [Assign or remove licenses for Microsoft 365 Apps for business](https://docs.microsoft.com/microsoft-365/admin/add-users/add-users).
```

2021-12-01 06:54 UTC, dariomws requested changes
Approved by mistake.

2021-12-01 12:01 UTC, get-itips approved these changes
I am ok after the suggestion is applied

2021-12-01 14:13 UTC, tseward approved these changes
Also good after the changes are applied.

2021-12-02 07:04 UTC, yogkumgit commented
@ruizoscar Please implement the suggested changes. Thanks

2021-12-07 19:29 UTC, ruizoscar commented
Hi @yogkumgit, I don't have access to publish the changes or merge this PR. Would it be possible for you or someone from the editorial team to publish these changes?

2021-12-07 19:36 UTC, opbld30 commented
Docs Build status updates of commit _[fedee10](https://github.com/ruizoscar/office-docs-powershell/commits/fedee10c144d7e3041f858a3158635652d94d1d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md](https://github.com/ruizoscar/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8652) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112071933548735-8652%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T19%3A36%3A15Z&sr=b&sp=r&sig=ht7vg7rP2MTYBN77xgoQUOjo9nSMa80uPYeBzuLggCY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 23:37 UTC, opbld30 commented
Docs Build status updates of commit _[8f329ea](https://github.com/ruizoscar/office-docs-powershell/commits/8f329ea0748022fd1846182e5cc4d9cb32d1c402)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md](https://github.com/ruizoscar/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8652) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112072334295137-8652%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T23%3A37%3A01Z&sr=b&sp=r&sig=aL%2FXIYQpzaYbJOMoEXZ85rh8K%2Bi7NiMbRyKUgMvHheU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 23:39 UTC, opbld30 commented
Docs Build status updates of commit _[858b4fe](https://github.com/ruizoscar/office-docs-powershell/commits/858b4fefd1ef7fc5a063d0d2e0391b0c136fe898)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md](https://github.com/ruizoscar/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8652) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112072334535231-8652%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T23%3A39%3A19Z&sr=b&sp=r&sig=Q1aM5Ls%2BkJUUGz8EFpvYBriBGoM3Mh%2F5BZL%2BXke8Ssc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 23:39 UTC, merged