Update Set-CsTenantFederationConfiguration.md
MicrosoftDocs/office-docs-powershell pull request #8667
Opened 2021-12-03 00:47 UTC by luis-msftpm

Adding information regarding -AllowTeamsConsumerInbound and -AllowTeamsConsumer.
This new properties were introduced as part of the effort to enable communications between people using Teams with an account managed by an organization and people using Teams with an account that's not managed by an organization.

2021-12-03 00:51 UTC, opbld33 commented
Docs Build status updates of commit _[3072ceb](https://github.com/luis-msftpm/office-docs-powershell/commits/3072ceb256c50ea6858aaec2c4b7323467ac18f4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2201ccf2)

<a id="2201ccf2"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C3%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112030047100182-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-03T00%3A51%3A44Z&sr=b&sp=r&sig=oM2Y8GfzhG64YG0NpX90UrZsliuQOOwj%2Bb7XxV9zrkE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-03 08:00 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2021-12-03 10:55 UTC, dariomws commented
Close https://github.com/MicrosoftDocs/office-docs-powershell/issues/8581.

2021-12-05 21:14 UTC, tseward approved these changes

2021-12-06 06:31 UTC, yogkumgit commented
@get-itips

2021-12-06 12:42 UTC, get-itips approved these changes

2021-12-06 12:43 UTC, get-itips commented on skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md
> +```yaml
```suggestion

```yaml
```

2021-12-06 12:43 UTC, get-itips commented on skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md
> +```yaml
```suggestion

```yaml
```

2021-12-07 12:58 UTC, yogkumgit commented
@dariomws

2021-12-07 13:33 UTC, dariomws commented
@luis-msftpm, could you review suggestions? Thanks.

2021-12-07 15:55 UTC, luis-msftpm commented
> @luis-msftpm, could you review suggestions? Thanks.

@dariomws Done. Thx.

2021-12-07 15:57 UTC, opbld31 commented
Docs Build status updates of commit _[08f4d31](https://github.com/luis-msftpm/office-docs-powershell/commits/08f4d31282f5430c4fe4428c3d4b4b653530dc92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112071554274283-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T15%3A57%3A04Z&sr=b&sp=r&sig=LOQIjof%2FDSKiUkCqAS%2Fa71MLsLRXqtHXE523119D7vk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 15:59 UTC, opbld33 commented
Docs Build status updates of commit _[8e1976a](https://github.com/luis-msftpm/office-docs-powershell/commits/8e1976aa5ba703e8224e63767286aacd6c66ba53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112071555068343-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T15%3A59%3A23Z&sr=b&sp=r&sig=uXlDvMBOCN7G1dmkYz8LEeAHKOlze%2FTr%2BIqCSm3f%2BFk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-08 06:09 UTC, yogkumgit commented
@dariomws

2021-12-14 17:23 UTC, opbld33 commented
Docs Build status updates of commit _[ba0da82](https://github.com/luis-msftpm/office-docs-powershell/commits/ba0da821e40b5718a09cfa9999ab17aa22605b81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C14%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112141721118172-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-14T17%3A23%3A52Z&sr=b&sp=r&sig=9FIvD1Qti6BqoSklBv5xKwBbjfcD6vl3W5Ev%2BoOaCiQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-14 22:50 UTC, opbld31 commented
Docs Build status updates of commit _[c784e4e](https://github.com/luis-msftpm/office-docs-powershell/commits/c784e4eac78633229266ae4b5e5d86b268de6731)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C14%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112142248398845-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-14T22%3A50%3A52Z&sr=b&sp=r&sig=p%2FUbJU4fohyLwyb2LkL0ClAwkM9EKAvT8QDf58018sY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 03:50 UTC, yogkumgit commented
@dariomws Please review.

2022-01-11 14:52 UTC, luis-msftpm commented
@dariomws - This PR has been open for over a month. We have companies opening ICMs due to this document being outdated. Can you please prioritize this? Is there anyone else that can help approve and merge this?

2022-01-11 14:52 UTC, opbld31 commented
Docs Build status updates of commit _[1be7941](https://github.com/luis-msftpm/office-docs-powershell/commits/1be7941be78b39cad708f6b2f7394b9783b73a9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201111450002390-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T14%3A52%3A36Z&sr=b&sp=r&sig=weJt9Rh5x0sg3wVw0GumsryDtORskxv%2FjhSr62zDHWU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 15:15 UTC, dariomws commented
@luis-msftpm, I think you are still missing a suggestion.

"When -AllowTeamsConsumer and this is disabled"

Should be as per my understanding:

"When -AllowTeamsConsumer is enabled and this parameter is disabled"

2022-01-11 23:41 UTC, opbld33 commented
Docs Build status updates of commit _[9cad317](https://github.com/luis-msftpm/office-docs-powershell/commits/9cad3176079c22b9b51c4b9cbeea900ce7f146a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201112338453246-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T23%3A41%3A17Z&sr=b&sp=r&sig=zGIhc8etaV84hLkmrcXF5Fq2D6m2aRerpNjSoqNEEC8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 23:45 UTC, luis-msftpm commented
> @luis-msftpm, I think you are still missing a suggestion.
> 
> "When -AllowTeamsConsumer and this is disabled"
> 
> Should be as per my understanding:
> 
> "When -AllowTeamsConsumer is enabled and this parameter is disabled"

Fixed now. Thanks for catching that one.

2022-01-11 23:46 UTC, opbld33 commented
Docs Build status updates of commit _[42f7f5e](https://github.com/luis-msftpm/office-docs-powershell/commits/42f7f5e1c93c14772e52dfea47af8a900247633e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201112344005500-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T23%3A46%3A23Z&sr=b&sp=r&sig=HLNcIPOpoYP0142FWopkKARN2uWO9zK7i89qolWfYmA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 07:53 UTC, dariomws approved these changes

2022-01-12 19:19 UTC, opbld33 commented
Docs Build status updates of commit _[e968c8e](https://github.com/luis-msftpm/office-docs-powershell/commits/e968c8e1b93d00c955d9479f954eceb3fe77791f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201121916455234-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T19%3A19%3A19Z&sr=b&sp=r&sig=%2B9TeULtN2bpiEm%2FNRySRaPxF2WeEkoXK4iq5ElXBSEo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 13:07 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md
> +The command shown in Example 1 enables communication with people using Teams with an account that's not managed by an organization, to only be initiated by people in your organization. This means tha
```suggestion
The command shown in Example 7 enables communication with people using Teams with an account that's not managed by an organization, to only be initiated by people in your organization. This means that people using Teams with an account that's not managed by an organization will not be able to discover or start a conversation with people in your organization.
```

2022-01-13 13:09 UTC, JohanFreelancer9 requested changes
Copy review - @luis-msftpm, kindly commit the additional suggested change. Many thanks.

2022-01-13 15:15 UTC, opbld30 commented
Docs Build status updates of commit _[d56cbab](https://github.com/luis-msftpm/office-docs-powershell/commits/d56cbab090477e30b1d33f824ee3431190b3202a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201131512123625-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T15%3A14%3A59Z&sr=b&sp=r&sig=rm3alO9vqNXkMYVRoDEZe3QZbhvCV5NXI5k35oVNpzY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 15:16 UTC, luis-msftpm commented
> Copy review - @luis-msftpm, kindly commit the additional suggested change. Many thanks.

@opbld33 - Done

2022-01-13 15:22 UTC, luis-msftpm commented
@opbld33 - can you please help get this closed and merged today? We have customers asking for this doc to be updated since we started rolling out over a month ago. Would really appreciate the help here.

2022-01-14 03:20 UTC, JohanFreelancer9 approved these changes

2022-01-14 15:12 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-01-14 23:17 UTC, opbld31 commented
Docs Build status updates of commit _[50b6823](https://github.com/luis-msftpm/office-docs-powershell/commits/50b6823c2b28aac22395f7140312d656a83f58f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md](https://github.com/luis-msftpm/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/Set-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-8667) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C14%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201142314282906-8667%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-14T23%3A17%3A08Z&sr=b&sp=r&sig=kX9tBIIud%2BpfgXTMgw0PqACfKSIfeLdZT9pFm56ZTqo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-14 23:17 UTC, merged