Update Set-CsTeamsComplianceRecordingPolicy.md
MicrosoftDocs/office-docs-powershell pull request #8692
Opened 2021-12-08 03:03 UTC by 2kiran

2021-12-08 03:06 UTC, opbld31 commented
Docs Build status updates of commit _[1a88f79](https://github.com/2kiran/office-docs-powershell/commits/1a88f793a4626f13a30cdf84bac703ba75a2e9cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md](https://github.com/2kiran/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscompliancerecordingpolicy?view=skype-ps&branch=pr-en-us-8692) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112080303528639-8692%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-08T03%3A06%3A12Z&sr=b&sp=r&sig=fvVmcDipQAfLHuwnQOE%2BGqKXepfuvBS3GgiGOhIzCWE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 06:39 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2021-12-09 08:17 UTC, dariomws requested changes
Please add the parameter to the syntax section. Thanks.

2021-12-09 17:50 UTC, get-itips requested changes
agreed with @dariomws

2021-12-10 11:06 UTC, yogkumgit commented
@2kiran please implement the suggestion. Thanks

2022-01-10 03:51 UTC, yogkumgit commented
@2kiran Gentle reminder, please update the PR. Thanks

2022-01-10 18:09 UTC, opbld31 commented
Docs Build status updates of commit _[507ed5e](https://github.com/2kiran/office-docs-powershell/commits/507ed5e5e0ee542e2f76e9a6b3ebf7f022639f31)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a1d129ba)

<a id="a1d129ba"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201101809153259-8692%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T18%3A09%3A41Z&sr=b&sp=r&sig=%2Fyai2M8QGf1vofNW62cHaqjk0bb%2BWkHR9Zbv0Tdxwy8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-10 19:34 UTC, opbld30 commented
Docs Build status updates of commit _[941b90d](https://github.com/2kiran/office-docs-powershell/commits/941b90d29948626ea964ea003cad71ba45046f0c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b8331cc6)

<a id="b8331cc6"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201101934241994-8692%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T19%3A34%3A49Z&sr=b&sp=r&sig=TAU1zziDZYUSnPIDe7iYb5xG4xATEmcOUDtjurR1eYc%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 11:15 UTC, dariomws approved these changes

2022-01-11 11:15 UTC, dariomws commented on skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md
> +Setting this attribute to true disables recording audio notifications for 1:1 calls that are under compliance recording
```suggestion
Setting this attribute to true disables recording audio notifications for 1:1 calls that are under compliance recording.
```

2022-01-11 12:28 UTC, yogkumgit commented
@tseward @get-itips

2022-01-11 13:20 UTC, get-itips commented
The branch has now conflicts that prevent merge @2kiran can you review ? Thanks

2022-01-17 06:53 UTC, yogkumgit commented
@tiburd Please take an appropriate next step. Thanks

2022-01-18 21:50 UTC, opbld31 commented
Docs Build status updates of commit _[4daeb41](https://github.com/2kiran/office-docs-powershell/commits/4daeb4183d11b8021d65636a9c3d76ffa442d162)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-53c604b5)

<a id="53c604b5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201182150007502-8692%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T21%3A50%3A35Z&sr=b&sp=r&sig=B3v8xO%2F%2B4f3ZsB9N7zsOaHIsBh%2F2mJfIXMOKhrtTRo4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 21:53 UTC, opbld32 commented
Docs Build status updates of commit _[e7f7ca7](https://github.com/2kiran/office-docs-powershell/commits/e7f7ca7164b798a12e61d0e6d19e05d702320210)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md](https://github.com/2kiran/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscompliancerecordingpolicy?view=skype-ps&branch=pr-en-us-8692) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201182151159970-8692%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T21%3A53%3A52Z&sr=b&sp=r&sig=pR9zLqf3CNMXq%2FI1I1NrTeazcFgdv9grXca%2FTmKj4VE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 23:47 UTC, tiburd commented
@2kiran 
Thank you for submitting this PR. After you make the requested updates, we'll continue reviewing it.

If the update isn't made soon, we might close this PR.

2022-01-18 23:58 UTC, 2kiran commented
Hi Tim,
I did make the changes. Didn't they come through?

From: Tina Burden ***@***.***>
Sent: Tuesday, January 18, 2022 3:48 PM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Kiran Kodali ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Update Set-CsTeamsComplianceRecordingPolicy.md (PR #8692)


@2kiran<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F2kiran&data=04%7C01%7Ckkodali%40microsoft.com%7Ccbbb846af77f4edd120708d9dadcfa66%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637781464975847969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3z9G%2B%2Fu3lQ6kKuROY0D6ofpYtV3FsuAyzyawYrpAyDw%3D&reserved=0>
Thank you for submitting this PR. After you make the requested updates, we'll continue reviewing it.

If the update isn't made soon, we might close this PR.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-docs-powershell%2Fpull%2F8692%23issuecomment-1015936228&data=04%7C01%7Ckkodali%40microsoft.com%7Ccbbb846af77f4edd120708d9dadcfa66%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637781464975847969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FE2VRgNZ4z1EAeGlynA1jX3GKj3uN9qrRu66HnRHvHc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWHIX5JMVYV6TQRU2M5XNALUWX33PANCNFSM5JSXR2CQ&data=04%7C01%7Ckkodali%40microsoft.com%7Ccbbb846af77f4edd120708d9dadcfa66%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637781464975847969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qr9vO2PxPbPoU1NyNXA%2BlWZlIYd7mRl2UH2Tk6kHohA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckkodali%40microsoft.com%7Ccbbb846af77f4edd120708d9dadcfa66%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637781464975847969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pF1vnvpssxvMrg0H5CgBYdcclFP8PP5MpZoDJOwkh88%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckkodali%40microsoft.com%7Ccbbb846af77f4edd120708d9dadcfa66%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637781464975847969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hJZi0dk8%2BNXH7IAWLsZ04nsDYKiVgG%2FvO4o3dh2%2Ft7U%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-01-19 06:31 UTC, JohanFreelancer9 approved these changes

2022-01-20 00:26 UTC, opbld31 commented
Docs Build status updates of commit _[9e7e9cb](https://github.com/2kiran/office-docs-powershell/commits/9e7e9cbe5f8ca9438084018ca88256262b4b5b93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md](https://github.com/2kiran/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/Set-CsTeamsComplianceRecordingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscompliancerecordingpolicy?view=skype-ps&branch=pr-en-us-8692) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201200022581165-8692%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T00%3A26%3A11Z&sr=b&sp=r&sig=aPVdtNfQwS66Xez%2BN0sqKHWOhHibWsqHRrfVq3bjDi8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 00:27 UTC, tseward approved these changes

2022-01-20 00:28 UTC, merged