Update Set-CsOnlineDialInConferencingUser.md
MicrosoftDocs/office-docs-powershell pull request #8732
Opened 2021-12-22 01:01 UTC by ruizoscar

Adding a note to call out 3 parameters of this cmdlets that will be deprecated by the end of Jan.

2021-12-22 01:04 UTC, opbld30 commented
Docs Build status updates of commit _[f495eb9](https://github.com/ruizoscar/office-docs-powershell/commits/f495eb9f8605a73c171471be168f80a6c729b99d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md](https://github.com/ruizoscar/office-docs-powershell/blob/patch-12/skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8732) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202112220101471603-8732%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-22T01%3A04%3A19Z&sr=b&sp=r&sig=w%2Fq4wDy%2BPB4f1iM1T399tSTtGqdn5WGBQLfSqfZT42U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-22 14:21 UTC, tiburd commented
@get-itips @dariomws @tseward 
Hi! 
Whoever of you reviews this PR last, please ping me so that I can merge it.
Thank you!

2021-12-22 14:26 UTC, tseward approved these changes

2021-12-22 14:32 UTC, dariomws requested changes
Enable-CsOnlineDialInConferencingUser cmdlet has the ConferenceId parameter. Is it available there?

Could we still reset the conference ID from the Teams Admin Center?

Thanks!

2021-12-22 14:32 UTC, dariomws commented on skype/skype-ps/skype/Set-CsOnlineDialInConferencingUser.md
> +> The AllowPSTNOnlyMeetings, ResetConferenceId, and ConferenceId parameters will be deprecated on Jan 31, 2022. To allow Teams meeting participants joining via the PSTN to bypass the lobby, use the A
```suggestion
> [!NOTE]
> The AllowPSTNOnlyMeetings, ResetConferenceId, and ConferenceId parameters will be deprecated on Jan 31, 2022. To allow Teams meeting participants joining via the PSTN to bypass the lobby, use the AllowPSTNUsersToBypassLobby of the [Set-CsTeamsMeetingPolicy cmdlet](/powershell/module/skype/set-csteamsmeetingpolicy). The capabilities associated with the ResetConferenceId and ConferenceId parameters are no longer supported.
```

2021-12-22 14:38 UTC, dariomws approved these changes

2021-12-22 14:47 UTC, get-itips approved these changes

2021-12-23 00:57 UTC, ruizoscar commented
@dariomws. Eventually, yes, but not for the moment. This deprecation is phased and the cmdlet is the first phase.

2021-12-23 01:41 UTC, merged