Update private preview note for cmdlets
MicrosoftDocs/office-docs-powershell pull request #8780
Opened 2022-01-10 13:38 UTC by bishalgautam-ms

In this PR, we are:
1. updating Preview note for the cmdlets which are still in private-preview mode.
2. updating example company-name to the company name 'contoso'

2022-01-10 13:47 UTC, opbld30 commented
Docs Build status updates of commit _[e4d754c](https://github.com/bishalgautam-ms/office-docs-powershell/commits/e4d754c4da4253da462ea71d27dd8f4f95c53896)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201101345162555-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T13%3A47%3A47Z&sr=b&sp=r&sig=cMVr6hLcfYQsQF%2BeLrsmQDdO5tksrejvHN69wAgLYYQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 09:39 UTC, opbld32 commented
Docs Build status updates of commit _[8a730e2](https://github.com/bishalgautam-ms/office-docs-powershell/commits/8a730e2238d118614e68a807a918459615e2b3c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201120937020640-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T09%3A39%3A39Z&sr=b&sp=r&sig=0eRQCaMN1WyWXSh8%2Fb0S3ljcRjgqWETCpHFytvIlbIo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 10:34 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-12 10:59 UTC, dariomws approved these changes
@bishalgautam-ms, maybe you meant "Public Preview"? I see these cmdlets available in the public preview version (3.0.1-preview).

2022-01-12 11:40 UTC, bishalgautam-ms commented
> @bishalgautam-ms, maybe you meant "Public Preview"? I see these cmdlets available in the public preview version (3.0.1-preview).

Yes, you are right.

2022-01-12 11:46 UTC, dariomws commented
@bishalgautam-ms, are you planning to update the PR? Thanks!

2022-01-12 13:38 UTC, bishalgautam-ms commented
> @bishalgautam-ms, are you planning to update the PR? Thanks!

All the changes are made for this PR.
Thanks @dariomws for asking.

2022-01-12 13:38 UTC, opbld30 commented
Docs Build status updates of commit _[f14d88b](https://github.com/bishalgautam-ms/office-docs-powershell/commits/f14d88ba81d337da8c51e54ef91bb876b7aa3260)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201121336195297-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T13%3A38%3A58Z&sr=b&sp=r&sig=V1a9PPjZ2RRsJRYGMySSBqbVGfrmSixGFz4ks8LsfUc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 14:05 UTC, get-itips reviewed
@bishalgautam-ms

Looks like these cmdlets are in the Public Preview version of the module, shouldn't the note say Public preview instead of private preview?

Thank you

2022-01-12 14:47 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:47 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:48 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:48 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:49 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:49 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:50 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:50 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:50 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:51 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:51 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:52 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md
> +**Note:** This cmdlet is currently in private preview.
```suggestion
**Note:** This cmdlet is currently in public preview.
```

2022-01-12 14:53 UTC, JohanFreelancer9 requested changes
Copy review - @bishalgautam-ms, kindly commit the suggested changes. Many thanks.

2022-01-12 15:04 UTC, opbld30 commented
Docs Build status updates of commit _[bf34182](https://github.com/bishalgautam-ms/office-docs-powershell/commits/bf341828954d37aaa4d68e5cdb9ae4e1893d77c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201121501342066-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T15%3A04%3A03Z&sr=b&sp=r&sig=Fhpgrk65g7%2FQYcWBj7DzziycmH5rVI1xO2AfbTt4MBc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 15:06 UTC, opbld32 commented
Docs Build status updates of commit _[d33ec60](https://github.com/bishalgautam-ms/office-docs-powershell/commits/d33ec60bf234c3995c477b0f56f1888f970e286a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201121501534734-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T15%3A06%3A38Z&sr=b&sp=r&sig=UuggMg%2Ff%2BR4QncK0qLpsA49RxWaMloBVKjzrZsSASg0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 15:09 UTC, opbld33 commented
Docs Build status updates of commit _[f6329da](https://github.com/bishalgautam-ms/office-docs-powershell/commits/f6329da7ffb8b1f45ce622cc903dd58142f4d021)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201121506143460-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T15%3A09%3A20Z&sr=b&sp=r&sig=t%2F0A1mqQ2b7pj05ylxr4ZVNHm59nq%2FOgnh8hx6D70EI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 15:15 UTC, get-itips approved these changes

2022-01-12 15:15 UTC, opbld31 commented
Docs Build status updates of commit _[0cd6182](https://github.com/bishalgautam-ms/office-docs-powershell/commits/0cd618257795e541b35f843ec1b5e610a66259ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Disable-CsTeamsShiftsConnectionErrorReport.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Disable-CsTeamsShiftsConnectionErrorReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/disable-csteamsshiftsconnectionerrorreport?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionerrorreport?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201121513118781-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T15%3A15%3A43Z&sr=b&sp=r&sig=%2F0i59%2FW5LTXXO39c3mjfaswDzxJrRSOQA8wtcwFSvBk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides [...]

2022-01-12 15:34 UTC, JohanFreelancer9 approved these changes

2022-01-13 03:11 UTC, tseward approved these changes

2022-01-13 09:59 UTC, opbld31 commented
Docs Build status updates of commit _[e213119](https://github.com/bishalgautam-ms/office-docs-powershell/commits/e21311921b308219e459c8d281b4eac0908d7095)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Disable-CsTeamsShiftsConnectionErrorReport.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Disable-CsTeamsShiftsConnectionErrorReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/disable-csteamsshiftsconnectionerrorreport?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionerrorreport?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201130956424015-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T09%3A59%3A35Z&sr=b&sp=r&sig=ZafAbMSOkwRWzWspTMVLBpHag4dPubePrwMNICE6wo8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a> [...]

2022-01-13 11:59 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-01-13 19:55 UTC, opbld30 commented
Docs Build status updates of commit _[f8d1a0e](https://github.com/bishalgautam-ms/office-docs-powershell/commits/f8d1a0ee6a28fbfb641cc34c99d9578a14d89165)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Disable-CsTeamsShiftsConnectionErrorReport.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Disable-CsTeamsShiftsConnectionErrorReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/disable-csteamsshiftsconnectionerrorreport?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionconnector?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionErrorReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionerrorreport?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionOperation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionoperation?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionSyncResult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionsyncresult?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmteam?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionWfmUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsshiftsconnectionwfmuser?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionBatchTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionbatchteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsConnectionTeamMap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsconnectionteammap?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Remove-CsTeamsShiftsScheduleRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsshiftsschedulerecord?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsshiftsconnectioninstance?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md](https://github.com/bishalgautam-ms/office-docs-powershell/blob/update-private-preview-cmdlets/teams/teams-ps/teams/Test-CsTeamsShiftsConnectionValidate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/test-csteamsshiftsconnectionvalidate?view=teams-ps&branch=pr-en-us-8780) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201131952156003-8780%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T19%3A55%3A02Z&sr=b&sp=r&sig=02mjhsEw%2BdKIPLBevgQ0Gk9UDV%2BuXdRRVvKQKNQ9%2FwI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guid [...]

2022-01-13 20:01 UTC, merged