Added PowerShell examples for Connect-MicrosoftTeams with AccessTokens
MicrosoftDocs/office-docs-powershell pull request #8788
Opened 2022-01-10 21:35 UTC by mariussm

2022-01-10 21:38 UTC, opbld32 commented
Docs Build status updates of commit _[3e707b7](https://github.com/mariussm/office-docs-powershell/commits/3e707b750bcbe8b1a0a64cfec81716df2d55a41f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/mariussm/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-8788) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201102135413653-8788%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-10T21%3A38%3A10Z&sr=b&sp=r&sig=mL5uo2WCJNYJRQQIElSjN7xJcAYnJGwDevmP2PUKy6Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 10:41 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-12 12:21 UTC, dariomws reviewed
@mariussm, thanks a lot for your contribution. Anyway, I think there are several options to acquire an access token and several articles with examples. I understand there is no need to add this information here but let's wait that my colleagues to share their thoughts.

About ApplicationId parameter, I've verified that it's not available in versions 3.0.0 and 2.6.0, so I think we need to confirm from what version it's not available or just remove it.

2022-01-12 12:24 UTC, mariussm commented
@dariomws

> @mariussm, thanks a lot for your contribution. Anyway, I think there are several options to acquire an access token and several articles with examples. I understand there is no need to add this information here but let's wait that my colleagues to share their thoughts.
> 
> About ApplicationId parameter, I've verified that it's not available in versions 3.0.0 and 2.6.0, so I think we need to confirm from what version it's not available or just remove it.

In that case we should point to that documentation (which I cannot find). I spent quite a lot of time to figure out the correct way, as the scope url needed the guid instead of the url of the API, and stuff.

2022-01-12 20:57 UTC, mariussm commented
Invoke-RestMethod changes to -Method Post automatically when a body is provided, in newer versions of PowerShell 7. :)

2022-01-13 00:01 UTC, get-itips commented
@mariussm Marius, it doesn't hurt to add it then, as people could try your example using Windows PowerShell, thanks

2022-01-13 03:03 UTC, tseward commented
Another question I'd have is would it be easier to mix this with the MgGraph module (i.e., https://docs.microsoft.com/en-us/graph/powershell/app-only?tabs=azure-portal) rather than hand roll the POST?

2022-01-13 07:51 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Connect-MicrosoftTeams.md
>  This example demonstrates how to sign in using AccessTokens. Admin can reterive Access Tokens. It requires two tokens, MS Graph Access Token and Teams Resource token.
```suggestion
This example demonstrates how to sign in using AccessTokens. Admin can retrieve Access Tokens. It requires two tokens, MS Graph Access Token and Teams Resource token. 
```

2022-01-13 07:54 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Connect-MicrosoftTeams.md
> +A delegated flow, such as Resouce Owner Password Credentials (ROPC), must be used, with the following delegated app permissions required.
```suggestion
A delegated flow, such as Resource Owner Password Credentials (ROPC), must be used, with the following delegated app permissions required.
```

2022-01-13 07:59 UTC, JohanFreelancer9 requested changes
Copy review - @mariussm, kindly commit my suggested changes to correct the typos. I'll do a final edit once the other reviewers' comments have been resolved. Many thanks.

2022-01-13 20:51 UTC, opbld32 commented
Docs Build status updates of commit _[2401150](https://github.com/mariussm/office-docs-powershell/commits/2401150394206c61b503566a42e2e359672c0621)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/mariussm/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-8788) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201132048290366-8788%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T20%3A51%3A29Z&sr=b&sp=r&sig=ECxxPmcUNxEAMFJDISANpc2jqoVeAbS1mxXYcF1%2F2o0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 20:53 UTC, opbld33 commented
Docs Build status updates of commit _[1f25dc7](https://github.com/mariussm/office-docs-powershell/commits/1f25dc7436bad643ec9109b27c006e5eb5a7cd88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/mariussm/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-8788) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201132050025900-8788%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T20%3A53%3A58Z&sr=b&sp=r&sig=3Jd8TEpcwtJ0pWCsb73u4l5AW%2BuSXNYjJdgHOHa2ngw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-14 15:08 UTC, yogkumgit commented
@tseward @get-itips @dariomws

2022-01-14 15:13 UTC, get-itips commented on teams/teams-ps/teams/Connect-MicrosoftTeams.md
> +### -ApplicationId (Removed from latest version)
Can you please move what you added in parenthesis to the description?

2022-01-16 19:16 UTC, opbld32 commented
Docs Build status updates of commit _[3fecf04](https://github.com/mariussm/office-docs-powershell/commits/3fecf049e6455ec9d18a0e33fc1ae33941494aa0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/mariussm/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-8788) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C16%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201161914161374-8788%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-16T19%3A16%3A46Z&sr=b&sp=r&sig=YVZEhmPRB1qHhgRJF2PJ0Sq8Dq7HBp6bPujdBrMKzWo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 20:30 UTC, opbld32 commented
Docs Build status updates of commit _[d5d87dd](https://github.com/mariussm/office-docs-powershell/commits/d5d87dd2d324e0dcd4609e8a41c5b2629e7d7c3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/mariussm/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-8788) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201172027596448-8788%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T20%3A30%3A30Z&sr=b&sp=r&sig=FuplPwbjDyP0bllaqbbRLdeyJ4P%2B3Yo4R43%2FdRn%2BPqw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 19:16 UTC, tiburd commented
@rajgodwin 
Please review this PR, or point us to someone who can.
Thank you!

2022-01-24 18:17 UTC, tiburd commented
@tseward 
Hi,

Does this PR have your approval?

Thanks!

2022-01-24 18:18 UTC, opbld31 commented
Docs Build status updates of commit _[44ae330](https://github.com/mariussm/office-docs-powershell/commits/44ae3308945b5a9dc418924eef726e932fd59022)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/mariussm/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-8788) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201241814569240-8788%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T18%3A18%3A02Z&sr=b&sp=r&sig=YMzfjtBPOW1%2B51HZ3sLKGmUaRh6Nb6L0NN9MKrj3uXM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 18:40 UTC, tseward approved these changes

2022-01-25 17:55 UTC, opbld31 commented
Docs Build status updates of commit _[20484a0](https://github.com/mariussm/office-docs-powershell/commits/20484a06f70b8c9fa5c7d89662bdb919738039ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/mariussm/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-8788) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201251752317992-8788%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T17%3A55%3A27Z&sr=b&sp=r&sig=RlmuHK%2Bziev8hLSUd97liCmgSGUUbPvSSYKXpc%2B4Q%2Fo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 06:54 UTC, yogkumgit commented
@get-itips @dariomws

2022-01-28 18:14 UTC, opbld31 commented
Docs Build status updates of commit _[f8dc078](https://github.com/mariussm/office-docs-powershell/commits/f8dc0782ac436cf2be2e07ef7d84e61baf5e492c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/mariussm/office-docs-powershell/blob/master/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-8788) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201281811234338-8788%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T18%3A14%3A15Z&sr=b&sp=r&sig=Ww2vpmK0GOhZpAUs5zB2kWPCgxRHoau5W6HIeEAgYHg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 19:02 UTC, merged