Update New-CsTeamsUnassignedNumberTreatment.md
MicrosoftDocs/office-docs-powershell pull request #8793
Opened 2022-01-11 15:58 UTC by JensTrier

Adding comment on assigned numbers in unassigned number range

2022-01-11 16:01 UTC, opbld30 commented
Docs Build status updates of commit _[743f339](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/743f3398601115bab3e34bd1decd32fa3bd1956b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UpdateUnassignedRouting/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-8793) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201111558399643-8793%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T16%3A01%3A09Z&sr=b&sp=r&sig=Bb%2BpcKbBoN6pHWMH6Eqx0dGbdQsmYn3ab5WfzxwbNLY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-11 16:42 UTC, opbld30 commented
Docs Build status updates of commit _[e703d1f](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/e703d1f597f7a0e0c00c88ada8c90332baa16f28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UpdateUnassignedRouting/teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-8793) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UpdateUnassignedRouting/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-8793) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201111639352471-8793%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-11T16%3A42%3A15Z&sr=b&sp=r&sig=%2BwoTmJB8W4fYTKz4BzEHfGaB4nVsWwZKBSPhC%2FUqTcI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 10:43 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-12 11:14 UTC, dariomws approved these changes

2022-01-12 13:41 UTC, get-itips approved these changes

2022-01-12 14:28 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md
> +This example displays all configured treatments with an Identity starting with Ann
```suggestion
This example displays all configured treatments with an Identity starting with Ann.

```

2022-01-12 14:29 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the minor suggested change. Many thanks.

2022-01-12 14:37 UTC, opbld31 commented
Docs Build status updates of commit _[a20e539](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/a20e5396d24e733602807557cf7f5513ad6292ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UpdateUnassignedRouting/teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-8793) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UpdateUnassignedRouting/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-8793) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201121434280982-8793%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T14%3A37%3A09Z&sr=b&sp=r&sig=7e2VAtqaFtayrH0qWLO8q6L%2BPjTjfaKFIcMlAAVL6Ac%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-12 15:21 UTC, JohanFreelancer9 approved these changes

2022-01-13 03:11 UTC, tseward approved these changes

2022-01-13 12:01 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-01-13 20:35 UTC, merged