Update Set-CaseHoldPolicy.md
MicrosoftDocs/office-docs-powershell pull request #8800
Opened 2022-01-12 17:36 UTC by scorrea4099

Related to PR 
https://github.com/MicrosoftDocs/office-docs-powershell/pull/8794

2022-01-12 17:39 UTC, opbld30 commented
Docs Build status updates of commit _[1d047cb](https://github.com/scorrea4099/office-docs-powershell/commits/1d047cbb9479a39d893a673b0b80cd4f63c98bc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md](https://github.com/scorrea4099/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-caseholdpolicy?view=exchange-ps&branch=pr-en-us-8800) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C12%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201121736129274-8800%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-12T17%3A39%3A16Z&sr=b&sp=r&sig=GrSYeiQkcdnauz22DNVTm7NpTWXg5ZL5U37FRG2WN1k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 12:03 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-13 13:23 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md
> +**Note**: Please avoid using a piped Foreach-Object when adding or removing scope Locations : "Value1","Value2",..."ValueN" | Foreach-Object { Set-CaseHoldPolicy -Identity "Regulation 123 Compliance"
```suggestion
**Note**: Avoid using a piped Foreach-Object when adding or removing scope Locations: "Value1","Value2",..."ValueN" | Foreach-Object { Set-CaseHoldPolicy -Identity "Regulation 123 Compliance" -RemoveExchangeLocation $_  }
```

2022-01-13 13:24 UTC, JohanFreelancer9 requested changes
Copy review.

2022-01-13 17:27 UTC, opbld30 commented
Docs Build status updates of commit _[dbce155](https://github.com/scorrea4099/office-docs-powershell/commits/dbce1558fc405eff606abb17dc254b01b7a59053)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md](https://github.com/scorrea4099/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-caseholdpolicy?view=exchange-ps&branch=pr-en-us-8800) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201131725069555-8800%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T17%3A27%3A48Z&sr=b&sp=r&sig=8r8MlnO%2BU4hVz78H28na5INAhixqKi9YGuOGCZrbwiU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 17:30 UTC, opbld32 commented
Docs Build status updates of commit _[11f7302](https://github.com/scorrea4099/office-docs-powershell/commits/11f73029ff208319aa97382d10fcb5c5416d0ff3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md](https://github.com/scorrea4099/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/Set-CaseHoldPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-caseholdpolicy?view=exchange-ps&branch=pr-en-us-8800) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C13%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201131727338607-8800%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-13T17%3A30%3A22Z&sr=b&sp=r&sig=9x55VCRKjz1rFo%2BvSRh98gYhfl3lSw%2BiLwulFZMVUYk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-13 17:32 UTC, merged