Updates for TPM 3.0 and above
MicrosoftDocs/office-docs-powershell pull request #8822
Opened 2022-01-17 19:34 UTC by isrumnon

2022-01-17 19:36 UTC, opbld31 commented
Docs Build status updates of commit _[ea04172](https://github.com/isrumnon/office-docs-powershell-new/commits/ea04172552a5b59bc88578859765abaec6c25648)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-6/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8822) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C17%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201171934209371-8822%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-17T19%3A36%3A58Z&sr=b&sp=r&sig=SQYdONbNkZkhqcHQlFnb65VuodHxu3%2Bvwcwx1MAaejE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 06:31 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +Beginning Teams PowerShell Module 3.0 onwards, the below updates are applicable for TeamsOnly customers.
```suggestion
Beginning with Teams PowerShell Module 3.0 onwards, the following updates are applicable for TeamsOnly customers.
```

2022-01-18 06:32 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +Below input paramters have been removed as they are either no longer relevant in Microsoft Teams or have very low usage
```suggestion
The following input parameters have been removed as they are either no longer relevant in Microsoft Teams or have very low usage.
```

2022-01-18 06:32 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:33 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:33 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:33 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:34 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:34 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:35 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:35 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:36 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*These parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*
```suggestion
*These parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```

2022-01-18 06:36 UTC, JohanFreelancer9 requested changes
Copy review - @isrumnon, kindly commit the suggested changes. Many thanks.

2022-01-18 07:07 UTC, isrumnon commented
@JohanFreelancer9 I've committed the suggestions. Thanks!

2022-01-18 07:09 UTC, opbld32 commented
Docs Build status updates of commit _[41fbdcf](https://github.com/isrumnon/office-docs-powershell-new/commits/41fbdcfc3e06fc342e757632624bc8a9074aac2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-6/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8822) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201180706316969-8822%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T07%3A09%3A17Z&sr=b&sp=r&sig=L7erD5nhqfeAjfLFXd83ELIRSnUBa%2FMuGJGdZ0VOLOc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 07:11 UTC, opbld31 commented
Docs Build status updates of commit _[ef23a16](https://github.com/isrumnon/office-docs-powershell-new/commits/ef23a16ac77bcf6cfe42f4d80c07e2b6f9b7690b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-6/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8822) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201180707074948-8822%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T07%3A11%3A48Z&sr=b&sp=r&sig=UKyJ%2FFNZgeVaNXCEd%2Bgfhuew%2FgGwmkirWSwoYYNjuCQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 07:37 UTC, JohanFreelancer9 approved these changes

2022-01-18 10:17 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-01-18 10:46 UTC, isrumnon commented
@dariomws you're right that section does not even seem to appear in documentation today. Removed the note from the docs

2022-01-18 10:47 UTC, opbld33 commented
Docs Build status updates of commit _[a1366de](https://github.com/isrumnon/office-docs-powershell-new/commits/a1366dec6b5f0dd1433ab7c7dfb92475bd50aaf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-6/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8822) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201181044452564-8822%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T10%3A47%3A28Z&sr=b&sp=r&sig=baGobg1iHDca98BwMBJSA6A1aJc7r%2F5o8bu3h%2BqY85s%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 13:14 UTC, get-itips reviewed
Hello!
Every cmdlet article, even Get- cmdlet's articles have the Examples section, and I see that you are removing it, when Get- has no parameters at all, we should leave it in its basic form, for example


### -------------------------- Example 1 --------------------------
```powershell
Get-CsOnlineDialInConferencingUser
```

also including a description

thanks

2022-01-19 06:25 UTC, yogkumgit commented
@tseward

2022-01-19 10:00 UTC, isrumnon commented
@get-itips Understood. I removed the previous examples as they were no longer relevant and might confuse users. I'll add more relevant examples

2022-01-19 10:09 UTC, opbld31 commented
Docs Build status updates of commit _[87ff99f](https://github.com/isrumnon/office-docs-powershell-new/commits/87ff99fb6a5c345d59fcaf83956e29803407ae06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-6/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8822) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201191007188516-8822%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T10%3A09%3A56Z&sr=b&sp=r&sig=a2ddwHqTL1944s%2FZMLQNj7Lg8uLl0vrggrs537zgdbk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 13:15 UTC, get-itips approved these changes

2022-01-20 01:13 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```suggestion
*This parameter has been deprecated from Teams PowerShell Modules 3.0 and above due to limited usage*.
```

2022-01-20 01:14 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```suggestion
*This parameter has been deprecated from Teams PowerShell Modules 3.0 and above due to limited usage*.
```

2022-01-20 01:15 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```suggestion
*This parameter has been deprecated from Teams PowerShell Modules 3.0 and above due to limited usage*.
```

2022-01-20 01:15 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```suggestion
*This parameter has been deprecated from Teams PowerShell Modules 3.0 and above due to limited usage*.
```

2022-01-20 01:16 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```suggestion
*This parameter has been deprecated from Teams PowerShell Modules 3.0 and above due to limited usage*.
```

2022-01-20 01:16 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```suggestion
*This parameter has been deprecated from Teams PowerShell Modules 3.0 and above due to limited usage*.
```

2022-01-20 01:16 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```suggestion
*This parameter has been deprecated from Teams PowerShell Modules 3.0 and above due to limited usage*.
```

2022-01-20 01:17 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md
> +*This parameter has been deprecated from Teams Powershell Modules 3.0 and above due to limited usage*.
```suggestion
*This parameter has been deprecated from Teams PowerShell Modules 3.0 and above due to limited usage*.
```

2022-01-20 01:18 UTC, JohanFreelancer9 requested changes
@isrumnon, please commit the additional changes. Many thanks.

2022-01-20 05:31 UTC, isrumnon commented
@JohanFreelancer9 Done!

2022-01-20 05:33 UTC, opbld30 commented
Docs Build status updates of commit _[2367523](https://github.com/isrumnon/office-docs-powershell-new/commits/23675239b7e2b4f148491030dcede517c42ca8f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-6/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8822) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201200530322315-8822%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T05%3A33%3A27Z&sr=b&sp=r&sig=bVIb6cI5K4oLenEVOpk%2F%2BKhAEJcIdO7vlpl7WgDeS3c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 05:36 UTC, opbld33 commented
Docs Build status updates of commit _[610879c](https://github.com/isrumnon/office-docs-powershell-new/commits/610879cd563769c11888e7edf304293631330708)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-6/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8822) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201200531073834-8822%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T05%3A36%3A24Z&sr=b&sp=r&sig=5mxfVLDt53iA9EI9iCW%2F2oJYbeKeCjMnsvJMHpbzivY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 06:07 UTC, yogkumgit commented
@tseward @JohanFreelancer9

2022-01-20 07:57 UTC, JohanFreelancer9 approved these changes

2022-01-21 16:17 UTC, opbld30 commented
Docs Build status updates of commit _[7bf3a17](https://github.com/isrumnon/office-docs-powershell-new/commits/7bf3a1731fe1f0b00a7a22dc259a41ea5bc15b49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-6/skype/skype-ps/skype/Get-CsOnlineDialInConferencingUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedialinconferencinguser?view=skype-ps&branch=pr-en-us-8822) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201211614516303-8822%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T16%3A17%3A38Z&sr=b&sp=r&sig=6v1qDOpSeISM7wH%2FfQ2MWbOhcUDBQLuASICD1gK7%2Fo8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 16:18 UTC, merged