Deprecated voice normalization rules
MicrosoftDocs/office-docs-powershell pull request #8833
Opened 2022-01-20 08:06 UTC by JensTrier

These 3 PS cmdlet will be removed from Teams PS Module in the middle of February 2022. For now just adding the note about the deprecation. After the removal from TPM is done, I'll update these 3 pages to remove references to Skype for Business Online/Microsoft Teams.

2022-01-20 08:09 UTC, opbld31 commented
Docs Build status updates of commit _[c7019ec](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/c7019ecd352ea0179c44d9639a22a0631b103c61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C20%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201200806280567-8833%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-20T08%3A09%3A15Z&sr=b&sp=r&sig=eVPUi7cFRCDq10Bhibh%2FYY3NWrTDl7l0p2WZIzgP3%2Fw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 07:47 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md
> +> This cmdlet will be deprecated from Teams PowerShell Module.
```suggestion
**Note**: This cmdlet will be deprecated from Teams PowerShell Module.
```

2022-01-21 07:48 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md
> +> This cmdlet will be deprecated from Teams PowerShell Module.
```suggestion
**Note**: This cmdlet will be deprecated from Teams PowerShell Module.
```

2022-01-21 07:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md
> +> This cmdlet will be deprecated from Teams PowerShell Module.
```suggestion
**Note**: This cmdlet will be deprecated from Teams PowerShell Module.
```

2022-01-21 07:51 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

2022-01-21 08:05 UTC, opbld30 commented
Docs Build status updates of commit _[8530dae](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/8530daeb4dc40bc8ec8003be51e9712d708a1533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201210802355090-8833%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T08%3A05%3A16Z&sr=b&sp=r&sig=NWvcse418AkduCld10kyNI5otZK%2FMaN3T5TzTmSWXoY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 08:08 UTC, opbld33 commented
Docs Build status updates of commit _[e8fda1f](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/e8fda1f125c98a663566b5f6455ea52b8ccb110c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201210802562172-8833%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T08%3A08%3A05Z&sr=b&sp=r&sig=GzYNLy%2BhIHqOjTvpOXUptYO8J2gpSAb%2FDSg5CTlr58c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 08:29 UTC, JohanFreelancer9 approved these changes

2022-01-24 06:56 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-01-24 08:22 UTC, dariomws approved these changes

2022-01-25 05:46 UTC, yogkumgit commented
@get-itips

2022-01-25 13:35 UTC, get-itips approved these changes

2022-01-26 07:24 UTC, opbld32 commented
Docs Build status updates of commit _[f1f7f0a](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/f1f7f0a7623f4fd5fca63340c4f389558ac4b50b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/DeprecatedVoiceNormalizationRules/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-8833) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201260722004421-8833%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T07%3A24%3A52Z&sr=b&sp=r&sig=nSAgyz67SluM2yxLczZejj%2BO3s00DOIqxYftdTJFj1E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-26 11:59 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-01-26 19:01 UTC, merged