Set-CsUser - Param updates for TPM 3+
MicrosoftDocs/office-docs-powershell pull request #8840
Opened 2022-01-21 13:36 UTC by pbafna03

2022-01-21 13:39 UTC, opbld31 commented
Docs Build status updates of commit _[1daeb6c](https://github.com/pbafna03/office-docs-powershell/commits/1daeb6cf1d4ee709ad721877cb2a5439e2897b5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsUser.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps&branch=pr-en-us-8840) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201211336587421-8840%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T13%3A39%3A35Z&sr=b&sp=r&sig=UsBlcoCZ5Kpz7PwG8tHTSu6RQjNXsLaSoYvrA7joNOI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 05:09 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:10 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:11 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:11 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:11 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:12 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:12 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:12 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:13 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +>This parameter will not be available for Teams only tenants from version 3.0.0 onwards.
```suggestion
> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 05:14 UTC, JohanFreelancer9 requested changes
Copy review - @pbafna03, kindly commit the suggested changes. Many thanks.

2022-01-24 06:22 UTC, opbld33 commented
Docs Build status updates of commit _[fea57ac](https://github.com/pbafna03/office-docs-powershell/commits/fea57ac5293a07d6fc1af74433d5a0ba7e4ab0d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsUser.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps&branch=pr-en-us-8840) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201240619201904-8840%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T06%3A22%3A25Z&sr=b&sp=r&sig=MfTGIWJs379LKMXyCBjMnByTKqz8Rx%2B8WhXS4skuV2Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 06:25 UTC, opbld30 commented
Docs Build status updates of commit _[03bd191](https://github.com/pbafna03/office-docs-powershell/commits/03bd1910a6b7a274a4c745c7c980e858fc633013)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsUser.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps&branch=pr-en-us-8840) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201240620122911-8840%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T06%3A25%3A23Z&sr=b&sp=r&sig=cDT1wPH2DyFVHXv%2FtzPqPXjK4H2MK1BBvHaDKKev2zw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 06:27 UTC, JohanFreelancer9 approved these changes

2022-01-24 07:02 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-01-24 07:41 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
>  > [!WARNING]
```suggestion

```

2022-01-24 07:41 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion
**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 07:44 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
>  > [!WARNING]
```suggestion

```

2022-01-24 07:45 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion
**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 07:46 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
>  > [!WARNING]
```suggestion

```

2022-01-24 07:46 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion
**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 07:46 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
>  > [!WARNING]
```suggestion

```

2022-01-24 07:46 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion
**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 07:47 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
>  > [!WARNING]
```suggestion

```

2022-01-24 07:48 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion
**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 07:48 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
>  > [!WARNING]
```suggestion


```

2022-01-24 07:48 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion
**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 07:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
>  > [!WARNING]
```suggestion

```

2022-01-24 07:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion
**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 07:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
>  > [!WARNING]
```suggestion

```

2022-01-24 07:50 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion
**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 07:53 UTC, JohanFreelancer9 requested changes
Apologies @pbafna03, some more, please.  Because PowerShell does not support markdown, [!NOTE], [!WARNING], etc. should be Note: <text>, Warning: <text>, etc. Also, suggest this should be a note, rather than a warning. Many thanks.

2022-01-24 07:58 UTC, pbafna03 commented
No worries, thanks @JohanFreelancer9

2022-01-24 07:59 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> [!WARNING]
```suggestion

```

2022-01-24 08:00 UTC, opbld32 commented
Docs Build status updates of commit _[077e727](https://github.com/pbafna03/office-docs-powershell/commits/077e72714a0122ee05a01cc8d6670334314c247f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsUser.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps&branch=pr-en-us-8840) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201240757234265-8840%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T08%3A00%3A02Z&sr=b&sp=r&sig=Fhl8gFLoD4%2F2G4snntRHMk%2B87KIVqdSep6Y1C3F0G1k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 08:00 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +> This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:00 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:01 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:01 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:01 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:02 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:02 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:02 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:03 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsUser.md
> +**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```suggestion

**Note**: This parameter is not available for Teams Only tenants from version 3.0.0 onwards.
```

2022-01-24 08:05 UTC, JohanFreelancer9 reviewed
Apologies again @pbafna03, a blank line is needed to prevent the note from becoming part of the preceding line. Thanks again.

2022-01-24 08:08 UTC, opbld33 commented
Docs Build status updates of commit _[90ff426](https://github.com/pbafna03/office-docs-powershell/commits/90ff4264b434e0f3bb8ff8ff47ced00917b70e44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsUser.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps&branch=pr-en-us-8840) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201240805542427-8840%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T08%3A08%3A48Z&sr=b&sp=r&sig=967GBmIoB39x1HrH6fRD%2BI3I40MG%2FFv6nYeJ0tdX%2FgM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 08:09 UTC, JohanFreelancer9 approved these changes
@pbafna03, thanks so much for committing the changes and your quick response. Appreciate it.

2022-01-24 08:17 UTC, dariomws requested changes
@pbafna03, I don't think this note is required because all these parameters are documented as not applicable to SfBO. They are in the code but when you try to use them you get:
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/33589238/150745375-6dfc4999-977d-4b66-b1c3-27288358b0fe.png">

Except for AudioVideoDisabled and PassThru, you can change them.

We should apply the following updates to this article:
- If the parameter is not available in Teams PS, document that it's not applicable to it is enough for me.
- If the parameter is available in Team PS, document that it's applicable to "Microsoft Teams" instead of SfBO is enough for me.

2022-01-24 08:20 UTC, dariomws commented
@pbafna03, after this PR I have reviewed the following one:
https://github.com/MicrosoftDocs/office-docs-powershell/pull/8834

If Set-CsUser will be deprecated, I think that note is enough and we don't need to merge this one.

2022-01-24 09:13 UTC, pbafna03 commented
> @pbafna03, after this PR I have reviewed the following one: #8834
> 
> If Set-CsUser will be deprecated, I think that note is enough and we don't need to merge this one.

Hi @dariomws - the overall Set-CsUser deprecation will take a bit of time (targeted for completion in Apr'22), but the unsupported params are part of flight and have already started not working for Teams only Tenants. Hence thought it would be good to explicitly callout.

2022-01-24 09:56 UTC, opbld32 commented
Docs Build status updates of commit _[90ff426](https://github.com/pbafna03/office-docs-powershell/commits/90ff4264b434e0f3bb8ff8ff47ced00917b70e44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsUser.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps&branch=pr-en-us-8840) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201240953115108-8840%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T09%3A56%3A06Z&sr=b&sp=r&sig=ecq0xCpZVyPrldXLY0todCNjcVjhIKV6sdKffqxK17o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 09:58 UTC, opbld31 commented
Docs Build status updates of commit _[832f1af](https://github.com/pbafna03/office-docs-powershell/commits/832f1af1b2cdc595c51ac9e24968b69c6e324215)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsUser.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps&branch=pr-en-us-8840) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201240955338404-8840%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T09%3A58%3A34Z&sr=b&sp=r&sig=sumykhLDmTff12%2FDatUP%2Bz%2BO0jOhgu6LkC3dPg03bOc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 11:05 UTC, dariomws approved these changes
@pbafna03, maybe you should use the same note:

**Note**: This cmdlet will be deprecated. Use the new [Set-CsPhoneNumberAssignment](/powershell/module/teams/set-csphonenumberassignment) cmdlet instead.

2022-01-24 15:57 UTC, get-itips approved these changes

2022-01-24 16:38 UTC, tseward approved these changes

2022-01-25 05:48 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-01-25 22:46 UTC, opbld30 commented
Docs Build status updates of commit _[c212823](https://github.com/pbafna03/office-docs-powershell/commits/c212823a141bbe20d1ec1dc411be6b0e324ff6d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsUser.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csuser?view=skype-ps&branch=pr-en-us-8840) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C25%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202201252243330784-8840%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-25T22%3A46%3A06Z&sr=b&sp=r&sig=D3lRFIJlCelxo5sNwtCrkRv2xJnkbbxuGho1mAh5PPc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-25 22:46 UTC, merged