Fixes broken markdown links
MicrosoftDocs/office-docs-powershell pull request #8895
Opened 2022-02-02 20:47 UTC by robdy

The links were broken because of the space between `[ ]` and `( )`.

2022-02-04 10:43 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Import-CsOnlineAudioFile.md
> +This example creates a new audio file using the WAV content that has a filename of Hello.wav to be used with organizational auto attendants. The stored variable, $audioFile, will be used when running
```suggestion
This example creates a new audio file using the WAV content that has a filename of Hello.wav to be used with organizational auto attendants. The stored variable, $audioFile, will be used when running other cmdlets to update the audio file for Auto Attendant, for example [New-CsAutoAttendantPrompt](https://docs.microsoft.com/powershell/module/skype/new-csautoattendantprompt).
```

2022-02-04 10:44 UTC, JohanFreelancer9 requested changes
Copy review - @robdy, kindly commit the additional minor suggested change. Many thanks.

2022-02-04 10:59 UTC, robdy commented
@JohanFreelancer9 done.

2022-02-04 11:01 UTC, opbld33 commented
Docs Build status updates of commit _[c532232](https://github.com/robdy/office-docs-powershell/commits/c5322320b0710a33c50f89eb7b6172117c09da25)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/robdy/office-docs-powershell/blob/patch-7/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-8895) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C4%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202041058248364-8895%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-07T11%3A01%3A16Z&sr=b&sp=r&sig=oaVwwC6NnsE7sO%2BmmuFnQZp7bREcvkWuQyvOYWNpmfQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-04 11:14 UTC, JohanFreelancer9 approved these changes

2022-02-07 17:09 UTC, get-itips approved these changes

2022-02-08 12:26 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-02-08 20:54 UTC, opbld30 commented
Docs Build status updates of commit _[d47b4f1](https://github.com/robdy/office-docs-powershell/commits/d47b4f1a6b522f4b749db6e83caa0faee377d970)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/robdy/office-docs-powershell/blob/patch-7/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-8895) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202082051421081-8895%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-11T20%3A54%3A02Z&sr=b&sp=r&sig=iS7zMMnKQrhbHux0sgERRYp73W5Q9SBcsgHSQtSQRpo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-08 20:54 UTC, merged