adding descriptions
MicrosoftDocs/office-docs-powershell pull request #8937
Opened 2022-02-09 20:37 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/7188

descriptions taken from Set-

2022-02-09 20:37 UTC, get-itips commented
@yogkumgit

2022-02-09 20:39 UTC, opbld31 commented
Docs Build status updates of commit _[499e281](https://github.com/get-itips/office-docs-powershell/commits/499e281d8d78389c4b365e587f12e3fa9a3f68f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-380/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-8937) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202092037039505-8937%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-12T20%3A39%3A52Z&sr=b&sp=r&sig=dCfQabenAzlnY1r7rI5izAQvuXNjkq1NeoUDw8wtPtU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-10 07:48 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +Controls the attendees who can attend a webinar meeting. The default is Everyone, meaning that everyone can register. If you want to restrict registration  to internal accounts set the value  to 'Eve
```suggestion
Controls the attendees who can attend a webinar meeting. The default is Everyone, meaning that everyone can register. If you want to restrict registration to internal accounts, set the value to 'EveryoneInCompany'. 
```

2022-02-10 07:48 UTC, JohanFreelancer9 requested changes
Copy review.

2022-02-10 08:50 UTC, yogkumgit commented
@get-itips copy review ( as suggested by Johan)

2022-02-10 15:09 UTC, opbld30 commented
Docs Build status updates of commit _[3be3ca9](https://github.com/get-itips/office-docs-powershell/commits/3be3ca913388154e04d1477ca182841be771dd1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-380/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-8937) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202101506468588-8937%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-13T15%3A09%3A39Z&sr=b&sp=r&sig=pwY66jmeKuR1R3Ur%2FcflEVEWAte5gBr1wAx164ijY1A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-10 15:20 UTC, dariomws approved these changes

2022-02-11 06:44 UTC, yogkumgit commented
@JohanFreelancer9

2022-02-11 06:52 UTC, JohanFreelancer9 approved these changes

2022-02-14 15:22 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-02-14 21:55 UTC, opbld33 commented
Docs Build status updates of commit _[f922fb4](https://github.com/get-itips/office-docs-powershell/commits/f922fb4c0db345f3234530023abedcef73a49572)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-380/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-8937) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202142152507475-8937%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T21%3A55%3A32Z&sr=b&sp=r&sig=dz5csxjzF48Ea6ylo%2FIXXQuxnKePh1w9TNaJGymZzwg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-14 23:17 UTC, merged