Changes to TPM 3.0.0 and above
MicrosoftDocs/office-docs-powershell pull request #8954
Opened 2022-02-14 19:36 UTC by isrumnon

2022-02-14 19:39 UTC, opbld33 commented
Docs Build status updates of commit _[2265c6b](https://github.com/isrumnon/office-docs-powershell-new/commits/2265c6b27cf1ba75e4a6fa7f786a8cbddd912db6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-7/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8954) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C14%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202141936405857-8954%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-17T19%3A39%3A05Z&sr=b&sp=r&sig=I%2BbiLHi%2FLB5uyOeME6Hkz7rYV1R7GH4nMkunlA%2BBpy4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 07:25 UTC, isrumnon commented
@JohanFreelancer9 @get-itips @tseward @yogkumgit can you please review? Need to get this doc updated asap

2022-02-15 07:42 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineUser.md
> +The below updates are applicable for TeamsOnly customers using Microsoft Teams PowerShell version 3.0.0 and above.
```suggestion
The following updates are applicable for TeamsOnly customers using Microsoft Teams PowerShell version 3.0.0 and above.
```

2022-02-15 07:46 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineUser.md
> +  - EnterpriseVoiceEnabled -eq true / false
```suggestion
  - EnterpriseVoiceEnabled -eq true/false
```

2022-02-15 07:49 UTC, JohanFreelancer9 requested changes
Copy review - @isrumnon, kindly commit the minor suggested edit. Many thanks.

2022-02-15 08:04 UTC, opbld31 commented
Docs Build status updates of commit _[48fb095](https://github.com/isrumnon/office-docs-powershell-new/commits/48fb09524452f5aa6c0973cea55421e92ac4c923)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-7/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8954) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202150801534905-8954%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T08%3A04%3A22Z&sr=b&sp=r&sig=p%2FdsktidowawogJfhSvGaMEtPQ7oAKK01TXP8acPXwU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 09:32 UTC, JohanFreelancer9 approved these changes

2022-02-15 14:32 UTC, dariomws approved these changes

2022-02-15 23:45 UTC, tseward approved these changes

2022-02-16 05:07 UTC, isrumnon commented
Hi @yogkumgit can you help with getting this PR merged and published?

2022-02-16 11:34 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-02-16 18:17 UTC, opbld30 commented
Docs Build status updates of commit _[322c366](https://github.com/isrumnon/office-docs-powershell-new/commits/322c366a81697dc905422208c9eb50578a98c923)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-7/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8954) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202161814454640-8954%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T18%3A17%3A23Z&sr=b&sp=r&sig=Rd34jHWa%2Flqc1C1uIipgkFHD5Z3Fn5ALJcM0OJhmcOU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 21:09 UTC, tiburd commented
close > reopen

2022-02-16 21:12 UTC, opbld32 commented
Docs Build status updates of commit _[322c366](https://github.com/isrumnon/office-docs-powershell-new/commits/322c366a81697dc905422208c9eb50578a98c923)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-7/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8954) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C16%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202162110012080-8954%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-19T21%3A12%3A47Z&sr=b&sp=r&sig=rD6DNrVi1lfn%2B7abzkvHwDqdmzVo7qAG3cCXWQLPihI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-16 21:13 UTC, merged