Update Get-CsOnlineUser.md - added some Renamed attributes + deprecated attributes
MicrosoftDocs/office-docs-powershell pull request #8988
Opened 2022-02-21 07:08 UTC by isrumnon

2022-02-21 07:10 UTC, opbld33 commented
Docs Build status updates of commit _[2bebf4d](https://github.com/isrumnon/office-docs-powershell-new/commits/2bebf4de4882c901c0605647c7b7d6d39ec8d8f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-11/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8988) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202210708083196-8988%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-24T07%3A10%3A54Z&sr=b&sp=r&sig=VshYR3%2FgGXbkbK5Fk6SPKuf642kvYmoV4OwoxbkCtrY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-21 09:21 UTC, isrumnon commented on skype/skype-ps/skype/Get-CsOnlineUser.md
> +- ProxyAddresses renamed to ProxyAddresse
Correct, thanks for pointing this out

2022-02-21 09:22 UTC, opbld32 commented
Docs Build status updates of commit _[cbcbd6a](https://github.com/isrumnon/office-docs-powershell-new/commits/cbcbd6ab44136bf057783bfd03c12fb37874b951)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-11/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8988) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202210920202376-8988%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-24T09%3A22%3A55Z&sr=b&sp=r&sig=126N862RBEywhoEQ5kJEFUUb4T7KFponozjir%2BlevDc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-21 10:33 UTC, JohanFreelancer9 approved these changes

2022-02-21 15:46 UTC, opbld33 commented
Docs Build status updates of commit _[9ac64f6](https://github.com/isrumnon/office-docs-powershell-new/commits/9ac64f6d0ea5787e43a30f5c5f36b59fd483ab79)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-11/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8988) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202211544179551-8988%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-24T15%3A46%3A58Z&sr=b&sp=r&sig=pQM2pH0G0IJXBJcqfZ7NM0h0Rsjpt%2FTO4HrymTEUtyg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-21 17:52 UTC, isrumnon commented
Hi @get-itips @dariomws @tseward can we get this reviewed asap? Need to address some customer queries through this documentaion

2022-02-21 17:57 UTC, get-itips commented on skype/skype-ps/skype/Get-CsOnlineUser.md
> +- TeamsEnhancedEncryptionPolicy
Hello! are these really not relevant to Teams? or do they belong to the filters list? Thanks for clarifying!

2022-02-21 19:06 UTC, isrumnon commented
@get-itips let me just double check with team and update

2022-02-22 07:36 UTC, dariomws requested changes

2022-02-22 07:36 UTC, dariomws commented on skype/skype-ps/skype/Get-CsOnlineUser.md
> +- TeamsBranchSurvivabilityPolicy renamed to TeamsSurvivableBranchAppliancePolicy
```suggestion
- ObjectId renamed to Identity
- FirstName renamed to GivenName
- DirSyncEnabled renamed to UserDirSyncEnabled
- MCOValidationErrors renamed to UserValidationErrors
- OnPremSIPEnabled renamed to OnPremIsSipEnabled
- Enabled renamed to IsSipEnabled
- OnPremOptionFlags renamed to OnPremOptionFlag
- OptionFlags renamed to OptionFlag
- ProxyAddresses renamed to ProxyAddress
- ShadowProxyAddresses renamed to ShadowProxyAddress
- TeamsBranchSurvivabilityPolicy renamed to TeamsSurvivableBranchAppliancePolicy
```

2022-02-22 07:44 UTC, dariomws approved these changes

2022-02-22 07:45 UTC, opbld33 commented
Docs Build status updates of commit _[02faffa](https://github.com/isrumnon/office-docs-powershell-new/commits/02faffaf7bddde5d7902c982b7f13d48343fa4e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-11/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8988) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202220742397035-8988%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T07%3A45%3A17Z&sr=b&sp=r&sig=sMEx7iRt0HF8FrGTYeNb31YDZd4wiXF4p242NSHHuXM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 12:09 UTC, isrumnon commented
@dariomws thanks for pointing out that discrepancy. I've made necessary changes

2022-02-22 12:11 UTC, opbld31 commented
Docs Build status updates of commit _[a88dfc3](https://github.com/isrumnon/office-docs-powershell-new/commits/a88dfc3f4dbfeefc64b98aa16131872f28421f48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-11/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8988) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202221208215593-8988%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T12%3A11%3A02Z&sr=b&sp=r&sig=jlO76oJmhtuB9SJlVgwxCX0YEKsygkhGU4mWoWcM%2Bww%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 13:32 UTC, get-itips approved these changes

2022-02-22 17:20 UTC, tseward approved these changes

2022-02-22 17:21 UTC, isrumnon commented
Hi @yogkumgit @tiburd can we get this merged?

2022-02-22 23:09 UTC, opbld31 commented
Docs Build status updates of commit _[57619e7](https://github.com/isrumnon/office-docs-powershell-new/commits/57619e7c823d7b12a6846874896501ee1f6cb1cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineUser.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-11/skype/skype-ps/skype/Get-CsOnlineUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps&branch=pr-en-us-8988) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202222307007409-8988%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T23%3A09%3A49Z&sr=b&sp=r&sig=mFws88iPbkuEBqr6KQPOXQUW7yWKFtpvrbvw%2BfhVtxI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 23:10 UTC, merged