Update Remove-CsAutoAttendant.md
MicrosoftDocs/office-docs-powershell pull request #8997
Opened 2022-02-22 18:54 UTC by CLYVR

Adding note to indicate that resource accounts must be removed first.

2022-02-22 18:57 UTC, opbld30 commented
Docs Build status updates of commit _[bf7d0fe](https://github.com/CLYVR/office-docs-powershell/commits/bf7d0fe7ee20b7aa400cacefe7fe81a7bcb23ecb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Remove-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-9/skype/skype-ps/skype/Remove-CsAutoAttendant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csautoattendant?view=skype-ps&branch=pr-en-us-8997) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202221854313671-8997%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T18%3A57%3A18Z&sr=b&sp=r&sig=1eKMWqN7vnnZ9hvL1BZBWSTITbvsOnyt0I80QwSWdX4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 19:02 UTC, opbld31 commented
Docs Build status updates of commit _[2441abd](https://github.com/CLYVR/office-docs-powershell/commits/2441abd4141500698c9ccc0e98be9d7e9140a26a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Remove-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-9/skype/skype-ps/skype/Remove-CsAutoAttendant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csautoattendant?view=skype-ps&branch=pr-en-us-8997) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlineSchedule.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-9/skype/skype-ps/skype/Set-CsOnlineSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlineschedule?view=skype-ps&branch=pr-en-us-8997) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202221859310330-8997%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T19%3A02%3A18Z&sr=b&sp=r&sig=4A%2F4qYDH48VhpLUt2getYM%2F2%2B9xsqBYr0Ehqhj6DqQA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 19:28 UTC, CLYVR commented
@get-itips @dariomws @tseward @tiburd - some minor corrects please and thanks.

2022-02-22 19:29 UTC, opbld31 commented
Docs Build status updates of commit _[1326161](https://github.com/CLYVR/office-docs-powershell/commits/1326161f3b6da2cd454cad1a5a2cafde7cb01a60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Remove-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-9/skype/skype-ps/skype/Remove-CsAutoAttendant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csautoattendant?view=skype-ps&branch=pr-en-us-8997) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlineSchedule.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-9/skype/skype-ps/skype/Set-CsOnlineSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlineschedule?view=skype-ps&branch=pr-en-us-8997) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202221926530491-8997%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T19%3A29%3A40Z&sr=b&sp=r&sig=s6L1K6BbS0Q3Os7KIrPVmUr%2FgBphNGB6SrYw9CmQ%2BPc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 19:58 UTC, get-itips approved these changes

2022-02-22 23:12 UTC, tiburd commented
@dariomws @tseward 
Please @ mention me after the last of you two review/approve this PR.
Thanks!

2022-02-23 09:21 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Remove-CsAutoAttendant.md
> +>Remove any associated resource accounts with [Remove-CsOnlineApplicationInstanceAssociation](Remove-CsOnlineApplicationInstanceAssociation.md) before attempting to delete the Auto Attendant (AA)
```suggestion
> Remove any associated resource accounts with [Remove-CsOnlineApplicationInstanceAssociation](Remove-CsOnlineApplicationInstanceAssociation.md) before attempting to delete the AA.
```

2022-02-23 09:22 UTC, dariomws approved these changes

2022-02-23 09:22 UTC, dariomws commented on skype/skype-ps/skype/Remove-CsAutoAttendant.md
> +>Remove any associated resource accounts with [Remove-CsOnlineApplicationInstanceAssociation](Remove-CsOnlineApplicationInstanceAssociation.md) before attempting to delete the Auto Attendant (AA)
```suggestion
> [!NOTE]
> Remove any associated resource accounts with [Remove-CsOnlineApplicationInstanceAssociation](Remove-CsOnlineApplicationInstanceAssociation.md) before attempting to delete the Auto Attendant (AA).
```

2022-02-23 09:22 UTC, JohanFreelancer9 requested changes
Copy review - @CLYVR, kindly commit the suggested change. Many thanks.

2022-02-24 03:07 UTC, JohanFreelancer9 approved these changes

2022-02-24 11:32 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-02-24 18:16 UTC, opbld33 commented
Docs Build status updates of commit _[a3f30b5](https://github.com/CLYVR/office-docs-powershell/commits/a3f30b571834d7559f41bff7034e0edcdd087092)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Remove-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-9/skype/skype-ps/skype/Remove-CsAutoAttendant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csautoattendant?view=skype-ps&branch=pr-en-us-8997) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlineSchedule.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-9/skype/skype-ps/skype/Set-CsOnlineSchedule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlineschedule?view=skype-ps&branch=pr-en-us-8997) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202241813164737-8997%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T18%3A16%3A11Z&sr=b&sp=r&sig=ao%2F2pm2MORUQFgIFxX5b7xs52Wn9%2BhyHP0oIh%2BSHl40%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 18:17 UTC, merged