Advanced settings DefaultSharingScope & DefaultShareLinkPermission now support files
MicrosoftDocs/office-docs-powershell pull request #8998
Opened 2022-02-22 19:25 UTC by cabailey

2022-02-22 19:27 UTC, opbld30 commented
Docs Build status updates of commit _[0c2f6fd](https://github.com/cabailey/office-docs-powershell/commits/0c2f6fd5f6619e5ce1a257b461931a49d0ab915b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-Label.md](https://github.com/cabailey/office-docs-powershell/blob/cabailey-m365powershell-advancedsettings/exchange/exchange-ps/exchange/New-Label.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-label?view=exchange-ps&branch=pr-en-us-8998) (exchange-ps) |
[exchange/exchange-ps/exchange/Set-Label.md](https://github.com/cabailey/office-docs-powershell/blob/cabailey-m365powershell-advancedsettings/exchange/exchange-ps/exchange/Set-Label.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps&branch=pr-en-us-8998) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202221925118784-8998%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-25T19%3A27%3A58Z&sr=b&sp=r&sig=tsh1BOo4xzmUSeXJfyVxH1Bh77jRpmIMRd0zoTLfB3I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-22 19:34 UTC, cabailey commented
#sign-off  For new release now rolled out & supporting article going live today

2022-02-23 09:30 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/New-Label.md
> +- **DefaultShareLinkPermission**: Specifies the permissions for the sharing link for a site when the label scope includes **Groups & sites**, and the permissions for the sharing link for a document w
```suggestion
- **DefaultShareLinkPermission**: Specifies the permissions for the sharing link for a site when the label scope includes **Groups & sites**, and the permissions for the sharing link for a document when the label scope includes **Files & emails**. Available values are View and Edit. Example: `New-Label -Identity General -AdvancedSettings @{DefaultShareLinkPermission="Edit"}`. For more information, see [Use sensitivity labels to configure the default sharing link type for sites and documents in SharePoint and OneDrive](https://docs.microsoft.com/microsoft-365/compliance/sensitivity-labels-default-sharing-link).
```

2022-02-23 09:30 UTC, JohanFreelancer9 requested changes
Copy review - minor suggestion.

2022-02-23 17:16 UTC, opbld31 commented
Docs Build status updates of commit _[22404d0](https://github.com/cabailey/office-docs-powershell/commits/22404d0640b4878bd8a9cf43070c735a895e26fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-Label.md](https://github.com/cabailey/office-docs-powershell/blob/cabailey-m365powershell-advancedsettings/exchange/exchange-ps/exchange/New-Label.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-label?view=exchange-ps&branch=pr-en-us-8998) (exchange-ps) |
[exchange/exchange-ps/exchange/Set-Label.md](https://github.com/cabailey/office-docs-powershell/blob/cabailey-m365powershell-advancedsettings/exchange/exchange-ps/exchange/Set-Label.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps&branch=pr-en-us-8998) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202231714035311-8998%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T17%3A16%3A49Z&sr=b&sp=r&sig=RJNqbWUGccmgb5sTwhJG2l5m95KM7i2LcNmDN5wq5vk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 17:19 UTC, opbld31 commented
Docs Build status updates of commit _[22404d0](https://github.com/cabailey/office-docs-powershell/commits/22404d0640b4878bd8a9cf43070c735a895e26fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-Label.md](https://github.com/cabailey/office-docs-powershell/blob/cabailey-m365powershell-advancedsettings/exchange/exchange-ps/exchange/New-Label.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-label?view=exchange-ps&branch=pr-en-us-8998) (exchange-ps) |
[exchange/exchange-ps/exchange/Set-Label.md](https://github.com/cabailey/office-docs-powershell/blob/cabailey-m365powershell-advancedsettings/exchange/exchange-ps/exchange/Set-Label.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps&branch=pr-en-us-8998) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202231714202367-8998%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T17%3A19%3A46Z&sr=b&sp=r&sig=evT%2BzL89McW%2FuH0lkXtegyMXx4lIwIv%2FCuXRSENXOYU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 17:22 UTC, opbld32 commented
Docs Build status updates of commit _[d584198](https://github.com/cabailey/office-docs-powershell/commits/d584198cc82b7aab6708c3b58fb14a9b2b5fe974)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-Label.md](https://github.com/cabailey/office-docs-powershell/blob/cabailey-m365powershell-advancedsettings/exchange/exchange-ps/exchange/New-Label.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-label?view=exchange-ps&branch=pr-en-us-8998) (exchange-ps) |
[exchange/exchange-ps/exchange/Set-Label.md](https://github.com/cabailey/office-docs-powershell/blob/cabailey-m365powershell-advancedsettings/exchange/exchange-ps/exchange/Set-Label.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-label?view=exchange-ps&branch=pr-en-us-8998) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202231717309914-8998%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T17%3A22%3A43Z&sr=b&sp=r&sig=4%2BP5haJj%2FmLfFOqrTfQ1sAEsRGEAEVauBN5whPFwhRg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 18:13 UTC, merged