Update Get-CsOnlineDirectoryTenant.md - Deprecation Info
MicrosoftDocs/office-docs-powershell pull request #9001
Opened 2022-02-23 16:10 UTC by isrumnon

2022-02-23 16:13 UTC, opbld33 commented
Docs Build status updates of commit _[bded58d](https://github.com/isrumnon/office-docs-powershell-new/commits/bded58d335c3371c93fa6bbabc52427bffd67b5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-12/skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedirectorytenant?view=skype-ps&branch=pr-en-us-9001) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202231610377423-9001%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T16%3A13%3A28Z&sr=b&sp=r&sig=RP9%2FM%2F3JmHNM4gXLSuqbVJgAxLEbqSl9vBciC1329tw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 05:16 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md
> +*Note: Starting with TeamsPowerShell Module 4.0 this cmdlet will be deprecated. Users are required to use the Get-CsTenant cmdlets to view information previously present in Get-CsOnlineDirectoryTenan
```suggestion
**Note**: Starting with Teams PowerShell Module 4.0, this cmdlet is deprecated. Use the Get-CsTenant cmdlet to view information previously present in Get-CsOnlineDirectoryTenant.
```

2022-02-24 05:17 UTC, JohanFreelancer9 requested changes
Copy review - @isrumnon, kindly commit the suggested changes. Many thanks.

2022-02-24 05:21 UTC, isrumnon commented
> Copy review - @isrumnon, kindly commit the suggested changes. Many thanks.

Done!

2022-02-24 05:23 UTC, opbld31 commented
Docs Build status updates of commit _[f25402b](https://github.com/isrumnon/office-docs-powershell-new/commits/f25402b8d9988833afd6f61eb1e6a91fb18b1778)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-12/skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedirectorytenant?view=skype-ps&branch=pr-en-us-9001) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202240521005942-9001%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T05%3A23%3A39Z&sr=b&sp=r&sig=bXhf02I%2BPR45e4Dc045ATKtH%2FESJr2jCc%2FK2byKPb1k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 07:10 UTC, JohanFreelancer9 approved these changes

2022-02-24 14:07 UTC, get-itips approved these changes

2022-02-24 14:07 UTC, dariomws reviewed
Hi @isrumnon,

When 4.0 is arriving? Should we add this here in advance? Thanks!

2022-02-24 17:39 UTC, isrumnon commented
> Hi @isrumnon,
> 
> When 4.0 is arriving? Should we add this here in advance? Thanks!

@dariomws done!

2022-02-24 17:41 UTC, opbld32 commented
Docs Build status updates of commit _[2046faa](https://github.com/isrumnon/office-docs-powershell-new/commits/2046faa9f2d488af426f5f225e84b12820de531b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-12/skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedirectorytenant?view=skype-ps&branch=pr-en-us-9001) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202241739002611-9001%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-27T17%3A41%3A51Z&sr=b&sp=r&sig=mmgTbqQPEOO4u6MSYw%2F7ka6IqCDDnfnBvU1fNJUozOI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-24 17:49 UTC, get-itips approved these changes

2022-02-24 18:00 UTC, dariomws approved these changes

2022-02-25 03:48 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md
> +**Note**: Starting with Teams PowerShell Module 4.0 (available on 1st March'22), this cmdlet is deprecated. Use the Get-CsTenant cmdlet to view information previously present in Get-CsOnlineDirectory
```suggestion
**Note**: Starting with Teams PowerShell Module 4.0 (available from March 1, 2022), this cmdlet is deprecated. Use the Get-CsTenant cmdlet to view information previously present in Get-CsOnlineDirectoryTenant.
```

2022-02-25 03:49 UTC, JohanFreelancer9 requested changes
@isrumnon, minor edit, please.

2022-02-25 04:14 UTC, opbld32 commented
Docs Build status updates of commit _[aa167fe](https://github.com/isrumnon/office-docs-powershell-new/commits/aa167fe37706969d7114a143aa9b1605172c8668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md](https://github.com/isrumnon/office-docs-powershell-new/blob/patch-12/skype/skype-ps/skype/Get-CsOnlineDirectoryTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinedirectorytenant?view=skype-ps&branch=pr-en-us-9001) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C25%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202202250411257563-9001%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-28T04%3A14%3A09Z&sr=b&sp=r&sig=49TlzwQbE4ES776VQccgoGs9pznHgBd30oc777iTaNY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-25 04:30 UTC, JohanFreelancer9 approved these changes

2022-02-25 11:12 UTC, yogkumgit commented
@tseward

2022-02-25 19:58 UTC, tseward approved these changes

2022-02-28 19:05 UTC, merged