Update UserCallingSettings/Delegates for GA
MicrosoftDocs/office-docs-powershell pull request #9063
Opened 2022-03-08 08:42 UTC by JensTrier

Remove Public preview note
Be more specific on Identity support
Add reference to Teams PS Module 4.0.0

2022-03-08 08:45 UTC, opbld31 commented
Docs Build status updates of commit _[6cbee80](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/6cbee804a85f852bfda93792ab62cd93e7af5f0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203080842298812-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T08%3A45%3A09Z&sr=b&sp=r&sig=7zgr1lO%2Bad1gLYuBvu%2FetmdkV0iDtHMsqiZl5fANX28%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 13:31 UTC, opbld31 commented
Docs Build status updates of commit _[0c471c8](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/0c471c8947ad539ddab89ebdca56e225a596d562)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203081328118541-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T13%3A31%3A05Z&sr=b&sp=r&sig=%2BdXiA9pGwyCyoqzc1E0xDJNZVzKeUP3cd%2BTrJmveYCU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 13:33 UTC, opbld32 commented
Docs Build status updates of commit _[06f58ba](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/06f58ba961306c007dabb0fb2dc79cbe491b38d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203081329283565-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T13%3A33%3A38Z&sr=b&sp=r&sig=953B3Uj9%2FLsW3ZY%2BJHoGljX2iNL65CnjAhkbyAICY64%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-08 13:36 UTC, opbld32 commented
Docs Build status updates of commit _[1dcfa36](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/1dcfa36e9849a1397f3acdb0538d967c01e2e170)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203081328497699-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T13%3A36%3A23Z&sr=b&sp=r&sig=Y2DueYOwQxx7rdDom4VONgxWk097aPsUeLKD%2FPLhjQo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 03:29 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-03-09 08:24 UTC, opbld31 commented
Docs Build status updates of commit _[88196a4](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/88196a4c96d0b044cc4aeadebae7fd647d5c88b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203090822154239-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T08%3A24%3A45Z&sr=b&sp=r&sig=A7FUuejO1Dv23kk0Gq2qWG7LWtPzzR72CNu6N%2BAfPXU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 09:16 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsUserCallingSettings.md
```suggestion
 
```

2022-03-09 09:17 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-CsUserCallingDelegate.md
```suggestion
```

2022-03-09 09:18 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsUserCallingSettings.md
```suggestion
```

2022-03-09 09:20 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the suggested changes to remove the extra blank lines. Many thanks.

2022-03-09 09:34 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the suggested changes to remove the extra blank lines. Many thanks.

Thanks & Done

2022-03-09 09:36 UTC, opbld32 commented
Docs Build status updates of commit _[667f29a](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/667f29ab3ebc90efc845da9c4d5bc088fe951469)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203090933115846-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T09%3A36%3A18Z&sr=b&sp=r&sig=sG9D3fp26NLRwzCkuJ%2FEJzEA6S7YZOaNJ2ZjuWkCgY4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 09:38 UTC, opbld31 commented
Docs Build status updates of commit _[df08b0b](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/df08b0b1a46c92b4bff0207c1667d6fcd607cc52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203090933437618-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T09%3A38%3A48Z&sr=b&sp=r&sig=4kHz9cnMaeLDAk%2FE8FO3voQQ9eLRZVMfwcjeLIDlHd8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 09:41 UTC, opbld31 commented
Docs Build status updates of commit _[3be53a6](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/3be53a6889ef20ae55ab54d901c0a7d87dcdbf74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203090933349375-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T09%3A41%3A49Z&sr=b&sp=r&sig=62tELcLaXUZQdK%2Fqe%2F5bMEImp%2FMBYB9TRt8Wo4NtzQg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 09:44 UTC, opbld30 commented
Docs Build status updates of commit _[9ffaf7b](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/9ffaf7bb56466690d13af8cfe25c746177c28112)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203090933240838-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T09%3A44%3A06Z&sr=b&sp=r&sig=iij2O3bjscMz%2Br4e%2BbVQFhUr9iEuCnhF2OI7Sg34sNg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 10:32 UTC, dariomws approved these changes

2022-03-09 10:46 UTC, JohanFreelancer9 approved these changes

2022-03-09 11:12 UTC, get-itips approved these changes

2022-03-10 02:32 UTC, yogkumgit commented
@tseward

2022-03-10 09:54 UTC, opbld31 commented
Docs Build status updates of commit _[b4f0b88](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/b4f0b88988ee6af790df810cabe1c391a86153e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C10%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203100951514776-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-10T09%3A54%3A39Z&sr=b&sp=r&sig=mT%2B96aaaglraYvUGsKaLn731njnySPWR9oOgdDZZb44%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-10 20:58 UTC, tseward approved these changes

2022-03-11 02:19 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-11 16:41 UTC, opbld33 commented
Docs Build status updates of commit _[dc7c491](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/dc7c4916926093ff9c1405f477618bfcb76cff32)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Get-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Remove-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/skype/skype-ps/skype/Set-CsVoiceNormalizationRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csvoicenormalizationrule?view=skype-ps&branch=pr-en-us-9063) (skype-ps) |
[teams/teams-ps/teams/Get-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Get-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/New-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/New-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Remove-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Remove-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingDelegate.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingDelegate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingdelegate?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |
[teams/teams-ps/teams/Set-CsUserCallingSettings.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/UCSUpdateForGA/teams/teams-ps/teams/Set-CsUserCallingSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csusercallingsettings?view=teams-ps&branch=pr-en-us-9063) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203111638454468-9063%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T16%3A41%3A32Z&sr=b&sp=r&sig=ZTXUzc5WHRtvNLDAOGG%2Bm0oT3c8353Yh1ZTiY4VoOAg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-11 17:00 UTC, merged