Update Set-CsPhoneNumberAssignment.md
MicrosoftDocs/office-docs-powershell pull request #9106
Opened 2022-03-15 16:31 UTC by RuiPereiraTabares

2022-03-16 02:41 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-03-16 03:43 UTC, RuiPereiraTabares commented
hence currently i have a bug open for changing the exception, right now assiging a phone or setting enterprise voice enable to a user that his location is MO, we will say that the user does not has a license assigned, the error message is planned to be changed.

2022-03-16 07:49 UTC, dariomws requested changes

2022-03-16 07:49 UTC, dariomws commented on teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
> +**Note**: Macao region is currently not supported for phone number assigment or enterprisevoice.
```suggestion

**Note**: Macao region is currently not supported for phone number assignment or Enterprise Voice.

```

2022-03-16 07:53 UTC, opbld31 commented
Docs Build status updates of commit _[07db4aa](https://github.com/RuiPereiraTabares/office-docs-powershell/commits/07db4aabec34d8ea04b75d0e520a9779d1a4b127)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/RuiPereiraTabares/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9106) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C16%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203160751254310-9106%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-16T07%3A53%3A55Z&sr=b&sp=r&sig=vh7OVmfxLPSOOcCYsAJGJKjpCJu3dAyCxP3EHJvs0%2Fc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-16 08:09 UTC, dariomws approved these changes

2022-03-16 12:28 UTC, get-itips approved these changes

2022-03-16 19:08 UTC, tiburd commented
@RuiPereiraTabares 
Hi, Rui,
Because you are a Microsoft employee, please be sure to [link your Microsoft and GitHub accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github?branch=main#link-your-github-and-microsoft-accounts).
Thanks!

2022-03-16 19:59 UTC, RuiPereiraTabares commented
@tiburd I have updated my account as a microsoft github account can you verify?

2022-03-16 20:46 UTC, tiburd commented
> @tiburd I have updated my account as a microsoft github account can you verify?
@RuiPereiraTabares 
Thank you!
It's now listed as being connected:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/54688693/158687849-7b261555-7203-4bb1-a8fd-19e5b62e8fbe.png">

2022-03-17 03:19 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-17 03:48 UTC, tseward commented
@RuiPereiraTabares is this a permanent (or very long term) issue or temporary? If temporary, I would suggest this would fit better as a Service Health issue in the admin dashboard on admin.microsoft.com. If it is permanent or very long term, then I can see why adding this to the documentation would be beneficial.

2022-03-17 07:11 UTC, RuiPereiraTabares commented
@tseward is going to be pretty long term (2+yers), we will change our exception to this region is not supported. Therefore is better to have it somewhere documented.

2022-03-17 08:42 UTC, JohanFreelancer9 approved these changes

2022-03-17 12:43 UTC, get-itips commented
@RuiPereiraTabares it seems Microsoft uses "Macau" in other articles like https://docs.microsoft.com/en-us/microsoftteams/what-is-phone-system-in-office-365 @JohanFreelancer9 ?

also, what about this? is it outdated? 

> Phone System is available world wide except for Macau.

2022-03-17 17:52 UTC, tseward approved these changes

2022-03-19 02:02 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-19 06:36 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md
> +**Note**: Macao region is currently not supported for phone number assignment or Enterprise Voice.
```suggestion
**Note**: Macau region is currently not supported for phone number assignment or Enterprise Voice.

```

2022-03-19 06:37 UTC, JohanFreelancer9 commented
@get-itips, thanks for pointing out this discrepancy. Although "Macao" is the official name, "Macau" also seems to be widely used, certainly in a number of Microsoft docs. So for the sake of consistency, I would suggest we stick to "Macau". @RuiPereiraTabares, could you please commit the suggestion. Thanks.

2022-03-19 09:38 UTC, RuiPereiraTabares commented
done @JohanFreelancer9

2022-03-19 09:40 UTC, opbld33 commented
Docs Build status updates of commit _[c13e304](https://github.com/RuiPereiraTabares/office-docs-powershell/commits/c13e30422720273775ddefd89f5689d463a0e548)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/RuiPereiraTabares/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9106) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C19%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203190937343323-9106%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-19T09%3A40%3A45Z&sr=b&sp=r&sig=x7T5MeTTTgQfBDxG5HQWurE2JclXkN%2Bm7UXWaEMcQus%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-19 09:42 UTC, RuiPereiraTabares commented
> @RuiPereiraTabares it seems Microsoft uses "Macau" in other articles like https://docs.microsoft.com/en-us/microsoftteams/what-is-phone-system-in-office-365 @JohanFreelancer9 ?
> 
> also, what about this? is it outdated?
> 
> > Phone System is available world wide except for Macau.

On regards this, @get-itips  i discussed internally to at least have one article where we mention Macao/Macau, if you use the blame tool you can see that over that article Macau was added 3 days ago, our internal discussion started last friday so mostlkely the PM pushed for this change.  I think also having this documented on this article will be good

2022-03-21 18:46 UTC, tiburd commented
Sent email to PMs to ask whether this information is better suited for a Service Health Issue.

2022-03-22 17:04 UTC, opbld33 commented
Docs Build status updates of commit _[e393b1f](https://github.com/RuiPereiraTabares/office-docs-powershell/commits/e393b1f404a01eb5879621c7992fd0016f1032b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/RuiPereiraTabares/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9106) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203221701412224-9106%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T17%3A04%3A33Z&sr=b&sp=r&sig=LQ0ls4Kh6f1Vf4KtuBJB6ddTD1P5iKjcTqeVXfrDqvM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 18:04 UTC, opbld30 commented
Docs Build status updates of commit _[5fe5df0](https://github.com/RuiPereiraTabares/office-docs-powershell/commits/5fe5df080981d6d761294970dbb5f32ab0a21366)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/RuiPereiraTabares/office-docs-powershell/blob/patch-4/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9106) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203221759345349-9106%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T18%3A04%3A27Z&sr=b&sp=r&sig=lJiqxAkfHuSz%2FbHQIoSfsPbzi2brXJLh3wHIHW3RhLw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 18:05 UTC, merged