MeetingRoom cmdlets - clarification for Teams
MicrosoftDocs/office-docs-powershell pull request #9129
Opened 2022-03-18 14:12 UTC by pbafna03

*-CsMeetingRoom  cmdlets are not supported for managing Microsoft Teams Rooms but has been a cause of confusion, hence adding the note to clarify.

2022-03-18 14:16 UTC, opbld30 commented
Docs Build status updates of commit _[f7614f3](https://github.com/pbafna03/office-docs-powershell/commits/f7614f33f45052b26adfae132511fc0b0a92b078)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Get-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203181413003796-9129%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T14%3A16%3A02Z&sr=b&sp=r&sig=IPrlauJKWJbgFnSy3a8V9oWSY9BEd1oFwjkEM%2FeXndg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 14:18 UTC, opbld33 commented
Docs Build status updates of commit _[afb85d8](https://github.com/pbafna03/office-docs-powershell/commits/afb85d8698abc3b3eea5c6a2c49ec8c1bcdfa0cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Get-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Set-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Set-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203181414144130-9129%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T14%3A18%3A52Z&sr=b&sp=r&sig=uimYGRtNiTJ8UGaWMLdBt3i1bLUkz3u1pKVkLygMJfE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-18 14:21 UTC, opbld31 commented
Docs Build status updates of commit _[a9b8bed](https://github.com/pbafna03/office-docs-powershell/commits/a9b8bed505604c7aba2a8061acc63740ebb4a9db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Disable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Disable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/disable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Enable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Enable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Get-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Get-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Set-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Set-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203181416339825-9129%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T14%3A21%3A42Z&sr=b&sp=r&sig=V0ndNPxEOM%2Bw8Y1xKLH5lGpEY57M%2BBIwXx7uTE1dTLI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-19 02:06 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-19 02:08 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-03-19 06:55 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Disable-CsMeetingRoom.md
> +**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms, please use the methods mentioned in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation for the same.
```suggestion
**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. We recommend you use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms.
```

2022-03-19 06:56 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Enable-CsMeetingRoom.md
> +**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms, please use the methods mentioned in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation for the same.
```suggestion
**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. We recommend you use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms.
```

2022-03-19 06:57 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsMeetingRoom.md
> +**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms, please use the methods mentioned in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation for the same.
```suggestion
**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. We recommend you use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms.
```

2022-03-19 06:57 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsMeetingRoom.md
> +**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms, please use the methods mentioned in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation for the same.
```suggestion
**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. We recommend you use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms.
```

2022-03-19 07:02 UTC, opbld32 commented
Docs Build status updates of commit _[5dceb31](https://github.com/pbafna03/office-docs-powershell/commits/5dceb31f9310e29dc04e668b07865b4aad0d7de5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Disable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Disable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/disable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Enable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Enable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Get-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Get-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Set-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Set-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C19%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203190700223453-9129%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-19T07%3A02%3A53Z&sr=b&sp=r&sig=XgPGKxuGfLbVTyFDvP%2F5iUWpJ57CB9FwvVOPW4IrPok%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-19 07:10 UTC, JohanFreelancer9 requested changes
Copy review - @pbafna03, kindly commit the suggested changes. Many thanks.

2022-03-19 07:11 UTC, JohanFreelancer9 approved these changes
@pbafna03, thank you.

2022-03-21 07:47 UTC, dariomws approved these changes

2022-03-21 07:47 UTC, dariomws commented on skype/skype-ps/skype/Disable-CsMeetingRoom.md
> +**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. We recommend you use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Mic
```suggestion
**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. You must use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms.
```

2022-03-21 07:47 UTC, dariomws commented on skype/skype-ps/skype/Disable-CsMeetingRoom.md
> +**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. We recommend you use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Mic
If they are not supported I think it's not a recommendation.

2022-03-21 09:22 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsMeetingRoom.md
> +**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. We recommend you use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Mic
```suggestion
**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. You must use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms.
```

2022-03-21 09:22 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsMeetingRoom.md
> +**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. We recommend you use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Mic
```suggestion
**Note**: This cmdlet is not supported for managing Microsoft Teams Rooms. You must use the methods described in the [Microsoft Teams Rooms](/microsoftteams/rooms) documentation to manage Microsoft Teams Rooms.
```

2022-03-21 09:29 UTC, opbld33 commented
Docs Build status updates of commit _[7c90dbe](https://github.com/pbafna03/office-docs-powershell/commits/7c90dbe0c8cff79e0f64dffd791c1789840b3e1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Disable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Disable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/disable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Enable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Enable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Get-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Get-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Set-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Set-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203210926266899-9129%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-21T09%3A29%3A01Z&sr=b&sp=r&sig=rmxTFlxi5uZLijNoquxv4KIyUJj%2F9rnXyg4igaHWFpc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 13:49 UTC, yogkumgit commented
@tseward

2022-03-23 07:47 UTC, opbld33 commented
Docs Build status updates of commit _[99b08fa](https://github.com/pbafna03/office-docs-powershell/commits/99b08fa3e31b3c8e4c9221bae19dcf879ed49bcc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Disable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Disable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/disable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Enable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Enable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Get-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Get-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Set-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Set-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203230743586676-9129%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T07%3A47%3A27Z&sr=b&sp=r&sig=2jF%2FKBeIQxzchfq%2FM%2B1yNhFvZoGsZwHrNFzRP8uLUDE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-23 11:50 UTC, yogkumgit commented
@tseward please review

2022-03-23 21:58 UTC, tseward approved these changes

2022-03-24 13:46 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-24 17:15 UTC, opbld30 commented
Docs Build status updates of commit _[6e5a05e](https://github.com/pbafna03/office-docs-powershell/commits/6e5a05eadba4cd72465969bb07cedbeb70f510de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Disable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Disable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/disable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Enable-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Enable-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/enable-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Get-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Get-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |
[skype/skype-ps/skype/Set-CsMeetingRoom.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/Set-CsMeetingRoom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csmeetingroom?view=skype-ps&branch=pr-en-us-9129) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203241712283530-9129%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-24T17%3A15%3A42Z&sr=b&sp=r&sig=TnWtmHiW2vX2ZiycXbVvPzaZ6vVFzgLgcz%2BHnI1hbCA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-24 17:17 UTC, merged