Update New-CsTeamsMeetingPolicy.md
MicrosoftDocs/office-docs-powershell pull request #9131
Opened 2022-03-18 18:14 UTC by vini-gupta

Adding new meetingPolicy setting AllowNetworkConfigurationSettingsLookup to help determines whether network configuration setting lookup can be made for not enterprise voice enabled users. It will be used for enabling network roaming policy

2022-03-18 18:17 UTC, opbld30 commented
Docs Build status updates of commit _[f9ae184](https://github.com/vini-gupta/office-docs-powershell/commits/f9ae184c7e1a1513d495c8d973118160671f1cb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/vini-gupta/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9131) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203181814132826-9131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T18%3A17%3A13Z&sr=b&sp=r&sig=UOvNw19j%2FTlP63UKGz6EeTN%2BTw4MZfEPfRL0LACuaeM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-19 02:08 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-19 07:24 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +Determines whether network configuration setting lookup can be made for users who are not enterprise voice enabled, it will be used for enabling network roaming policy
```suggestion
Determines whether network configuration setting lookups can be made by users who are not Enterprise Voice enabled. It is used to enable Network Roaming policies.
```

2022-03-19 07:25 UTC, JohanFreelancer9 requested changes
Copy review - @vini-gupta, kindly commit the suggested change if you agree with it. Many thanks.

2022-03-20 01:55 UTC, yogkumgit commented
@vini-gupta kindly implement the suggested changes. Thanks

2022-03-20 01:58 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-03-21 07:49 UTC, dariomws approved these changes

2022-03-21 18:04 UTC, opbld32 commented
Docs Build status updates of commit _[cb8113f](https://github.com/vini-gupta/office-docs-powershell/commits/cb8113f2579c2f7540adb3969ea8be4734f9b1a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/vini-gupta/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9131) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203211801050346-9131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-21T18%3A04%3A55Z&sr=b&sp=r&sig=IRa3i9CdAvm6V%2FvqkZHKpK7mg9bFGN4nZkXA%2BhAf%2FAs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 03:26 UTC, JohanFreelancer9 approved these changes

2022-03-22 05:24 UTC, opbld31 commented
Docs Build status updates of commit _[40d051f](https://github.com/vini-gupta/office-docs-powershell/commits/40d051f5a00be2e2b26ae35458ab3f19cd15ec52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/vini-gupta/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9131) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203220520131072-9131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-22T05%3A24%3A28Z&sr=b&sp=r&sig=i2jnb8E0C6CPtCRv8cbMUUkG8aUpQYz44hHXM2KWOgo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 13:49 UTC, yogkumgit commented
@tseward

2022-03-23 11:51 UTC, yogkumgit commented
@tseward please review

2022-03-23 21:54 UTC, tseward approved these changes

2022-03-24 13:46 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-24 17:21 UTC, opbld30 commented
Docs Build status updates of commit _[d79a92f](https://github.com/vini-gupta/office-docs-powershell/commits/d79a92f8307b7c4b26c4bd399af65f40a34fc9d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/vini-gupta/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9131) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203241718582781-9131%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-24T17%3A21%3A46Z&sr=b&sp=r&sig=QHQrXCIFQskPaI4spGBMYEphxUxQHE1lkvjXirqBXxA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-24 17:26 UTC, merged