Update Set-CsTeamsNetworkRoamingPolicy.md
MicrosoftDocs/office-docs-powershell pull request #9134
Opened 2022-03-18 19:13 UTC by vini-gupta

Update users to enable the network roaming policy for users who are not enterprise voice enabled in TeamsMeetingPolicy.

2022-03-18 19:15 UTC, opbld33 commented
Docs Build status updates of commit _[15c9367](https://github.com/vini-gupta/office-docs-powershell/commits/15c93673f06bc7efdd8b88848ae2b731f209a308)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md](https://github.com/vini-gupta/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsnetworkroamingpolicy?view=skype-ps&branch=pr-en-us-9134) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203181913310070-9134%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-18T19%3A15%3A41Z&sr=b&sp=r&sig=fWYoKjqIikg7BDvkxUJ6czYK%2FCDaTUTVJaNzLzjdRNc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-19 02:13 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-19 02:13 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-03-19 07:42 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md
> +To enable the network roaming policy for users who are not enterprise voice enabled, you must also enable the AllowNetworkConfigurationSettingsLookup setting in TeamsMeetingPolicy. This setting is of
```suggestion
To enable the network roaming policy for users who are not Enterprise Voice enabled, you must also enable the AllowNetworkConfigurationSettingsLookup setting in TeamsMeetingPolicy. This setting is off by default. See Set-TeamsMeetingPolicy for more information on how to enable AllowNetworkConfigurationSettingsLookup for users who are not Enterprise Voice enabled. 
```

2022-03-19 07:43 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md
> +To enable the network roaming policy for users who are not enterprise voice enabled, you must also enable the AllowNetworkConfigurationSettingsLookup setting in TeamsMeetingPolicy. This setting is of
Kindly insert a link to Set-TeamsMeetingPolicy if you want to refer to it.

2022-03-19 07:43 UTC, JohanFreelancer9 requested changes
Copy review - @vini-gupta, kindly commit the suggested changes. Many thanks.

2022-03-21 07:51 UTC, dariomws approved these changes

2022-03-21 14:44 UTC, get-itips approved these changes

2022-03-21 18:09 UTC, opbld32 commented
Docs Build status updates of commit _[f024fd1](https://github.com/vini-gupta/office-docs-powershell/commits/f024fd19697d039b13a9b389542e75c5f272f903)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md](https://github.com/vini-gupta/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsnetworkroamingpolicy?view=skype-ps&branch=pr-en-us-9134) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203211805120377-9134%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-21T18%3A09%3A21Z&sr=b&sp=r&sig=DRPLGKmpE%2Be1YblJk8DUzVXAkO65bFnxeEoSUxa7cKk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-21 18:12 UTC, opbld31 commented
Docs Build status updates of commit _[f024fd1](https://github.com/vini-gupta/office-docs-powershell/commits/f024fd19697d039b13a9b389542e75c5f272f903)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md](https://github.com/vini-gupta/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsnetworkroamingpolicy?view=skype-ps&branch=pr-en-us-9134) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203211805231355-9134%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-21T18%3A12%3A31Z&sr=b&sp=r&sig=O5JURWQmCrzRv3rFqFjt%2BIMncqGsVrkh%2F%2FNnBaoCWxo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-22 05:08 UTC, JohanFreelancer9 approved these changes

2022-03-22 13:50 UTC, yogkumgit commented
@tseward

2022-03-23 11:51 UTC, yogkumgit commented
@tseward please review

2022-03-23 21:55 UTC, tseward approved these changes

2022-03-24 13:48 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-24 17:55 UTC, opbld32 commented
Docs Build status updates of commit _[349cd7c](https://github.com/vini-gupta/office-docs-powershell/commits/349cd7cabeca01609eee9de273014c9d853767aa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md](https://github.com/vini-gupta/office-docs-powershell/blob/patch-4/skype/skype-ps/skype/Set-CsTeamsNetworkRoamingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsnetworkroamingpolicy?view=skype-ps&branch=pr-en-us-9134) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203241747405604-9134%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-24T17%3A55%3A44Z&sr=b&sp=r&sig=BJ3%2B9u2LNaKRnCUMM93iZUxsFgTIkIStZ6thgI9aGl0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-24 17:56 UTC, merged