Fix example 2 in Get-CsTenantFederationConfiguration.md
MicrosoftDocs/office-docs-powershell pull request #9163
Opened 2022-03-23 21:47 UTC by dariomws

Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/9062.

2022-03-23 21:50 UTC, opbld32 commented
Docs Build status updates of commit _[9cb8435](https://github.com/dariomws/office-docs-powershell/commits/9cb8435d3d4846880e9bded7294d14f3a5fb448e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsTenantFederationConfiguration.md](https://github.com/dariomws/office-docs-powershell/blob/patch-266/skype/skype-ps/skype/Get-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-9163) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203232147284893-9163%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T21%3A50%3A17Z&sr=b&sp=r&sig=Ogcoxs9E%2BrRra4ckpw3rL35saP8035MW6xarDreGcUw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-24 08:04 UTC, JohanFreelancer9 requested changes
Copy review - minor edit, please.

2022-03-24 13:54 UTC, yogkumgit commented
@dariomws

2022-03-24 14:28 UTC, get-itips approved these changes

2022-03-24 15:23 UTC, tseward approved these changes

2022-03-25 05:25 UTC, JohanFreelancer9 approved these changes

2022-03-25 12:30 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-25 15:59 UTC, opbld30 commented
Docs Build status updates of commit _[c67ab94](https://github.com/dariomws/office-docs-powershell/commits/c67ab943783cd53b7ef80d1a1754862f805cc366)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsTenantFederationConfiguration.md](https://github.com/dariomws/office-docs-powershell/blob/patch-266/skype/skype-ps/skype/Get-CsTenantFederationConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cstenantfederationconfiguration?view=skype-ps&branch=pr-en-us-9163) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C25%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202203251557306357-9163%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-25T15%3A59%3A54Z&sr=b&sp=r&sig=fn0youoFUV8UhQWmxWs8DXC3URF%2Bv7HRpjfcFj6howo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-25 16:03 UTC, merged