Update New-DlpComplianceRule.md
MicrosoftDocs/office-docs-powershell pull request #9223
Opened 2022-04-04 17:58 UTC by ybhargav1995

2022-04-04 18:01 UTC, opbld33 commented
Docs Build status updates of commit _[16778c2](https://github.com/ybhargav1995/office-docs-powershell/commits/16778c25a60b97df9c1c1dffb1a0b00170c6a152)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-DlpComplianceRule.md](https://github.com/ybhargav1995/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/New-DlpComplianceRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancerule?view=exchange-ps&branch=pr-en-us-9223) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204041758594261-9223%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T18%3A01%3A23Z&sr=b&sp=r&sig=f9kw5MhT8STzMtB3LJUnI42HUoopsbkXCJzO8RSvM8I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-04 20:27 UTC, chrisda commented
@ybhargav1995, why remove the description?

2022-04-05 05:29 UTC, ybhargav1995 commented
> @ybhargav1995, why remove the description?
Because the params FromMemberOf and ExceptIfFromMemberOf are no longer for internal use. It is available for the customers

2022-04-05 05:42 UTC, opbld32 commented
Docs Build status updates of commit _[2d762a6](https://github.com/ybhargav1995/office-docs-powershell/commits/2d762a6db1f30a5a0d0469499bfcf454217b3637)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-DlpComplianceRule.md](https://github.com/ybhargav1995/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/New-DlpComplianceRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancerule?view=exchange-ps&branch=pr-en-us-9223) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204050540092088-9223%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T05%3A42%3A30Z&sr=b&sp=r&sig=NBkEPT6Qr9Y%2Bb6PxsdDQ23Oaqrt5R2njovaRhHgDymM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 09:10 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/New-DlpComplianceRule.md
> +The ExceptIfFromMemberOf parameter specifies an exception for the DLP rule that looks for senders' email in the lists given as values to this param. You can give multiple lists to this parameter.
```suggestion
The ExceptIfFromMemberOf parameter specifies an exception for the DLP rule that looks for senders' emails in the lists given as values to this parameter. You can give multiple lists to this parameter.
```

2022-04-05 09:10 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/New-DlpComplianceRule.md
> +The FromMemberOf parameter specifies an condition for the DLP rule that looks for senders' email in the lists given as values to this param. You can give multiple lists to this parameter.
```suggestion
The FromMemberOf parameter specifies a condition for the DLP rule that looks for senders' emails in the lists given as values to this parameter. You can give multiple lists to this parameter.
```

2022-04-05 09:11 UTC, JohanFreelancer9 requested changes
Copy review - @ybhargav1995, kindly commit the suggested changes. Many thanks.

2022-04-05 09:26 UTC, opbld31 commented
Docs Build status updates of commit _[e5f5c38](https://github.com/ybhargav1995/office-docs-powershell/commits/e5f5c38b59de9ae5658129a303bacc8d7cc9ab6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-DlpComplianceRule.md](https://github.com/ybhargav1995/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/New-DlpComplianceRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancerule?view=exchange-ps&branch=pr-en-us-9223) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204050923336433-9223%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T09%3A26%3A33Z&sr=b&sp=r&sig=uqOOROdQydEGt4NcCPkpRubLsmajfh0rMx%2F5OTHVXDc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 09:29 UTC, opbld30 commented
Docs Build status updates of commit _[c8dd88c](https://github.com/ybhargav1995/office-docs-powershell/commits/c8dd88c81553f74fec399929c52c820f009ac013)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-DlpComplianceRule.md](https://github.com/ybhargav1995/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/New-DlpComplianceRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancerule?view=exchange-ps&branch=pr-en-us-9223) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204050924003272-9223%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T09%3A29%3A27Z&sr=b&sp=r&sig=whS0xMiz2%2FwQd%2FXVxjqjXM4a9BILjjrd%2BARHjKW0h4M%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 11:41 UTC, JohanFreelancer9 approved these changes

2022-04-05 16:38 UTC, opbld32 commented
Docs Build status updates of commit _[29545b1](https://github.com/ybhargav1995/office-docs-powershell/commits/29545b145d6905556b71a4c634b195f7a4ba98d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/New-DlpComplianceRule.md](https://github.com/ybhargav1995/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/New-DlpComplianceRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/new-dlpcompliancerule?view=exchange-ps&branch=pr-en-us-9223) (exchange-ps) |
[exchange/exchange-ps/exchange/Set-DlpComplianceRule.md](https://github.com/ybhargav1995/office-docs-powershell/blob/patch-2/exchange/exchange-ps/exchange/Set-DlpComplianceRule.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-dlpcompliancerule?view=exchange-ps&branch=pr-en-us-9223) (exchange-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204051635579942-9223%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T16%3A38%3A16Z&sr=b&sp=r&sig=gOgPdy01lCfr%2BjW8oa3ywwaqKg0%2FsT39OMy4GuEuoEA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 16:44 UTC, merged