Update Test-CsOnlineLisCivicAddress.md
MicrosoftDocs/office-docs-powershell pull request #9238
Opened 2022-04-05 22:58 UTC by vivekiiit

We have deprecated this cmdlet and moved the validation logic to New-CsOnlineLisCivicAddress instead. Updating the docs for the same.

2022-04-05 23:01 UTC, opbld31 commented
Docs Build status updates of commit _[1bcded1](https://github.com/vivekiiit/office-docs-powershell/commits/1bcded1e8b4b0640e878c84be78dc33482a3462a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/vivekiiit/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9238) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204052258500760-9238%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T23%3A01%3A33Z&sr=b&sp=r&sig=4dLWhqC7LfBTD9ikdi3yrnsdH%2B6pO0w9bwzZGNtvCQw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 01:51 UTC, yogkumgit commented
@JohanFreelancer9

2022-04-07 03:34 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md
> +> Please use [New-CsOnlineLisCivicAddress](New-CsOnlineLisCivicAddress.md) cmdlet instead.
```suggestion
**Note**: This cmdlet has been deprecated and is no longer supported. Use the [New-CsOnlineLisCivicAddress](New-CsOnlineLisCivicAddress.md) cmdlet instead.
```

2022-04-07 03:37 UTC, JohanFreelancer9 requested changes
Copy review - @vivekiiit, kindly commit the suggested change. Many thanks.

2022-04-07 16:30 UTC, opbld30 commented
Docs Build status updates of commit _[e20b95f](https://github.com/vivekiiit/office-docs-powershell/commits/e20b95f5d24f221ed8ca2caf100d07d99ab43bd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/vivekiiit/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9238) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204071628172664-9238%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T16%3A30%3A33Z&sr=b&sp=r&sig=HE1c%2F2MGQKa10KoWcFVhj1FrLMrUunttIUdeFrPq4uE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 16:33 UTC, opbld33 commented
Docs Build status updates of commit _[2b2daa2](https://github.com/vivekiiit/office-docs-powershell/commits/2b2daa2f5477bcfb175adfa0415f81d1e03a0e78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/vivekiiit/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9238) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204071629182853-9238%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T16%3A33%3A26Z&sr=b&sp=r&sig=O2caZaedAAll%2F%2BF1C%2FDCWp3xcfP0bYEzreFV4SbAMX8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 17:23 UTC, closed without merging