New PS cmdlet and updates to existing
MicrosoftDocs/office-docs-powershell pull request #9243
Opened 2022-04-06 09:04 UTC by JensTrier

- Adding Get-CsPhoneNumberAssignment and referencing it in Set/Remove-CsPhoneNumberAssignment
- Adding deprecation notice to Get-CsOnlineTelephoneNumber and a reference to Get-CsPhoneNumberAssignment
- Updating Import-CsOnlineAudioFile to talk about automatic marked for deletion of AA and CQ audio files
- Adding information about the exported audio format in Export-CsOnlineAudioFile

2022-04-06 09:07 UTC, opbld33 commented
Docs Build status updates of commit _[df5ab61](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/df5ab61f6e857ae492790251f1eddbe447a796bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) | [Details](#user-content-6996077f60caa23298c5a6c87c6ab029-b1e17553)
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

<a id="6996077f60caa23298c5a6c87c6ab029-b1e17553"></a>
### [skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md)
 - **Line 0, Column 0**: **[Warning: link-out-of-scope]** `````File 'skype-ps/skype/Get-CsOnlineAudioFile.md' referenced by link 'Get-CsOnlineAudioFile.md' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204060904167458-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T09%3A07%3A07Z&sr=b&sp=r&sig=9qQeICFc82Eexa9pk1KxYh1EEDl36uei9%2FCvEdDfFgg%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 09:15 UTC, opbld32 commented
Docs Build status updates of commit _[cbbff25](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/cbbff2505460a9d92f6649cb73ba4dcd88df4f91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204060912481641-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T09%3A15%3A12Z&sr=b&sp=r&sig=bJaKpPU6uYxxkM2H3ss12HJKcsCfoXVVcdcR%2FWI0kzs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 15:16 UTC, get-itips commented on skype/skype-ps/skype/Import-CsOnlineAudioFile.md
> +When you are importing an audio file to be used for Auto Attenant or Call Queue, the audio file will automatically be marked for deletion (as seen by running
```suggestion
When you are importing an audio file to be used for Auto Attendant or Call Queue, the audio file will automatically be marked for deletion (as seen by running
```

2022-04-07 15:39 UTC, opbld30 commented
Docs Build status updates of commit _[c5f4763](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/c5f47639f16a09e613b04434793ecf120c89a5af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204071537080470-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T15%3A39%3A28Z&sr=b&sp=r&sig=nIpT8p8XXs3a5U4F%2FtSQf6buvsL%2Fr8oovyUtcc467oA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 16:09 UTC, get-itips commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +If you specify only one capability, you will get all phone numbers returned that have that capability assigned. If you specify a comma seperated list for instance like
```suggestion
If you specify only one capability, you will get all phone numbers returned that have that capability assigned. If you specify a comma separated list for instance like 

```

2022-04-08 01:25 UTC, tseward approved these changes

2022-04-08 02:19 UTC, yogkumgit commented
@JohanFreelancer9 @dariomws

2022-04-08 05:11 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +Filters the returned results based on the user or resource account id the phone number is assigned to. Supported values are UserPrincipalName, SIP address and ObjectId.
```suggestion
Filters the returned results based on the user or resource account ID the phone number is assigned to. Supported values are UserPrincipalName, SIP address, and ObjectId.

```

2022-04-08 05:12 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +Filters the returned results based on the capabilities assigned to the phone number. You can specify one or more capabilities delimited by comma. Supported capabilities
```suggestion
Filters the returned results based on the capabilities assigned to the phone number. You can specify one or more capabilities delimited by a comma. Supported capabilities

```

2022-04-08 05:13 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +are ConferenceAssignment, VoiceApplicationAssignment, UserAssignment and OCMobile.
```suggestion
are ConferenceAssignment, VoiceApplicationAssignment, UserAssignment, and OCMobile.

```

2022-04-08 05:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +Filters the returned results based on the number type. Supported values are DirectRouting, CallingPlan and OperatorConnect.
```suggestion
Filters the returned results based on the number type. Supported values are DirectRouting, CallingPlan, and OperatorConnect.

```

2022-04-08 05:15 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +Filters the returned results based on the assignment status. Support values are Unassigned, UserAssigned, ConferenceAssigned, VoiceApplicationAssigned and ThirdPartyAppAssigned
```suggestion
Filters the returned results based on the assignment status. Support values are Unassigned, UserAssigned, ConferenceAssigned, VoiceApplicationAssigned, and ThirdPartyAppAssigned.

```

2022-04-08 05:15 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +Skipping the first X returned results and the default value is 0.
```suggestion
Skips the first X returned results and the default value is 0.

```

2022-04-08 05:19 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +The Id of the object the phone number is assigned to.
```suggestion
The ID of the object the phone number is assigned to.

```

2022-04-08 05:20 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +The Id of the CivicAddress assigned to the phone number.
```suggestion
The ID of the CivicAddress assigned to the phone number.

```

2022-04-08 05:20 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +The Id of the Location assigned to the phone number.
```suggestion
The ID of the Location assigned to the phone number.

```

2022-04-08 05:21 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +The Id of the PSTN partner providing the phone number.
```suggestion
The ID of the PSTN partner providing the phone number.

```

2022-04-08 05:23 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +The name of the PSTN partner
```suggestion
The name of the PSTN partner.

```

2022-04-08 05:24 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +
```suggestion
```

2022-04-08 05:26 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Import-CsOnlineAudioFile.md
> +The ApplicationId parameter is the identifier for the application which will use this audio file. For example, if the audio file will be used with an Auto Attendant, then it needs to be set to "OrgAu
```suggestion
The ApplicationId parameter is the identifier for the application which will use this audio file. For example, if the audio file will be used with an Auto Attendant, then it needs to be set to "OrgAutoAttendant". If the audio file will be used with a Call Queue, then it needs to be set to "HuntGroup". If the audio file will be used with Microsoft Teams, then it needs to be set to "TenantGlobal."
```

2022-04-08 05:26 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Import-CsOnlineAudioFile.md
> +When you are importing an audio file to be used for Auto Attendant or Call Queue, the audio file will automatically be marked for deletion (as seen by running
```suggestion
When you import an audio file to be used for Auto Attendant or Call Queue, the audio file will automatically be marked for deletion (as seen by running
```

2022-04-08 05:27 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/export-csonlineaudiofile.md
> +Therefore please ensure that the file extension used to store the content is WAV.
```suggestion
Therefore, ensure that the file extension used to store the content is WAV.
```

2022-04-08 05:28 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +This cmdlet will display information about one or more phone numbers.
```suggestion
This cmdlet displays information about one or more phone numbers.

```

2022-04-08 05:29 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +Filters the returned results based on the number type. Supported values are Activated, AssignmentPending, AssignmentFailed, UpdatePending and UpdateFailed.
```suggestion
Filters the returned results based on the number type. Supported values are Activated, AssignmentPending, AssignmentFailed, UpdatePending, and UpdateFailed.

```

2022-04-08 05:30 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +
```suggestion
```

2022-04-08 05:39 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

2022-04-08 06:08 UTC, opbld30 commented
Docs Build status updates of commit _[670b3b7](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/670b3b7c63ff4223c7be00913bd95d6eeb67c452)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080605336225-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A08%3A19Z&sr=b&sp=r&sig=ngDbZDygKeRWy8OLOH7IPxa5dbb7TnjpJPcK2aJxq9o%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:09 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

Thanks @JohanFreelancer9! Done.

2022-04-08 06:10 UTC, opbld32 commented
Docs Build status updates of commit _[1b91649](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/1b91649ae27de4a7ab279a00d9eb3242531d2478)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080608195561-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A10%3A44Z&sr=b&sp=r&sig=AjMvksRaqMfYyG7reQcKT%2BIzw0lGLYzhX8lqXxsttx4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:13 UTC, opbld31 commented
Docs Build status updates of commit _[73d9e4b](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/73d9e4b82bc963e165680fd37463cedd7baa2c4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080607116222-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A13%3A34Z&sr=b&sp=r&sig=ETarfHXoL4n4vd4ZdTBF7RPfkmWY8WLILm6S7KWqU%2BE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:16 UTC, opbld33 commented
Docs Build status updates of commit _[ad202df](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/ad202df7138d3dc57b6ce1aa3a917767dcee92eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080607514303-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A16%3A09Z&sr=b&sp=r&sig=O%2FBRZxLDptGTcpr0Ho9CMjdGIvy%2BTpEdnr3E5Dnr1Vc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:19 UTC, opbld30 commented
Docs Build status updates of commit _[5649c23](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/5649c23ded0e0c4e1334899f014491c1e873eb54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080607220899-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A19%3A02Z&sr=b&sp=r&sig=S%2ByIJ%2FIk4GVBGEgnvNVGFsoUQ5ZcSCjdD0VozvYnNnc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:21 UTC, opbld30 commented
Docs Build status updates of commit _[c9cc7ab](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/c9cc7aba119173e093b7967d0232b487de004116)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080609071283-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A21%3A47Z&sr=b&sp=r&sig=fPHIaAJRpYBGq7mzpDkO4q%2B%2B9u6q3yjIECIK6r%2BUGpg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:24 UTC, opbld32 commented
Docs Build status updates of commit _[2b505bf](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/2b505bf099b6f0f66ca3914e4c32e5172e6a86fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080608547941-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A24%3A17Z&sr=b&sp=r&sig=y5tcvJWVdghD8J3sh6Nd2NR%2BgjRck4sBu5cTL5nOQ10%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:24 UTC, dariomws approved these changes

2022-04-08 06:26 UTC, opbld33 commented
Docs Build status updates of commit _[b19abcf](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/b19abcf5832e2c2787bf8ec9c61969fb80307632)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080608323182-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A26%3A40Z&sr=b&sp=r&sig=rn4BMXOMeonn124DyJemqjRCy938PtUVjO99dtBmc40%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:29 UTC, opbld33 commented
Docs Build status updates of commit _[bf1c7bf](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/bf1c7bf53f229b3dd8f4a3a018d57abb35588ffd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080607423611-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A29%3A07Z&sr=b&sp=r&sig=mX78kA9NMn4uG2K3q8C8YCCte4E5e0UFmxpHkV%2Fu0N8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:31 UTC, opbld30 commented
Docs Build status updates of commit _[06769d8](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/06769d883f33aa33b9dfb634525835594f9902e4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080608442111-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A31%3A26Z&sr=b&sp=r&sig=%2F%2B8Fr9uxObPbv1iPgYbaim456xQKHINuO8D3doQEVt4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:37 UTC, opbld31 commented
Docs Build status updates of commit _[f931905](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/f93190527987acf773a1aa48fda4fa5d4652310a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080607005742-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A37%3A39Z&sr=b&sp=r&sig=ZDN%2BPHbRSOO3k%2FhrTXxphYt8ExO9P6VH%2B5XBqQpAOyw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:40 UTC, opbld33 commented
Docs Build status updates of commit _[febad49](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/febad49094d46efa0c325ec6aeadc79215b83910)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080606375036-9243%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T06%3A40%3A28Z&sr=b&sp=r&sig=mhBC5R6st95SeeClVqv14nzP8f8WqI1N5CQhlDvFZrY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:43 UTC, opbld32 commented
Docs Build status updates of commit _[ce8ba7d](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/ce8ba7dafa44ab57c71c101abd53cf59ff2b3940)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080606031187-9243%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T06%3A43%3A24Z&sr=b&sp=r&sig=qoDQLq8Ac%2Bq91YDGHlqSTVYRU2CXXfD5%2FjBhsbehyCs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:46 UTC, opbld33 commented
Docs Build status updates of commit _[5bcb9e0](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/5bcb9e03422bd839e7618cdc118d6bde7388439c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080606143818-9243%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T06%3A46%3A31Z&sr=b&sp=r&sig=8FB5VViD4GBAB0ut5lO3ByIF%2BszpBw%2FoxAkyK9lR5BM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:49 UTC, opbld31 commented
Docs Build status updates of commit _[75dac53](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/75dac5355ecf76a663f066f540c889f2c1120dcd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080607337528-9243%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-09T06%3A49%3A25Z&sr=b&sp=r&sig=uwoTxpcnTDQZpfSnY%2FxpkGBSaVcR%2BAdd5JwHEzZEmnI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:52 UTC, opbld33 commented
Docs Build status updates of commit _[ee323ed](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/ee323ed17bbf861f2c7821b61175ffcf02c73592)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080609156418-9243%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T06%3A52%3A04Z&sr=b&sp=r&sig=3ml3kV4a9qkIpm%2BCZGoSho6%2FqQeWi3DTq7Y1lJ7O100%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 06:55 UTC, opbld33 commented
Docs Build status updates of commit _[900e1b3](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/900e1b3c182d966449e2b353904da99800d87d7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080606258711-9243%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T06%3A55%3A06Z&sr=b&sp=r&sig=PbQ8U0PqsYtit0NyzvJlf7NIZ0PAHSnfkdcf2DI6aOw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-08 07:00 UTC, JensTrier commented
@yogkumgit please do not merge this PR until further notice by me or Michael Chan

2022-04-08 09:35 UTC, JohanFreelancer9 approved these changes

2022-04-08 12:34 UTC, opbld31 commented
Docs Build status updates of commit _[e44a062](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/e44a062c7e32adf232c06a1dbd157c4b43f8b150)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204080606493028-9243%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T12%3A34%3A01Z&sr=b&sp=r&sig=4Jcx%2BoQVU9ySVcEhssZrV9GcCh8QsLW%2BZ%2BV6dBAlKss%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-09 03:42 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-09 06:01 UTC, JensTrier commented
@tiburd @yogkumgit NO  - please do NOT merge this until you hear from me or Michael Chan

2022-04-21 07:22 UTC, opbld31 commented
Docs Build status updates of commit _[a04371a](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/a04371a1955f9a7c2e82ae263b43cffbbd0535be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204210719550619-9243%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T07%3A22%3A13Z&sr=b&sp=r&sig=B89bDwW1wSNQGJ7K5APlcqkf15EIyZTYz5e64%2ByUfzg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 07:27 UTC, opbld32 commented
Docs Build status updates of commit _[8899bd6](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/8899bd6482afb7a390be26546f739d989bdc9799)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinetelephonenumber?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/Import-CsOnlineAudioFile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Import-CsOnlineAudioFile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/import-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[skype/skype-ps/skype/export-csonlineaudiofile.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/export-csonlineaudiofile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/export-csonlineaudiofile?view=skype-ps&branch=pr-en-us-9243) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |
[teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9243) (teams-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204210725100883-9243%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T07%3A27%3A35Z&sr=b&sp=r&sig=7KMcaCX%2Fa0agFikGzuUWyi%2FdKITec25YkMHoqpV5mwo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 07:36 UTC, JensTrier commented
@tiburd please merge this PR

2022-04-21 12:18 UTC, merged