Update Get-CsAutoAttendant.md
MicrosoftDocs/office-docs-powershell pull request #9289
Opened 2022-04-14 21:47 UTC by CLYVR

Adding a note about a known issues with the -IncludeStatus

2022-04-14 21:48 UTC, CLYVR commented
@get-itips @dariomws @tseward @tiburd - Please and thanks!

2022-04-14 21:49 UTC, opbld33 commented
Docs Build status updates of commit _[807de0f](https://github.com/CLYVR/office-docs-powershell/commits/807de0fa1ba10a2431d5d6492175339ceb2eb4dc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAutoAttendant.md) | :x:Error | | [Details](#user-content-d624c345e64353910aefa0f6085c686e-bea330c8)
[skype/skype-ps/skype/Export-CsRgsConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Export-CsRgsConfiguration.yml) | :warning:Warning | | [Details](#user-content-f10df3c2e1eeb19169ee6ceff58fa951-bea330c8)
[skype/skype-ps/skype/Disable-CsComputer.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsComputer.yml) | :warning:Warning | | [Details](#user-content-60e53150ca6e0f3c60c65a82ec650bce-bea330c8)
[skype/skype-ps/skype/Debug-CsAddressBookReplication.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsAddressBookReplication.yml) | :warning:Warning | | [Details](#user-content-560eda5289c99a741f7ecaee66e88f56-bea330c8)
[skype/skype-ps/skype/Export-CsConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Export-CsConfiguration.yml) | :warning:Warning | | [Details](#user-content-39e77a9cee84400d57011cbc42513282-bea330c8)
[skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml) | :warning:Warning | | [Details](#user-content-5b0c7aa08a8a09fb612a7fcea49272cb-bea330c8)
[skype/skype-ps/skype/Disable-CsHostingProvider.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsHostingProvider.yml) | :warning:Warning | | [Details](#user-content-7890cdb6d206f8a21782c1b175110b58-bea330c8)
[skype/skype-ps/skype/Debug-CsDataConference.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsDataConference.yml) | :warning:Warning | | [Details](#user-content-76cd46aa5f2ebd3ca25c81246b53b822-bea330c8)
[skype/skype-ps/skype/Backup-CsPool.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Backup-CsPool.yml) | :warning:Warning | | [Details](#user-content-507a33032c59cd803e69bc12959acd90-bea330c8)
[skype/skype-ps/skype/Debug-CsLisConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsLisConfiguration.yml) | :warning:Warning | | [Details](#user-content-eede4467c4735fc0e75a4544463eba1c-bea330c8)
[skype/skype-ps/skype/Convert-CsUserData.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Convert-CsUserData.yml) | :warning:Warning | | [Details](#user-content-de6b735a56330198b4471e3d61072a96-bea330c8)
[skype/skype-ps/skype/Clear-CsPersistentChatRoom.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Clear-CsPersistentChatRoom.yml) | :warning:Warning | | [Details](#user-content-95b7fabb24606df45c639b89148a2a1e-bea330c8)
[skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml) | :warning:Warning | | [Details](#user-content-2989c7e3e2b6daff14a4e756123a25ca-bea330c8)
[skype/skype-ps/skype/Disable-CsUser.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsUser.yml) | :warning:Warning | | [Details](#user-content-c4eb9b3ac009422fea1774926ade20c6-bea330c8)
[skype/skype-ps/skype/Disable-CsMeetingRoom.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-fbf528d33ca281a47815a84b1ca6d38a-bea330c8)
[skype/skype-ps/skype/Enable-CsPublicProvider.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsPublicProvider.yml) | :warning:Warning | | [Details](#user-content-e0d0020b651061faa1ea3eb20cfd90d7-bea330c8)
[skype/skype-ps/skype/Get-CsAllowedDomain.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAllowedDomain.yml) | :warning:Warning | | [Details](#user-content-23d2227dece722369b94dd720a9f2bf3-bea330c8)
[skype/skype-ps/skype/Get-CsAdUser.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAdUser.yml) | :warning:Warning | | [Details](#user-content-2bb78d53cfe80f5c9e0858574bdd92b8-bea330c8)
[skype/skype-ps/skype/Get-CsAddressBookNormalizationRule.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAddressBookNormalizationRule.yml) | :warning:Warning | | [Details](#user-content-661c8af74e9ef9f260da6f8d43a90adb-bea330c8)
[skype/skype-ps/skype/Get-CsApplicationAccessPolicy.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsApplicationAccessPolicy.yml) | :warning:Warning | | [Details](#user-content-86df3068453e06ff0e0b92ed0c518108-bea330c8)
[skype/skype-ps/skype/Enable-CsComputer.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsComputer.yml) | :warning:Warning | | [Details](#user-content-1f99a67827c75608f3b97149ef5a2466-bea330c8)
[skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml) | :warning:Warning | | [Details](#user-content-b3adbc432a8402141afc7bac7adf9d9f-bea330c8)
[skype/skype-ps/skype/Enable-CsOnlineSipDomain.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsOnlineSipDomain.yml) | :warning:Warning | | [Details](#user-content-53b9316a503beb879d14014f9e39c775-bea330c8)
[skype/skype-ps/skype/Get-CsArchivingPolicy.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsArchivingPolicy.yml) | :warning:Warning | | [Details](#user-content-aaf14738eaff5b5f98da4b4685f6543a-bea330c8)
[skype/skype-ps/skype/Get-CsAVEdgeConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAVEdgeConfiguration.yml) | :warning:Warning | | [Details](#user-content-b27bc37ed225ebb73e6c5975893f917f-bea330c8)
[skype/skype-ps/skype/Enable-CsUser.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsUser.yml) | :warning:Warning | | [Details](#user-content-6b0a984aa70ff804cd024169566176a0-bea330c8)
[skype/skype-ps/skype/Enable-CsReplica.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsReplica.yml) | :warning:Warning | | [Details](#user-content-ad27758c0de7dda8f1507cad998d260f-bea330c8)
[skype/skype-ps/skype/Get-CsCertificate.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsCertificate.yml) | :warning:Warning | | [Details](#user-content-bf2da2372b66ba9749499cee80c68edc-bea330c8)
[skype/skype-ps/skype/Get-CsAnnouncement.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAnnouncement.yml) | :warning:Warning | | [Details](#user-content-1e93550ea020233d79e9c48984f7c747-bea330c8)
[skype/skype-ps/skype/Enable-CsTopology.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsTopology.yml) | :warning:Warning | | [Details](#user-content-6fb5056995de31b3f33a28a921be1cc2-bea330c8)
[skype/skype-ps/skype/Get-CsAnalogDevice.yml](https://github.com/C [...]

2022-04-14 22:22 UTC, tseward commented
@CLYVR is this issue just for v4.0.0 or v4.x+?

2022-04-14 22:24 UTC, CLYVR commented
@tseward Starts with 4.0.0 so probably better if that says v4.x+ as you've noted.

2022-04-14 22:27 UTC, CLYVR commented
@tseward Updated to say "starting with v4.0.0"

2022-04-14 22:28 UTC, opbld31 commented
Docs Build status updates of commit _[cf9060a](https://github.com/CLYVR/office-docs-powershell/commits/cf9060acd29b45f84690e0f312ccf18e50771369)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAutoAttendant.md) | :x:Error | | [Details](#user-content-d624c345e64353910aefa0f6085c686e-43a44be2)
[skype/skype-ps/skype/Enable-CsHostingProvider.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsHostingProvider.yml) | :warning:Warning | | [Details](#user-content-6bec6124fff513cb5f513d6f9379e38d-43a44be2)
[skype/skype-ps/skype/Clear-CsDeviceUpdateLog.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Clear-CsDeviceUpdateLog.yml) | :warning:Warning | | [Details](#user-content-9435c4133c7c001c8bb02be24998b63e-43a44be2)
[skype/skype-ps/skype/Debug-CsLisConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsLisConfiguration.yml) | :warning:Warning | | [Details](#user-content-eede4467c4735fc0e75a4544463eba1c-43a44be2)
[skype/skype-ps/skype/Backup-CsPool.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Backup-CsPool.yml) | :warning:Warning | | [Details](#user-content-507a33032c59cd803e69bc12959acd90-43a44be2)
[skype/skype-ps/skype/Enable-CsPublicProvider.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsPublicProvider.yml) | :warning:Warning | | [Details](#user-content-e0d0020b651061faa1ea3eb20cfd90d7-43a44be2)
[skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml) | :warning:Warning | | [Details](#user-content-2989c7e3e2b6daff14a4e756123a25ca-43a44be2)
[skype/skype-ps/skype/Clear-CsPersistentChatRoom.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Clear-CsPersistentChatRoom.yml) | :warning:Warning | | [Details](#user-content-95b7fabb24606df45c639b89148a2a1e-43a44be2)
[skype/skype-ps/skype/Clear-CsDeviceUpdateFile.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Clear-CsDeviceUpdateFile.yml) | :warning:Warning | | [Details](#user-content-39fbfdc2142b139f35bf5e5674421630-43a44be2)
[skype/skype-ps/skype/Disable-CsPublicProvider.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsPublicProvider.yml) | :warning:Warning | | [Details](#user-content-00090a0918f34d3ccf1a431d5a522e87-43a44be2)
[skype/skype-ps/skype/Enable-CsMeetingRoom.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-7f79575f4c926fb4cf859f8b0cd336b3-43a44be2)
[skype/skype-ps/skype/Enable-CsOnlineSipDomain.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsOnlineSipDomain.yml) | :warning:Warning | | [Details](#user-content-53b9316a503beb879d14014f9e39c775-43a44be2)
[skype/skype-ps/skype/Disable-CsHostingProvider.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsHostingProvider.yml) | :warning:Warning | | [Details](#user-content-7890cdb6d206f8a21782c1b175110b58-43a44be2)
[skype/skype-ps/skype/Approve-CsDeviceUpdateRule.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Approve-CsDeviceUpdateRule.yml) | :warning:Warning | | [Details](#user-content-76225584b96cc482114eb0d6ad8d35b8-43a44be2)
[skype/skype-ps/skype/Disable-CsMeetingRoom.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-fbf528d33ca281a47815a84b1ca6d38a-43a44be2)
[skype/skype-ps/skype/Debug-CsDataConference.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsDataConference.yml) | :warning:Warning | | [Details](#user-content-76cd46aa5f2ebd3ca25c81246b53b822-43a44be2)
[skype/skype-ps/skype/export-csonlineaudiofile.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/export-csonlineaudiofile.yml) | :warning:Warning | | [Details](#user-content-2b8dca861312eccc8d9afed9e8b59ed6-43a44be2)
[skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml) | :warning:Warning | | [Details](#user-content-5b0c7aa08a8a09fb612a7fcea49272cb-43a44be2)
[skype/skype-ps/skype/Disable-CsOnlineSipDomain.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsOnlineSipDomain.yml) | :warning:Warning | | [Details](#user-content-d488986015a6c8f5fd115bfe3a1bd13e-43a44be2)
[skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml) | :warning:Warning | | [Details](#user-content-b3adbc432a8402141afc7bac7adf9d9f-43a44be2)
[skype/skype-ps/skype/Get-CsAddressBookConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAddressBookConfiguration.yml) | :warning:Warning | | [Details](#user-content-0d436e28b52e7ffd9a7ac36365c517e1-43a44be2)
[skype/skype-ps/skype/Get-CsAdContact.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAdContact.yml) | :warning:Warning | | [Details](#user-content-913765819ce64beace4187ed2589e5bd-43a44be2)
[skype/skype-ps/skype/Get-CsApplicationAccessPolicy.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsApplicationAccessPolicy.yml) | :warning:Warning | | [Details](#user-content-86df3068453e06ff0e0b92ed0c518108-43a44be2)
[skype/skype-ps/skype/Get-CsArchivingConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsArchivingConfiguration.yml) | :warning:Warning | | [Details](#user-content-3721516abf0ed5136c8bcd165179b3ec-43a44be2)
[skype/skype-ps/skype/Export-CsRgsConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Export-CsRgsConfiguration.yml) | :warning:Warning | | [Details](#user-content-f10df3c2e1eeb19169ee6ceff58fa951-43a44be2)
[skype/skype-ps/skype/Get-CsAudioTestServiceApplication.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAudioTestServiceApplication.yml) | :warning:Warning | | [Details](#user-content-c6c7f2ff4670df18625fe3cb6b1875d3-43a44be2)
[skype/skype-ps/skype/Export-CsUserData.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Export-CsUserData.yml) | :warning:Warning | | [Details](#user-content-8f7fc11bbc24e12076b53255d84205d0-43a44be2)
[skype/skype-ps/skype/Get-CsAutoAttendantStatus.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAutoAttendantStatus.yml) | :warning:Warning | | [Details](#user-content-d8ee12c84ad121d894a71231099c51b7-43a44be2)
[skype/skype-ps/skype/Get-CsBackupServiceConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsBackupServiceConfiguration.yml) | :warning:Warning | | [Details](#user-content-a97a046abee6a172ae79429b82afcf03-43a44be2)
[skype/skype-ps/skype/Get-CsAllowedDomain.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAllowedDomain.yml)  [...]

2022-04-14 22:59 UTC, tseward approved these changes

2022-04-15 09:46 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsAutoAttendant.md
> +
```suggestion
**Note**: Expect slow response times when using this parameter with Teams PowerShell module starting with version 4.0.0.  Use the **-Skip** and **-First** parameters to limit the result size instead.  This issue is expected to be resolved within the next few months.
```

2022-04-15 09:47 UTC, JohanFreelancer9 requested changes
Copy review - @CLYVR, kindly commit the suggested changes. Many thanks.

2022-04-15 12:51 UTC, tiburd commented
@CLYVR 
Hi, Colin,
In case you don't know, I won't be able to merge this PR until after the error in the changed file is fixed:

> <img width="615" alt="image" src="https://user-images.githubusercontent.com/54688693/163572544-2217db11-ea6c-4d98-85ea-74267ef4eb5d.png">

If you need assistance, you can post a question in the PubOps [Ask an Admin Teams channel](https://aka.ms/askanadmin).

Thanks!

2022-04-18 16:42 UTC, opbld32 commented
Docs Build status updates of commit _[1b93172](https://github.com/CLYVR/office-docs-powershell/commits/1b93172e7b64cfd1febb4d1fac4d83c12182684b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAutoAttendant.md) | :x:Error | | [Details](#user-content-d624c345e64353910aefa0f6085c686e-02d91f7b)
[skype/skype-ps/skype/Disable-CsPublicProvider.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsPublicProvider.yml) | :warning:Warning | | [Details](#user-content-00090a0918f34d3ccf1a431d5a522e87-02d91f7b)
[skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsUnifiedContactStore.yml) | :warning:Warning | | [Details](#user-content-2989c7e3e2b6daff14a4e756123a25ca-02d91f7b)
[skype/skype-ps/skype/export-csonlineaudiofile.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/export-csonlineaudiofile.yml) | :warning:Warning | | [Details](#user-content-2b8dca861312eccc8d9afed9e8b59ed6-02d91f7b)
[skype/skype-ps/skype/Clear-CsPersistentChatRoom.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Clear-CsPersistentChatRoom.yml) | :warning:Warning | | [Details](#user-content-95b7fabb24606df45c639b89148a2a1e-02d91f7b)
[skype/skype-ps/skype/Disable-CsHostingProvider.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsHostingProvider.yml) | :warning:Warning | | [Details](#user-content-7890cdb6d206f8a21782c1b175110b58-02d91f7b)
[skype/skype-ps/skype/Debug-CsAddressBookReplication.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsAddressBookReplication.yml) | :warning:Warning | | [Details](#user-content-560eda5289c99a741f7ecaee66e88f56-02d91f7b)
[skype/skype-ps/skype/Disable-CsMeetingRoom.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-fbf528d33ca281a47815a84b1ca6d38a-02d91f7b)
[skype/skype-ps/skype/Enable-CsOnlineSipDomain.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsOnlineSipDomain.yml) | :warning:Warning | | [Details](#user-content-53b9316a503beb879d14014f9e39c775-02d91f7b)
[skype/skype-ps/skype/Clear-CsDeviceUpdateFile.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Clear-CsDeviceUpdateFile.yml) | :warning:Warning | | [Details](#user-content-39fbfdc2142b139f35bf5e5674421630-02d91f7b)
[skype/skype-ps/skype/Enable-CsMeetingRoom.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsMeetingRoom.yml) | :warning:Warning | | [Details](#user-content-7f79575f4c926fb4cf859f8b0cd336b3-02d91f7b)
[skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsIntraPoolReplication.yml) | :warning:Warning | | [Details](#user-content-5b0c7aa08a8a09fb612a7fcea49272cb-02d91f7b)
[skype/skype-ps/skype/Approve-CsDeviceUpdateRule.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Approve-CsDeviceUpdateRule.yml) | :warning:Warning | | [Details](#user-content-76225584b96cc482114eb0d6ad8d35b8-02d91f7b)
[skype/skype-ps/skype/Convert-CsUserData.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Convert-CsUserData.yml) | :warning:Warning | | [Details](#user-content-de6b735a56330198b4471e3d61072a96-02d91f7b)
[skype/skype-ps/skype/Disable-CsComputer.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsComputer.yml) | :warning:Warning | | [Details](#user-content-60e53150ca6e0f3c60c65a82ec650bce-02d91f7b)
[skype/skype-ps/skype/Disable-CsOnlineSipDomain.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsOnlineSipDomain.yml) | :warning:Warning | | [Details](#user-content-d488986015a6c8f5fd115bfe3a1bd13e-02d91f7b)
[skype/skype-ps/skype/Export-CsAutoAttendantHolidays.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Export-CsAutoAttendantHolidays.yml) | :warning:Warning | | [Details](#user-content-7459e158fde33fb015f2e0b95591953f-02d91f7b)
[skype/skype-ps/skype/Disable-CsUser.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Disable-CsUser.yml) | :warning:Warning | | [Details](#user-content-c4eb9b3ac009422fea1774926ade20c6-02d91f7b)
[skype/skype-ps/skype/Debug-CsLisConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Debug-CsLisConfiguration.yml) | :warning:Warning | | [Details](#user-content-eede4467c4735fc0e75a4544463eba1c-02d91f7b)
[skype/skype-ps/skype/Export-CsConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Export-CsConfiguration.yml) | :warning:Warning | | [Details](#user-content-39e77a9cee84400d57011cbc42513282-02d91f7b)
[skype/skype-ps/skype/Get-CsAddressBookConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAddressBookConfiguration.yml) | :warning:Warning | | [Details](#user-content-0d436e28b52e7ffd9a7ac36365c517e1-02d91f7b)
[skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAddressBookNormalizationConfiguration.yml) | :warning:Warning | | [Details](#user-content-b3adbc432a8402141afc7bac7adf9d9f-02d91f7b)
[skype/skype-ps/skype/Export-CsLisConfiguration.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Export-CsLisConfiguration.yml) | :warning:Warning | | [Details](#user-content-4311dab54afa2cdd0fdecedd521a418d-02d91f7b)
[skype/skype-ps/skype/Get-CsAddressBookNormalizationRule.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAddressBookNormalizationRule.yml) | :warning:Warning | | [Details](#user-content-661c8af74e9ef9f260da6f8d43a90adb-02d91f7b)
[skype/skype-ps/skype/Get-CsAdPrincipal.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAdPrincipal.yml) | :warning:Warning | | [Details](#user-content-152da6886e7500b9481d28f58dbfedb5-02d91f7b)
[skype/skype-ps/skype/Export-CsUserData.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Export-CsUserData.yml) | :warning:Warning | | [Details](#user-content-8f7fc11bbc24e12076b53255d84205d0-02d91f7b)
[skype/skype-ps/skype/Get-CsAdServerSchema.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAdServerSchema.yml) | :warning:Warning | | [Details](#user-content-855172a4cc425fe223fd3c34e60c505a-02d91f7b)
[skype/skype-ps/skype/Get-CsAnnouncement.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAnnouncement.yml) | :warning:Warning | | [Details](#user-content-1e93550ea020233d79e9c48984f7c747-02d91f7b)
[skype/skype-ps/skype/Clear-CsDeviceUpdateLog.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Clear-CsDeviceUpdateLog.yml) | :warning:Warning | | [Details](#user-content-9435c4133c7c001c8bb02be24998b63e-02d91f7b)
[skype/skype-ps/skype/Enable-CsReplica.yml](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Enable-CsReplica.yml) | :warning:Warning | | [Details](#user-content-ad277 [...]

2022-04-18 16:44 UTC, opbld33 commented
Docs Build status updates of commit _[9c69812](https://github.com/CLYVR/office-docs-powershell/commits/9c698124430fab019e8e533398125b3c61180701)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAutoAttendant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendant?view=skype-ps&branch=pr-en-us-9289) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204181641464405-9289%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T16%3A44%3A47Z&sr=b&sp=r&sig=CbIQbRYRvXqANHRaECjPucMFJY%2Bfrw3KKagzC0xSZFM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 02:26 UTC, tseward approved these changes

2022-04-19 07:09 UTC, dariomws approved these changes

2022-04-19 11:50 UTC, yogkumgit commented
@get-itips

2022-04-19 12:29 UTC, get-itips approved these changes
approving, but, what if we use _releases_ instead of _months_? @CLYVR

2022-04-19 15:47 UTC, CLYVR commented
@get-itips Updated to say "This issue is expected to be resolved in a future release."

2022-04-19 15:48 UTC, get-itips commented
> @get-itips Updated to say "This issue is expected to be resolved in a future release."

Awesome, thanks.

2022-04-19 15:49 UTC, opbld33 commented
Docs Build status updates of commit _[2424b52](https://github.com/CLYVR/office-docs-powershell/commits/2424b52e5ec3be577577ead7c876f99c7a9df2b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAutoAttendant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendant?view=skype-ps&branch=pr-en-us-9289) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204191547065332-9289%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T15%3A49%3A19Z&sr=b&sp=r&sig=uWJGR1jtFEY9Fokqre7qzGMyrrYP5mUVYZjSqrETs0Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 17:06 UTC, opbld31 commented
Docs Build status updates of commit _[d050ef2](https://github.com/CLYVR/office-docs-powershell/commits/d050ef2b899596c9974637dc227a780efe731c8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendant.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-11/skype/skype-ps/skype/Get-CsAutoAttendant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendant?view=skype-ps&branch=pr-en-us-9289) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204191703522640-9289%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T17%3A06%3A02Z&sr=b&sp=r&sig=jPpfcOBFWPT0U%2Br%2BHS6IrZEzqZFbLYtwc7zKx8SLtkE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 04:17 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-20 14:35 UTC, merged