Adding EnhancedEmergencyServiceDisclaimer
MicrosoftDocs/office-docs-powershell pull request #9306
Opened 2022-04-19 12:43 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/9273

2022-04-19 12:46 UTC, opbld32 commented
Docs Build status updates of commit _[1e1cebc](https://github.com/get-itips/office-docs-powershell/commits/1e1cebc1b234966ca1b31580969683b446f55162)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-382/skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9306) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204191243530761-9306%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T12%3A46%3A17Z&sr=b&sp=r&sig=sZp6Xdp7WLshum0DoYArmWXEtQXOosgeJa0iSYK34PM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 12:48 UTC, opbld33 commented
Docs Build status updates of commit _[e6a7d7c](https://github.com/get-itips/office-docs-powershell/commits/e6a7d7cad48f5fd4e68bd41c812c2f8925d08a15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-382/skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9306) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-382/skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9306) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204191246365706-9306%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T12%3A48%3A55Z&sr=b&sp=r&sig=JHs0em9xytFd98YqZR7QXygy%2FFupb3hTTMqIj5V2744%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 04:20 UTC, yogkumgit commented
@JohanFreelancer9

2022-04-20 06:52 UTC, dariomws approved these changes

2022-04-20 09:34 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
> +Allows the tenant administrator to configure a text string, which is shown at the top of the Calls app. The user can acknowledge the string by clicking on OK. The string will be shown on client resta
```suggestion
Allows the tenant administrator to configure a text string, which is shown at the top of the Calls app. The user can acknowledge the string by selecting OK. The string will be shown on client restart.
```

2022-04-20 09:34 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md
> +Allows the tenant administrator to configure a text string, which is shown at the top of the Calls app. The user can acknowledge the string by clicking on OK. The string will be shown on client resta
```suggestion
Allows the tenant administrator to configure a text string, which is shown at the top of the Calls app. The user can acknowledge the string by selecting OK. The string will be shown on client restart.
```

2022-04-20 09:34 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-20 11:34 UTC, opbld33 commented
Docs Build status updates of commit _[4583d9a](https://github.com/get-itips/office-docs-powershell/commits/4583d9a00790bfa8a8c1e54652e1aec734514b9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-382/skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9306) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-382/skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9306) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204201132459916-9306%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T11%3A34%3A57Z&sr=b&sp=r&sig=zRJk0wnamBhGcgfIr0FW3hiI5phXyBKMMHVF7%2Fw%2FIHU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 11:37 UTC, opbld32 commented
Docs Build status updates of commit _[e18c117](https://github.com/get-itips/office-docs-powershell/commits/e18c11729f4931d548800ef33db7356210d90e2b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-382/skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9306) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-382/skype/skype-ps/skype/Set-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9306) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204201132528522-9306%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T11%3A37%3A32Z&sr=b&sp=r&sig=ZoqZ4ptwWHPPgJS2CYTKAw%2FnERIgqV5nuGjYqcizweE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 12:47 UTC, JohanFreelancer9 approved these changes

2022-04-20 18:22 UTC, tseward approved these changes

2022-04-21 03:50 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-21 14:40 UTC, merged