Added LiveStreamingMode parameter to New/Set-CsTeamsMeetingPolicy.md
MicrosoftDocs/office-docs-powershell pull request #9325
Opened 2022-04-21 20:49 UTC by dariomws

Closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/9175.

The instance parameter is not available anymore in Set-.

2022-04-21 20:52 UTC, opbld32 commented
Docs Build status updates of commit _[519c9ee](https://github.com/dariomws/office-docs-powershell/commits/519c9eea84b1cdb13a842aaa8a1a6bac03672ffe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204212049387826-9325%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T20%3A52%3A07Z&sr=b&sp=r&sig=fwpxCmjmoiRmo1k1wzREB6YIaI%2F2ZqBhuAVOcVNHsZ8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 20:54 UTC, opbld32 commented
Docs Build status updates of commit _[cc76a5b](https://github.com/dariomws/office-docs-powershell/commits/cc76a5b33107fc0618b33a696baa433b393885b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204212051204081-9325%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T20%3A54%3A51Z&sr=b&sp=r&sig=szHsAV9Ka4xl5FK5ywdhPq9IoOrmKw8DVDM17KSGs5g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 03:25 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +Determines wheter you provide support for your users to stream their Teams meetings to large audiences through Real Time Messaging Protocol (RTMP).
```suggestion
Determines whether you provide support for your users to stream their Teams meetings to large audiences through Real-Time Messaging Protocol (RTMP).
```

2022-04-22 03:25 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
> +Determines wheter you provide support for your users to stream their Teams meetings to large audiences through Real Time Messaging Protocol (RTMP).
```suggestion
Determines whether you provide support for your users to stream their Teams meetings to large audiences through Real-Time Messaging Protocol (RTMP).
```

2022-04-22 03:26 UTC, JohanFreelancer9 requested changes
Copy review.

2022-04-22 09:45 UTC, yogkumgit commented
@dariomws

2022-04-22 13:38 UTC, opbld30 commented
Docs Build status updates of commit _[3a545ec](https://github.com/dariomws/office-docs-powershell/commits/3a545eceb3591f7a932d5be463850ead7ff92964)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204221336185287-9325%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T13%3A38%3A51Z&sr=b&sp=r&sig=kp1CzkJQztHn39mqb0DV5%2BFwjFPydjJI9O9mmgEGzhQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-22 13:41 UTC, opbld31 commented
Docs Build status updates of commit _[f6d2f0e](https://github.com/dariomws/office-docs-powershell/commits/f6d2f0e44bb5530d7d2d7f807304b3dc10e60b17)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C22%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204221336292029-9325%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-23T13%3A41%3A44Z&sr=b&sp=r&sig=F0V0qnQn3tdGsFGKv2cZkcThpu00fQp1HMNdmAhfFJQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-23 05:26 UTC, JohanFreelancer9 approved these changes

2022-04-23 08:27 UTC, yogkumgit commented
@get-itips @tseward

2022-04-25 00:07 UTC, tseward approved these changes

2022-04-25 11:30 UTC, yogkumgit commented
@get-itips

2022-04-25 15:33 UTC, get-itips approved these changes

2022-04-26 07:36 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-26 12:43 UTC, opbld33 commented
Docs Build status updates of commit _[e3cc255](https://github.com/dariomws/office-docs-powershell/commits/e3cc255ef2123ffb38f11bb1bb0fe356fc040ece)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/dariomws/office-docs-powershell/blob/patch-269/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9325) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C26%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204261239384339-9325%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-27T12%3A43%3A46Z&sr=b&sp=r&sig=36CjAg8tEC2eBmbhlJTGWG1S%2FJ1%2BoMnHNsqeDB0UPsY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-26 12:58 UTC, merged