Update New-CsTeamsMeetingPolicy.md
MicrosoftDocs/office-docs-powershell pull request #9370
Opened 2022-04-29 12:16 UTC by bwilsonms

Adding parameter for CART captions

2022-04-29 12:18 UTC, opbld33 commented
Docs Build status updates of commit _[2fb6c62](https://github.com/bwilsonms/office-docs-powershell/commits/2fb6c629661f1f0ad2aae907568b83a3e4864834)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/bwilsonms/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9370) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C29%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202204291216278716-9370%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-30T12%3A18%3A50Z&sr=b&sp=r&sig=i%2Bm0dEcC05OvWBOX%2Bins3ROMG8qYoEBW4JK%2BeSVenHA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-30 10:46 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-02 07:13 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +Determines whether a user can add a URL for captions from a Communicatons Access Real-Time Translation (CART) captioner for providing real time captions in meetings.
```suggestion
Determines whether a user can add a URL for captions from a Communications Access Real-Time Translation (CART) captioner for providing real-time captions in meetings.
```

2022-05-02 07:21 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md
> +- **Disabled**, if you'd like to not allow CART captions in meeting.
```suggestion
- **EnabledUserOverride**: CART captions are available by default but you can disable them.
- **DisabledUserOverride**: If you would like users to be able to use CART captions in meetings but they are disabled by default. 
- **Disabled**: If you do not want to allow CART captions in meetings.
```

2022-05-02 07:24 UTC, JohanFreelancer9 requested changes
Copy review - @bwilsonms, kindly commit the suggested changes. Many thanks.

2022-05-03 07:48 UTC, dariomws approved these changes
I'm ok after @JohanFreelancer9 suggestions.

2022-05-03 07:52 UTC, dariomws commented
Could we also apply @JohanFreelancer9 suggestions to the Set- cmdlet?

2022-05-03 11:49 UTC, yogkumgit commented
@bwilsonms

2022-05-03 11:53 UTC, opbld32 commented
Docs Build status updates of commit _[0bc9f89](https://github.com/bwilsonms/office-docs-powershell/commits/0bc9f89f0839503a5228568afa1fcdc6b81e4a21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/bwilsonms/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9370) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202205031151112381-9370%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T11%3A53%3A45Z&sr=b&sp=r&sig=XDzamjVkOMtNH9tm10QLMibjawF%2FTBFP0AGDTu9uqEM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 11:56 UTC, opbld33 commented
Docs Build status updates of commit _[3267514](https://github.com/bwilsonms/office-docs-powershell/commits/3267514df7118e33489f5a1bbfdbf4235653ef8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/bwilsonms/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9370) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202205031151452223-9370%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T11%3A56%3A29Z&sr=b&sp=r&sig=flHb4cPlC4UHF5YJVvJvWnxlokcUT3nhBLGP9nPXujI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-03 12:13 UTC, bwilsonms commented
Done thanks all I was off yesterday.

From: Yogesh Kumar ***@***.***>
Sent: Tuesday, May 3, 2022 7:50 AM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Brad Wilson ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Update New-CsTeamsMeetingPolicy.md (PR #9370)


@bwilsonms<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbwilsonms&data=05%7C01%7CBrad.Wilson%40microsoft.com%7Cf935426d73a240ea5fee08da2cfafffc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637871753796063151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Cw1RAMKdORc3s0Qr4dKxWB8gBEic2QmM3zajoR7MUOs%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-docs-powershell%2Fpull%2F9370%23issuecomment-1116009440&data=05%7C01%7CBrad.Wilson%40microsoft.com%7Cf935426d73a240ea5fee08da2cfafffc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637871753796063151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Bfj1fhbH4DL%2BP49evaod%2FXRZL2LQfA8XNNLIJpcuzTs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJVYG3BDI5T3AZ7HHR64GITVIEHFDANCNFSM5UVZOIWA&data=05%7C01%7CBrad.Wilson%40microsoft.com%7Cf935426d73a240ea5fee08da2cfafffc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637871753796063151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ghboWOEK%2BBTl%2FBCxa261Yphcyby%2BMutfxOOAVAigiJU%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2022-05-03 19:08 UTC, tseward approved these changes

2022-05-04 08:06 UTC, yogkumgit commented
@JohanFreelancer9 @get-itips

2022-05-04 12:15 UTC, JohanFreelancer9 approved these changes

2022-05-05 03:55 UTC, yogkumgit commented
@get-itips

2022-05-05 10:42 UTC, get-itips approved these changes

2022-05-06 03:44 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-06 15:17 UTC, opbld32 commented
Docs Build status updates of commit _[0c0c22c](https://github.com/bwilsonms/office-docs-powershell/commits/0c0c22cad6904157e1fd86cae12f001902814749)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md](https://github.com/bwilsonms/office-docs-powershell/blob/patch-1/skype/skype-ps/skype/New-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9370) (skype-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C6%5C3603fd28-efce-f87f-e986-fc8a694fc312%5CPullRequest%5C202205061514312058-9370%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-06T15%3A17%3A03Z&sr=b&sp=r&sig=qAVg%2FYqIPI%2B4bctXMqaxQmumQUvoAYdgr7bU5N%2F%2B1m0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-06 15:34 UTC, merged

2022-05-06 15:35 UTC, bwilsonms commented
Thanks all!

From: Tina Burden ***@***.***>
Sent: Friday, May 6, 2022 11:35 AM
To: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: Brad Wilson ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/office-docs-powershell] Update New-CsTeamsMeetingPolicy.md (PR #9370)


Merged #9370<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-docs-powershell%2Fpull%2F9370&data=05%7C01%7CBrad.Wilson%40microsoft.com%7Cc06e76959c3646d56bbf08da2f75f353%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637874480894867134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pvtTbSiP4%2BNvo8%2F3E%2FaKl5M9sMvtjKXgRDYHlUcurOs%3D&reserved=0> into main.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Foffice-docs-powershell%2Fpull%2F9370%23event-6564476460&data=05%7C01%7CBrad.Wilson%40microsoft.com%7Cc06e76959c3646d56bbf08da2f75f353%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637874480894867134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QexjrZ0zenSffHcCATgSw8ftgzEtko2iRc02VmXfZQg%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJVYG3G6QHNLCBMB24KWCR3VIU3ZNANCNFSM5UVZOIWA&data=05%7C01%7CBrad.Wilson%40microsoft.com%7Cc06e76959c3646d56bbf08da2f75f353%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637874480894867134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r4HrVVN8a65hpPnBEekkpCRhAROnYLHz5zp0R9O33wg%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>