various updates
MicrosoftDocs/office-docs-powershell pull request #9503
Opened 2022-06-03 09:31 UTC by JensTrier

Updating the following:

- New output fields from Get-CsPhoneNumberAssignment
- New example and note in Get-CsAutoAttendantHolidays
- Noted that cmdlet has been removed for Test-CsOnlineLisCivicAddress
- Updating *-CsCallingLineIdentity and *-CsOnlineLisCivicAddress with links etc
- Removing deleted parameters from New/Set-CsTeamsCallingPolicy

2022-06-03 09:34 UTC, opbld32 commented
Docs Build status updates of commit _[441566d](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/441566d9aee6a01078aaef1de3e8f03808bc63a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206030931322312-9503/BuildReport?accessString=e69145e49cb0d1824a6c58d76fbc6e61f88e198202f9495bc1af2640d5ea0a4e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 16:23 UTC, yogkumgit commented
@dariomws @get-itips @tseward

2022-06-03 16:25 UTC, yogkumgit commented
@JohanFreelancer9

2022-06-03 16:48 UTC, opbld32 commented
Docs Build status updates of commit _[f9780b9](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/f9780b98ae072aad2d8f5778f327857edb9b5bbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206031645360630-9503/BuildReport?accessString=3c2dc229c1c76f9259bb1c9388bafa13a4a65df372958670aae6f093585fd73e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 16:49 UTC, get-itips approved these changes

2022-06-03 16:51 UTC, opbld33 commented
Docs Build status updates of commit _[b370669](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/b3706697b3177c27bcdbba8466962603474937c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206031646035991-9503/BuildReport?accessString=0cbf56e3221d41b2e96caa818f04b2cf535dce304cd327d6fd2bde9322646fd3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-03 16:55 UTC, opbld32 commented
Docs Build status updates of commit _[0b2435f](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/0b2435f028e658ddd94866c9048fda78d8e7990d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206031653201720-9503/BuildReport?accessString=935af9e07208ae244bf020fdf56ad03dfe7c87338d614e51f4bcbea2f69e9fc0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 02:42 UTC, tseward approved these changes

2022-06-04 05:32 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
> +You can either a Caller ID policy to a specific user or you can set the Global policy instance.
```suggestion
You can either create a Caller ID policy for a specific user or you can set the Global policy instance.
```

2022-06-04 05:33 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
> +You can either a Caller ID policy to a specific user or you can set the Global policy instance.
@JensTrier, I am not sure about this. Please feel free to change it. However, the original line is incomplete.

2022-06-04 05:38 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
> +The Identity of the user to whom the policy is being assigned. User Identities can be specified using the user's SIP address, the user's user principal name (UPN) or,
```suggestion
The Identity of the user to whom the policy is being assigned. User Identities can be specified using the user's SIP address, the user's user principal name (UPN), or
```

2022-06-04 05:39 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
> +The Confirm switch causes the command to pause processing, and requires confirmation to proceed.
```suggestion
The Confirm switch causes the command to pause processing and requires confirmation to proceed.
```

2022-06-04 05:42 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsCallingLineIdentity.md
> +The CallingIDSubstitute parameter lets you specify an alternate Caller ID. The default value is LineUri. Supported values are Anonymous, Service, LineUri and Resource.
```suggestion
The CallingIDSubstitute parameter lets you specify an alternate Caller ID. The default value is LineUri. Supported values are Anonymous, Service, LineUri, and Resource.
```

2022-06-04 05:43 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsCallingLineIdentity.md
> +The Confirm switch causes the command to pause processing, and requires confirmation to proceed.
```suggestion
The Confirm switch causes the command to pause processing and requires confirmation to proceed. 
```

2022-06-04 05:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md
> +For example, "425 NE Smith Avenue ".
```suggestion
For example, "425 NE Smith Avenue".
```

2022-06-04 05:58 UTC, dariomws approved these changes

2022-06-04 06:04 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md
> +The sub division within the country assigned to the phone number, for example the state for US phone numbers.
```suggestion
The subdivision within the country assigned to the phone number, for example, the state for US phone numbers.

```

2022-06-04 06:06 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the few minor suggested changes. Many thanks.

2022-06-04 14:22 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the few minor suggested changes. Many thanks.

Thanks @JohanFreelancer9 & Done.

2022-06-04 14:24 UTC, opbld30 commented
Docs Build status updates of commit _[0f8d3c2](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/0f8d3c292409981c2f6efe6608fd0b6793fd6ab6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206041421049454-9503/BuildReport?accessString=4d1b161ba8f87c7fdf014baacb34cf7b9ae4a84fc88b59af7f7fedc64ec26bc2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 14:26 UTC, opbld30 commented
Docs Build status updates of commit _[d5419bc](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/d5419bceeb926110b649faa2b515cff5c0e89aca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206041421425464-9503/BuildReport?accessString=8861952b9a5cebf9db88680b7ca846ecbb64fe985be3e9b597c1ecf88f886365).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 14:29 UTC, opbld32 commented
Docs Build status updates of commit _[dea40c3](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/dea40c3da872f517a0cb580de20896c5a69f324b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206041422090264-9503/BuildReport?accessString=4d0768255c75d62cd204eabc9be9f26fa3f1886bf03423b8ea139f57b05dbf45).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 14:32 UTC, opbld31 commented
Docs Build status updates of commit _[35268a3](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/35268a39e9f98b263977f323d77d438e03ee4b12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206041421595499-9503/BuildReport?accessString=2cbc1e85dc1c8d85f66ed009a2d41d07b4692b25d157a6f6589c9ab666895b05).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 14:35 UTC, opbld31 commented
Docs Build status updates of commit _[e9a354a](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/e9a354aef92b57d599ecf8167621816ac7fc493f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206041421505863-9503/BuildReport?accessString=8c78aaa5484168b3c38093f4365995d9240a7a76fb04ef63c956ae763eac547a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 14:38 UTC, opbld31 commented
Docs Build status updates of commit _[67a6aa7](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/67a6aa71110d982b6827965f71dac9e599880de5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206041421228264-9503/BuildReport?accessString=f339cd9d7c36a2936f1742ee8b2ff39883a1d48eeb6af8ba0dea3b4f43d87d15).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-04 14:40 UTC, opbld30 commented
Docs Build status updates of commit _[fdaa407](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/fdaa40760198d3a27ea55239177c78d8d5bc44d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsAutoAttendantHolidays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csautoattendantholidays?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Get-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Remove-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/skype/skype-ps/skype/Test-CsOnlineLisCivicAddress.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/test-csonlineliscivicaddress?view=skype-ps&branch=pr-en-us-9503) (skype-ps) |
[teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/GetPNAUpdate/teams/teams-ps/teams/Get-CsPhoneNumberAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csphonenumberassignment?view=teams-ps&branch=pr-en-us-9503) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206041421333266-9503/BuildReport?accessString=d4f9b0a66fea6e3e742a7489da6588df22c5c3290fb7c280fc82a589f18f360d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-05 08:20 UTC, JohanFreelancer9 approved these changes

2022-06-06 02:04 UTC, tseward approved these changes

2022-06-06 05:14 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-06-06 16:59 UTC, merged