Documentation for New/Get/Remove-CsHybridTelephoneNumber
MicrosoftDocs/office-docs-powershell pull request #9604
Opened 2022-06-29 11:39 UTC by JensTrier

Adding documentation for GCCH and DOD only cmdlets.

2022-06-29 11:42 UTC, opbld30 commented
Docs Build status updates of commit _[4869139](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/4869139548afdda86d09dcd2d314ff6537bf5194)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/New-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/New-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206291139532026-9604/BuildReport?accessString=71a5902f696346aa897b66da4b0fb8e7b65d5b36ee43443e4e4488c615b086f7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 07:27 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
> +Returned results are sorted by TelephoneNumber in ascending order.
```suggestion
Returned results are sorted by telephone number in ascending order.

```

2022-06-30 07:28 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
> +This example displays information about all hybrid telephone phone numbers in the tenant. Note that O365Region, TargetType and UserId will not be populated.
```suggestion
This example displays information about all hybrid telephone numbers in the tenant. Note that O365Region, TargetType, and UserId will not be populated.

```

2022-06-30 07:29 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
> +Filters the returned results to a specific phone number. The number should be specified without a prefixed "+". The phone number can not have "tel:" prefixed.
```suggestion
Filters the returned results to a specific phone number. The number should be specified without a prefixed "+". The phone number cannot have "tel:" prefixed.

```

2022-06-30 07:34 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsHybridTelephoneNumber.md
> +
```suggestion

```

2022-06-30 07:37 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md
> +
```suggestion

```

2022-06-30 07:40 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

2022-06-30 07:41 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
> +
```suggestion

```

2022-06-30 07:43 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

Thanks @JohanFreelancer9 & done!

2022-06-30 07:44 UTC, opbld33 commented
Docs Build status updates of commit _[17956bd](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/17956bd7e7eed191c5c8d61c5c5489225920969c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/New-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/New-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206300742173392-9604/BuildReport?accessString=eaadc97a50a36742fdc3c97927ccbcefbdf28a449915e124069bc30edf6e2415).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 07:45 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md
> +
```suggestion

```

2022-06-30 07:46 UTC, JohanFreelancer9 requested changes
Apologies @JensTrier, one more, please.

2022-06-30 07:47 UTC, JohanFreelancer9 approved these changes

2022-06-30 07:47 UTC, opbld31 commented
Docs Build status updates of commit _[e4449e9](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/e4449e9ec091ba9651af91f0560879a0add0358e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/New-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/New-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206300742587955-9604/BuildReport?accessString=c63e9499c18c448b2ec5cecd334221898f1fef473c792bc02115ea408c0532ca).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 07:50 UTC, opbld32 commented
Docs Build status updates of commit _[23be10b](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/23be10bc31e56329dcbc6aa811cee28da8e3df14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/New-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/New-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206300742390888-9604/BuildReport?accessString=4870427d4977adc90d38317b3083833e13661658f8919e103bc8d467f115a6e6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 07:53 UTC, opbld33 commented
Docs Build status updates of commit _[535774c](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/535774cf9cc4aaad2a6bd117d1bad76daa9a6406)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/New-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/New-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206300743138038-9604/BuildReport?accessString=b74db67c0341815f826eb041998955a6db1119d716eb33bc9a481dac52da3077).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 07:56 UTC, opbld33 commented
Docs Build status updates of commit _[73bc3a1](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/73bc3a1850ca46aefe2acb2d1bfef5a6e0b1010e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/New-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/New-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206300746187968-9604/BuildReport?accessString=ac5a57d0048722b17fdd72823c9c5119e8a0bea74e699911d1a952504d10fe24).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 07:58 UTC, opbld33 commented
Docs Build status updates of commit _[cd4f7d5](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/cd4f7d531c2afe5f7ac7ab62edd3998038167a37)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Get-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/New-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/New-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |
[teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrHybridTelephoneNumber/teams/teams-ps/teams/Remove-CsHybridTelephoneNumber.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-cshybridtelephonenumber?view=teams-ps&branch=pr-en-us-9604) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202206300742495995-9604/BuildReport?accessString=d3f87e0f61dd15089ebaa480a17ca4e77a11e7161a51ac1cc7655133b175e71d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-30 09:57 UTC, yogkumgit commented
@get-itips @tseward

2022-06-30 17:25 UTC, tseward approved these changes

2022-06-30 17:38 UTC, merged