Adding Example 2 to illustrate NotificationGroup parameter
MicrosoftDocs/office-docs-powershell pull request #9654
Opened 2022-07-11 17:11 UTC by DEberhardt

Set-CsTeamsEmergencyCallingPolicy has a good example on how to use the NotificationGroup parameter.
Copying this example here as Example 2

Addresses #9653

2022-07-11 17:14 UTC, opbld31 commented
Docs Build status updates of commit _[4b58e6b](https://github.com/DEberhardt/office-docs-powershell/commits/4b58e6b90e67c1ed197a2f3a241008cc7bafaa3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md](https://github.com/DEberhardt/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9654) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207111711534468-9654/BuildReport?accessString=68d7ef1b39d263d84c59c445b4aa99d84d1472709acde7447273410afcadb26c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-12 04:51 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
>   This example creates a Teams Emergency Calling policy that has a identity of testECP, where a notification group and number is being defined, the external location lookup mode is enabled and also th
```suggestion
 This example creates a Teams Emergency Calling policy that has an identity of testECP, where a notification group and number are being defined, the external location lookup mode is enabled and also the type of notification.
```

2022-07-12 04:52 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md
> + This example creates a Teams Emergency Calling policy that has a identity of testECP2, with default settings except for the Notification Group. This parameter expects a single string with all users
```suggestion
 This example creates a Teams Emergency Calling policy that has an identity of testECP2, with default settings except for the Notification Group. This parameter expects a single string with all users and groups separated with ";".
```

2022-07-12 04:52 UTC, JohanFreelancer9 requested changes
Copy review - @DEberhardt, kindly commit the suggested changes. Many thanks.

2022-07-13 13:50 UTC, opbld32 commented
Docs Build status updates of commit _[4efc61c](https://github.com/DEberhardt/office-docs-powershell/commits/4efc61ca3a213c458583defb07966cc11c02fda7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md](https://github.com/DEberhardt/office-docs-powershell/blob/patch-5/skype/skype-ps/skype/New-CsTeamsEmergencyCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamsemergencycallingpolicy?view=skype-ps&branch=pr-en-us-9654) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207131348195782-9654/BuildReport?accessString=1457f9937291dc320813ad471af7a07354ff6f34ea31ab0f4c8d10e47a63b058).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-14 05:43 UTC, yogkumgit commented
@JohanFreelancer9

2022-07-14 07:12 UTC, JohanFreelancer9 approved these changes

2022-07-15 11:23 UTC, yogkumgit commented
@get-itips @dariomws @tseward

2022-07-15 11:34 UTC, dariomws approved these changes

2022-07-15 12:24 UTC, get-itips approved these changes

2022-07-18 05:09 UTC, yogkumgit commented
@tseward

2022-07-20 07:09 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-07-20 14:36 UTC, merged