Update to support Grant to Group syntax
MicrosoftDocs/office-docs-powershell pull request #9675
Opened 2022-07-14 13:17 UTC by JensTrier

Updating some Grant PS cmdlet pages to show grant to group syntax.

2022-07-18 06:23 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-07-18 06:26 UTC, yogkumgit commented
@JohanFreelancer9

2022-07-18 08:14 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
> +Use the `Grant-CsCallingLineIdentity` cmdlet to apply a Caller ID policy to a user account, to a group of users or set the tenant Global instance.
```suggestion
Use the `Grant-CsCallingLineIdentity` cmdlet to apply a Caller ID policy to a user account, to a group of users, or to set the tenant Global instance.
```

2022-07-18 08:15 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsCallingLineIdentity.md
> +You can either assign a Caller ID policy to a specific user, to a group of users or you can set the Global policy instance.
```suggestion
You can either assign a Caller ID policy to a specific user, to a group of users, or you can set the Global policy instance.
```

2022-07-18 08:18 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsDialoutPolicy.md
> +Use the `Grant-CsDialoutPolicy` cmdlet to assign the tenant global, a group of users or a per-user outbound calling restriction policy to one or more users.
```suggestion
Use the `Grant-CsDialoutPolicy` cmdlet to assign the tenant global, a group of users, or a per-user outbound calling restriction policy to one or more users.
```

2022-07-18 08:18 UTC, dariomws approved these changes

2022-07-18 08:20 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsDialoutPolicy.md
> +This parameter set the tenant global policy instance. This is the policy that all users in the tenant will get, unless they have a specific policy instance assigned.
```suggestion
This parameter sets the tenant global policy instance. This is the policy that all users in the tenant will get unless they have a specific policy instance assigned.
```

2022-07-18 08:21 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md
> +Assigns a per-user online voice routing policy to one user, a group of users or sets the Global policy instance. Online voice routing policies manage online PSTN usages for Phone System users.
```suggestion
Assigns a per-user online voice routing policy to one user, a group of users, or sets the Global policy instance. Online voice routing policies manage online PSTN usages for Phone System users.
```

2022-07-18 08:25 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md
> +Indicates the Identity of the user account to be assigned the per-user online voice routing policy. User Identities can be specified using one of the following formats: 1) the user's SIP address; 2)
```suggestion
Indicates the Identity of the user account to be assigned the per-user online voice routing policy. User Identities can be specified using one of the following formats: the user's SIP address, the user's user principal name (UPN), or the user's Active Directory display name (for example, Ken Myer).
```

2022-07-18 08:27 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md
> +"Name" of the policy to be assigned. The PolicyName is simply the policy Identity minus the policy scope (the "tag:" prefix). For example, a policy with the Identity tag:Redmond has a PolicyName equa
```suggestion
Name of the policy to be assigned. The PolicyName is simply the policy Identity minus the policy scope (the "tag:" prefix). For example, a policy with the Identity tag:Redmond has a PolicyName equal to Redmond; likewise, a policy with the Identity tag:RedmondOnlineVoiceRoutingPolicy has a PolicyName equal to RedmondOnlineVoiceRoutingPolicy.
```

2022-07-18 08:31 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md
> +Assigns an online voice mail policy to a user account, to a group of users or set the tenant Global instance. Online voicemail policies manage usages for Voicemail service.
```suggestion
Assigns an online voicemail policy to a user account, to a group of users, or set the tenant Global instance. Online voicemail policies manage usages for Voicemail service.
```

2022-07-18 08:31 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md
> +This cmdlet assigns an existing user-specific online voicemail policy to a user, a group of users or the Global policy instance.
```suggestion
This cmdlet assigns an existing user-specific online voicemail policy to a user, a group of users, or the Global policy instance.
```

2022-07-18 08:39 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md
> +The User Id of the user to whom the policy is being assigned.
```suggestion
The User ID of the user to whom the policy is being assigned.
```

2022-07-18 08:41 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md
> +"Name" of the policy to be assigned. The PolicyName is simply the policy Identity minus the policy scope ("tag:"). For example, a policy that has the Identity tag:Redmond has a PolicyName equal to Re
```suggestion
Name of the policy to be assigned. The PolicyName is simply the policy Identity minus the policy scope ("tag:"). For example, a policy that has the Identity tag:Redmond has a PolicyName equal to Redmond; a policy with the Identity tag:RedmondConferencingPolicy has a PolicyName equal to RedmondConferencingPolicy.
```

2022-07-18 08:41 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md
> +If you set PolicyName to a null value, then the command will unassign any per-user policy assigned to the user.
```suggestion
If you set PolicyName to a null value, the command will unassign any per-user policy assigned to the user. 
```

2022-07-18 08:43 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md
>  For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see about_CommonParameters(https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-07-18 08:45 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
> +Cmdlet to assign a specific Teams Calling Policy to a user, a group of users or sets the Global policy instance.
```suggestion
Assigns a specific Teams Calling Policy to a user, a group of users, or sets the Global policy instance.
```

2022-07-18 08:46 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
> +The Teams Calling Policies designate how users are able to use calling functionality within Microsoft Teams. This cmdlet allows admins to grant user level policies to individual users, to members of
```suggestion
The Teams Calling Policies designate how users are able to use calling functionality within Microsoft Teams. This cmdlet allows admins to grant user level policies to individual users, to members of a group, or to set the Global policy instance.
```

2022-07-18 08:54 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTenantDialPlan.md
> +Use the Grant-CsTenantDialPlan cmdlet to assign an existing tenant dial plan to a user, to a group of users or sets the Global policy instance.
```suggestion
Use the Grant-CsTenantDialPlan cmdlet to assign an existing tenant dial plan to a user, to a group of users, or to set the Global policy instance.
```

2022-07-18 08:55 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTenantDialPlan.md
> +The Grant-CsTenantDialPlan cmdlet assigns an existing tenant dial plan to a user, a group of users or sets the Global policy instance.
```suggestion
The Grant-CsTenantDialPlan cmdlet assigns an existing tenant dial plan to a user, a group of users, or sets the Global policy instance.
```

2022-07-18 08:59 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

2022-07-18 09:15 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsDialoutPolicy.md
>  This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-07-18 09:16 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md
>  For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-07-18 09:18 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md
>  For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-07-18 09:20 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md
>  For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable.
For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-07-18 09:33 UTC, opbld32 commented
Docs Build status updates of commit _[cd13786](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/cd13786a51d2a78cf1d00a5f83f02cabebf3351c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsDialoutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsDialoutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csdialoutpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoicemailpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallholdpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallparkpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTenantDialPlan.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTenantDialPlan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cstenantdialplan?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207180931179552-9675/BuildReport?accessString=1027ea44473dcf3d9734bceb9eee5a7768fae1084eb0824045ed4fd7ecdbbaeb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 09:36 UTC, opbld33 commented
Docs Build status updates of commit _[ca77f8d](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/ca77f8d7e7ae14392d2693ad9591baa470cf3c00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsDialoutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsDialoutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csdialoutpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoicemailpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallholdpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallparkpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTenantDialPlan.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTenantDialPlan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cstenantdialplan?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207180933180358-9675/BuildReport?accessString=e8530cf887f0410ea383df4eb5fe006def7a390eba37225d63516dcda2d7c1e6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 09:37 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the suggested changes. Many thanks.

Thanks! & done :-)

2022-07-18 09:39 UTC, opbld30 commented
Docs Build status updates of commit _[12374ac](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/12374ac45d98d18aa3bb3b68fb1ec7daf2b6fc80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsDialoutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsDialoutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csdialoutpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoicemailpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallholdpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallparkpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTenantDialPlan.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTenantDialPlan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cstenantdialplan?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207180934273774-9675/BuildReport?accessString=92a01551ef6b69c03ebfc0ba8db8a5697bf9d1328529370441751690c9aec2a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 09:41 UTC, opbld32 commented
Docs Build status updates of commit _[b695f3a](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/b695f3a38a3c94ac84bf47599e61dc66d9881cd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Grant-CsCallingLineIdentity.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsCallingLineIdentity.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cscallinglineidentity?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsDialoutPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsDialoutPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csdialoutpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsOnlineVoicemailPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoicemailpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallHoldPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallholdpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTeamsCallParkPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csteamscallparkpolicy?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |
[skype/skype-ps/skype/Grant-CsTenantDialPlan.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensTrGrantToGroup/skype/skype-ps/skype/Grant-CsTenantDialPlan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-cstenantdialplan?view=skype-ps&branch=pr-en-us-9675) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207180936204883-9675/BuildReport?accessString=3aad2b269133597af67824333f13f851a8fbbac6295ceef93bdcf24dd680bec4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-18 11:56 UTC, get-itips approved these changes

2022-07-19 05:44 UTC, yogkumgit commented
@tseward

2022-07-20 07:13 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-07-20 15:24 UTC, merged