add note
MicrosoftDocs/office-docs-powershell pull request #9676
Opened 2022-07-14 13:21 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/9465

2022-07-14 13:23 UTC, opbld33 commented
Docs Build status updates of commit _[495b7c7](https://github.com/get-itips/office-docs-powershell/commits/495b7c7127b008775310520aa63390715f644267)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/get-itips/office-docs-powershell/blob/patch-387/skype/skype-ps/skype/Move-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps&branch=pr-en-us-9676) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207141321179750-9676/BuildReport?accessString=69ca21838aae879b4cfe0e9647ff66c8482aaa10afbaaf9a1f5496d286d2998d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-15 07:57 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Move-CsUser.md
> +- If you receive an error while running this cmdlet about multiple federated edge pools, Skype for Business Federation can only be enabled for a single Edge pool. If you have multiple Edge pools, sel
```suggestion
- If you receive an error while running this cmdlet about multiple federated Edge pools, Skype for Business Federation can only be enabled for a single Edge pool. If you have multiple Edge pools, select one to use as the federating Edge pool.
```

2022-07-15 07:57 UTC, JohanFreelancer9 requested changes
Copy review.

2022-07-15 12:00 UTC, yogkumgit commented
@get-itips

2022-07-15 12:28 UTC, opbld31 commented
Docs Build status updates of commit _[367eb40](https://github.com/get-itips/office-docs-powershell/commits/367eb40ca0bc8face971850609fe0c4a611cece3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Move-CsUser.md](https://github.com/get-itips/office-docs-powershell/blob/patch-387/skype/skype-ps/skype/Move-CsUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/move-csuser?view=skype-ps&branch=pr-en-us-9676) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207151225156602-9676/BuildReport?accessString=1a6f974b803f010a5868a39828bfe1604992f984b381f54cbc1d4defd4377a77).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-15 13:05 UTC, dariomws approved these changes

2022-07-15 16:22 UTC, JohanFreelancer9 approved these changes

2022-07-18 05:10 UTC, yogkumgit commented
@tseward

2022-07-20 07:14 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-07-20 15:26 UTC, merged