Various updates to blocked numbers cmdlet
MicrosoftDocs/office-docs-powershell pull request #9717
Opened 2022-07-25 14:52 UTC by JensTrier

Various updates to blocked numbers cmdlet.

2022-07-25 14:55 UTC, opbld30 commented
Docs Build status updates of commit _[afb5fce](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/afb5fce6ca2a0ccb15beaa910a88476d4477d2d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207251452320079-9717/BuildReport?accessString=0bd82086a1a8914676fa0f16295899655a12d533ed99a2f4a338206e85cd898e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 04:35 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md
> +This returns the exempt number patterns with Identity starting with Exempt.
```suggestion
This example returns the exempt number patterns with Identity starting with Exempt.

```

2022-07-26 04:53 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the minor suggested change. Many thanks.

2022-07-26 05:13 UTC, yogkumgit commented
@get-itips @dariomws @tseward

2022-07-26 05:43 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the minor suggested change. Many thanks.

@JohanFreelancer9 thanks & done!

2022-07-26 05:44 UTC, opbld32 commented
Docs Build status updates of commit _[09c8b28](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/09c8b28aaf348a7361e29cfbe42020d79cb88111)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207260542413692-9717/BuildReport?accessString=39c8e6fe94708aa5a4428f94279fa24323b1aa1c73d99aca7a36a33f889ffecc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 10:35 UTC, dariomws requested changes

2022-07-26 10:35 UTC, dariomws commented on skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md
> +Remove-CsInboundBlockedNumberPattern [-Identity] <string> [-WhatIf] [-Confirm] [<CommonParameters>]
```suggestion
Remove-CsInboundExemptNumberPattern [-Identity] <string> [-WhatIf] [-Confirm] [<CommonParameters>]
```

I think there is a typo here.

2022-07-26 12:33 UTC, get-itips approved these changes
I am ok once @dariomws suggestion is applied

2022-07-26 13:56 UTC, JohanFreelancer9 approved these changes

2022-07-26 15:55 UTC, JensTrier commented on skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md
> +Remove-CsInboundBlockedNumberPattern [-Identity] <string> [-WhatIf] [-Confirm] [<CommonParameters>]
> I think there is a typo here.

@dariomws Thanks!

2022-07-26 15:56 UTC, opbld33 commented
Docs Build status updates of commit _[e2d9e6b](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/e2d9e6bac98a7f09f8ec7169e64854a65e687d10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207261553397648-9717/BuildReport?accessString=2dd5137862c9e3654517d99729b5dd255128201a3a4ccfc7af16af3e5ebe719e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-26 16:34 UTC, dariomws approved these changes

2022-07-27 02:24 UTC, tseward requested changes

2022-07-27 02:24 UTC, tseward commented on skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md
>  PS C:> Get-CsInboundBlockedNumberPattern
The prompt should be ```PS>``` per https://docs.microsoft.com/en-us/powershell/scripting/community/contributing/powershell-style-guide?view=powershell-7.2#avoid-using-powershell-prompts-in-examples.

2022-07-27 02:24 UTC, tseward commented on skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md
> +PS C:> Get-CsInboundBlockedNumberPattern -Filter Block*
Another where the prompt should be ```PS>```.

2022-07-27 02:24 UTC, tseward commented on skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md
> +Get-CsInboundExemptNumberPattern -Filter "Exempt*"
Add ```PS>``` to the example.

2022-07-27 02:30 UTC, yogkumgit commented
@JensTrier

2022-07-27 06:51 UTC, opbld31 commented
Docs Build status updates of commit _[17fdda9](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/17fdda93bc07d67b12901b994e80989ac59df25d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207270648526908-9717/BuildReport?accessString=b0a66dee012bf7f508eb6c87cbdabf3d51677494125f0a21548a30340d1cb743).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 06:52 UTC, JensTrier commented
@tseward thanks! I updated the examples.

2022-07-27 06:55 UTC, opbld32 commented
Docs Build status updates of commit _[02dcf8c](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/02dcf8ca559598589c861e719960431f94b85369)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Get-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/New-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Remove-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundBlockedNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundblockednumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |
[skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JensBlockedNumbers/skype/skype-ps/skype/Set-CsInboundExemptNumberPattern.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csinboundexemptnumberpattern?view=skype-ps&branch=pr-en-us-9717) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202207270650287160-9717/BuildReport?accessString=17f3b0b6c36afeda94edc87571a282dd4d80b6b5a141f8b4eba62e748dd838b5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-27 15:33 UTC, tseward approved these changes

2022-07-28 02:17 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-07-28 16:09 UTC, merged