Fix teamsMediaLoggingPolicy related links
MicrosoftDocs/office-docs-powershell pull request #9744
Opened 2022-08-01 18:35 UTC by LeoKuhorev

Fix related links for teamsMediaLoggingPolicy cmdlets

2022-08-01 18:37 UTC, opbld30 commented
Docs Build status updates of commit _[17d99ff](https://github.com/LeoKuhorev/office-docs-powershell/commits/17d99ff3ef0835d459a3c3967a46c2109138fe9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md](https://github.com/LeoKuhorev/office-docs-powershell/blob/leokukharau/fixPublicDocsLink/teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsmedialoggingpolicy?view=teams-ps&branch=pr-en-us-9744) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md](https://github.com/LeoKuhorev/office-docs-powershell/blob/leokukharau/fixPublicDocsLink/teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamsmedialoggingpolicy?view=teams-ps&branch=pr-en-us-9744) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208011835237247-9744/BuildReport?accessString=d26ba690c4cd30f843993c768c204861f991e9f5a5373955df00a5b13cc6ed51).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-01 18:40 UTC, opbld32 commented
Docs Build status updates of commit _[9dcf2fa](https://github.com/LeoKuhorev/office-docs-powershell/commits/9dcf2fac56c7e812c25903e3444c07510aa20664)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md](https://github.com/LeoKuhorev/office-docs-powershell/blob/leokukharau/fixPublicDocsLink/teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsmedialoggingpolicy?view=teams-ps&branch=pr-en-us-9744) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md](https://github.com/LeoKuhorev/office-docs-powershell/blob/leokukharau/fixPublicDocsLink/teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamsmedialoggingpolicy?view=teams-ps&branch=pr-en-us-9744) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208011837335372-9744/BuildReport?accessString=3fb2bae5e749cc72d814dd385303ad5bc1d7d0df97d1413f9399ec35d5c18200).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-02 08:31 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md
> +[Grant-CsTeamsMediaLoggingPolicy](https://docs.microsoft.com/en-us/powershell/module/teams/grant-csteamsmedialoggingpolicy)
```suggestion
[Grant-CsTeamsMediaLoggingPolicy](/powershell/module/teams/grant-csteamsmedialoggingpolicy)
```

2022-08-02 08:33 UTC, JohanFreelancer9 requested changes
Copy review - @LeoKuhorev, kindly commit the suggested changes to change the links to relative links. Many thanks.

2022-08-02 11:47 UTC, get-itips approved these changes
I am ok after @JohanFreelancer9 suggestions applied

2022-08-02 13:02 UTC, dariomws approved these changes

2022-08-02 17:55 UTC, LeoKuhorev commented on teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md
> +[Get-CsTeamsMediaLoggingPolicy](https://docs.microsoft.com/en-us/powershell/module/teams/get-csteamsmedialoggingpolicy)
Thanks for the suggestion, applied!

2022-08-02 17:57 UTC, opbld33 commented
Docs Build status updates of commit _[4e19b87](https://github.com/LeoKuhorev/office-docs-powershell/commits/4e19b87cccdab0f4fa05baea2e6a537363d4c7ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md](https://github.com/LeoKuhorev/office-docs-powershell/blob/leokukharau/fixPublicDocsLink/teams/teams-ps/teams/Get-CsTeamsMediaLoggingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsmedialoggingpolicy?view=teams-ps&branch=pr-en-us-9744) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md](https://github.com/LeoKuhorev/office-docs-powershell/blob/leokukharau/fixPublicDocsLink/teams/teams-ps/teams/Grant-CsTeamsMediaLoggingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamsmedialoggingpolicy?view=teams-ps&branch=pr-en-us-9744) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208021754331776-9744/BuildReport?accessString=ced306d14e35f7af9c8745b0dc90a77c8a3e340e43a45fcd5ac8169da5b11c8d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 06:56 UTC, JohanFreelancer9 approved these changes

2022-08-04 12:27 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-04 15:24 UTC, merged