remove note
MicrosoftDocs/office-docs-powershell pull request #9747
Opened 2022-08-02 12:58 UTC by get-itips

confirmed with PM and in lab that at least one of the parameters (EnablePrivacyMode) has effect in Teams

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9104

2022-08-02 13:01 UTC, opbld32 commented
Docs Build status updates of commit _[e78d7e8](https://github.com/get-itips/office-docs-powershell/commits/e78d7e8bdfc2deb7c6a434b261158d8da75d1e9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsPrivacyConfiguration.md](https://github.com/get-itips/office-docs-powershell/blob/patch-391/skype/skype-ps/skype/Set-CsPrivacyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csprivacyconfiguration?view=skype-ps&branch=pr-en-us-9747) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208021258171359-9747/BuildReport?accessString=ee7e13d04f2ab8e9caa9cca0374ccb747761ee546854a9e8f1058b14c4fcf5c4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 05:23 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsPrivacyConfiguration.md
```suggestion
```

2022-08-03 05:23 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-03 11:16 UTC, yogkumgit commented
@get-itips

2022-08-03 12:01 UTC, opbld33 commented
Docs Build status updates of commit _[d1bab26](https://github.com/get-itips/office-docs-powershell/commits/d1bab26cce8a2b645b209c51e60f855d5b4b82a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsPrivacyConfiguration.md](https://github.com/get-itips/office-docs-powershell/blob/patch-391/skype/skype-ps/skype/Set-CsPrivacyConfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csprivacyconfiguration?view=skype-ps&branch=pr-en-us-9747) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208031159026685-9747/BuildReport?accessString=a81220c3c11b0e67bfeca579296485d2ad7b192e017dbf11c85467b44cf87478).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-03 13:39 UTC, dariomws reviewed
Does anything else in this cmdlet work for Teams?

If not, maybe we should change the note to "Only EnablePrivacyMode for federated users works for Teams".

2022-08-03 13:45 UTC, JohanFreelancer9 approved these changes

2022-08-03 17:09 UTC, tseward approved these changes

2022-08-04 12:23 UTC, yogkumgit commented
@get-itips

2022-08-04 12:29 UTC, get-itips commented
> Does anything else in this cmdlet work for Teams?
> 
> If not, maybe we should change the note to "Only EnablePrivacyMode for federated users works for Teams".

waiting on some confirmations for now i would just remove the note

2022-08-04 12:56 UTC, dariomws approved these changes

2022-08-05 15:15 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-05 17:35 UTC, merged