add missing parameters
MicrosoftDocs/office-docs-powershell pull request #9786
Opened 2022-08-11 17:34 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/9771

2022-08-11 17:37 UTC, opbld30 commented
Docs Build status updates of commit _[c1cd448](https://github.com/get-itips/office-docs-powershell/commits/c1cd448ea0a0afcc5dc227ade9de235175f7db62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-392/skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamschannelspolicy?view=skype-ps&branch=pr-en-us-9786) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208111734150013-9786/BuildReport?accessString=48317b72022d293783fdabe22e0356c0f5cf48964d9bd063fdebba8f9f656b7f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-11 17:39 UTC, opbld30 commented
Docs Build status updates of commit _[936e12f](https://github.com/get-itips/office-docs-powershell/commits/936e12fb1a9da5f1ee396bcf7918153c29f11044)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-392/skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamschannelspolicy?view=skype-ps&branch=pr-en-us-9786) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-392/skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamschannelspolicy?view=skype-ps&branch=pr-en-us-9786) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208111736454611-9786/BuildReport?accessString=0a10d81b4d75c1763e8b38b08ee5ef102a79168c6df3fbb5652602fc524cebda).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 03:03 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
> +Owners of a shared channel can invite external users to join the channel, if Azure AD external sharing policies are configured. If the channel has been shared with an external member or team, they wi
```suggestion
Owners of a shared channel can invite external users to join the channel if Azure AD external sharing policies are configured. If the channel has been shared with an external member or team, they will continue to have access to the channel even if this parameter is set to FALSE. For more information, see [Manage channel policies in Microsoft Teams](/microsoftteams/teams-policies).
```

2022-08-12 03:03 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md
> +Users and teams can be invited to external shared channels, if Azure AD external sharing policies are configured. If a team in your organization is part of an external shared channel, new team member
```suggestion
Users and teams can be invited to external shared channels if Azure AD external sharing policies are configured. If a team in your organization is part of an external shared channel, new team members will have access to the channel even if this parameter is set to FALSE. For more information, see [Manage channel policies in Microsoft Teams](/microsoftteams/teams-policies).
```

2022-08-12 03:03 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
> +Owners of a shared channel can invite external users to join the channel, if Azure AD external sharing policies are configured. If the channel has been shared with an external member or team, they wi
```suggestion
Owners of a shared channel can invite external users to join the channel if Azure AD external sharing policies are configured. If the channel has been shared with an external member or team, they will continue to have access to the channel even if this parameter is set to FALSE. For more information, see [Manage channel policies in Microsoft Teams](/microsoftteams/teams-policies).
```

2022-08-12 03:04 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md
> +Users and teams can be invited to external shared channels, if Azure AD external sharing policies are configured. If a team in your organization is part of an external shared channel, new team member
```suggestion
Users and teams can be invited to external shared channels if Azure AD external sharing policies are configured. If a team in your organization is part of an external shared channel, new team members will have access to the channel even if this parameter is set to FALSE. For more information, see [Manage channel policies in Microsoft Teams](/microsoftteams/teams-policies).
```

2022-08-12 03:04 UTC, JohanFreelancer9 requested changes
Copy review.

2022-08-12 12:15 UTC, opbld30 commented
Docs Build status updates of commit _[0a517ce](https://github.com/get-itips/office-docs-powershell/commits/0a517ce97a6bdbbbef4c486ecf2595d9ea2d6bee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-392/skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamschannelspolicy?view=skype-ps&branch=pr-en-us-9786) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-392/skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamschannelspolicy?view=skype-ps&branch=pr-en-us-9786) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208121212446600-9786/BuildReport?accessString=10279decb0d4a55adc792de52cfd609b1918d42482d34f904c2d8c5e261a07a3).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 12:17 UTC, opbld32 commented
Docs Build status updates of commit _[b263e60](https://github.com/get-itips/office-docs-powershell/commits/b263e60bb1d00219cd4ea7481249c079c5ef002b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-392/skype/skype-ps/skype/New-CsTeamsChannelsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamschannelspolicy?view=skype-ps&branch=pr-en-us-9786) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md](https://github.com/get-itips/office-docs-powershell/blob/patch-392/skype/skype-ps/skype/Set-CsTeamsChannelsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamschannelspolicy?view=skype-ps&branch=pr-en-us-9786) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208121212590315-9786/BuildReport?accessString=b507331af8425287aa7ba4a22a70592b094d12d6b11e9d0cb14fdc7d8df3028f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-12 12:34 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-12 12:36 UTC, yogkumgit commented
@dariomws @tseward

2022-08-12 13:45 UTC, JohanFreelancer9 approved these changes

2022-08-12 15:22 UTC, dariomws approved these changes

2022-08-12 18:21 UTC, tseward approved these changes

2022-08-15 05:13 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-15 17:20 UTC, merged