Adding Live Interpretation parameter, and matching syntax for String
MicrosoftDocs/office-docs-powershell pull request #9799
Opened 2022-08-15 13:08 UTC by bwilsonms

Adding new parameter for Live Interpretation to Set-CsTeamsMeetingPolicy, matching all string to String

2022-08-15 13:11 UTC, opbld33 commented
Docs Build status updates of commit _[641edf5](https://github.com/bwilsonms/office-docs-powershell/commits/641edf5bf2b385cce4d969dcf174c5823c25c1b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/bwilsonms/office-docs-powershell/blob/bwilson_edit/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9799) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208151308173450-9799/BuildReport?accessString=7cfbd0000db6456ae2f66d93e3a05f2d53e4faab22ff328417ae20db9ecd4c6e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-16 02:50 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
> +Allows meeting organizers to configure a meeting for Language Interpretation, selecting attendees of the meeting to become interpreters that other attendees can select and listen to the real-time tra
```suggestion
Allows meeting organizers to configure a meeting for language interpretation, selecting attendees of the meeting to become interpreters that other attendees can select and listen to the real-time translation they provide.
```

2022-08-16 02:52 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md
> +- **Disabled**, prevents the option to be enabled in Meeting Options
```suggestion
- **Disabled**, prevents the option to be enabled in Meeting Options.
```

2022-08-16 02:53 UTC, JohanFreelancer9 requested changes
Copy review - @bwilsonms, kindly commit the minor suggested changes. Many thanks.

2022-08-16 08:41 UTC, dariomws approved these changes
I'm fine after Johan's suggestions.

2022-08-16 08:43 UTC, dariomws commented
@bwilsonms, will this parameter be also added to New-CsTeamsMeetingPolicy?

2022-08-16 09:14 UTC, get-itips approved these changes

2022-08-16 12:09 UTC, bwilsonms commented
> Copy review - @bwilsonms, kindly commit the minor suggested changes. Many thanks.

Done, thanks for the feedback.

2022-08-16 12:09 UTC, bwilsonms commented
> @bwilsonms, will this parameter be also added to New-CsTeamsMeetingPolicy?

Possibly, the developer only suggested here. Will ask and add to New as well if needed.

2022-08-16 12:10 UTC, opbld33 commented
Docs Build status updates of commit _[43196c4](https://github.com/bwilsonms/office-docs-powershell/commits/43196c46ebe3274994717af28aa2ed85c30a673a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md](https://github.com/bwilsonms/office-docs-powershell/blob/bwilson_edit/skype/skype-ps/skype/Set-CsTeamsMeetingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps&branch=pr-en-us-9799) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208161207557232-9799/BuildReport?accessString=a77a47d72e0042d0f62ceea2bfadb367b982569bb0236827fa179bb44f70a9de).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 01:42 UTC, tseward approved these changes

2022-08-17 04:03 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-17 13:52 UTC, JohanFreelancer9 approved these changes

2022-08-18 04:02 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-18 17:19 UTC, merged