Update Set-CsCallQueue.md
MicrosoftDocs/office-docs-powershell pull request #9807
Opened 2022-08-17 15:53 UTC by CLYVR

Removing restriction note on -OboResourceAccountIds as this feature now works all call queues
@get-itips @dariomws @tseward @tiburd  Please and thanks!

2022-08-17 15:57 UTC, opbld31 commented
Docs Build status updates of commit _[aaa7f3d](https://github.com/CLYVR/office-docs-powershell/commits/aaa7f3dd23226bb99329bf096210a2c2bf35ec3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-13/skype/skype-ps/skype/Set-CsCallQueue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps&branch=pr-en-us-9807) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208171553326143-9807/BuildReport?accessString=76a23db69064210e7e610cea6e6462b9593ea7b4350206dd376a734ab4f964e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 16:00 UTC, dariomws approved these changes

2022-08-17 16:04 UTC, get-itips approved these changes

2022-08-18 04:08 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-18 05:25 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Set-CsCallQueue.md
```suggestion
```

2022-08-18 05:29 UTC, JohanFreelancer9 requested changes
@CLYVR, please also remove the extra blank line. Many thanks.

2022-08-18 17:23 UTC, tiburd commented
@CLYVR 
Hi, Colin,
Please see Johan's comment above, and then @ mention me again when this PR is ready to merge (or merge it, if you have perms to do so).
Thank you!

2022-08-18 17:48 UTC, CLYVR commented
@tiburd Blank line removed.  I don't have the perms to merge myself.  Thank you!

2022-08-18 17:49 UTC, opbld33 commented
Docs Build status updates of commit _[5482241](https://github.com/CLYVR/office-docs-powershell/commits/54822416be3314de95b5bc6f74e2f00af64108e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Set-CsCallQueue.md](https://github.com/CLYVR/office-docs-powershell/blob/patch-13/skype/skype-ps/skype/Set-CsCallQueue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-cscallqueue?view=skype-ps&branch=pr-en-us-9807) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208181747103442-9807/BuildReport?accessString=ee219908bf674f18afbc8647c1c5ffdd11c94b638192d0fe5890348271a99df2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-18 17:50 UTC, merged