Various updates
MicrosoftDocs/office-docs-powershell pull request #9823
Opened 2022-08-23 15:49 UTC by JensTrier

Various updates to cover updated syntax for cmdlets and MoH for LBR users.

2022-08-23 15:52 UTC, opbld33 commented
Docs Build status updates of commit _[218e9e3](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/218e9e33e76374209bb68bb79e898a6c7a9f2576)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinepstngateway?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlinePstnUsage.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlinePstnUsage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinepstnusage?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineVoiceRoute.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineVoiceRoute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinevoiceroute?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlinePSTNGateway.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/New-CsOnlinePSTNGateway.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlinepstngateway?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineVoiceRoute.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/New-CsOnlineVoiceRoute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlinevoiceroute?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/New-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlinepstngateway?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineVoiceRoute.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Remove-CsOnlineVoiceRoute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlinevoiceroute?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Remove-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlinePstnUsage.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsOnlinePstnUsage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstnusage?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceroute?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-9823) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-9823) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-9823) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-9823) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsUnassignedNumberTreatment.md](https://github [...]

2022-08-24 06:07 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-24 06:29 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md
> +This example selects all SBC with Identity matching the pattern *.contoso.com. For example: sbc1.contoso.com, sbc2.contoso.com etc
```suggestion
This example selects all SBC with Identity matching the pattern *.contoso.com. For example: sbc1.contoso.com, sbc2.contoso.com, etc.
```

2022-08-24 06:33 UTC, JohanFreelancer9 requested changes
Copy review - @JensTrier, kindly commit the suggested minor change. Many thanks.

2022-08-24 06:48 UTC, JensTrier commented
> Copy review - @JensTrier, kindly commit the suggested minor change. Many thanks.

@JohanFreelancer9 Thanks & done!

2022-08-24 06:51 UTC, opbld33 commented
Docs Build status updates of commit _[4c04735](https://github.com/JensTrier/jenstr-office-docs-powershell/commits/4c04735508f8ca5de6f61800abc672082801155f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlinePSTNGateway.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinepstngateway?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlinePstnUsage.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlinePstnUsage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinepstnusage?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineVoiceRoute.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineVoiceRoute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinevoiceroute?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Get-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Get-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/get-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Grant-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/grant-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlinePSTNGateway.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/New-CsOnlinePSTNGateway.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlinepstngateway?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineVoiceRoute.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/New-CsOnlineVoiceRoute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlinevoiceroute?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/New-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/New-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/New-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/New-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Remove-CsOnlinePSTNGateway.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlinepstngateway?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineVoiceRoute.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Remove-CsOnlineVoiceRoute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlinevoiceroute?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Remove-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Remove-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/remove-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsOnlinePSTNGateway.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstngateway?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlinePstnUsage.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsOnlinePstnUsage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinepstnusage?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsOnlineVoiceRoute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceroute?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsOnlineVoiceRoutingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsOnlineVoiceRoutingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csonlinevoiceroutingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/skype/skype-ps/skype/Set-CsTeamsCallingPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/set-csteamscallingpolicy?view=skype-ps&branch=pr-en-us-9823) (skype-ps) |
[teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Get-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-9823) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-9823) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-9823) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md](https://github.com/JensTrier/jenstr-office-docs-powershell/blob/JTRUpdate1/teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamsunassignednumbertreatment?view=teams-ps&branch=pr-en-us-9823) (teams-ps) |
[teams/teams-ps/teams/Test-CsTeamsUnassignedNumberTreatment.md](https://github [...]

2022-08-24 10:35 UTC, JohanFreelancer9 approved these changes

2022-08-24 10:38 UTC, dariomws approved these changes

2022-08-25 03:27 UTC, yogkumgit commented
@get-itips @tseward

2022-08-25 04:23 UTC, tseward approved these changes

2022-08-25 14:24 UTC, get-itips approved these changes

2022-08-26 04:03 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-26 21:40 UTC, merged