Update Set-UnifiedGroup.md
MicrosoftDocs/office-docs-powershell pull request #9827
Opened 2022-08-24 07:07 UTC by Ashok-Lobo

2022-08-24 07:10 UTC, opbld30 commented
Docs Build status updates of commit _[fc8ce98](https://github.com/Ashok-Lobo/office-docs-powershell/commits/fc8ce980b527bb003f36d95530d64f67844cf6f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6471390/exchange/exchange-ps/exchange/Set-UnifiedGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps&branch=pr-en-us-9827) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208240707171361-9827/BuildReport?accessString=60ad561c6b40f37cd428a8bb5f4f826860ccd5243db718824df72e517733bb08).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 07:29 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-24 11:17 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-UnifiedGroup.md
> +- If Microsoft 365 Groups are hidden from exchange clients, users cannot view the option to subscribe or unsubscribe to a Microsoft 365 Group.
```suggestion
- If Microsoft 365 Groups are hidden from Exchange clients, users cannot view the option to subscribe or unsubscribe to a Microsoft 365 Group.
```

2022-08-24 11:18 UTC, JohanFreelancer9 requested changes
Copy review - @Ashok-Lobo, kindly commit the minor suggested change. Many thanks.

2022-08-24 11:27 UTC, opbld31 commented
Docs Build status updates of commit _[7dc6257](https://github.com/Ashok-Lobo/office-docs-powershell/commits/7dc6257e1140ecee534e5d5150314246ed9b025d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-UnifiedGroup.md](https://github.com/Ashok-Lobo/office-docs-powershell/blob/Ashok-Lobo-6471390/exchange/exchange-ps/exchange/Set-UnifiedGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps&branch=pr-en-us-9827) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208241124365116-9827/BuildReport?accessString=c750285baf1b8e99af73f6bf54e56864115c06961381afb13e99cb2e6ef5c873).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 11:38 UTC, JohanFreelancer9 approved these changes

2022-08-24 11:48 UTC, Ashok-Lobo commented
@JohanFreelancer9, committed the suggested change. thank you

2022-08-25 04:34 UTC, Ashok-Lobo commented
@JohanFreelancer9 @chrisda @yogkumgit 

Please merge this PR. Thank you.

2022-08-25 16:11 UTC, merged