Update Connect-ExchangeOnline.md
MicrosoftDocs/office-docs-powershell pull request #9829
Opened 2022-08-24 11:44 UTC by abhisk11

2022-08-24 11:47 UTC, opbld32 commented
Docs Build status updates of commit _[4d9d7f7](https://github.com/abhisk11/office-docs-powershell/commits/4d9d7f727b82e3d52c896c900a1b7164ea92b074)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/abhisk11/office-docs-powershell/blob/patch-6/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps&branch=pr-en-us-9829) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208241144307173-9829/BuildReport?accessString=2919e808f8c8b03ec41b542ffeb10f17dfe7373fdd134386a268e1942e05f8e4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 03:28 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-25 08:47 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Connect-ExchangeOnline.md
> +Note - Please use an .onmicrosoft.com domain for the parameter value. Not doing so may result in permission related issues when you run commands in the app context.
```suggestion
**Note**: Use an .onmicrosoft.com domain for the parameter value. Not doing so might result in permission-related issues when you run commands in the app context. 
```

2022-08-25 08:48 UTC, JohanFreelancer9 requested changes
Copy review - @abhisk11, kindly commit the suggested changes. Many thanks.

2022-08-25 16:52 UTC, opbld32 commented
Docs Build status updates of commit _[8d2d8c8](https://github.com/abhisk11/office-docs-powershell/commits/8d2d8c8e958d44ea4a88bdf13b96a3f216691f65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Connect-ExchangeOnline.md](https://github.com/abhisk11/office-docs-powershell/blob/patch-6/exchange/exchange-ps/exchange/Connect-ExchangeOnline.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/connect-exchangeonline?view=exchange-ps&branch=pr-en-us-9829) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208251649056639-9829/BuildReport?accessString=4d30533dcee18194f3ddc1471f96ad1bd46086386cb48793cb6fbc256bf09570).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-25 17:32 UTC, merged