Update Set-OwaMailboxPolicy.md
MicrosoftDocs/office-docs-powershell pull request #9840
Opened 2022-08-29 09:41 UTC by Benny-54

This article is updates as per TASK 6527407, thank you!

2022-08-29 09:44 UTC, opbld30 commented
Docs Build status updates of commit _[b76ed6e](https://github.com/Benny-54/office-docs-powershell/commits/b76ed6edcc858c9d2fad6102456823826acddff1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/Benny-54/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps&branch=pr-en-us-9840) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208290941293153-9840/BuildReport?accessString=5dea3102c880d39f055ba79d1b2aa1b56049445827cae7bf6d087b9c6221f527).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-29 16:30 UTC, opbld33 commented
Docs Build status updates of commit _[4219816](https://github.com/Benny-54/office-docs-powershell/commits/42198163d5d3dae804fb1bedc5efe84d775f69b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/Benny-54/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps&branch=pr-en-us-9840) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208291627411601-9840/BuildReport?accessString=5d86f4d2a6a326ffd3c9e70734792bdc4fc7a05b6e474f0fe67cc4cc8655cba6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 04:35 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md
> +The OneWinNativeOutlookEnabled parameter controls the availability of the new Outlook for Windows app. Valid values are:
```suggestion
The OneWinNativeOutlookEnabled parameter controls the availability of the new Outlook for Windows App. Valid values are:
```

2022-08-30 04:40 UTC, JohanFreelancer9 requested changes
Copy review - @Benny-54, kindly commit the suggested change. Many thanks.

2022-08-30 10:29 UTC, dariomws approved these changes

2022-08-30 12:28 UTC, get-itips approved these changes

2022-08-30 16:40 UTC, opbld33 commented
Docs Build status updates of commit _[1a98e84](https://github.com/Benny-54/office-docs-powershell/commits/1a98e84252ad3b044472fd6a5839469a3c8048ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/Benny-54/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps&branch=pr-en-us-9840) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208301638046495-9840/BuildReport?accessString=7e2992e0f5b8d894c8bc22b02d933dff78d02763bc44d5a884f2bb4462332145).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 19:41 UTC, opbld31 commented
Docs Build status updates of commit _[ac055ff](https://github.com/Benny-54/office-docs-powershell/commits/ac055ff65c86f4990af57bfc8ec076712e15f9f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md](https://github.com/Benny-54/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-OwaMailboxPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps&branch=pr-en-us-9840) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208301938552070-9840/BuildReport?accessString=7b9ec9ef81be8e7593c0da30c4e4d64e452d032ed12656c87fc92a977fc880d7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 10:25 UTC, JohanFreelancer9 approved these changes

2022-09-01 14:43 UTC, yogkumgit commented
@chrisda

2022-09-01 15:46 UTC, chrisda commented
Has the SME reviewed this yet? I know about the new 'Monarch' Outlook app; it's likely more of a question of availability.

2022-09-02 17:45 UTC, tseward approved these changes

2022-09-02 18:09 UTC, merged

2022-09-12 10:14 UTC, Benny-54 commented
> Has the SME reviewed this yet? I know about the new 'Monarch' Outlook app; it's likely more of a question of availability.

Hi Chris,
Could you please revert this? this is not yet approved for publish by SME.

Thank you!