Updated doc of ShareWithTeam cmdlets
MicrosoftDocs/office-docs-powershell pull request #9842
Opened 2022-08-29 23:09 UTC by zhongxl1993

Update ShareWithTeam cmdlets doc.

2022-08-29 23:11 UTC, opbld32 commented
Docs Build status updates of commit _[516e080](https://github.com/zhongxl1993/office-docs-powershell/commits/516e080eb65d0d9f794f4dc4e6689a2ad092445c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :x:Error | | [Details](#user-content-d5aa790457078d70b41a1d33a40446cd-e0b1efc6)
[teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.yml) | :warning:Warning | | [Details](#user-content-3d83e1a2f98ee2f6fb3f6ce0b274e6e9-e0b1efc6)
[teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.yml) | :warning:Warning | | [Details](#user-content-c1e10dbbc62490bcc9f449312c3e01d2-e0b1efc6)
[teams/teams-ps/teams/index.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/index.yml) | :warning:Warning | | [Details](#user-content-b61f50182cfc6b2c2e4f61000005186d-e0b1efc6)
[teams/teams-ps/teams/New-CsCustomPolicyPackage.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/New-CsCustomPolicyPackage.yml) | :warning:Warning | | [Details](#user-content-79a31d412288c826f3e8bf725528aa5f-e0b1efc6)
[teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/New-CsTeamsShiftsConnectionInstance.yml) | :warning:Warning | | [Details](#user-content-e226d5c21d46a902f39d655eeea9dff5-e0b1efc6)
[teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/New-CsTeamsUnassignedNumberTreatment.yml) | :warning:Warning | | [Details](#user-content-90dbe97d670a1a2961a19507904e009c-e0b1efc6)
[teams/teams-ps/teams/New-Team.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/New-Team.yml) | :warning:Warning | | [Details](#user-content-883c025663984962d6467869fb00157a-e0b1efc6)
[teams/teams-ps/teams/Remove-CsCustomPolicyPackage.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-CsCustomPolicyPackage.yml) | :warning:Warning | | [Details](#user-content-a02e090a4c28a99dd8dd93e64c4e23f5-e0b1efc6)
[teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-CsTeamsUnassignedNumberTreatment.yml) | :warning:Warning | | [Details](#user-content-df0570420a296331f256b4db8c86416b-e0b1efc6)
[teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Set-CsTeamsShiftsConnectionInstance.yml) | :warning:Warning | | [Details](#user-content-284b1b1c9fb9ab3f14926fd11beb1914-e0b1efc6)
[teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Set-CsTeamsUnassignedNumberTreatment.yml) | :warning:Warning | | [Details](#user-content-4949868722a193a660c6ebbc73ca80dd-e0b1efc6)

<a id="d5aa790457078d70b41a1d33a40446cd-e0b1efc6"></a>
### [teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md)
 - **Line 0, Column 0**: **[Error: MAML2Yaml_LoadFileFailed]** 
`````
Failed to load file: C:/LocalRun/W/pzdd-s/teams/teams-ps/teams/Get-AssociatedTeam.md:24:(219) '```

Returns associated teams of given user emai...'
 Expect Heading, please try to use PlatyPS validate the content
`````

<a id="3d83e1a2f98ee2f6fb3f6ce0b274e6e9-e0b1efc6"></a>
### [teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-CsTeamsAcsFederationConfiguration.yml)
 - **Line 10, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Set-CsTeamsAcsFederationConfiguration.yml'.`````

<a id="c1e10dbbc62490bcc9f449312c3e01d2-e0b1efc6"></a>
### [teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-CsTeamsShiftsConnectionConnector.yml)
 - **Line 12, Column 9**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Test-CsTeamsShiftsConnectionValidate.yml'.`````

<a id="b61f50182cfc6b2c2e4f61000005186d-e0b1efc6"></a>
### [teams/teams-ps/teams/index.yml](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/index.yml)
 - **Line 13, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Get-AssociatedTeam'.`````
 - **Line 98, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Remove-Team'.`````
 - **Line 107, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-CsTeamsAcsFederationConfiguration'.`````
 - **Line 117, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamChannel'.`````
 - **Line 118, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamFunSettings'.`````
 - **Line 119, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamGuestSettings'.`````
 - **Line 120, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamMemberSettings'.`````
 - **Line 121, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamMessagingSettings'.`````
 - **Line 122, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamPicture'.`````
 - **Line 123, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamsApp'.`````
 - **Line 124, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Set-TeamTargetingHierarchy'.`````
 - **Line 125, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Test-CsTeamsShiftsConnectionValidate'.`````
 - **Line 126, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Test-CsTeamsUnassignedNumberTreatment'.`````
 - **Line 127, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Update-CsCustomPolicyPackage'.`````
 - **Line 128, Column 5**: **[Warning: xref-not-found]** `````Cross reference not found: 'MicrosoftTeamsPowerShell.Update-CsTeamTemplate'.`````
 - **Line 129, Column 5**: **[Warning: xr [...]

2022-08-30 00:06 UTC, opbld31 commented
Docs Build status updates of commit _[a0494d7](https://github.com/zhongxl1993/office-docs-powershell/commits/a0494d7367f0391a7c33fdc6a155b9045e64a366)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxl1993/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208300002349687-9842/BuildReport?accessString=4626156b3e122615912cd032313c8557ed3133b8327bc4da54ba3a6e29545aab).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 06:33 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-30 13:27 UTC, get-itips commented on teams/teams-ps/teams/Get-AssociatedTeam.md
> +Get-TeamChannel -user example@example.com
```suggestion
Get-AssociatedTeam -user example@example.com
```

2022-08-30 13:27 UTC, get-itips commented on teams/teams-ps/teams/Get-AssociatedTeam.md
> +Get-TeamChannel -user 0e4249a7-6cfd-8c93-a510-91cda44c8c73
```suggestion
Get-AssociatedTeam -user 0e4249a7-6cfd-8c93-a510-91cda44c8c73
```

2022-08-30 13:30 UTC, get-itips requested changes
Please add missing common parameters, inputs, outputs, notes section in the new articles that you are submitting, thanks

2022-08-30 13:34 UTC, get-itips commented on teams/teams-ps/teams/Remove-SharedWithTeam.md
> +This cmdlet supports usharing a channel with a team.
Please fix the description

2022-08-30 13:37 UTC, get-itips requested changes
Please see my comments, thanks

2022-08-30 16:30 UTC, get-itips commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +Get-AssociatedTeam -HostTeamId 126b90a5-e65a-4fef-98e3-d9b49f4acf12 -ChannelId 19:cUfyYYw3h_t-1KG8-WkvVa7KLEsIx-JHmyeG43VJojg1@thread.tacv2
```suggestion
Get-Get-SharedWithTeam -HostTeamId 126b90a5-e65a-4fef-98e3-d9b49f4acf12 -ChannelId 19:cUfyYYw3h_t-1KG8-WkvVa7KLEsIx-JHmyeG43VJojg1@thread.tacv2
```

2022-08-30 16:33 UTC, get-itips commented on teams/teams-ps/teams/Get-SharedWithTeamUser.md
> +Get-AssociatedTeamUser -HostTeamId 126b90a5-e65a-4fef-98e3-d9b49f4acf12 -ChannelId 19:cUfyYYw3h_t-1KG8-WkvVa7KLEsIx-JHmyeG43VJojg1@thread.tacv2
```suggestion
Get-SharedWithTeamUser -HostTeamId 126b90a5-e65a-4fef-98e3-d9b49f4acf12 -ChannelId 19:cUfyYYw3h_t-1KG8-WkvVa7KLEsIx-JHmyeG43VJojg1@thread.tacv2
```

2022-08-31 05:03 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-AssociatedTeam.md
> +Returns associated teams of current user.
```suggestion
Returns associated teams of the current user.
```

2022-08-31 05:03 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-AssociatedTeam.md
> +Returns associated teams of given user email.
```suggestion
Returns associated teams of the given user email.
```

2022-08-31 05:04 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-AssociatedTeam.md
> +Returns associated teams of given user id.
```suggestion
Returns associated teams of the given user ID.
```

2022-08-31 05:06 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-AssociatedTeam.md
> +User's UPN (user principal name - e.g.
```suggestion
User's UPN (user principal name, for example
```

2022-08-31 05:07 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-AssociatedTeam.md
> +johndoe@example.com) or user id (e.g. 0e4249a7-6cfd-8c93-a510-91cda44c8c73)
```suggestion
johndoe@example.com) or user ID (for example 0e4249a7-6cfd-8c93-a510-91cda44c8c73).
```

2022-08-31 05:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +This cmdlet supports retrieving teams with which specified channel is shared.
```suggestion
This cmdlet supports retrieving teams with which a specified channel is shared.
```

2022-08-31 05:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +This cmdlet supports retrieving teams with which specified channel is shared.
```suggestion
This cmdlet supports retrieving teams with which a specified channel is shared.
```

2022-08-31 05:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +Returns teams with which specified channel is shared.
```suggestion
Returns teams with which a specified channel is shared.
```

2022-08-31 05:09 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +Returns detail of a team with which specified channel is shared.
```suggestion
Returns detail of a team with which a specified channel is shared.
```

2022-08-31 05:10 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +Team id of the host team (group id)
```suggestion
Team ID of the host team (group ID)
```

2022-08-31 05:10 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +Thread id of the shared channel
```suggestion
Thread ID of the shared channel.
```

2022-08-31 05:13 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +Team id of the shared with team
```suggestion
Team ID of the shared with team.
```

2022-08-31 05:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeamUser.md
> +Returns users of a team with which specified channel is shared.
```suggestion
Returns users of a team with which a specified channel is shared.
```

2022-08-31 05:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeamUser.md
> +Returns owners of a team with which specified channel is shared.
```suggestion
Returns owners of a team with which a specified channel is shared.
```

2022-08-31 05:15 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeamUser.md
> +Team id of the host team (group id)
```suggestion
Team ID of the host team (group ID)
```

2022-08-31 05:16 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeamUser.md
> +Thread id of the shared channel
```suggestion
Thread ID of the shared channel.
```

2022-08-31 05:16 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeamUser.md
> +Team id of the shared with team
```suggestion
Team ID of the shared with team.
```

2022-08-31 05:18 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeamUser.md
> +Filter the results to only users with the given role: Owner or Member.
```suggestion
Filters the results to only users with the given role of "Owner" or "Member".
```

2022-08-31 05:20 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-TeamAllChannel.md
> +Group id of the team
```suggestion
Returns the Group ID of the team.
```

2022-08-31 05:21 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-TeamAllChannel.md
> +Membership type of the channel to display, Standard, Private, or Shared
```suggestion
Membership type of the channel to display; Standard, Private, or Shared
```

2022-08-31 05:23 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-TeamChannel.md
> +Get the channels hosted by a team.
```suggestion
This cmdlet gets the channels hosted by a team.
```

2022-08-31 05:23 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-TeamIncomingChannel.md
> +Group id of the team
```suggestion
Group ID of the team
```

2022-08-31 05:24 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-SharedWithTeam.md
> +This cmdlet supports usharing a channel with a team.
```suggestion
This cmdlet supports sharing a channel with a team.
```

2022-08-31 05:24 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-SharedWithTeam.md
> +This cmdlet supports usharing a channel with a team.
```suggestion
This cmdlet supports sharing a channel with a team.
```

2022-08-31 05:25 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-SharedWithTeam.md
> +Ushares a channel with a team.
```suggestion
Shares a channel with a team.
```

2022-08-31 05:28 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-SharedWithTeam.md
> +Team id of the host team (group id)
```suggestion
Team ID of the host team (Group ID).
```

2022-08-31 05:28 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-SharedWithTeam.md
> +Thread id of the shared channel
```suggestion
Thread ID of the shared channel.
```

2022-08-31 05:29 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-SharedWithTeam.md
> +Team id of the shared with team
```suggestion
Team ID of the shared with team.
```

2022-08-31 05:35 UTC, JohanFreelancer9 requested changes
Copy review - @zhongxl1993, kindly commit the suggested changes. Many thanks.

2022-08-31 11:26 UTC, dariomws requested changes

2022-08-31 11:26 UTC, dariomws commented on teams/teams-ps/teams/Add-TeamChannelUser.md
> +### -TenantId
You must add this parameter to the Syntax section.

2022-08-31 11:26 UTC, dariomws commented on teams/teams-ps/teams/Get-TeamIncomingChannel.md
> +```
You are missing common parameters, output, etc

2022-08-31 11:27 UTC, yogkumgit commented
@zhongxl1993 Please implement the suggested changes. Thanks

2022-09-01 18:02 UTC, opbld33 commented
Docs Build status updates of commit _[c563725](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/c5637256a6e9e72fc1c2ae1a1a141edde6b7a07e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209011759008364-9842/BuildReport?accessString=899e1a022456f59be8bcac34decfea7a94354872b09492973f9339530c9c6412).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 18:04 UTC, opbld33 commented
Docs Build status updates of commit _[233ad4c](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/233ad4c4f5d0472a2a2ca49227fa251fc9e958b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209011759491922-9842/BuildReport?accessString=b025f64a51a664e8c6ea54d4e477215ed65ec643bc64130e9e9993855e534909).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 18:08 UTC, opbld32 commented
Docs Build status updates of commit _[d34892e](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/d34892e77b9c719cd64afeee9d20dd4e46afa280)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209011803113072-9842/BuildReport?accessString=d17c5b983ba0308f1c81d13f003fe5bf933e5c5ea8bcc28978afb4d573ff3df6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 22:14 UTC, opbld32 commented
Docs Build status updates of commit _[f68e7cf](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/f68e7cfad4e96119dab8eb2edf24c252ff499b04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209012211117186-9842/BuildReport?accessString=c8a7e5cd78dca6fa2eb2c68cca44df8ea8aaa06d3a5479cf360b9d6f0291d211).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 22:17 UTC, opbld33 commented
Docs Build status updates of commit _[d560b29](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/d560b29ec40b9f842690e85673556eedc95ed7ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209012211586254-9842/BuildReport?accessString=06645519cd2bf7251f66d1e09b4c3ad172f6fca0bf6707071d39c43bcd087bab).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 22:21 UTC, opbld33 commented
Docs Build status updates of commit _[647843b](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/647843b943acc8974e405abddd6d6f28f84e454f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209012219117023-9842/BuildReport?accessString=97cdc649bab9583c0d0f2950c689e732ac2e8f8a4c694e861cdd75438145c77f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 22:24 UTC, opbld32 commented
Docs Build status updates of commit _[c32b2b0](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/c32b2b0d0ba4ddb9422d3b2700cb3ab3b490a42d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209012219560070-9842/BuildReport?accessString=90e85efd439348d7dfdda06d25da6556d18de4a6799061cfad5602308e349199).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 23:10 UTC, opbld30 commented
Docs Build status updates of commit _[fd2c280](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/fd2c280332e4c4d7caf313fba1d8c411ed8ce50c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209012307460132-9842/BuildReport?accessString=222013b4c5f25b7c9fd4bf2c9c0f0b62a76297113746496447c87cbf0254fec4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 23:13 UTC, opbld32 commented
Docs Build status updates of commit _[afc6a74](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/afc6a74b283d24bf3db9c9d9d5685364dca38f62)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209012307547704-9842/BuildReport?accessString=9ccaf6db1dfb5a7ff7cf7ad2ed9f3933a0a384908835b387549cec375d23486b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 04:20 UTC, opbld30 commented
Docs Build status updates of commit _[5cbf5e4](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/5cbf5e4bdf40c731bfcd0a93b747d422f465eee4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209020417320292-9842/BuildReport?accessString=f2e0c1e9661f6e587592203aab42253429df5726ef097d9243b41ddd0e9f50a0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 04:43 UTC, opbld30 commented
Docs Build status updates of commit _[fee4e63](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/fee4e6311e4add806bac3c8173500c31bf5d5c82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209020440131425-9842/BuildReport?accessString=b6fcbb1bd8826c59a3707bbc0e60c719b3a0fa6614366f398663681eb4de3e34).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 09:36 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-AssociatedTeam.md
> +For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-02 09:37 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeam.md
> +For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-02 09:40 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-SharedWithTeamUser.md
> +For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-02 09:41 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-TeamAllChannel.md
> +For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-02 09:42 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-TeamIncomingChannel.md
> +For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-02 09:43 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-SharedWithTeam.md
> +For more information, see about_CommonParameters (https://go.microsoft.com/fwlink/?LinkID=113216).
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-05 07:59 UTC, yogkumgit commented
@zhongxlmicrosoft Please implement the suggested changes. Thanks

2022-09-08 10:47 UTC, yogkumgit commented
@zhongxlmicrosoft Gentle reminder.

2022-09-13 11:43 UTC, yogkumgit commented
@zhongxlmicrosoft Please implement the suggested changes so that merge can be initiated. In the event of no response we may proceed to close this PR. Thanks

2022-09-14 22:55 UTC, opbld32 commented
Docs Build status updates of commit _[a3b14a1](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/a3b14a14bccae8fbe37a689cac80038a9adbad34)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0cdba1bc)

<a id="0cdba1bc"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit a3b14a14bccae8fbe37a689cac80038a9adbad34 in branch zhongxl/update_ShareWithTeamCmdlets of repository https://github.com/zhongxlmicrosoft/office-docs-powershell into branch main (commit 39f6b6ec11c3bed2221f23b8138230a9cc2dc11b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209142254430134-9842/BuildReport?accessString=9e1b096625cf26d137da6f89d8ad73af1564b28a4cf3a83b63617bef5c785254).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 22:53 UTC, opbld32 commented
Docs Build status updates of commit _[3394268](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/3394268d6b5d1a8790d3efebbe7fc111d6449c8b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-278c3cbd)

<a id="278c3cbd"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 3394268d6b5d1a8790d3efebbe7fc111d6449c8b in branch zhongxl/update_ShareWithTeamCmdlets of repository https://github.com/zhongxlmicrosoft/office-docs-powershell into branch main (commit 39f6b6ec11c3bed2221f23b8138230a9cc2dc11b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209162253008346-9842/BuildReport?accessString=3876cb09a1f17c898b33c26cb6c2d735d06e7e8acd7373b7bc1a56f456f6a5de).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 23:00 UTC, opbld31 commented
Docs Build status updates of commit _[a7d76d3](https://github.com/zhongxlmicrosoft/office-docs-powershell/commits/a7d76d381b36d2b7b656cdc37e6b8c17811d7de8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Add-TeamChannelUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Add-TeamChannelUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/add-teamchanneluser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-AssociatedTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-AssociatedTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-associatedteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-SharedWithTeamUser.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-SharedWithTeamUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-sharedwithteamuser?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamAllChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamAllChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamallchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Get-TeamIncomingChannel.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Get-TeamIncomingChannel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-teamincomingchannel?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/Remove-SharedWithTeam.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/Remove-SharedWithTeam.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-sharedwithteam?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/zhongxlmicrosoft/office-docs-powershell/blob/zhongxl/update_ShareWithTeamCmdlets/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9842) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209162257149025-9842/BuildReport?accessString=55b0d61ce478a04d5ae0e3bfa648ab416dbc132b4def172dc29cb24515f5a281).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 03:45 UTC, JohanFreelancer9 approved these changes

2022-09-19 08:58 UTC, dariomws approved these changes

2022-09-19 18:14 UTC, tseward approved these changes

2022-09-20 08:10 UTC, yogkumgit commented
@get-itips

2022-09-20 10:53 UTC, get-itips approved these changes

2022-09-20 14:15 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-09-20 17:14 UTC, tiburd commented
@zhongxlmicrosoft 

Hello,

At your earliest convenience, please complete your account setup so that your GitHub and Microsoft accounts are connected:
- [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main)

Thanks!

2022-09-20 17:14 UTC, merged