Adding the docs for CsTeamsEventsPolicy cmdlets
MicrosoftDocs/office-docs-powershell pull request #9845
Opened 2022-08-30 06:07 UTC by musingh1

2022-08-30 06:11 UTC, opbld33 commented
Docs Build status updates of commit _[8be5fdb](https://github.com/musingh1/office-docs-powershell/commits/8be5fdb98f4648fcd81ca773806a425b3299c13e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208300607426562-9845/BuildReport?accessString=1745a30ce554418ec4f8673be44c3197335295ffa92dac19ae9ba5fdc637c745).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 06:39 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-30 12:35 UTC, get-itips commented on teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

```

2022-08-30 12:37 UTC, get-itips commented on teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

```

2022-08-30 16:23 UTC, get-itips commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> +Set this to EveryoneInCompanyExcludingGuests to disable a user from creating public webinars
What are all the possible values of this parameter? Everyone and EveryoneInCompanyExcludingGuests? please specify

2022-08-31 04:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
> +Return information for all Teams Events policies available for use in the tenant.
```suggestion
Returns information for all Teams Events policies available for use in the tenant.

```

2022-08-31 04:08 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
> +Return information for Teams Events policy with identity "Global".
```suggestion
Returns information for Teams Events policy with identity "Global".

```

2022-08-31 04:10 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
> +Unique identifier assigned to the Teams events policy.
```suggestion
Unique identifier assigned to the Teams Events policy.

```

2022-08-31 04:11 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

```

2022-08-31 04:13 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
> +Assigns Teams Events policy to a user, group of users or the entire tenant. Note that this policy is currently still in preview.
```suggestion
Assigns Teams Events policy to a user, group of users, or the entire tenant. Note that this policy is currently still in preview.

```

2022-08-31 04:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
> +Assigns Teams Events policy to a user, group of users or the entire tenant.
```suggestion
Assigns Teams Events policy to a user, group of users, or the entire tenant.

```

2022-08-31 04:14 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
> +The command shown in Example 1 assigns the per-user Teams events policy, DisablePublicWebinars, to the user with the user principal name (UPN) "user1@contoso.com".
```suggestion
The command shown in Example 1 assigns the per-user Teams Events policy, DisablePublicWebinars, to the user with the user principal name (UPN) "user1@contoso.com".

```

2022-08-31 04:15 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
> +The command shown in Example 2 revokes the per-user Teams events policy for the user with the user principal name (UPN) "user1@contoso.com". As a result, the user will be managed by the global Teams
```suggestion
The command shown in Example 2 revokes the per-user Teams Events policy for the user with the user principal name (UPN) "user1@contoso.com". As a result, the user will be managed by the global Teams Events policy.

```

2022-08-31 04:16 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
> +The command shown in Example 3 assigns the Teams events policy, DisablePublicWebinars, to the members of the group "sales@contoso.com".
```suggestion
The command shown in Example 3 assigns the Teams Events policy, DisablePublicWebinars, to the members of the group "sales@contoso.com".

```

2022-08-31 04:19 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
> +Use the "Global" Identity if you wish to set the policy for the entire tenant
```suggestion
Use the "Global" Identity if you wish to set the policy for the entire tenant.

```

2022-08-31 04:23 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> +This cmdlet allows you to create a new TeamsEventsPolicy instance and set it's properties. Note that this policy is currently still in preview.
```suggestion
This cmdlet allows you to create a new TeamsEventsPolicy instance and set its properties. Note that this policy is currently still in preview.

```

2022-08-31 04:30 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> +This setting governs if a user can create Webinars using Teams Events. Set this to Disabled to disable a user from creating webinars
```suggestion
This setting governs if a user can create webinars using Teams Events. Set this to **Disabled** to disable a user from creating webinars.

```

2022-08-31 04:31 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> +Enables administrators to provide explanatory text to accompany a Teams events policy.
```suggestion
Enables administrators to provide explanatory text to accompany a Teams Events policy.

```

2022-08-31 04:31 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> +Unique identifier assigned to the Teams events policy.
```suggestion
Unique identifier assigned to the Teams Events policy.

```

2022-08-31 04:32 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

```

2022-08-31 04:36 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md
> +In the example shown above, the command will delete the DisablePublicWebinars policy from the organization's list of policies.
```suggestion
In this example, the command will delete the DisablePublicWebinars policy from the organization's list of policies.

```

2022-08-31 04:41 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

```

2022-08-31 04:42 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +This cmdlet allows you to configure options for customizing Teams events experiences. Note that this policy is currently still in preview.
```suggestion
This cmdlet allows you to configure options for customizing Teams Events experiences. Note that this policy is currently still in preview.

```

2022-08-31 04:42 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +User-level policy for tenant admin to configure options for customizing Teams events experiences. Use this cmdlet to update an existing policy.
```suggestion
User-level policy for tenant admin to configure options for customizing Teams Events experiences. Use this cmdlet to update an existing policy.

```

2022-08-31 04:43 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +The command shown in Example 1 sets the value of the Default (Global) Events Policy in the organization to disable webinars, and leaves all other parameters the same.
```suggestion
The command shown in Example 1 sets the value of the default (Global) Events Policy in the organization to disable webinars and leaves all other parameters the same.

```

2022-08-31 04:43 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +This setting governs if a user can create Webinars using Teams Events.
```suggestion
This setting governs if a user can create webinars using Teams Events.

```

2022-08-31 04:44 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +Enables administrators to provide explanatory text to accompany a Teams events policy.
```suggestion
Enables administrators to provide explanatory text to accompany a Teams Events policy.

```

2022-08-31 04:45 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +Unique identifier assigned to the Teams events policy.
```suggestion
Unique identifier assigned to the Teams Events policy.

```

2022-08-31 04:46 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

```

2022-08-31 04:49 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/teams.md
> +Assigns Teams Events policy to a user, group of users or the entire tenant. Note that this policy is currently still in preview.
```suggestion
Assigns Teams Events policy to a user, group of users, or the entire tenant. Note that this policy is currently still in preview.
```

2022-08-31 04:49 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/teams.md
>  Cmdlet to assign a specific Teams enhanced encryption Policy to a user.
```suggestion
Cmdlet to assign a specific Teams enhanced encryption policy to a user.
```

2022-08-31 04:50 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/teams.md
> +Allows you to configure options for customizing Teams events experiences. Note that this policy is currently still in preview.
```suggestion
Allows you to configure options for customizing Teams Events experiences. Note that this policy is currently still in preview.
```

2022-08-31 04:52 UTC, JohanFreelancer9 requested changes
Copy review - @musingh1, kindly commit the suggested changes. Many thanks.

2022-08-31 10:49 UTC, dariomws approved these changes
I'm ok after the suggested changes.

2022-08-31 10:58 UTC, yogkumgit commented
@musingh1 Please implement the suggested changes. Thanks

2022-08-31 11:21 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

```

2022-09-01 15:19 UTC, opbld31 commented
Docs Build status updates of commit _[f265cb0](https://github.com/musingh1/office-docs-powershell/commits/f265cb010d7e35e630558a6252810e729003bb5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209011516482910-9845/BuildReport?accessString=41578685cd76b3d3be4cc66b1b22f7b11960f454b1900634edb76e67060c4fd1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 15:22 UTC, opbld31 commented
Docs Build status updates of commit _[41188f9](https://github.com/musingh1/office-docs-powershell/commits/41188f9c735a654c46e900f26bf72cc884c9c81c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209011519373588-9845/BuildReport?accessString=3c51f92a3a5d2402a12261252fa690c867387de3489c7a8c8bd2da17a155440c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 15:31 UTC, opbld30 commented
Docs Build status updates of commit _[c265fee](https://github.com/musingh1/office-docs-powershell/commits/c265feed10e274ba64a966ba210fd2e21d511311)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209011526305187-9845/BuildReport?accessString=039954ae2412367001624d35fc76f79314aa4e8b0e17903c69614817d24e02de).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 16:16 UTC, opbld31 commented
Docs Build status updates of commit _[4c85a1b](https://github.com/musingh1/office-docs-powershell/commits/4c85a1b96ce396ced9c7fc9337ec2b04a3362fd6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209011614045916-9845/BuildReport?accessString=d5f80701b158e47bcc0a4244e0cac526391aa0fdc227460561418c2805bbf468).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-01 16:22 UTC, opbld32 commented
Docs Build status updates of commit _[c5e179a](https://github.com/musingh1/office-docs-powershell/commits/c5e179a8bd440195689a4268508b8afc6d012631)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209011619277199-9845/BuildReport?accessString=e8651ec9e5da4db7aeee45f7fb5ff283aa5eb39c1b980d0c72983c591e9258ce).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 04:11 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).

```

2022-09-02 04:15 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> + - **Everyone**, Enables creating events to allow in tenant + guests + federated + anonymous (external to tenant) users to register and join the event
```suggestion
 - **Everyone**, Enables creating events to allow in-tenant, guests, federated, and anonymous (external to the tenant) users to register and join the event

```

2022-09-02 04:15 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> + - **EveryoneInCompanyExcludingGuests**, Enables creating events to allow only in tenant users to register and join the event
```suggestion
 - **EveryoneInCompanyExcludingGuests**, Enables creating events to allow only in-tenant users to register and join the event

```

2022-09-02 04:28 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsTeamsEventsPolicy.md
> + - **Disabled**, Disables creating webinars
```suggestion
 - **Enabled**: Enables creating webinars.
 - **Disabled**: Disables creating webinars.

```

2022-09-02 04:32 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> + - **Disabled**, Disables creating webinars
```suggestion
 - **Enabled**: Enables creating webinars.
 - **Disabled**: Disables creating webinars.

```

2022-09-02 04:34 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md
> + - **EveryoneInCompanyExcludingGuests**, Enables creating events to allow only in tenant users to register and join the event
```suggestion
 - **Everyone**: Enables creating events to allow in-tenant, guests, federated, and anonymous (external to the tenant) users to register and join the event.
 - **EveryoneInCompanyExcludingGuests**: Enables creating events to allow only in-tenant users to register and join the event.

```

2022-09-02 04:36 UTC, JohanFreelancer9 requested changes
@musingh1, a few more suggested changes, please.

2022-09-02 17:46 UTC, tseward approved these changes

2022-09-05 08:01 UTC, yogkumgit commented
@musingh1 Gentle reminder. Thanks

2022-09-12 12:04 UTC, yogkumgit commented
@musingh1 Gentle reminder.

2022-09-13 11:44 UTC, yogkumgit commented
@musingh1 Please implement the suggested changes so that merge can be initiated. In the event of no response we may proceed to close this PR. Thanks

2022-09-16 15:52 UTC, opbld30 commented
Docs Build status updates of commit _[1d1ab87](https://github.com/musingh1/office-docs-powershell/commits/1d1ab87f0e35e7bc5e1d5e1d55880900ccebc9f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-88fe26f8)

<a id="88fe26f8"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 1d1ab87f0e35e7bc5e1d5e1d55880900ccebc9f5 in branch main of repository https://github.com/musingh1/office-docs-powershell into branch main (commit 39f6b6ec11c3bed2221f23b8138230a9cc2dc11b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209161552288939-9845/BuildReport?accessString=dcdf8a39bb436e776581e2ef51370af7e2e120f9384ee8c83d0a493b6ccb9f74).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 15:53 UTC, opbld33 commented
Docs Build status updates of commit _[f0dc96f](https://github.com/musingh1/office-docs-powershell/commits/f0dc96f368f8d548bedaca881ab33d073454f4e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-995c233f)

<a id="995c233f"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit f0dc96f368f8d548bedaca881ab33d073454f4e1 in branch main of repository https://github.com/musingh1/office-docs-powershell into branch main (commit 39f6b6ec11c3bed2221f23b8138230a9cc2dc11b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209161552434584-9845/BuildReport?accessString=f3d44f0ffacca151f96bd7b8a171b999c3dd669fe9858b9b1cbe6724850e3674).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 15:53 UTC, opbld33 commented
Docs Build status updates of commit _[5b4a190](https://github.com/musingh1/office-docs-powershell/commits/5b4a190b1b253cabda79291442d683f7634729f6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-16af0483)

<a id="16af0483"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit 5b4a190b1b253cabda79291442d683f7634729f6 in branch main of repository https://github.com/musingh1/office-docs-powershell into branch main (commit 39f6b6ec11c3bed2221f23b8138230a9cc2dc11b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209161553135669-9845/BuildReport?accessString=7620c89ca3563f009a1c959591e671a2a30bc3c8fd78c15a252b7a2c1bf0f158).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 15:56 UTC, opbld32 commented
Docs Build status updates of commit _[a296c40](https://github.com/musingh1/office-docs-powershell/commits/a296c40ddad55a165f136f287acc033022f98a91)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0933bfb5)

<a id="0933bfb5"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit a296c40ddad55a165f136f287acc033022f98a91 in branch main of repository https://github.com/musingh1/office-docs-powershell into branch main (commit 39f6b6ec11c3bed2221f23b8138230a9cc2dc11b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209161556288650-9845/BuildReport?accessString=77a34579122a06147a425c86643f1fa10a69376676a0f17817982c49b7ce210f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 15:57 UTC, opbld30 commented
Docs Build status updates of commit _[f784c92](https://github.com/musingh1/office-docs-powershell/commits/f784c921f5d103362f07878d519f6f41fb1024f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f05e3831)

<a id="f05e3831"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit f784c921f5d103362f07878d519f6f41fb1024f5 in branch main of repository https://github.com/musingh1/office-docs-powershell into branch main (commit 39f6b6ec11c3bed2221f23b8138230a9cc2dc11b). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209161556368327-9845/BuildReport?accessString=854108e2e87747bfbe1b932ee8ff0714af0b45abe312d3be370682858a256246).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 16:01 UTC, opbld30 commented
Docs Build status updates of commit _[aca1008](https://github.com/musingh1/office-docs-powershell/commits/aca1008caf353f4aa6556b00078ea8256b856753)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209161559225970-9845/BuildReport?accessString=2d4ed00fb2959c1022880b80700d1fba0e441ac7c7ba6bc0a7f5b03f6f85ac42).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 19:55 UTC, tseward approved these changes

2022-09-19 04:11 UTC, JohanFreelancer9 requested changes
@musingh1, thank you for committing the suggested changes, but you seem to have missed one. Could you also commit that one, please? Many thanks.

2022-09-19 21:48 UTC, musingh1 commented
> @musingh1, thank you for committing the suggested changes, but you seem to have missed one. Could you also commit that one, please? Many thanks.

Done!

2022-09-19 21:52 UTC, opbld32 commented
Docs Build status updates of commit _[de9675b](https://github.com/musingh1/office-docs-powershell/commits/de9675b4d94c5ef9dea727195ba70f0595554300)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209192148141313-9845/BuildReport?accessString=13589517fbf9d6b53b67e8edf5745c0f3ecbf8ac74c3bff988651114a7cf1e2a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 21:55 UTC, opbld33 commented
Docs Build status updates of commit _[de9675b](https://github.com/musingh1/office-docs-powershell/commits/de9675b4d94c5ef9dea727195ba70f0595554300)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209192149104071-9845/BuildReport?accessString=23887b22ce7a25dddd85dddd04fd5472e6e9c6f854d88d32983d1d193343484d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 07:56 UTC, yogkumgit commented
@JohanFreelancer9 @get-itips

2022-09-22 04:49 UTC, yogkumgit commented
@JohanFreelancer9 @get-itips Gentle reminder. Please approve.

2022-09-22 10:42 UTC, get-itips approved these changes

2022-09-22 10:56 UTC, JohanFreelancer9 approved these changes

2022-09-23 04:21 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-09-23 16:38 UTC, tiburd commented
@pbafna03 
Hi!
I sent you email with a few questions to answer before I can merge this PR.
Thanks!

2022-09-23 18:51 UTC, opbld30 commented
Docs Build status updates of commit _[2636ebc](https://github.com/musingh1/office-docs-powershell/commits/2636ebc191cab40d641bf740c94c43691f0b7969)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/get-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Grant-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/grant-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/New-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/new-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Remove-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/remove-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsTeamsEventsPolicy.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/set-csteamseventspolicy?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/musingh1/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9845) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209231845577423-9845/BuildReport?accessString=326bd4363fafb436e5c57f4f7fff0c12e28ee705f767b5a0446159abfc446cf1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-23 18:51 UTC, merged