Renaming file Get-CsBatchTeamsDeployment.md to Get-CsBatchTeamsDeploymentStatus
MicrosoftDocs/office-docs-powershell pull request #9848
Opened 2022-08-30 17:30 UTC by srinidhikMS

2022-08-30 17:34 UTC, opbld31 commented
Docs Build status updates of commit _[f8a5d9f](https://github.com/srinidhikMS/office-docs-powershell/commits/f8a5d9f4988b7557a29cc2531f3f85fcc232e3e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/New-CsBatchTeamsDeployment.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsBatchTeamsDeployment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csbatchteamsdeployment?view=teams-ps&branch=pr-en-us-9848) (teams-ps) | [Details](#user-content-3493d9c49733ff91b73fde0ba4486b44-4cb2dfce)
[teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csbatchteamsdeploymentstatus?view=teams-ps&branch=pr-en-us-9848) (teams-ps) |

<a id="3493d9c49733ff91b73fde0ba4486b44-4cb2dfce"></a>
### [teams/teams-ps/teams/New-CsBatchTeamsDeployment.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsBatchTeamsDeployment.md)
 - **Line 0, Column 0**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Get-CsBatchTeamsDeployment.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208301730192129-9848/BuildReport?accessString=7d698d3bfbe6ed7b7ad4e36577dae75748fadfaa31eba925ce2457fd4ffc7ca1).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 17:39 UTC, opbld32 commented
Docs Build status updates of commit _[bc01184](https://github.com/srinidhikMS/office-docs-powershell/commits/bc01184081513a3a56935868319f536cee9b344e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csbatchteamsdeploymentstatus?view=teams-ps&branch=pr-en-us-9848) (teams-ps) |
[teams/teams-ps/teams/New-CsBatchTeamsDeployment.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsBatchTeamsDeployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csbatchteamsdeployment?view=teams-ps&branch=pr-en-us-9848) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208301736213953-9848/BuildReport?accessString=c94409a4384568765c1d840f958bc58370d4e8070388a6b0d6078ed829a8cf3d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 06:43 UTC, JohanFreelancer9 approved these changes

2022-08-31 11:29 UTC, yogkumgit commented
@dariomws @get-itips @tseward

2022-08-31 11:35 UTC, dariomws requested changes
In the Description section the cmdlet name must also be updated.

2022-08-31 11:35 UTC, dariomws commented on teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md
> +# GGet-CsBatchTeamsDeploymentStatus
```suggestion
# Get-CsBatchTeamsDeploymentStatus

```

2022-08-31 13:27 UTC, get-itips approved these changes
I am ok after @dariomws suggestions applied

2022-08-31 16:42 UTC, dariomws approved these changes

2022-08-31 16:42 UTC, opbld31 commented
Docs Build status updates of commit _[dfacedf](https://github.com/srinidhikMS/office-docs-powershell/commits/dfacedfe76fbc4ed6506d688a6638360dba65d6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csbatchteamsdeploymentstatus?view=teams-ps&branch=pr-en-us-9848) (teams-ps) |
[teams/teams-ps/teams/New-CsBatchTeamsDeployment.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsBatchTeamsDeployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csbatchteamsdeployment?view=teams-ps&branch=pr-en-us-9848) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208311640007282-9848/BuildReport?accessString=4940dc5aa61cff54e1bae79f4b8b9f000ef3be939d679a6d8b3cdebc01edc787).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 16:43 UTC, srinidhikMS commented
> In the Description section the cmdlet name must also be updated.

Cmdlet name is updated in description. Thanks.

2022-08-31 16:47 UTC, opbld30 commented
Docs Build status updates of commit _[2f4ec04](https://github.com/srinidhikMS/office-docs-powershell/commits/2f4ec045c7878808495ff7349450a8d37e532d1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsBatchTeamsDeploymentStatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-csbatchteamsdeploymentstatus?view=teams-ps&branch=pr-en-us-9848) (teams-ps) |
[teams/teams-ps/teams/New-CsBatchTeamsDeployment.md](https://github.com/srinidhikMS/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsBatchTeamsDeployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-csbatchteamsdeployment?view=teams-ps&branch=pr-en-us-9848) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202208311641246302-9848/BuildReport?accessString=73b1194e757f20eb0d0a72aa49fc5919d3f3ab79213e0c7b2058ce20854bff5c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 10:15 UTC, yogkumgit commented
@tseward Gentle reminder please.

2022-09-02 17:46 UTC, tseward approved these changes

2022-09-05 08:01 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-09-06 16:44 UTC, merged