Basic Auth update
MicrosoftDocs/office-docs-powershell pull request #9861
Opened 2022-09-02 07:14 UTC by pbafna03

2022-09-02 07:32 UTC, opbld30 commented
Docs Build status updates of commit _[5714616](https://github.com/pbafna03/office-docs-powershell/commits/5714616aec832e2e3f04260986301d2e6e5d4b29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-10/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-9861) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209020730189263-9861/BuildReport?accessString=986fe070622e3daa5712d71cf8f9670f7ac8e3c21059daec1a4dfc867880a198).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 10:19 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-02 11:34 UTC, dariomws approved these changes

2022-09-02 11:34 UTC, dariomws commented on teams/teams-ps/teams/Connect-MicrosoftTeams.md
> +**Note**: With versions 4.x.x or later, enablement of basic authentication is not needed anymore in Commercial Environments. For GCC High / DoD environments & customers that are or have previously be
```suggestion
**Note**: With versions 4.x.x or later, enablement of basic authentication is not needed anymore in Commercial environments. For GCC High/DoD environments and customers that are, or have previously been enabled for Regionally Hosted Meetings in Skype for Business Online, basic authentication needs to be enabled for *-Cs cmdlets to function properly.
```

2022-09-02 11:59 UTC, opbld33 commented
Docs Build status updates of commit _[bc51ebf](https://github.com/pbafna03/office-docs-powershell/commits/bc51ebf928dd6ab16bb2ef7452f789daab8e01cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-10/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-9861) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209021156430781-9861/BuildReport?accessString=4a06ef23505e2a91c5feb5323b4df0cc065dfd8a71e72c02949ad30c4c2cc7f9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 12:14 UTC, get-itips approved these changes

2022-09-02 12:35 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Connect-MicrosoftTeams.md
> +**Note**: With versions 4.x.x or later, enablement of basic authentication is not needed anymore in Commercial environments. For GCC High/DoD environments and customers that are, or have previously b
```suggestion
**Note**: With versions 4.x.x or later, enablement of basic authentication is not needed anymore in commercial environments. For GCC High/DoD environments and customers that are, or have previously been enabled for Regionally Hosted Meetings in Skype for Business Online, basic authentication needs to be enabled for *-Cs cmdlets to function properly.
```

2022-09-02 12:36 UTC, JohanFreelancer9 requested changes
Copy review - @pbafna03, kindly commit the minor suggested change. Many thanks.

2022-09-02 12:38 UTC, pbafna03 commented
@JohanFreelancer9  - Done!

2022-09-02 12:40 UTC, opbld33 commented
Docs Build status updates of commit _[cf8506a](https://github.com/pbafna03/office-docs-powershell/commits/cf8506a5e83adb4d36e287a0c786cd50fa484146)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Connect-MicrosoftTeams.md](https://github.com/pbafna03/office-docs-powershell/blob/patch-10/teams/teams-ps/teams/Connect-MicrosoftTeams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps&branch=pr-en-us-9861) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209021238018345-9861/BuildReport?accessString=7220227e45866da8f5b81c6e1858b05f3f561b49be1ed2aff1e215ca3307f70b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 17:40 UTC, tseward approved these changes

2022-09-05 05:45 UTC, JohanFreelancer9 approved these changes

2022-09-05 08:06 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-09-06 16:51 UTC, merged