Update New-CsTenantNetworkSite.md
MicrosoftDocs/office-docs-powershell pull request #9891
Opened 2022-09-11 15:56 UTC by hbunkradt

I have removed the Parameter OnlineVoiceRoutingPolicy, because this parameter is no longer used for location based routing. This parameter still exist on powershell command new-CSNetworkSite, but is no longer used for location based routing. I change example 2 to assign a emergency policy with LBR for a network site

2022-09-11 15:56 UTC, hbunkradt commented
I create a new pull request with changes on syntax and also on example 2

2022-09-11 15:59 UTC, opbld30 commented
Docs Build status updates of commit _[b8ac635](https://github.com/hbunkradt/office-docs-powershell/commits/b8ac63540bd97c2bf6280383e711952f1ef2b7da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTenantNetworkSite.md](https://github.com/hbunkradt/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsTenantNetworkSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cstenantnetworksite?view=skype-ps&branch=pr-en-us-9891) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209111556191489-9891/BuildReport?accessString=4c417ec9f1edf395412aacf66fc89cc0c0ed976a50305ccc0070ab8e618952e9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 07:45 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTenantNetworkSite.md
> +The command shown in Example 2 created the network site 'site2' with description 'site 2'. This site is enabled for LBR, and associates with network region 'RedmondRegion', with location policy 'Test
```suggestion
The command shown in Example 2 created the network site 'site2' with description 'site 2'. This site is enabled for LBR, and associates with network region 'RedmondRegion', with location policy 'TestLocationPolicy', and assigns an emergency policy 'ECRP1'.
```

2022-09-12 07:46 UTC, JohanFreelancer9 requested changes
Copy review - @hbunkradt, kindly commit the suggested changes. Many thanks.

2022-09-13 17:52 UTC, get-itips commented on skype/skype-ps/skype/New-CsTenantNetworkSite.md
> +The command shown in Example 2 created the network site 'site2' with description 'site 2'. This site is enabled for LBR, and associates with network region 'RedmondRegion', with location policy 'Test
I suggest "assigns a custom emergency call routing policy 'ECRP1'"

2022-09-13 19:35 UTC, opbld33 commented
Docs Build status updates of commit _[e14c22a](https://github.com/hbunkradt/office-docs-powershell/commits/e14c22a6f13dd16a803b44a738c89d93a4c716bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[skype/skype-ps/skype/New-CsTenantNetworkSite.md](https://github.com/hbunkradt/office-docs-powershell/blob/patch-2/skype/skype-ps/skype/New-CsTenantNetworkSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/skype/new-cstenantnetworksite?view=skype-ps&branch=pr-en-us-9891) (skype-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209131932548257-9891/BuildReport?accessString=e6aca583b91ee1825aa1f043aeedd576c8ad030ad1a837f07c471bda897d2e1e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 02:58 UTC, tseward approved these changes

2022-09-14 04:56 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-14 04:56 UTC, yogkumgit commented
@dariomws @get-itips

2022-09-14 06:49 UTC, JohanFreelancer9 commented on skype/skype-ps/skype/New-CsTenantNetworkSite.md
> +The command shown in Example 2 created the network site 'site2' with description 'site 2'. This site is enabled for LBR, and associates with network region 'RedmondRegion', with location policy 'Test
```suggestion
The command shown in Example 2 created the network site 'site2' with description 'site 2'. This site is enabled for LBR, and associates with network region 'RedmondRegion', with location policy 'TestLocationPolicy', and assigns a custom emergency call routing policy 'ECRP1.
```

2022-09-14 06:50 UTC, JohanFreelancer9 requested changes
@hbunkradt, please commit the suggested change to incorporate @get-itips' suggestion. Many thanks.

2022-09-14 06:55 UTC, dariomws requested changes

2022-09-14 06:55 UTC, dariomws commented on skype/skype-ps/skype/New-CsTenantNetworkSite.md
> +PS C:\> New-CsTenantNetworkSite -NetworkSiteID "site2" -Description "site 2" -EnableLocationBasedRouting $true -NetworkRegionID "RedmondRegion" -LocationPolicy "TestLocationPolicy" -EnableLocationBas
```suggestion
PS C:\> New-CsTenantNetworkSite -NetworkSiteID "site2" -Description "site 2" -NetworkRegionID "RedmondRegion" -LocationPolicy "TestLocationPolicy" -EnableLocationBasedRouting $true -SiteAddress "One Microsoft way" -EmergencyCallRoutingPolicy "ECRP1"
```

Duplicate parameter, please remove

2022-09-20 14:18 UTC, yogkumgit commented
@hbunkradt Gentle reminder.

2022-09-28 14:45 UTC, yogkumgit commented
Closing as there is no response. Please feel free to create a new PR for revised update. Thanks

2022-09-28 14:45 UTC, closed without merging