Add New|Get-CsCloudCallDataConnection cmdlets public docs
MicrosoftDocs/office-docs-powershell pull request #9895
Opened 2022-09-12 11:05 UTC by 2012ucp1544

2022-09-12 11:09 UTC, opbld31 commented
Docs Build status updates of commit _[53325ad](https://github.com/2012ucp1544/office-docs-powershell/commits/53325ad4c82cf7c5e62de44d24cf7f2e04f406d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsCloudCallDataConnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cscloudcalldataconnection?view=teams-ps&branch=pr-en-us-9895) (teams-ps) | [Details](#user-content-be3a041dbffb635e6864c0c467f02a51-04fdcf23)
[teams/teams-ps/teams/New-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsCloudCallDataConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cscloudcalldataconnection?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |

<a id="be3a041dbffb635e6864c0c467f02a51-04fdcf23"></a>
### [teams/teams-ps/teams/Get-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsCloudCallDataConnection.md)
 - **Line 0, Column 0**: **[Warning: author-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Invalid value for author: '2012ucp1544,' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209121105307612-9895/BuildReport?accessString=741063f950b046dedc59c257afeca9e1c0f6174917d4d7716063dc5d4bccc4ea).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 12:07 UTC, yogkumgit commented
@get-itips @dariomws @tseward

2022-09-12 12:07 UTC, yogkumgit commented
@JohanFreelancer9

2022-09-12 12:32 UTC, opbld33 commented
Docs Build status updates of commit _[9b3dfd6](https://github.com/2012ucp1544/office-docs-powershell/commits/9b3dfd6cacfbf95f22e8731bb090a952e4a7cc73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsCloudCallDataConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cscloudcalldataconnection?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |
[teams/teams-ps/teams/New-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsCloudCallDataConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cscloudcalldataconnection?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209121229346014-9895/BuildReport?accessString=fecc2b44d41c83526daae15e5c610160bd11446ef1e24ba37dadcb87fba4f575).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 12:47 UTC, opbld32 commented
Docs Build status updates of commit _[04e59bc](https://github.com/2012ucp1544/office-docs-powershell/commits/04e59bc47229d68900ee8db24c004648a3fa82e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsCloudCallDataConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cscloudcalldataconnection?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |
[teams/teams-ps/teams/New-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsCloudCallDataConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cscloudcalldataconnection?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209121244347014-9895/BuildReport?accessString=37939ed522b6488d4934cd480fc5b45de4aeb74b5515cfc13f186bdc831eae61).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 12:50 UTC, pbafna03 approved these changes

2022-09-12 13:06 UTC, get-itips commented on teams/teams-ps/teams/New-CsCloudCallDataConnection.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-12 13:06 UTC, get-itips commented on teams/teams-ps/teams/Get-CsCloudCallDataConnection.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2022-09-12 13:39 UTC, dariomws approved these changes
I'm ok after suggestions.

2022-09-12 13:39 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/Get-CsCloudCallDataConnection.md
> +Get-CsCloudCallDataConnection cmdlet is now supported only from Teams PowerShell Module versions 4.6.0 or later.
```suggestion
The Get-CsCloudCallDataConnection cmdlet is only supported from Teams PowerShell Module versions 4.6.0 or later.
```

2022-09-12 13:40 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsCloudCallDataConnection.md
> +This cmdlet creates an online call data connection. If you get an error that the connection already exists, this means that the call data connection already exists for your tenant. In this case, run
```suggestion
This cmdlet creates an online call data connection. If you get an error that the connection already exists, it means that the call data connection already exists for your tenant. In this case, run Get-CsCloudCallDataConnection.
```

2022-09-12 13:41 UTC, JohanFreelancer9 commented on teams/teams-ps/teams/New-CsCloudCallDataConnection.md
> +New-CsCloudCallDataConnection cmdlet is now supported only from Teams PowerShell Module versions 4.6.0 or later.
```suggestion
The New-CsCloudCallDataConnection cmdlet is only supported from Teams PowerShell Module versions 4.6.0 or later.
```

2022-09-12 13:43 UTC, JohanFreelancer9 requested changes
Copy review - @2012ucp1544, kindly commit the suggested changes. Many thanks.

2022-09-12 14:17 UTC, 2012ucp1544 commented on teams/teams-ps/teams/New-CsCloudCallDataConnection.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
Incorporated review comments, please review again.

2022-09-12 14:17 UTC, 2012ucp1544 commented on teams/teams-ps/teams/Get-CsCloudCallDataConnection.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
Incorporated review comments, please review again.

2022-09-12 14:19 UTC, opbld31 commented
Docs Build status updates of commit _[67c0569](https://github.com/2012ucp1544/office-docs-powershell/commits/67c05696a9f76b588cc256d59c8a7896fffd8b55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[teams/teams-ps/teams/Get-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/Get-CsCloudCallDataConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/get-cscloudcalldataconnection?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |
[teams/teams-ps/teams/New-CsCloudCallDataConnection.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/New-CsCloudCallDataConnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/new-cscloudcalldataconnection?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |
[teams/teams-ps/teams/teams.md](https://github.com/2012ucp1544/office-docs-powershell/blob/main/teams/teams-ps/teams/teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/teams/index?view=teams-ps&branch=pr-en-us-9895) (teams-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209121416399364-9895/BuildReport?accessString=1231955bc186e9087c2b7e639985a53fca2e31310209e2218703037f6783c694).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-12 14:41 UTC, JohanFreelancer9 approved these changes

2022-09-12 14:50 UTC, tseward approved these changes

2022-09-12 15:12 UTC, get-itips approved these changes

2022-09-13 10:58 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-09-13 15:01 UTC, merged