Update Set-Mailbox.md
MicrosoftDocs/office-docs-powershell pull request #9957
Opened 2022-09-24 14:05 UTC by DMoenks

Fixes #9953

2022-09-24 14:11 UTC, opbld31 commented
Docs Build status updates of commit _[78e80d3](https://github.com/DMoenks/office-docs-powershell/commits/78e80d3e3c530805ba68d961ac2b7b90985ef60b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/DMoenks/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-Mailbox.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps&branch=pr-en-us-9957) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209241405468324-9957/BuildReport?accessString=5ecd3ee504b9143342aef15193ab3aa7b11d45dbb726d4f9b66c0f9aa9619cd2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 11:22 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-Mailbox.md
> +The MessageCopyForSMTPClientSubmissionEnabled parameter specifies whether to store copies of messages in the mailbox that are submitted via SMTP. Valid values are:
```suggestion
The MessageCopyForSMTPClientSubmissionEnabled parameter specifies whether to store copies of messages in the mailbox that are submitted via SMTP. Valid values are:
```

2022-09-26 11:30 UTC, JohanFreelancer9 commented on exchange/exchange-ps/exchange/Set-Mailbox.md
> +- $false: When a message is submitted for the mailbox by using SMTP, a copy of the message isn't stored in the mailbox.
```suggestion
- $true: When a message is submitted to the mailbox by using SMTP, a copy of the message is stored in the mailbox. This is the default value.
- $false: When a message is submitted to the mailbox by using SMTP, a copy of the message isn't stored in the mailbox.
```

2022-09-26 11:31 UTC, JohanFreelancer9 requested changes
Copy review - @DMoenks, kindly commit the minor suggested changes. Many thanks.

2022-09-26 14:21 UTC, opbld31 commented
Docs Build status updates of commit _[ba12e2d](https://github.com/DMoenks/office-docs-powershell/commits/ba12e2de4cf69c3cd4de6604f73c3c8e8010d86c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[exchange/exchange-ps/exchange/Set-Mailbox.md](https://github.com/DMoenks/office-docs-powershell/blob/patch-1/exchange/exchange-ps/exchange/Set-Mailbox.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps&branch=pr-en-us-9957) (exchange-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3603fd28-efce-f87f-e986-fc8a694fc312/202209261417051242-9957/BuildReport?accessString=5f2f2de1469aef93e0df0d9d00d872e38e4287c853ce902a1f781086d750e8b6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3603fd28-efce-f87f-e986-fc8a694fc312?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-26 14:54 UTC, JohanFreelancer9 approved these changes

2022-09-26 17:50 UTC, chrisda commented
@DMoenks, sorry, I was going through my email in order, and the comments on Issue #9953 led me to do my own PR for the changes before I saw that you also did (perfectly fine) changes for the same issue.

So, closing to avoid merge conflicts

2022-09-26 17:50 UTC, closed without merging